ExView.Plugins({info:{name:"5弹幕视频",version:"2.2",author:"Gentle",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAnFBMVEX/UFD////69/L/T0//VFT/c3L/+vr/7u7/oKD/g4P/Z2b/YF/+q6v/paX/Y2P+W1v/8PD47+b639z45db/1dX6w77+kpL/+/v7+vb59O/58Or47eH/3t746Nv/2tr53tb34dP52tH/qKj/fX39eXj/Vlb59PH67+362tj23Mb22MH11br10bT+sbD8oqH8nJr/l5f/jo78jIr+a2sAQZRfAAAAtklEQVQY0z2PVw4CMQxEHadtsr3S27L0Dve/G46RyEc070ljyyCEGM0Tp7Xrl4aARJF4BfSUT20QxXMXkFVnBYwS4r9JDcz9L0sp6c8a6BVjPrzjECJwzFm7rtuc0hY0F5JZOdt4KmkW0lf1ebEeWLgguvJyPW0yrqSh0WJZLx6Shy7J5xXidPUhETdgUiX1FHGyorUqMiBsB26CiMcc1MuG42x035Oo4jiyfK0wxXiMeLg1huAL0qwKAIflVYQAAAAASUVORK5CYII=",
db:"5dm",apihost:"http://www.5dm.tv/",pagetitle:["<br>","收藏","新番连载","类型","下载"],download:!1,lazyload:!0,setting:!0,type:"video",theme:"pink",cdn:""},set:function(a){},unset:function(a){},init:function(a){ExView.workers.fav.listloader({callback:function(){}})},flags:{indexflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"video/bgm/bangumi/page/"+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){a.callback({img:pluginfo(a.plugin).icon,
multpage:!0,result:b,header:c})}}},finder:function(a){return{query:!0,selector:".video-item",str:a.result,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:function(a){return{query:!0,selector:".pages",str:a.result,successfn:function(b){try{var c=getstr(/共\s*(\d+)\s*页/g,$$(b).text())||0}catch(f){c=-1}a.callback({pagecount:c})}}}},typeflag:{loader:!1,finder:function(a){a.callback({title:"新番连载",img:pluginfo(a.plugin).icon,
group:{name:"daohang",title:"导航"},content:"新番连载"});a.callback({tid:"",listflag:"video/bgm/end/page/{{page}}",title:"旧番补档",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"旧番补档"});a.callback({tid:"",listflag:"video/bgm/ova/page/{{page}}",title:"剧场OVA",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"剧场OVA"})}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
a.flag.replace("{{page}}",a.page||1),method:"GET",timeout:120,successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})}}},finder:function(a){return{query:!0,selector:".video-item",str:a.result,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:function(a){return{query:!0,selector:".pages",str:a.result,successfn:function(b){try{var c=getstr(/共\s*(\d+)\s*页/g,$$(b).text())||0}catch(f){c=-1}a.callback({pagecount:c})}}}},
searchflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"page/"+(a.page||1)+"?s="+encodeURIComponent(a.keyword),method:"GET",timeout:120,successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})}}},finder:function(a){return{query:!0,selector:".video-item",str:a.result,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:function(a){return{query:!0,selector:".pages",str:a.result,successfn:function(b){try{var c=getstr(/共\s*(\d+)\s*页/g,
$$(b).text())||0}catch(f){c=-1}a.callback({pagecount:c})}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"bangumi/dv"+a.pid,method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{query:!0,selector:".multilink-table-wrap",str:a.result,successfn:function(b,c,f,d){if(array_count(b)){if(a.checkupdate)return a.callback({pid:a.pid,cid:$$(b).find(".multilink-btn").length-1,title:$$(b).find(".multilink-btn").eq(-1).text()}),
!0;d=[];$$(b).find(".multilink-btn").each(function(c){d[c]=a.callback({id:c,newest:a.newest&&0==c,pid:a.pid,cid:c+"",title:$$(this).text(),count:$$(b).length,reverse:0})});return d}if(a.checkupdate)return a.callback({pid:a.pid,cid:"-1",title:"第一集"}),!0;d=[];d[0]=a.callback({id:0,newest:a.newest,pid:a.pid,cid:"-1",title:"第一集",count:1,reverse:0});return d}}},infoloader:!1,infofinder:function(a){return{query:!0,selector:".video-conent",str:a.result,successfn:function(b,
c,f,d){c=getlistname(a.pid,a.plugin);var e=[];$$(b).find(".item-tax-list a").each(function(){e.push($$(this).text())});b=$$(b).find(".item-content").text();a.callback({added:a.data,description:"<p>"+(e?"【类型】"+e.join(",")+"<br>":"")+(b?"【简介】"+b:"")+"</p>",comment:1,preview:0,tags:gettag(c)+gettag(e),sourceurl:pluginfo(a.plugin).apihost+"bangumi/dv"+a.pid});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"bangumi/dv"+a.pid+("-1"==
a.cid?"":"?link="+a.cid),method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{reg:/&cid=(.*?)\"/g,find:"$1",str:a.result,successfn:function(b,c,f,d){if(b){var e="-1"==a.cid?["http://api.tucao.tv/api/down/"+b]:["https://xxxooo.duapp.com/ey.php?vid="+b];if(a.download)a.callback({source:e,type:"video",download:a.download,plugin:a.plugin});else{var g=function(b){a.callback({poster:getlistimg(a.pid,a.plugin),url:pluginfo(a.plugin).apihost+"bangumi/dv"+
a.pid+"?link="+a.cid,source:e,type:"video",title:myContent.name+getnavundertitle(a.title),danmaku:{id:"5dm_"+a.pid,api:"https://api.prprpr.me/dplayer/",token:"tokendemo",maximum:1E3,addition:b?[b]:[],user:"ExView"}})};ExView.modules.curl({url:pluginfo(a.plugin).apihost+"player/xml.php?id="+b+"&r=372",successfn:function(a){var b=[];a=getquery(a,"d");$$(a).each(function(){var a=$$(this).attr("p"),c=$$(this).text(),a=a.split(",")[0];-1==c.indexOf("无关的弹幕")&&b.push({author:"",
time:a,text:c,color:"#ffffff",type:"right"})});b={code:1,danmaku:b};console.log(b);a=new Blob([JSON.stringify(b)],{type:"text/plain; charset=utf-8"});var c=URL.createObjectURL(a);setTimeout(function(){URL.revokeObjectURL(c)},1E3);g(c);console.log(c)},errorfn:function(a){g()},showinfo:{text:"正在获取弹幕信息...",title:"视频",name:getlistname(a.pid),img:getlistimg(a.pid)}})}}else a.callback();return!0}}}},commentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"bangumi/dv"+a.pid+"/comment-page-"+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){b?a.callback({result:b,header:c,commentbrowser:{url:pluginfo(a.plugin).apihost+"bangumi/dv"+a.pid+"/comment-page-"+(a.page||1),title:"评论 - "+pluginfo(a.plugin).name+'<br><span style="font-size:16px">'+(myContent.name||"")+"</span>",browser:!0,flag:""}}):a.callback()}}},finder:function(a){return{query:!0,selector:".commentlist",str:a.result,successfn:function(b,c,f,d){array_count(b)&&$$(b).children(".comment").each(function(){a.callback({page:a.page||
1,pagecount:0,comment:{text:$$(this).find(".comment-content").text(),name:$$(this).find(".comment-author .url").text(),avatar:$$(this).find(".avatar").attr("src"),type:"received",label:$$(this).find("time").attr("datetime"),day:"",time:"",reverse:1,extra:""}})})}}},send:!1},previewflag:{loader:!1,finder:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"video/bgm/bangumi/page/"+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,
header:c})}}},finder:function(a){return{query:!0,selector:".video-item",str:a.result,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"video/bgm/end/page/"+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{query:!0,selector:".video-item",str:a.result,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}}}},
fns:{pagedeal:function(a,b){b=b||{};$$(a).each(function(){var a=getstr(/\/dv(\d+)/,$$(this).find("a").attr("href")),f=$$(this).find("img").attr("data-original"),d=$$(this).find("img").attr("title")||"",e=getstr(/【(.*?)】/,d),d=d.split("【更新")[0].split("【完结")[0].split("【已完结")[0],g=$$(this).find(".item-content").text();if(b.multupdate||b.multhot||b.multsearch)return b.callback(obj_contact(b,{pid:a,img:f,title:d,content:e})),!1;b.callback({pid:a,
title:d,img:f,stitle:e,content:g,comment:1})})}}});
