ExView.Plugins({info:{name:"八号文库",version:"2.2",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAolBMVEX///8PVEUUV0kMUUOcvLWzycQGTT7X4uBijoVIfHHF1tLE1dGxyMNtl44bXE4RVUfZ5OKburSYt7GTsqx3npZbioBWhXxOgndLfnNEe3A4cmYpZ1smZFcjYlXw9fTi6ujP3drI2NW1y8atxcB7oppslIxolIpfjYNBeG0xbWAhYFMESzz1+Pfs8fHp7+6/0c68z8ymv7qCp591nZV1nJQ+dWqDhS6yAAAAvUlEQVQY0z2MR3LDQAwEBwtvEoOYk0jlLOfw/68ZK7ncBxy6eoD86Z+8kIPJ+xLed1vcWaDFA505fDiXQjUNM2PSs79CXVET1qRnaxwOiRT0hhVIBMZtRnMRBLCICIFaBAPLUBgTW0Mi8NyjpfhRnDGFwQuAyBh9L1ISlAo3vYandl8Qa/5KktdytyugjuqdzS2vyNhoFe+hkmPJlFF1c3bjLjL55hMvmauus/FpM8fY9+fL6NtmGD5/hkX9CxlLDDEBlRbzAAAAAElFTkSuQmCC",
author:"Gentle",type:"text",db:"8wenku",apihost:"http://www.8wenku.com/",pagetitle:["<br>","收藏","首页","类型","下载"],lazyload:!0,download:!0,setting:!0,nativeres:!0,typelistmode:!0,smallpicmode:!0,requestcookie:"",cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){ExView.workers.index.loader();ExView.workers.type.loader()}})},flags:{indexflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost,method:"GET",
timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{Cookie:pluginfo(a.plugin).requestcookie},successfn:function(b,c){ExView.workers.index.countfinder(obj_contact(a,{result:b,header:c}));a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),name:"首页",title:a.title,img:a.img}}},finder:function(a){return{reg:/\/book\/(\d+)">\s*<img\s*src="((?!\").*?)"(?!<).*?alt="((?!\").*?)"/g,str:a.result,find:{pid:"$1",
img:"$2",title:"$3"},successfn:function(a){console.log(JSON.stringify(a));array_count(a)?addcardlist({pid:a.pid,title:a.title,img:a.img,content:a.content,comment:1}):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',2)},errorfn:function(){a.page||setnowlistname("首页","",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("网络错误！","ExView")}}},countloader:function(a){return!1},
countfinder:function(a){return{successfn:function(){mySession.nowlistpages="-1|首页|index";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},typeflag:{loader:function(a){return{successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){addtypelist({title:"首页",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"首页"});for(var b=[],c=0;26>c;c++)b.push(String.fromCharCode(97+c));b.forEach(function(b){addtypelist({tid:b,
title:b.toUpperCase(),img:pluginfo(a.plugin).icon,group:{name:"souyin",title:"索引"},content:b.toUpperCase()})});return!1}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"letter/"+a.keyword+"?page="+(a.page||1),method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{Cookie:pluginfo(a.plugin).requestcookie},successfn:function(b,c){b?(ExView.workers.list.countfinder(obj_contact(a,{result:b,header:c})),a.successfn&&a.successfn({result:b,header:c})):(ExView.fw.hidePreloader(),
mySession.isloading=0,ExView.fw.alert("【"+a.title+"】<br>获取失败！","ExView"))},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),title:a.title,name:"【"+a.title+"】",img:a.img}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',
1)}}},countloader:function(a){return!1},countfinder:function(a){return{reg:plugfns(a.plugin).pagecountrule,str:a.result,find:plugfns(a.plugin).pagecountfind,successfn:function(b){mySession.nowlistpages=(b||"0")+"|"+a.keyword+"|list";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},searchflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"site/search?keyword="+a.keyword+"&page="+(a.page||1),method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{Cookie:pluginfo(a.plugin).requestcookie},
successfn:function(b,c){b?(a.multsearch||(ExView.workers.search.countfinder(obj_contact(a,{result:b,header:c})),setnowlistname("搜索【"+a.keyword+"】")),a.successfn&&a.successfn({result:b,header:c})):a.multsearch?a.multsearch():(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+a.keyword+"】<br>获取搜索结果失败！","ExView"))},showinfo:{text:"正在搜索..."+(1<a.page?"<br>第"+a.page+"页":""),name:"【"+
a.keyword+"】",title:"搜索"}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b,c,f){console.log(b);array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.multsearch?a.multsearch():addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{reg:plugfns(a.plugin).pagecountrule,str:a.result,
find:plugfns(a.plugin).pagecountfind,successfn:function(b){mySession.nowlistpages=(b||"0")+"|"+a.keyword+"|search";mySession.nowlistpage=1;console.log(mySession.nowlistpages)}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"book/"+a.pid,method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{Cookie:pluginfo(a.plugin).requestcookie},successfn:function(b,c){b?a.successfn&&a.successfn({result:b,header:c}):a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=
0,ExView.fw.alert("内容页获取失败！","ExView"))},showinfo:{text:"正在加载目录...",title:"内容页",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){var b=[];a.result=getresult(a.result).replace(/<\/dd>/g,"</dd>\n");var c=getstrs(a.result,/<h2\s*class="ft-24">\s*<strong>\s*((?!<).*?)\s*<\/strong>\s*<\/h2>\s*<ul\s*class="lk-chapter-list(.*?)<\/dd>/g,"$1{{separator}}$2"),c=c.map(function(a){a=(a||"").split("{{separator}}");
var c=gettrimtext(a[0]);getstrs(a[1],/\&chapter_no=(\d+)"><span\s*class="lk-ellipsis inline">((?!<).*?)</g,"$1{{separator}}$2").map(function(a){a=(a||"").split("{{separator}}");b.push({group:{name:"type_"+ExView.tools.md5.hex_md5(c),title:c},item:{cid:a[0],title:a[1]}})})});return{successfn:function(c,e,d,g){console.log(typeof c);if(array_count(c)){if(a.checkupdate)return e=b,c=e[e.length-1],d=(c||{}).group.title,c=(c||{}).item,{pid:a.pid,cid:c.cid,title:d+" "+c.title};myContent.mhkey=ExView.modules.commentpage.duoshuoloader(a.result);
e=b;g=[];b.map(function(b,c){var d=b.item;g[c]=additemlist({id:c,newest:a.newest&&0==c,pid:a.pid,cid:d.cid,title:d.title,group:b.group,count:e.length,reverse:0});g[c].title=b.group.title+" "+d.title});return g}a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},afterfn:function(){a.checkupdate||ExView.workers.content.infofinder(a)}}},infoloader:function(a){return!1},infofinder:function(a){console.log(a);return{reg:/class="lk-book-cover(.*?)<dl>/g,
str:getresult(a.result),find:"$1",successfn:function(b,c,f,e){console.log(JSON.stringify(b));c=getstr(/<img(?!<).*?src="((?!\").*?)"/,b);f=getstr(/<strong>((?!<).*?)<\/strong>/,b);e=getstr(/width="140">((?!<).*?)</,b).trim();var d=getstrs(b,/'\/tag\/((?!').*?)'/g,"$1"),g=gettext(getstr(/\&chapter_no=\d+">((?!<).*?)</,b).trim()),h=getstr(/<td>([\d,\ ,\-,\:]+)<\/td>/,b).trim(),k=getstr(/浏览：<\/strong>(\d+)</,b).trim();b=gettext(getstr(/>内容简介<\/strong>(.*?)<\/div>/,
b)).trim();var l=gettag(d),d=(d||[]).join(" ").trim();setlistpic({name:f,img:c,added:a.data,description:"<p>"+(e?"【作者】"+e+"<br>":"")+(d?"【类型】"+d+"<br>":"")+(k?"【浏览】"+k+"<br>":"")+(h?"【更新】"+h+"<br>":"")+(g?"【最新话】"+g+"<br>":"")+(b?"【简介】"+b:"")+"</p>",sourceurl:pluginfo(a.plugin).apihost+"book/"+a.pid,comment:1,preview:0,tags:gettag(f)+l+gettag(e)});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"chapter/view?id="+a.pid+"&chapter_no="+a.cid,method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{Cookie:pluginfo(a.plugin).requestcookie},successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"正在加载文章信息...",title:"文章",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){console.log(a);return{reg:/<div id="J_view"(?!>).*?>(.*?)<\/div>/g,str:getresult(a.result),find:"$1",successfn:function(b){b?
(b=getarticle(b),console.log(b),a.download?chapterpredownload({type:"text",source:b,download:a.download,plugin:a.plugin}):chapterviewer({source:b,type:"text",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.download?chapterpredownload({error:"解析错误！",download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("文章信息获取失败！","ExView"));return!0}}}},
commentflag:{loader:function(a){return myContent.mhkey?{url:"http://8wenku.duoshuo.com/api/threads/listPosts.json?thread_key="+myContent.mhkey+"&max_depth=1&page="+parseInt(a.page||1),method:"GET",timeout:120,successfn:function(b,c){b?a.callback&&a.callback({result:b,header:c,commentbrowser:{url:pluginfo(a.plugin).apihost+"book/"+a.pid+"/",title:"评论 - "+pluginfo(a.plugin).name+'<br><span style="font-size:16px">'+(myContent.name||"")+"</span>",browser:!1,flag:""}}):a.callback&&a.callback()}}:
(ExView.modules.curl({url:pluginfo(a.plugin).apihost+"book/"+a.pid+"/",method:"GET",timeout:120,successfn:function(b,c){myContent.mhkey=ExView.modules.commentpage.duoshuoloader(b);ExView.modules.curl({url:"http://8wenku.duoshuo.com/api/threads/listPosts.json?thread_key="+myContent.mhkey+"&max_depth=1&page="+parseInt(a.page||1),method:"GET",timeout:120,successfn:function(b,c){b?($$(".page[data-page='commentpage']").remove(),setTimeout(function(){a.callback&&a.callback({result:b,header:c,commentbrowser:{url:pluginfo(a.plugin).apihost+
"book/"+a.pid+"/",title:"评论 - "+pluginfo(a.plugin).name+'<br><span style="font-size:16px">'+(myContent.name||"")+"</span>",browser:!1,flag:""}})},300)):a.callback&&a.callback()},showinfo:{text:"正在获取评论信息...",title:"评论页",name:getlistname(a.pid),img:getlistimg(a.pid)}})},showinfo:{text:"正在获取评论信息...",title:"评论页",name:getlistname(a.pid),img:getlistimg(a.pid)}}),!1)},finder:function(a){console.log(a);
return{json:!0,str:a.result,successfn:function(b,c,f,e){if(array_count(b)){c=(b.cursor||{}).pages;b=b.parentPosts;for(var d in b)a.callback&&a.callback({page:a.page||1,pagecount:c,comment:{text:b[d].message,name:b[d].author.name,avatar:b[d].author.avatar_url,type:"received",label:b[d].created_at.replace(/T/g," ").replace(/\+/g," "),day:"",time:"",reverse:1,extra:""}})}}}},send:!1},previewflag:{loader:!1,finder:!1,more:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return 1<a.page?(a.multupdate(),
!1):{url:pluginfo(a.plugin).apihost,method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{Cookie:pluginfo(a.plugin).requestcookie},successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));array_count(b)&&plugfns(a.plugin).pagedeal(b,a)}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"letter/s?page="+(a.page||1),method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{Cookie:pluginfo(a.plugin).requestcookie},successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));array_count(b)&&plugfns(a.plugin).pagedeal(b,a)}}}}},fns:{pagecountrule:/page=(\d+)">末页/,pagecountfind:"$1",
pagerule:/\/book\/(\d+)">\s*<img\s*src="((?!\").*?)"(?!<).*?alt="((?!\").*?)".*?\&chapter_no=\d+">((?!<).*?)</g,pagefind:{pid:"$1",img:"$2",title:"$3",content:"$4"},pagedeal:function(a,b){b=b||{};var c=a.pid,f=a.img,e=a.title,d="更新至 "+a.content;if(b.multupdate)return b.multupdate(obj_contact(b,{pid:c,img:f,title:e,content:d})),!1;if(b.multhot)return b.multhot(obj_contact(b,{pid:c,img:f,title:e,content:d})),!1;if(b.multsearch)return b.multsearch(obj_contact(b,{pid:c,img:f,title:e,content:d})),
!1;addcardlist({pid:c,title:e,name:e,img:f,content:d,comment:1,preview:0,extrabutton:""})}}});
