ExView.Plugins({info:{name:"半次元Cosplay图库",version:"2.2",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAMFBMVEUAAAD/cKP/daX/utb/t9T/////s9H/b6L/utb/////////////daX/utb/b6L/caR1qzmHAAAAC3RSTlMA/fXu/QP+8vEJBupgDmwAAABbSURBVAjXY2DgCWBg4DzAwMBwGkgwbQcK7N7DEHV69wMgY/eZM7vBDCCAMAR373bbLQBkyO/efWX3AagUKkN79+69YMY+YeNuEOMMSOYuXA2miAIDwxkQuMsAAARdRpkQ7tigAAAAAElFTkSuQmCC",db:"bcycos",apihost:"http://bcy.net/coser/",pagetitle:["<br>","收藏","本周排行榜",
"类型","下载"],lazyload:!0,download:!0,setting:!0,search:!1,nativeres:!0,theme:"pink",cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){ExView.workers.index.loader()}})},flags:{indexflag:{loader:function(a){a.front||a.page||addtypelist('<div align="center" class="list-block"><img src="img/logo.png"/><br>类型<br>正在加载...<div class="progress"></span></div>',2);return{url:pluginfo(a.plugin).apihost+
"toppost100",method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{"User-Agent":"ExView",Referer:pluginfo(a.plugin).apihost},successfn:function(b,c){ExView.workers.index.countfinder(obj_contact(a,{result:b,header:c}));a.front||a.page||ExView.workers.type.finder({result:b,plugin:a.plugin});a.successfn&&a.successfn({result:b,header:c})},errorfn:function(){a.page||addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>加载失败，请刷新重试！</a></div>',
2);ExView.fw.alert("网络错误！","ExView")},canclefn:function(){a.page||addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>加载失败，请刷新重试！</a></div>',2)},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),name:"首页",title:a.title,img:a.img}}},finder:function(a){return{reg:/<i\s*class="i-rise">(.*?)<\/span>/g,
str:getresult(a.result),find:"$1",successfn:function(a){if(a){var c=getstr(/\/coser\/detail\/([\w,\/]+)/,a).replace(/\//g,"_"),e=getstr(/alt="((?!\").*?)"/,a).split(" "),d=1<e.length?e.pop():"",e=e.join(" ");a=getstr(/src="((?!\").*?)"/,a);addcardlist({pid:c,title:e,img:a,stitle:d,comment:0})}else addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',2)},errorfn:function(){a.page||setnowlistname("首页","",pluginfo(a.plugin).icon);
ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("网络错误！","ExView")}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="-1|首页|index";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},typeflag:{loader:function(a){return{successfn:function(){ExView.workers.index.loader()}}},finder:function(a){addtypelist({title:"本周排行榜",img:pluginfo(a.plugin).icon,
content:"本周排行榜"});addtypelist({tid:"lastday",listflag:"toppost100?type=lastday",title:"今日排行榜",img:pluginfo(a.plugin).icon,content:"今日排行榜"});addtypelist({tid:"preview",listflag:"toppost100?type=preview",title:"预告榜",img:pluginfo(a.plugin).icon,content:"预告榜"});addtypelist({tid:"newPeople",listflag:"toppost100?type=newPeople",title:"新人榜",img:pluginfo(a.plugin).icon,content:"新人榜"});
addtypelist({tid:"discover",listflag:"discover?",title:"精选COS",img:pluginfo(a.plugin).icon,content:"精选COS"});addtypelist({tid:"allwork",listflag:"allwork?",title:"最新正片",img:pluginfo(a.plugin).icon,content:"最新正片"});addtypelist({tid:"allpre",listflag:"allpre?",title:"最新预告",img:pluginfo(a.plugin).icon,content:"最新预告"});return!1}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+a.flag+
"&p="+(a.page||1),method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{"User-Agent":"ExView",Referer:pluginfo(a.plugin).apihost},successfn:function(b,c){b?(ExView.workers.list.countfinder(obj_contact(a,{result:b,header:c})),a.successfn&&a.successfn({result:b,header:c})):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+a.title+"】<br>获取失败！","ExView"))},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+
"页":""),name:"【"+a.title+"】",title:a.title,img:a.img}}},finder:function(a){var b=plugfns(a.plugin).getrule(a.keyword),c=b.pagefind,e=b.pagedeal;return{reg:b.pagerule,str:getresult(a.result),find:c,successfn:function(b){b?e(b,a):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{reg:/&p=(\d+)">尾页<\/a>/,str:a.result,find:"$1",successfn:function(b){mySession.nowlistpages=
(b||"-1")+"|"+a.keyword+"|list";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},searchflag:{loader:function(a){a.multsearch?a.callback():ExView.fw.alert("此插件不支持搜索功能！")},finder:!1,countloader:!1,countfinder:!1},contentflag:{loader:function(a){return{successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"正在加载内容页...",title:"内容页",name:getlistname(a.pid),
img:getlistimg(a.pid)}}},finder:function(a){return{successfn:function(b,c,e,d){console.log(typeof b);if(a.checkupdate)return{pid:a.pid,cid:"1",title:"全1话"};d=[];d[0]=additemlist({id:0,newest:a.newest&&0==e,pid:a.pid,cid:"1",title:"全1话",count:1,reverse:0});return d}}},infoloader:function(a){return!1},infofinder:function(a){console.log(a);return!1}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"detail/"+(a.pid||"").replace(/\_/g,"/"),method:"GET",timeout:120,
nativerequest:pluginfo(a.plugin).nativeres,header:{"User-Agent":"ExView",Referer:pluginfo(a.plugin).apihost},successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"正在加载图片信息...",title:"图片",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){console.log(a);return{reg:/detail_clickable'\s*src='((?!\').*?)'/g,str:a.result,find:"$1",successfn:function(b,c,e,d){array_count(c)?(console.log(d),a.download?chapterpredownload({source:d,
download:a.download,plugin:a.plugin}):chapterviewer({source:d,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.download?chapterpredownload({error:"解析错误！",download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("图片信息获取失败！","ExView"));return!0}}}},commentflag:{loader:!1,finder:!1},previewflag:{loader:!1,finder:!1,more:!1},pageimgflag:{parser:!1},
updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"allwork?&p="+(a.page||1),method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{"User-Agent":"ExView",Referer:pluginfo(a.plugin).apihost},successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){var b,c,e,d=plugfns(a.plugin).getrule("allwork");b=d.pagerule;c=d.pagefind;e=d.pagedeal;return{reg:b,str:getresult(a.result),find:c,successfn:function(b){b&&e(b,a)}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"discover?&p="+(a.page||1),method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{"User-Agent":"ExView",Referer:pluginfo(a.plugin).apihost},successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){var b,c,e,d=plugfns(a.plugin).getrule("discover");b=d.pagerule;c=d.pagefind;e=d.pagedeal;return{reg:b,str:getresult(a.result),find:c,successfn:function(b){b&&e(b,a)}}}}},fns:{getrule:function(a){switch(a){default:case "lastday":case "preview":case "newPeople":case "allwork":case "allpre":pagerule=
/\/coser\/(.*?)<\/a>/g;pagefind="$1";pagedeal=function(a,c){var e=getstr(/detail\/([\w,\/]+)/,a).replace(/\//g,"_"),d=getstr(/alt="((?!\").*?)"/,a).split(" "),f=1<d.length?d.pop():"",d=d.join(" "),g=getstr(/src="((?!\").*?)"/,a);e&&plugfns(c.plugin).pagedeal({pid:e,title:d,img:g,stitle:f},c)};break;case "discover":pagerule=/\/coser\/(.*?)<\/a>/g,pagefind="$1",pagedeal=function(a,c){var e=getstr(/detail\/([\w,\/]+)/,a).replace(/\//g,"_"),d=getstr(/title="((?!\").*?)"/,a),f=getstr(/mr5\s*">((?!<).*?)<\/span>/,
a),g=getstr(/src="((?!\").*?)"/,a);e&&plugfns(c.plugin).pagedeal({pid:e,title:d,img:g,stitle:f},c)}}return{pagerule:pagerule,pagefind:pagefind,pagedeal:pagedeal}},pagedeal:function(a,b){b=b||{};var c=a.pid,e=a.title,d=a.img,f=a.stitle;if(b.multupdate)return b.multupdate(obj_contact(b,{pid:c,img:d,title:e,content:f})),!1;if(b.multhot)return b.multhot(obj_contact(b,{pid:c,img:d,title:e,content:f})),!1;if(b.multsearch)return b.multsearch(obj_contact(b,{pid:c,img:d,title:e,content:f})),!1;addcardlist({pid:c,
title:e,name:e,img:d,content:"",stitle:f,comment:0,preview:0,extrabutton:""})}}});
