ExView.Plugins({info:{name:"BiliPlus视频",version:"2.2",author:"Gentle",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAMFBMVEUziP/h7f+ZxP94sP/////y9/+EuP9boP9bn//W6P/q8/+92P+axP9wrP9pqP9gov87WRrDAAAAK0lEQVQI12MgAyQwMDC72AdpXZsGZMhJCCkWbAAyYjyADAMgIxLEYCATAAAVAQcc4jPzZgAAAABJRU5ErkJggg==",db:"biliplus",type:"video",apihost:"https://www.biliplus.com/",pagetitle:["<br>","收藏","连载动画","类型","下载"],typelistmode:!0,download:!1,
lazyload:!0,setting:!0,cdn:""},set:function(b){},unset:function(b){},init:function(b){ExView.workers.fav.listloader({callback:function(){}})},flags:{indexflag:{loader:function(b){return{url:"https://api.bilibili.com/archive_rank/getarchiverankbypartion?tid=33&pn="+(b.page||1),method:"GET",timeout:120,successfn:function(a,c){b.callback({img:pluginfo(b.plugin).icon,multpage:!0,result:a,header:c})}}},finder:function(b){return{json:!0,str:b.result,successfn:function(a){a=((a||{}).data||{}).archives;array_count(a)?
plugfns(b.plugin).pagedeal(a,b):b.callback()}}},countloader:!1,countfinder:function(b){return{json:!0,str:b.result,successfn:function(a){try{a=(a=(a||{}).pages)||0}catch(c){a=-1}b.callback({pagecount:a})}}}},typeflag:{loader:function(b){return{url:pluginfo(b.plugin).apihost+"?list",method:"GET",timeout:120,successfn:function(a,c){b.callback({result:a,header:c})}}},finder:function(b){b.callback({title:"连载动画",img:pluginfo(b.plugin).icon,group:{name:"daohang",title:"导航"},
content:"连载动画"});b.callback({tid:"cached",title:"已缓存的投稿",img:pluginfo(b.plugin).icon,listflag:"api/cached?page={{page}}",group:{name:"daohang",title:"导航"},content:"已缓存的投稿"});var a=[];getstr(/tidTree=([\s\S]*)chklist/,b.result).split("\n").forEach(function(b){"\t"==b[0]&&(b=b.split(":"),b.shift(),a.push(b.join(":")))});a=JSON.parse("["+a.join("")+"]");console.log(a);return{successfn:function(c){c=a;array_count(c)&&
c.forEach(function(a,c){var f="s"+ExView.tools.md5.hex_md5(a.name),g=a.name;(function(a,c){(a.child||[]).forEach(function(c,d){b.callback({tid:c,title:a.child_name[d],img:pluginfo(b.plugin).icon,group:{name:f,title:g},content:a.child_name[d]})})})(a,c)});$$.get(pluginfo(b.plugin).apihost+"?bangumi",function(a){a=getstr(/bangumis=(.*?)\;\r*\n/g,a);a=JSON.parse(a);console.log(a);var c="周日 周一 周二 周三 周四 周五 周六".split(" ");(a||[]).forEach(function(a,
d){(function(c){(a||[]).forEach(function(a){b.callback({tid:"week",listflag:a.link,title:a.title,img:0==a.cover.indexOf("//")?"https:"+a.cover:a.cover,group:{name:"s_"+ExView.tools.md5.hex_md5(c),title:c},content:a.title+"("+a.count+")"+(a.lastUpdate?"<br>"+getLocalTime(1E3*a.lastUpdate):"")})})})(c[d])})})}}}},listflag:{loader:function(b){return{url:b.flag?pluginfo(b.plugin).apihost+("week"==b.tid?"api/bangumi?season="+b.flag.substring(2):b.flag.replace("{{page}}",b.page||1)):"https://api.bilibili.com/archive_rank/getarchiverankbypartion?tid="+
b.tid+"&pn="+(b.page||1),method:"GET",timeout:120,successfn:function(a,c){b.callback({multpage:!0,result:a,header:c})}}},finder:function(b){return{json:!0,str:b.result,successfn:function(a){"cached"==b.tid?(a=(a||{}).data,(a||[]).forEach(function(a){b.callback({pid:a[0],title:a[1],img:"img/nopic.png",stitle:a[2]+" "+a[3],content:"",comment:1})})):"week"==b.tid?(a=(a||{}).result.episodes,(a||[]).forEach(function(a){var d=a.av_id,e=b.title,f=0==a.cover.indexOf("//")?"https:"+a.cover:a.cover;b.callback({pid:d,
title:e,img:f,stitle:"AV"+d,content:"第"+a.index+"集 "+a.index_title,comment:1})})):(a=((a||{}).data||{}).archives,array_count(a)?plugfns(b.plugin).pagedeal(a,b):b.callback())}}},countloader:!1,countfinder:function(b){return{json:!0,str:b.result,successfn:function(a){try{a=(a=b.flag?(a||{}).pages:Math.ceil((a||{}).data.page.count/(a||{}).data.page.size))||0}catch(c){a=-1}"week"==b.tid&&(a=-1);b.callback({pagecount:a})}}}},searchflag:{loader:function(b){return{url:"https://m.bilibili.com/search/searchengine",
method:"POST",data:'{"keyword":"'+encodeURIComponent(b.keyword)+'","page":'+(b.page||1)+',"pagesize":20,"platform":"h5","search_type":"all","main_ver":"v3","order":"totalrank","bangumi_num":3,"movie_num":3}',timeout:120,postjson:!0,successfn:function(a,c){b.callback({multpage:!0,result:a,header:c})}}},finder:function(b){return{json:!0,str:b.result,successfn:function(a){a=(a||{}).result.video;array_count(a)?(console.log(a),plugfns(b.plugin).pagedeal(a,b)):b.callback()}}},countloader:!1,countfinder:function(b){return{json:!0,
str:b.result,successfn:function(a){try{a=(a=(a||{}).numPages)||0}catch(c){a=-1}b.callback({pagecount:a})}}}},contentflag:{loader:function(b){return{url:"https://www.bilibili.com/video/av"+b.pid+"/",method:"GET",timeout:120,referer:"",successfn:function(a,c){var d=getquery(a,"#plist option"),e={list:[]};$$(d).each(function(a){e.list.push({index:a,cid:$$(this).attr("cid"),part:$$(this).text()})});e.list.length||e.list.push({index:0,cid:getstr(/cid\=(\d+)\&/,a)});a=JSON.stringify(e);b.callback({result:a,
header:c})},errorfn:function(a,c,d){a={list:[{index:0,cid:getstr(/cid\=(\d+)\&/,result)}]};result=JSON.stringify(a);b.callback({result:result,header:d.headers})}}},finder:function(b){return{json:!0,str:b.result,successfn:function(a,c,d,e){a=(a||{}).list;if(array_count(a)){if(b.checkupdate)return c=a.length,a=a.pop(),b.callback({pid:b.pid,cid:a.cid+"_"+(parseInt(a.index)+1),title:a.part||"第 "+c+" 集"}),!0;e=[];a.forEach(function(a,c){e[c]=b.callback({id:c,newest:b.newest&&0==c,pid:b.pid,cid:a.cid+
"_"+(parseInt(a.index)+1),title:a.part||"第 "+(c+1)+" 集",count:a.length,reverse:0})});return e}b.callback()}}},infoloader:!1,infofinder:function(b){return{successfn:function(a,c,d,e){b.callback({added:b.data,comment:1,preview:0,sourceurl:"https://www.bilibili.com/video/av"+b.pid+"/",tags:gettag(myContent.name)});return!0}}}},parseflag:{loader:function(b){return{url:"https://api.bilibili.com/playurl?aid="+b.pid+"&page=1&platform=html5&quality=1&vtype=mp4&token=",method:"GET",timeout:120,cookie:"sid=l8ux4sc5; fts=1506868253; buvid3=9B790452-4F56-467D-B7CE-CF4DBB77F6C21984infoc; UM_distinctid=15ed858d65cfe-0f11e319c9a37-514e5e4d-100200-15ed858d65d1d6",
successfn:function(a,c){-5009==JSON.parse(a).code?ExView.modules.curl({url:pluginfo(b.plugin).apihost+"api/geturl?bangumi=0&av="+b.pid+"&page="+b.cid.split("_")[1],method:"GET",timeout:120,successfn:function(a,c){b.callback({web:!0,result:a,header:c})},showinfo:{text:"正在尝试获取...",title:"视频",name:getlistname(b.pid),img:getlistimg(b.pid)}}):b.callback({result:a,header:c})}}},finder:function(b){console.log(JSON.parse(b.result));return{successfn:function(a,c,d,e){if(b.web&&
(a=JSON.parse(b.result),"error"==a.mode))return ExView.fw.hidePreloader(),ExView.fw.alert("版权受限，将跳转网站播放！",function(){var a="https://www.bilibili.com/video/av"+b.pid+"/";isdesktop()?nw.Shell.openExternal(a):window.open(a,"_system","location=no,zoom=no")}),!0;if(!b.web){a=JSON.parse(b.result);var f=a.durl[0].url,g=a.img,h="mp4",k=getstr(/(\d+)\.xml/,a.cid),l=function(a){b.callback({poster:g,url:"https://www.bilibili.com/video/av"+b.pid+
"/",source:f,type:"video",videoType:h,title:encodeURIComponent(myContent.name)+getnavundertitle(b.title),danmaku:{id:"Bilibili_"+(k||b.cid.split("_")[0]),api:"https://api.prprpr.me/dplayer/",token:"tokendemo",maximum:1E3,addition:[a?[a]:[]],user:"ExView"}})};ExView.modules.curl({url:"https://comment.bilibili.com/"+(k||b.cid.split("_")[0])+".xml",successfn:function(a){var b=[];a=getquery(a,"d");$$(a).each(function(){var a=$$(this).attr("p"),c=$$(this).text(),a=a.split(",")[0];b.push({author:"",time:a,
text:c,color:"#ffffff",type:"right"})});b={code:1,danmaku:b};console.log(b);a=new Blob([JSON.stringify(b)],{type:"text/plain; charset=utf-8"});var c=URL.createObjectURL(a);setTimeout(function(){URL.revokeObjectURL(c)},5E3);l(c);console.log(c)},errorfn:function(a){l()},showinfo:{text:"正在获取弹幕信息...",title:"视频",name:getlistname(b.pid),img:getlistimg(b.pid)}});return!0}a=JSON.parse(b.result);k=a.cid;g=$$(".listcover img").attr("src");h="mp4";a=(a||{}).data;
f="";for(d=0;d<a.length;d++)if(a[d].url){f=a[d].url;break}l=function(a){b.callback({poster:g,url:"https://www.bilibili.com/video/av"+b.pid+"/",source:f,type:"video",videoType:h,title:myContent.name+getnavundertitle(b.title),danmaku:{id:"Bilibili_"+(k||b.cid.split("_")[0]),api:"https://api.prprpr.me/dplayer/",token:"tokendemo",maximum:1E3,addition:a?[a]:[],user:"ExView"}})};ExView.modules.curl({url:"https://comment.bilibili.com/"+(k||b.cid.split("_")[0])+".xml",successfn:function(a){var b=[];a=getquery(a,
"d");$$(a).each(function(){var a=$$(this).attr("p"),c=$$(this).text(),a=a.split(",")[0];b.push({author:"",time:a,text:c,color:"#ffffff",type:"right"})});b={code:1,danmaku:b};console.log(b);a=new Blob([JSON.stringify(b)],{type:"text/plain; charset=utf-8"});var c=URL.createObjectURL(a);setTimeout(function(){URL.revokeObjectURL(c)},1E3);l(c);console.log(c)},errorfn:function(a){l()},showinfo:{text:"正在获取弹幕信息...",title:"视频",name:getlistname(b.pid),img:getlistimg(b.pid)}});
return!0}}}},commentflag:{loader:function(b){return{url:pluginfo(b.plugin).apihost+"api/reply?isReply=0&type=1&sort=0&oid="+b.pid+"&pn="+(b.page||1)+"&callback=review&_="+getTimeNow(),method:"GET",timeout:120,successfn:function(a,c){a?b.callback({result:a,header:c,commentbrowser:{url:"https://www.bilibili.com/video/av"+b.pid+"/",title:myContent.name||"",browser:!0,flag:""}}):b.callback()}}},finder:function(b){return{json:!0,str:b.result,successfn:function(a,c,d,e){a=(a||{}).data;if(array_count(a)){c=
Math.ceil(a.page.count/a.page.size);a=a.replies;for(var f in a)b.callback({page:b.page||1,pagecount:c,comment:{text:a[f].content.message,name:a[f].member.uname||"",avatar:a[f].member.avatar,type:"received",label:getLocalTime(1E3*parseInt(a[f].ctime||0)),day:"",time:"",reverse:1,extra:""}})}}}},send:!1},previewflag:{loader:!1,finder:!1},pageimgflag:{parser:!1},updateflag:{loader:function(b){return{url:pluginfo(b.plugin).apihost+"api/list.php?callback=showlist&page="+(b.page||1),method:"GET",timeout:120,
successfn:function(a,c){b.callback({result:getstr(/showlist\((.*?)\)\;/g,a),header:c})}}},finder:function(b){return{json:!0,str:b.result,successfn:function(a){a=(a||{}).list;array_count(a)?plugfns(b.plugin).pagedeal(a,b):b.callback()}}}},hotflag:{loader:function(b){return{url:"https://api.bilibili.com/archive_rank/getarchiverankbypartion?tid=33&pn="+(b.page||1),method:"GET",timeout:120,successfn:function(a,c){b.callback({result:a,header:c})}}},finder:function(b){return{json:!0,str:b.result,successfn:function(a){a=
((a||{}).data||{}).archives;array_count(a)?plugfns(b.plugin).pagedeal(a,b):b.callback()}}}}},fns:{playerpagecallback:function(b){try{screen.lockOrientation("landscape"),$$(".page[data-page='webpage']").find(".dynamic-page-close").on("click",function(){screen.unlockOrientation()})}catch(a){}},pagedeal:function(b,a){a=a||{};b.forEach(function(b){var d=b.aid,e=b.pic,e=0==e.indexOf("//")?"https:"+e:e,f=b.title,g=b.author+" "+(b.create||getLocalTime(1E3*parseInt(b.pubdate))),h=b.duration||"";b=getboxitem(b.typename||
b.tname)+(h?getboxitem("时长"+h)+b.description:"");if(a.multupdate||a.multhot||a.multsearch)return a.callback(obj_contact(a,{pid:d,img:e,title:f,content:g})),!1;a.callback({pid:d,title:f,img:e,stitle:g,content:b,comment:1})})}}});
