ExView.Plugins({info:{name:"CC图库漫画",version:"2.2",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAABCFBMVEUAAAD80wD71wLfxRPCpg7mxgb42AX+2QP83gHb2da9s4VzcnJGQ1rMrxXfwQz70wvnyAvjxAvfxQrLrgr31AbvzAX40wPzzwP11wH81QDW1NPT0dKxsbKmpaafnZe8tJa4sZW2rZGln5DBt3/97n356XyZkHiwpHa0qHOpnm+Be27p2We9rWKwoWHEtF314Vmpm1iOgVLLt06Mfk2pmUz/6kvQuUZST0bLtEOikUP94ELMuECaiTw8PDxSTDMzMzPArDBLPyqhiynFryfbxCTNtSBgUCD82RzgwBqEbxnIrBjBphi/pBWljRXRshJLQA/30w7jyw64nAvx1AftyweskgX/6AP42wNLuxxrAAAAAXRSTlMAQObYZgAAAKdJREFUGNONjkUOw0AMRWeapEkhzGVmZmZm7v1vUkuz6DZvYek/f8lGzgh5PL5wot7MBEn2NnbUbFSsas91fAw5mR6w9FnqbI2Hcu/CPiVia+4XaEv1bz5XhFYixrb6lk8uc09/Jwi5MCAdLjA5quwjQj/CtIVcAAEKCIM3MXbHyNEWB+bW0zFXmhJTo9ysNpShUokgQjS7YFjotfP/7/s882KWBeSAH7VZEHpFpIFlAAAAAElFTkSuQmCC",
db:"cctuku",apihost:"http://m.tuku.cc/",pagetitle:["<br>","收藏","首页","类型","下载"],lazyload:!0,download:!0,setting:!0,gallerymode:!0,typelistmode:!0,theme:"amber",cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){ExView.workers.index.loader()}})},flags:{indexflag:{loader:function(a){a.front||a.page||setnowlistname("首页","",pluginfo(a.plugin).icon);a.front||a.page||addtypelist('<div align="center" class="list-block"><img src="img/logo.png"/><br>类型<br>正在加载...<div class="progress"></span></div>',
2);return{url:pluginfo(a.plugin).apihost,method:"GET",timeout:120,successfn:function(b,c){ExView.workers.index.countfinder(obj_contact(a,{result:b,header:c}));ExView.workers.type.finder({result:b,plugin:a.plugin});a.successfn&&a.successfn({result:b,header:c})},errorfn:function(){a.page||setnowlistname("首页","",pluginfo(a.plugin).icon);addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>加载失败，请刷新重试！</a></div>',
2);ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("网络错误！","ExView")},canclefn:function(){a.page||setnowlistname("首页","",pluginfo(a.plugin).icon);addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>加载失败，请刷新重试！</a></div>',2)},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+
"页":""),name:"首页",title:a.title,img:a.img}}},finder:function(a){return{reg:/main-list-con">(.*?)<\/div>/g,str:getresult(a.result),find:"$1",successfn:function(a){console.log(JSON.stringify(a));if(a){var c=getstr(/\/comic\/(\d+)\//,a),d=getstr(/alt="((?!\").*?)"/,a),e=getstr(/src="((?!\").*?)"/,a);a=gettext(getstr(/"orange-footnotes">((?!\").*?)<\/a>/,a));addcardlist({pid:c,title:d,img:e,content:a,comment:1})}else addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',
2)},errorfn:function(){a.page||setnowlistname("首页","",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("网络错误！","ExView")}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="-1|首页|index";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},typeflag:{loader:function(a){return{successfn:function(){ExView.workers.index.loader()}}},finder:function(a){addtypelist({title:"首页",
img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"首页"});addtypelist({tid:"",title:"今日漫画",listflag:"newest",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"今日漫画"});addtypelist({tid:"",title:"热门连载",listflag:"lianzai",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"热门连载"});return{reg:/href="\/list\/(list|comic)_(\d+)_1.htm"\s*>((?!<).*?)<\/a>/g,
str:a.result,find:"$1{{separator}}$2{{separator}}$3",successfn:function(b){b=b.split("{{separator}}");array_count(b)?addtypelist({tid:b[1],title:b[2],img:pluginfo(a.plugin).icon,group:{name:"fenlei",title:"分类"},listflag:b[0],content:b[2]}):addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>加载失败，请刷新重试！</a></div>',2)}}}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
("newest"==a.flag||"lianzai"==a.flag?a.flag+"/"+(a.page||1):"list/"+a.flag+"_"+a.keyword+"_"+(a.page||1)+".htm"),method:"GET",timeout:120,successfn:function(b,c){b?(ExView.workers.list.countfinder(obj_contact(a,{result:b,header:c})),a.successfn&&a.successfn({result:b,header:c})):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+a.title+"】<br>获取失败！","ExView"))},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":
""),name:"【"+a.title+"】",title:a.title,img:a.img}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:a.result,find:plugfns(a.plugin).pagefind,successfn:function(b){b?plugfns(a.plugin).pagedeal(b):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="0|"+a.keyword+"|list";mySession.nowlistpage=1;console.log(mySession.nowlistpages);
return!0}}}},searchflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"comic/search?word="+a.keyword+"&page="+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){b?(a.multsearch||(ExView.workers.search.countfinder(obj_contact(a,{result:b,header:c})),setnowlistname("搜索【"+a.keyword+"】")),a.successfn&&a.successfn({result:b,header:c})):a.multsearch?a.multsearch():(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+a.keyword+"】<br>获取搜索结果失败！",
"ExView"))},showinfo:{text:"正在搜索..."+(1<a.page?"<br>第"+a.page+"页":""),name:"【"+a.keyword+"】",title:"搜索"}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:a.result,find:plugfns(a.plugin).pagefind,successfn:function(b,c,d){console.log(b);b?plugfns(a.plugin).pagedeal(b,a):a.multsearch?a.multsearch():addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}},countloader:function(a){return!1},
countfinder:function(a){return{successfn:function(b){mySession.nowlistpages="0|"+a.keyword+"|search";mySession.nowlistpage=1;console.log(mySession.nowlistpages)}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"comic/"+a.pid+"/",method:"GET",timeout:120,successfn:function(b,c){b?a.successfn&&a.successfn({result:b,header:c}):a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},showinfo:{text:"正在加载内容页...",
title:"内容页",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){return{reg:/<a href="\/comic\/(\d+)\/([\w,\d,\-]+)\/">\s*((?!<).*?)\s*<\/a>/g,str:getstr(/<ul\s*class="list-body">(.*?)<\/ul>/,getresult(a.result)),find:{pid:"$1",cid:"$2",title:"$3"},successfn:function(b,c,d,e){console.log(typeof b);if(array_count(b)){if(a.checkupdate)return{pid:b.pid,cid:b.cid,title:b.title};additemlist({id:c.length-d-1,newest:a.newest&&0==d,pid:b.pid,cid:b.cid,title:b.title,count:c.length,
reverse:1})}else a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},afterfn:function(){a.checkupdate||ExView.workers.content.infofinder(a)}}},infoloader:function(a){return!1},infofinder:function(a){console.log(a);return{reg:/<div class="container book-title">(.*?)<div\s*class="book-details-all"/g,str:getresult(a.result),find:"$1",successfn:function(b,c,d,e){console.log(JSON.stringify(b));c=getstr(/<img(?!<).*?src="((?!\").*?)"/,
b);d=getstr(/<h1>((?!<).*?)<\/h1>/,b);e=gettext(getstr(/<dt>作者：<\/dt><dd>(.*?)<\/dd>/,b).trim());var f=gettext(getstr(/<dt>类别：<\/dt><dd>(.*?)<\/dd>/,b).trim().replace(/<a\s*href="\/list\/list_\d+_\d+.htm">/g,","));gettext(getstr(/<dt>地区：<\/dt><dd>(.*?)<\/dd>/,b).trim());var k=gettext(getstr(/<dt>更新至：<\/dt><dd>(.*?)<\/dd>/,b).trim()),g=gettext(getstr(/<dt>更新于：<\/dt><dd>(.*?)<\/dd>/,b).trim());b=getstr(/class="book-details">(.*?)<\/div>/,
b).trim();var h=gettag(f),h=f.split(",").map(function(a){return gettag(a.trim())}).join(""),h=h+e.split(",").map(function(a){return gettag(a.trim())}).join("");setlistpic({name:d,img:c,added:a.data,description:"<p>【作者】"+e+"<br>【类型】"+f.replace(/,/g," ")+"<br>【最新话】"+k+"<br>【更新日期】"+g+"<br>【简介】"+gettext(b)+"</p>",comment:1,preview:0,tags:gettag(d)+gettag(status)+h,sourceurl:pluginfo(a.plugin).apihost+
"comic/"+a.pid+"/"});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"comic/"+a.pid+"/"+a.cid+"/",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"正在加载图片信息...",title:"图片",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){console.log(a);return{reg:/<option\s*value="\/comic\/(\d+)\/([\w,\d,\-]+)\/([(\d+)\/]*)"/g,str:a.result,find:{pid:"$1",
ccid:"$2",index:"$3"},successfn:function(b,c,d,e){array_count(e)?(b=e.map(function(b){return getpageload(pluginfo(a.plugin).apihost+"comic/"+b.pid+"/"+b.ccid+"/"+b.index,a.plugin||mySession.nowplugin)}),console.log(b),a.download?chapterpredownload({source:b,download:a.download,plugin:a.plugin}):chapterviewer({source:b,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.download?chapterpredownload({error:"解析错误！",download:a.download,
plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("图片信息获取失败！","ExView"));return!0}}}},commentflag:{loader:function(a){return{url:"http://rtk.um5.cc/comment/get?model=1&item_id="+a.pid+"&page="+parseInt(a.page||1),method:"GET",timeout:120,successfn:function(b,c){b?a.callback&&a.callback({result:b,header:c,commentbrowser:{url:"http://www.tuku.cc/comic/"+a.pid+"/",title:"评论 - "+pluginfo(a.plugin).name+'<br><span style="font-size:16px">'+
(myContent.name||"")+"</span>",browser:!1,flag:""}}):a.callback&&a.callback()}}},finder:function(a){console.log(a);return{json:!0,str:(a.result||"").substr(1,a.result.length-2),successfn:function(b,c,d,e){if(array_count(b)){c=b.pages;b=b.list;for(var f in b)a.callback&&a.callback({page:a.page||1,pagecount:c,comment:{text:b[f].message,name:b[f].author_name,avatar:"",type:"received",label:b[f].created_at,day:"",time:"",reverse:1,extra:""}})}}}},send:!1},previewflag:{loader:!1,finder:!1,more:!1},pageimgflag:{parser:function(a){return{reg:/eval\(((?!<).*?)\)\r*\n/g,
str:a.result,find:"$1",successfn:function(b){(function(){var c=getstr(/var\s*serverUrl\s*=\s*'(.*?)'\s*;/,a.result)||"http://tkpic.um5.cc";eval('var serverUrl="'+c+'";'+eval("("+b+")"));c=getstr(/var\s*page\s*=\s*(\d+)\s*;/,a.result);a.loadimgurl(getImgUrl(c,0))})()}}}},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"newest/"+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,
str:a.result,find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));b&&plugfns(a.plugin).pagedeal(b,a)}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"lianzai/"+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:a.result,find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));b&&plugfns(a.plugin).pagedeal(b,
a)}}}}},fns:{pagerule:/<div\s*class="row">((?:.|[\r\n])*?)<\/font><\/dd><\/dl>/g,pagefind:"$1",pagedeal:function(a,b){b=b||{};a=getresult(a);var c=getstr(/\/comic\/(\d+)\//,a),d=gettext(getstr(/<div\s*class="book-name">(.*?)<\/div>/,a)),e=getstr(/src="((?!\").*?)"/,a),f=gettext(getstr(/<dt>作者：<\/dt><dd>(.*?)<\/dd>/,a).trim()),k=gettext(getstr(/<dt>类别：<\/dt><dd>(.*?)<\/dd>/,a).trim()),g=gettext(getstr(/<dt>更新至：<\/dt><dd>(.*?)<\/dd>/,a).trim()),h=gettext(getstr(/<dt>更新于：<\/dt><dd>(.*?)$/,
a).trim());if(b.multupdate)return b.multupdate(obj_contact(b,{pid:c,img:e,title:d,content:g})),!1;if(b.multhot)return b.multhot(obj_contact(b,{pid:c,img:e,title:d,content:g})),!1;if(b.multsearch)return b.multsearch(obj_contact(b,{pid:c,img:e,title:d,content:g})),!1;addcardlist({pid:c,title:d,name:d,img:e,content:(k?"【类型】"+k+"<br>":"")+(f.replace(/&nbsp;/g,"")?"【作者】"+f+"<br>":"")+"【最新】"+g,stitle:(status?"【"+status+"】":"")+h,comment:1,
preview:0,extrabutton:""})}}});
