ExView.Plugins({info:{name:"CC图库漫画",version:"2.2",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAABCFBMVEUAAAD80wD71wLfxRPCpg7mxgb42AX+2QP83gHb2da9s4VzcnJGQ1rMrxXfwQz70wvnyAvjxAvfxQrLrgr31AbvzAX40wPzzwP11wH81QDW1NPT0dKxsbKmpaafnZe8tJa4sZW2rZGln5DBt3/97n356XyZkHiwpHa0qHOpnm+Be27p2We9rWKwoWHEtF314Vmpm1iOgVLLt06Mfk2pmUz/6kvQuUZST0bLtEOikUP94ELMuECaiTw8PDxSTDMzMzPArDBLPyqhiynFryfbxCTNtSBgUCD82RzgwBqEbxnIrBjBphi/pBWljRXRshJLQA/30w7jyw64nAvx1AftyweskgX/6AP42wNLuxxrAAAAAXRSTlMAQObYZgAAAKdJREFUGNONjkUOw0AMRWeapEkhzGVmZmZm7v1vUkuz6DZvYek/f8lGzgh5PL5wot7MBEn2NnbUbFSsas91fAw5mR6w9FnqbI2Hcu/CPiVia+4XaEv1bz5XhFYixrb6lk8uc09/Jwi5MCAdLjA5quwjQj/CtIVcAAEKCIM3MXbHyNEWB+bW0zFXmhJTo9ysNpShUokgQjS7YFjotfP/7/s882KWBeSAH7VZEHpFpIFlAAAAAElFTkSuQmCC",
db:"cctuku",apihost:"http://m.tuku.cc/",pagetitle:["<br>","收藏","首页","类型","下载"],lazyload:!0,download:!0,setting:!0,gallerymode:!0,theme:"amber",cdn:""},set:function(a){},unset:function(a){},init:function(a){ExView.workers.fav.listloader({callback:function(){}})},flags:{indexflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost,method:"GET",timeout:120,successfn:function(b,c){a.callback({img:pluginfo(a.plugin).icon,multpage:!0,result:b,header:c})}}},
finder:function(a){return{query:!0,selector:".indexList>li,.m_list_1 li",str:a.result,successfn:function(b){if(array_count(b)){var c=getstr(/\/comic\/(\d+)\//g,$$(b).find("a").attr("href")),d=$$(b).find("p").text();b=$$(b).find("img").attr("src");a.callback({pid:c,title:d,img:b,comment:0})}else a.callback()}}},countloader:!1,countfinder:function(a){return{successfn:function(b){a.callback({pagecount:-1})}}}},typeflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"Category/index.html",method:"GET",
timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){a.callback({title:"首页",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"首页"});a.callback({tid:"hot_0",title:"最热门",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"最热门"});a.callback({tid:"newest_0",title:"最新发布",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},
content:"最新发布"});a.callback({tid:"top_0",title:"推荐漫画",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"推荐漫画"});return{query:!0,selector:".groupList>li",str:a.result,successfn:function(b){if(array_count(b)){var c=getstr(/list\/([\w,\_,\d]+)_1\.htm/,$$(b).find("a").attr("href"));(c=(c||"").replace("list","tag").replace("comic","area"))||(c=($$(b).find("a").attr("href")||"").substring(1));a.callback({tid:c,title:$$(b).find(".nameBar").text(),
img:pluginfo(a.plugin).apihost+($$(b).find("img").attr("src")||"").substring(1),group:{name:"fenlei",title:"分类"},content:$$(b).find(".nameBar").text()})}}}}},listflag:{loader:function(a){var b=(a.tid||"").split("_")[0],c=(a.tid||"").split("_")[1];return{url:pluginfo(a.plugin).apihost+"Tag/pagelist/",method:"POST",data:"nickname="+b+(c?"&id="+c:"")+"&pageindex="+(a.page||1),postform:!0,timeout:120,successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})}}},finder:function(a){return{json:!0,
str:a.result,successfn:function(b){array_count(b)?a.callback({pid:b.id,title:b.title,img:b.pic,stitle:b.author||"",comment:0}):a.callback()}}},countloader:!1,countfinder:function(a){return{successfn:function(b){a.callback({pagecount:0})}}}},searchflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"search-"+encodeURIComponent(a.keyword)+"/?language=1",method:"GET",timeout:120,successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})}}},finder:function(a){1<a.page&&a.callback();
return{query:!0,selector:".searchResultList>li",str:a.result,successfn:function(b){if(array_count(b)){var c=$$(b).find(".author").text();a.callback(obj_contact(a,{pid:getstr(/\/comic\/(\d+)\//g,$$(b).find("a").attr("href")),img:$$(b).find("img").attr("src"),title:$$(b).find(".title").text(),content:(c?"【"+c+"】":"")+$$(b).find(".bottom").text()}))}else a.callback()}}},countloader:!1,countfinder:function(a){return{successfn:function(b){a.callback({pagecount:-1})}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"comic/"+a.pid+"/",method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{query:!0,selector:"#chapter",str:a.result,successfn:function(b){if(array_count(b)){var c=$$(b).find("li");if(a.checkupdate)return b=c[0],a.callback({pid:a.pid,cid:getstr(/\/comic\/\d+\/([\w,\-,\d]+)\//,$$(b).find("a").attr("href")),title:$$(b).find("a").text()}),!0;var d=[];c.each(function(b){d[b]=a.callback({id:c.length-b-1,newest:a.newest&&0==b,pid:a.pid,cid:getstr(/\/comic\/\d+\/([\w,\-,\d]+)\//,
$$(this).find("a").attr("href")),title:$$(this).find("a").text(),count:c.length,reverse:1})});return d}a.callback()}}},infoloader:!1,infofinder:function(a){return{query:!0,selector:".detailTop",str:a.result,successfn:function(b,c,d,f){c=$$(b).find("img.cover").attr("src");d=$$(b).find(".title").text();f=$$(b).find(".subtitle").eq(2).find("a").text();var e=$$(b).find(".subtitle").eq(0).find("a").text();b=$$(b).find(".subtitle").eq(1).find("a").text();var g=getquery(a.result,".detailContent").text();
a.callback({name:d,img:c,added:a.data,description:"<p>"+(e?"【作者】"+e+"<br>":"")+(b?"【类型】"+b+"<br>":"")+(f?"【更新】"+f+"<br>":"")+(g?"【简介】"+g:"")+"</p>",comment:0,preview:0,sourceurl:pluginfo(a.plugin).apihost+"comic/"+a.pid+"/",tags:gettag(d)+gettag(e)+gettag(b)});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"comic/"+a.pid+"/"+a.cid+"/",method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,
header:c})}}},finder:function(a){return{query:!0,selector:"img.lazy",str:a.result,successfn:function(b,c,d,f){var e=[];e.push($$(b).attr("src"));var g=function(b){ExView.modules.curl({url:pluginfo(a.plugin).apihost+"comic/"+a.pid+"/"+a.cid+"/p"+b+"/",method:"GET",timeout:120,progressname:"progress_"+a.plugin+"_"+a.pid+"_"+a.cid,progressfn:function(b,c){if(b||c)$$(".downloadprogress_"+a.plugin+"_"+a.pid+"_"+a.cid+".downloadnowpage").html("正在解析中..."),$$(".progress_"+a.plugin+
"_"+a.pid+"_"+a.cid).html(" "+b+(c?"/"+c:"")+" Bytes")},successfn:function(c,d){if(c){var f=getquery(c,"img.lazy").attr("src");if(f){e.push(f);try{return g(b+1),!1}catch(h){}}!a.download&&ExView.fw.hidePreloader();a.download?chapterpredownload({source:e,download:a.download,plugin:a.plugin}):chapterviewer({source:e,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})}else a.download?chapterpredownload({error:"解析错误！",download:a.download,
plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("图片信息获取失败！","ExView"))},errorfn:function(){chapterpredownload({error:"解析错误！",download:a.download,plugin:a.plugin})},showinfo:a.download?"":2==b?{text:"正在加载图片信息...",title:"图片",name:getlistname(a.pid),img:getlistimg(a.pid)}:""})};g(2);return!0}}}},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"Tag/pagelist/",method:"POST",data:"nickname=newest&id=0&pageindex="+(a.page||1),postform:!0,timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){array_count(b)?a.callback({pid:b.id,title:b.title,img:b.pic,stitle:b.author||"",comment:0}):a.callback()}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"Tag/pagelist/",method:"POST",data:"nickname=top&id=0&pageindex="+(a.page||1),postform:!0,timeout:120,
successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){array_count(b)?a.callback({pid:b.id,title:b.title,img:b.pic,stitle:b.author||"",comment:0}):a.callback()}}}}},fns:{}});
