ExView.Plugins({info:{name:"吹雪漫画",version:"2.2",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAA7EAAAOxAGVKw4bAAACfElEQVQ4jYWR3UtTcRjHv7+z7ZyzDTc9WyOW2ziuBQdxWlrKfLlwhmVMKSoo6sKbYOuiogj8DxS6CLoIMkKKxLoo8KKkF5HADr1dVC7fcps2k7C5+dKce/t1JWy59Hv1PA/P98PzQpAjp9PJSZI0k8lk9rAsC1mW9cFgcAXbSLEZuFyuCqPROM8wjI4QglgshkAggEQi8Xo7ALMZqNXqIyzLIhKJQJZlEEIgCMKV7cx5stvt4DhuAAAFQJ1OJ+2qOkDLRJE6HA7K8/ylHSFlogiWkIxAQLv0OrrW3ELbHPuo3W6nnZ2d6UIeZW7Ccyrc0PPMUZqCJr2B3tkQSupqsT+ZxFn3ccUJ06G0p8erLAQCABgMhkEtAa1RMdSkUlGWZWljYxMdHnlD/f5v9MfNV7ShvMb03wkcpeLliCB4tGYz3GYzXPX1aO/ogEGtwNP+B2hRS7jgrjBFE7+j/plQKg9QuVfE/XPXX2qsNvyJrcJy3oW+vj7whGChvhbNFjt0rVnsNhZ/rbaWKP0zIQA5b1xbWcZYaPijfplAmWGQzWaRXviCqUAAyYFBBNvcmK+S0p++Twjy5Hxmywp1kg226vLHoZ8fTt1eHCRNDxtw0KKBdjYAPHuOF9ZVbNx7NN4zNhbNXZvkJrWSiFt3e/uf3Ll2ZhdbBIWuGHVpE4qOtUNjE6HQlsBaasnz5B3x3XgQvxKRSpVKCemkD62HTyOVTCGbzYLjOESiS1s+x/xbKBsavaqjPDQqNQgIWJYFpRQAEI+vJ3cEjE7PDnmSlrfmkfdIpdKIx9cBAIuRJfR0dwtbRigkn8+HifEJ41w4PDAXDn+enJ666PV6C/b+Bepx4rL1vn51AAAAAElFTkSuQmCC",
db:"chuixue",apihost:"http://m.chuiyao.com/",pagetitle:["<br>","收藏","首页","类型","下载"],lazyload:!0,download:!0,setting:!0,cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){ExView.workers.index.loader()}})},flags:{indexflag:{loader:function(a){a.front||a.page||addtypelist('<div align="center" class="list-block"><img src="img/logo.png"/><br>类型<br>正在加载...<div class="progress"></span></div>',
2);return{url:pluginfo(a.plugin).apihost,method:"GET",timeout:120,successfn:function(b,c){ExView.workers.index.countfinder(obj_contact(a,{result:b,header:c}));a.front||a.page||ExView.workers.type.finder({result:b,plugin:a.plugin});a.successfn&&a.successfn({result:b,header:c})},errorfn:function(){a.page||addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>加载失败，请刷新重试！</a></div>',
2);ExView.fw.alert("网络错误！","ExView")},canclefn:function(){a.page||addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>加载失败，请刷新重试！</a></div>',2)},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),title:a.title,name:"首页",img:a.img}}},finder:function(a){return{reg:/\/manhua\/(\d+)\/\">\s*<img\s*data\-src\=\"((?!<).*?)\"\s*>\s*<h3>((?!<).*?)<\/h3>\s*<p>(.*?)<\/p>\s*<\/a>/g,
str:(a.result||"").replace(/\r*\n/g,""),find:{pid:"$1",img:"$2",title:"$3",content:"$4"},successfn:function(a){console.log(JSON.stringify(a));array_count(a)?addcardlist({pid:a.pid,title:a.title,img:a.img,content:a.content,comment:1}):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',2)},errorfn:function(){a.page||setnowlistname("首页","",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("网络错误！",
"ExView")}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="-1|首页|index";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},typeflag:{loader:function(a){return{successfn:function(){ExView.workers.index.loader()}}},finder:function(a){addtypelist({title:"首页",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"首页"});addtypelist({tid:"0",title:"最新更新",
img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"最新更新"});addtypelist({tid:"0",listflag:"hot",title:"风云榜",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"风云榜"});var b=0;return{reg:/\/comic\/([a-z]+)\/\"(?!<).*?>(.*?)<\/a>/g,str:(a.result||"").replace(/\r*\n/g,"").replace(/>\s*</g,"><"),find:"$1{{separator}}$2",successfn:function(c){c=c.split("{{separator}}");array_count(c)?(8==b&&(addtypelist({tid:b,
title:"搞基日常",img:pluginfo(a.plugin).icon,group:{name:"fenlei",title:"分类"},content:"搞基日常"}),b++),addtypelist({tid:b,title:c[1],img:pluginfo(a.plugin).icon,group:{name:"fenlei",title:"分类"},content:c[1]})):addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>加载失败，请刷新重试！</a></div>',2);b++}}}},
listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"act/?act=list&page="+(a.page||1)+"&catid="+a.keyword+"&ajax=1&order="+(a.flag?"4":"1"),method:"GET",timeout:120,successfn:function(b,c){b?(ExView.workers.list.countfinder(obj_contact(a,{result:b,header:c})),a.successfn&&a.successfn({result:b,header:c})):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+a.title+"】<br>获取失败！","ExView"))},showinfo:{text:"正在加载..."+
(1<a.page?"<br>第"+a.page+"页":""),title:a.title,name:"【"+a.title+"】",img:a.img}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:a.result,find:plugfns(a.plugin).pagefind,successfn:function(b){b?plugfns(a.plugin).pagedeal(b):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="0|"+a.keyword+"|list";
mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},searchflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"search/?page="+(a.page||1)+"&ajax=1&order=1&key="+a.keyword+"&act=search",method:"GET",timeout:120,successfn:function(b,c){b?(a.multsearch||(ExView.workers.search.countfinder(obj_contact(a,{result:b,header:c})),setnowlistname("搜索【"+a.keyword+"】")),a.successfn&&a.successfn({result:b,header:c})):a.multsearch?a.multsearch():(ExView.fw.hidePreloader(),
mySession.isloading=0,ExView.fw.alert("【"+a.keyword+"】<br>获取搜索结果失败！","ExView"))},showinfo:{text:"正在搜索..."+(1<a.page?"<br>第"+a.page+"页":""),name:"【"+a.keyword+"】",title:"搜索"}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:a.result,find:plugfns(a.plugin).pagefind,successfn:function(b,c,d){console.log(b);b?plugfns(a.plugin).pagedeal(b,a):a.multsearch?a.multsearch():addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',
1)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(b){mySession.nowlistpages="0|"+a.keyword+"|search";mySession.nowlistpage=1;console.log(mySession.nowlistpages)}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"manhua/"+a.pid+"/",method:"GET",timeout:120,successfn:function(b,c){b?a.successfn&&a.successfn({result:b,header:c}):a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！",
"ExView"))},showinfo:{text:"正在加载内容页...",title:"内容页",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){return{reg:/<li><a\s*href\=\"(?!\").*?\/manhua\/(\d+)\/(\d+)\.html\"\s*title="((?!\").*?)"/g,str:(a.result||"").replace(/\r*\n/g,"").replace(/>\s*</g,"><"),find:{pid:"$1",cid:"$2",title:"$3"},successfn:function(b,c,d,f){console.log(typeof b);if(array_count(b)){if(a.checkupdate)return{pid:b.pid,cid:b.cid,title:b.title};additemlist({id:c.length-
d-1,newest:a.newest&&0==d,pid:b.pid,cid:b.cid,title:b.title,count:c.length,reverse:1})}else a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},afterfn:function(){a.checkupdate||ExView.workers.content.infofinder(a)}}},infoloader:function(a){return!1},infofinder:function(a){console.log(a);return{reg:/<div class="main-bar bar-bg1">(.*?)<a class="more-show">/g,str:(a.result||"").replace(/\r*\n/g,"").replace(/>\s*</g,
"><"),find:"$1",successfn:function(b,c,d,f){console.log(JSON.stringify(b));c=getstr(/<img(?!<).*?src="((?!\").*?)"/,b);d=getstr(/<h1>((?!<).*?)<\/h1>/,b);f=getstr(/<i>((?!<).*?)<\/i>/,b).trim();var e=getstr(/<dt>作者：<\/dt><dd>((?!<).*?)<\/dd>/,b).trim(),h=getstr(/<dt>类别：<\/dt><dd>((?!<).*?)<\/dd>/,b).trim(),k=getstr(/<dt>更新至：<\/dt><dd>((?!<).*?)<\/dd>/,b).trim(),g=getstr(/<dt>更新于：<\/dt><dd>((?!<).*?)<\/dd>/,b).trim(),l=getstr(/id="bookIntro">(.*?)<\/div>/,
b).trim();b=gettag(b[6]);setlistpic({name:d,img:c,added:a.data,description:"<p>【作者】"+e+"<br>【类型】"+h+"<br>【"+f+"】"+g+"<br>【最新话】"+k+"<br>【简介】"+gettext(l)+"</p>",comment:1,preview:0,tags:gettag(d)+gettag(f)+b+gettag(e),sourceurl:pluginfo(a.plugin).apihost+"manhua/"+a.pid+"/"});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"manhua/"+a.pid+"/"+a.cid+".html",method:"GET",timeout:120,
successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"正在加载图片信息...",title:"图片",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){console.log(a);return{reg:/images:(?!<).*?\[(.*?)\]/g,str:a.result,find:"$1",successfn:function(b){b?(b=eval("(["+b+"])"),console.log(b),a.download?chapterpredownload({source:b,download:a.download,plugin:a.plugin}):chapterviewer({source:b,type:"image",startindex:a.startindex||
0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.download?chapterpredownload({error:"解析错误！",download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("图片信息获取失败！","ExView"));return!0}}}},commentflag:{loader:function(a){return{url:1==parseInt(a.page||1)?"http://api.uyan.cc/v4/comment/?uid=2079740&url="+pluginfo(a.plugin).apihost+"manhua/"+a.pid+"/":"http://api.uyan.cc/v4/action/?sid="+
a.sid+"&sort=1&pn="+a.page,method:"GET",timeout:120,successfn:function(b,c){if(b){var d={};1==parseInt(a.page||1)&&(d=ExView.modules.commentpage.uyanloader(b),b=JSON.stringify(d));a.callback&&a.callback({result:b,header:c,sid:d.sid||a.sid,commentbrowser:{url:"http://api.uyan.cc/v4/comment/?uid=2079740&url="+pluginfo(a.plugin).apihost+"manhua/"+a.pid+"/",title:"评论 - "+pluginfo(a.plugin).name+'<br><span style="font-size:16px">'+(myContent.name||"")+"</span>",browser:!1,flag:""}})}else a.callback&&
a.callback()}}},finder:function(a){console.log(a);return{json:!0,str:a.result,successfn:function(b,c,d,f){b=b||{};1==parseInt(a.page||1)&&(b=b.comments);var e=0<b.more?0:-1;b=(b||[]).data;array_count(b)&&b.forEach(function(b){a.callback&&a.callback({page:a.page||1,pagecount:e,comment:{text:b.cnt,name:b.uname,avatar:b.uface,type:"received",label:b.time,day:"",time:"",reverse:1}})})}}},send:!1},previewflag:{loader:!1,finder:!1,more:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"act/?act=list&page="+(a.page||1)+"&catid=0&ajax=1&order=1",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:a.result,find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));b&&plugfns(a.plugin).pagedeal(b,a)}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"act/?act=list&page="+(a.page||1)+"&catid=0&ajax=1&order=4",method:"GET",timeout:120,
successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:a.result,find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));b&&plugfns(a.plugin).pagedeal(b,a)}}}}},fns:{pagerule:/<li>((?:.|[\r\n])*?)<\/li>/g,pagefind:"$1",pagedeal:function(a,b){b=b||{};a=(a||"").replace(/\r*\n/g,"").replace(/>\s*</g,"><");var c=getstr(/\/manhua\/(\d+)\//,a),d=getstr(/<img(?!<).*?src="((?!\").*?)"/,a),f=getstr(/<i>((?!<).*?)<\/i>/,
a).trim(),e=getstr(/<h3>((?!<).*?)<\/h3>/,a).trim(),h=getstr(/<dt>作　者：<\/dt><dd>((?!<).*?)<\/dd>/,a).trim(),k=getstr(/<dt>类　别：<\/dt><dd>((?!<).*?)<\/dd>/,a).trim(),g=getstr(/<dt>更新至：<\/dt><dd>((?!<).*?)<\/dd>/,a).trim(),l=getstr(/<dt>更新于：<\/dt><dd>((?!<).*?)<\/dd>/,a).trim();if(b.multupdate)return b.multupdate(obj_contact(b,{pid:c,img:d,title:e,content:g})),!1;if(b.multhot)return b.multhot(obj_contact(b,{pid:c,img:d,title:e,
content:g})),!1;if(b.multsearch)return b.multsearch(obj_contact(b,{pid:c,img:d,title:e,content:g})),!1;addcardlist({pid:c,title:e,name:e,img:d,content:(k?"【类型】"+k+"<br>":"")+(h.replace(/&nbsp;/g,"")?"【作者】"+h+"<br>":"")+"【最新】"+g,stitle:(f?"【"+f+"】":"")+l,comment:1,preview:0,extrabutton:""})}}});
