ExView.Plugins({info:{name:"墨瞳漫画",version:"2.2",author:"Gentle",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAw1BMVEXrKzjtGSbnGSb////nEyDqJDHmEB3mDBr9/PzqQUzwLDjrHyvoHSrzGSblBxX86+zub3foLjnoJzPtFiPnFiPtEyDlCRfkAAX99fb74OL509X2s7jzmZ7wkZfve4LvdHzxaXHtZW3tYGnvWWLxUVvrR1HuPknuPEjpNUDqKTXmIzDlBBL+9/f85eb43N341tj4ys73vsL1r7P1q6/0qa7yoabznqPuhozwgonyYmvrTVbwRE/oN0LuMDvoLzvsJDHoGid/sXWwAAAAv0lEQVQY00XPR5bCMBREUemXLEecjcmhSd3Q5JzZ/6qQERxqeCd1Hhs6TM91/xhzhswo8WJJ1u/dE14yGOMkiMhsYNa8CM4UeLEv5S+wPg2ogMRb7KJcQTcXL+CTBoL2uI7NhDTIqAKsxlXLNjWQ37YAO67URKqB/CXQyVsYmBpSqgZdaUZW7w3Sxr9NsTe/CQ3lH2C6bYWHMn0BtX1TpJ+XMKhbCKUgBUVcdu5fjx0347yIGzkKXcN7qHiVP3oCROsN7+mJXEUAAAAASUVORK5CYII=",
db:"cm233",apihost:"http://cm233.com/",pagetitle:["<br>","收藏","首页","类型","下载"],download:!0,lazyload:!0,vphotomode:!0,theme:"red",webpage:{url:"http://m.cm233.com/login",title:'墨瞳漫画<br><span style="font-size:16px">登录</span>',browser:!1,flag:""},setting:!0,cdn:""},set:function(a){},unset:function(a){},init:function(a){ExView.workers.fav.listloader({callback:function(){}})},flags:{indexflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"Api/Recommend/getHot",method:"POST",data:"cursor="+(a.page||1)+"&moduleId=6",postform:!0,timeout:120,successfn:function(b,c){a.callback({img:pluginfo(a.plugin).icon,multpage:!0,result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){b=(b||{}).data.list;array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:function(a){return{json:!0,str:a.result,successfn:function(b){try{b=(b=Math.ceil((b||{}).data.total/10))?b:-1}catch(c){b=
-1}a.callback({pagecount:b})}}}},typeflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"Api/Category/getList",method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){a.callback({title:"首页",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"首页"});a.callback({tid:"",listflag:"Api/Book/getUpdateByDate",title:"更新",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},
content:"更新"});a.callback({tid:"",listflag:"Api/Recommend/getRank",title:"排行",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"排行"});a.callback({tid:"",listflag:"Api/Book/getRecentlyIssue",title:"新书",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"新书"});a.callback({tid:"",listflag:"Api/Book/getFinished",title:"完结",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},
content:"完结"});a.callback({tid:"",listflag:"Api/Book/getFree",title:"免费",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"免费"});a.callback({tid:"",listflag:"Api/Rank/rise",title:"热度",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"热度"});return{json:!0,str:a.result,successfn:function(b){b=(b||{}).data.list||[];array_count(b)&&b.forEach(function(b){a.callback({tid:b.categoryId,title:b.categoryName,
img:getcoverload(b.categoryIcon,{loadingimg:"img/logo.png",errorimg:sessionStorage.blankimg}),group:{name:"fenlei",title:"分类"},content:b.categoryName})})}}}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+(a.flag?a.flag.replace("{{page}}",a.page||1):"Api/Category/getBookList"),method:"POST",data:"count=10&client=h5&cursor="+(a.page||1)+(a.flag?"":"&categoryId="+a.tid),postform:!0,timeout:120,successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})}}},finder:function(a){return{json:!0,
str:a.result,successfn:function(b){b=(b||{}).data.list;array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:function(a){return{json:!0,str:a.result,successfn:function(b){try{var c=(b||{}).data.total?(b=Math.ceil((b||{}).data.total/10))?b:-1:0}catch(d){c=-1}a.callback({pagecount:c})}}}},searchflag:{loader:function(a){return{url:"http://search.cm233.com/Api/Search/books",method:"POST",postform:!0,data:"cursor="+(a.page||1)+"&client=android&keyword="+encodeURIComponent(a.keyword),
timeout:120,successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){b=(b||{}).data.list;array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:function(a){return{json:!0,str:a.result,successfn:function(b){try{b=(b=Math.ceil((b||{}).data.total/10))?b:-1}catch(c){b=-1}a.callback({pagecount:b})}}}},contentflag:{loader:function(a){return{successfn:function(b,c){var d=[],e=function(b){var c=
{url:pluginfo(a.plugin).apihost+"Api/Chapter/getList",method:"POST",postform:!0,data:"bookId="+a.pid+"&count=20&startChapter="+(20*((b||1)-1)+1),timeout:120,successfn:function(c,g){var l=JSON.parse(c),m=(l||{}).data.nextCursor;d=d.concat((l||{}).data.list);m?e((b||1)+1):a.callback({result:JSON.stringify({data:{list:d}}),header:g})},errorfn:function(){a.callback()},showinfo:{text:"正在加载内容页...",title:"内容页",name:getlistname(a.pid),img:getlistimg(a.pid)}};
a.checkupdate&&(c.showinfo="");ExView.modules.curl(c)};e(1)}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b,c,d,e){b=(b||{}).data.list;if(array_count(b)){if(a.checkupdate){try{b=b.pop()}catch(f){b={}}a.callback({pid:a.pid,cid:b.seqNum,title:(0<parseInt(b.price)?"【VIP】":"")+((b.chapterTitle||"").trim()||"第"+b.length+"话")});return!0}e=[];(b||[]).forEach(function(c,d){e[d]=a.callback({id:d,newest:a.newest&&0==d,pid:a.pid,cid:c.seqNum,title:(0<parseInt(c.price)?
"【VIP】":"")+((c.chapterTitle||"").trim()||"第"+(d+1)+"话"),count:b.length,reverse:0})});return e}a.callback()}}},infoloader:function(a){return{url:pluginfo(a.plugin).apihost+"Api/Book/getDetail",method:"POST",postform:!0,data:"bookId="+a.pid,timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},infofinder:function(a){return{json:!0,str:a.result,successfn:function(b,c,d,e){b=(b||{}).data;c=b.bookCover;d=b.bookName;e=b.currTime;var f=b.author,g=(b.tags||[]).map(function(a){return a.tagName});
b=b.resume;a.callback({name:d,img:c,added:a.data,description:"<p>"+(f?"【作者】"+f+"<br>":"")+(g?"【类型】"+g+"<br>":"")+(e?"【更新】"+e+"<br>":"")+(b?"【简介】"+b:"")+"</p>",comment:0,preview:0,tags:gettag(d)+gettag(f)+gettag(g||"")});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"Api/Chapter/getDetailBySeqNum",method:"POST",postform:!0,data:"seqNum="+a.cid+"&bookId="+a.pid+"&client=h5",timeout:120,
successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b,c,d,e){b=(b||{}).data;array_count(b)?(b=b.imgs,a.download?a.callback({source:b,type:"image",download:a.download,plugin:a.plugin}):a.callback({source:b,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.callback();return!0}}}},commentflag:{loader:!1,finder:!1,send:!1},previewflag:{loader:!1,finder:!1},pageimgflag:{parser:!1},
updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"Api/Book/getUpdateByDate",method:"POST",data:"count=10&client=h5&cursor="+(a.page||1),postform:!0,timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){b=(b||{}).data.list;array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"Api/Recommend/getRank",method:"POST",data:"count=10&client=h5&cursor="+
(a.page||1),postform:!0,timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){b=(b||{}).data.list;array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}}}},fns:{pagedeal:function(a,b){b=b||{};a.forEach(function(a){var d=a.bookId,e=a.bookCover,f=gettext(a.bookName),g=gettext(a.author),h=a.tags.map(function(a){return gettext(a.tagName)}).join(","),k=(g?"【"+g+"】":"")+(h||"");a=a.resume;if(b.multupdate||
b.multhot||b.multsearch)return b.callback(obj_contact(b,{pid:d,img:e,title:f,content:k})),!1;b.callback({pid:d,title:f,img:e,stitle:g||"",content:(h?function(a){var b="";(a.split(",")||[]).forEach(function(a){b+='<span style="font-size:10px;"><span class="color-white bg-'+getnowtheme()+'" style="padding:3px;border-radius:3px;margin-right:3px;">'+a+"</span></span>"});return b}(h):"")+a,comment:0})})}}});
