ExView.Plugins({info:{name:"\u53ef\u9177\u7c73\u6f2b\u753b",version:"2.2",author:"Gentle",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAXVBMVEXiODjmLDLtXGDnMDf97Oz61Nb3urzxgYTqTFHqRUrpPEL95+j60dL2qaz1pKfuaGztYmb83N772Nn6zs/5yMn4v8H3t7n2ra/wen7weHz+8/P84eL2sLP0mpzxiIxss+YCAAAAAXRSTlMJOTpgwgAAAHtJREFUGNNlz4sKgzAMhWH/ZmvXVq2Xedvt/R9z2jCcGAgkXyBwioJD6X4QCB63BJDgXYaFFqaW3lb1vMGNC5TyxM5vvwNg0R8NEYYNvEIyjC8AZxRckq5HupJKwRBhfMBwhd/TfLz/A2mHD+tQx7UnBQk0htwGTuFO8b+OkwSF7mv0rQAAAABJRU5ErkJggg==",
db:"comicool",apihost:"http://proxy.comicool.cn/",pagetitle:["<br>","\u6536\u85cf","\u4e3b\u9875","\u7c7b\u578b","\u4e0b\u8f7d"],download:!0,lazyload:!0,setting:!0,vphotomode:!0,theme:"red",cdn:""},set:function(a){},unset:function(a){},init:function(a){ExView.workers.fav.listloader({callback:function(){}})},flags:{indexflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"homepage4h5",method:"GET",timeout:120,successfn:function(b,c){a.callback({img:pluginfo(a.plugin).icon,multpage:!0,result:b,
header:c})}}},finder:function(a){return{reg:/jsonp_\w+\((.*?)\r*\n*\)$/g,str:a.result,find:"$1",successfn:function(b){b=JSON.parse(b);b=b.area_list;array_count(b)?b.forEach(function(b){b=b.area_content;b.forEach(function(b){1==b.content_type&&plugfns(a.plugin).pagedeal(b,a)})}):a.callback()}}},countloader:!1,countfinder:function(a){return{successfn:function(b){a.callback({pagecount:-1})}}}},typeflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"categorylist4h5",method:"GET",timeout:120,
successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){a.callback({title:"\u4e3b\u9875",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u4e3b\u9875"});a.callback({tid:"",listflag:"timeline4h5",title:"\u6700\u65b0\u7ae0\u8282",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u6700\u65b0\u7ae0\u8282"});a.callback({tid:"",listflag:"allcomic4h5?comic_id={{lastpid}}&page_size=20&page_direction=2&list_type=all&order_type=rating&req_id=0&req_param=0",
title:"\u6392\u884c\u699c",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u6392\u884c\u699c"});return{reg:/jsonp_\w+\((.*?)\r*\n*\)/g,str:a.result,find:"$1",successfn:function(b){b=JSON.parse(b);b=b.category_list;array_count(b)&&b.forEach(function(b){var d=b.category_id,e=b.category_title;b=b.category_cover_url.replace("https://","http://");a.callback({tid:d,title:e,img:b,group:{name:"fenlei",title:"\u5206\u7c7b"},content:e})})}}}},listflag:{loader:function(a){a.page=
a.page||1;1==a.page&&(plugfns(a.plugin).comic_lastpid=0);var b=plugfns(a.plugin).comic_lastpid;return a.flag?{url:pluginfo(a.plugin).apihost+a.flag.replace(/{{lastpid}}/g,b),method:"GET",timeout:120,successfn:function(b,d){a.callback({multpage:!0,result:b,header:d})}}:{url:pluginfo(a.plugin).apihost+"allcomic4h5?comic_id="+b+"&page_size=20&page_direction=2&list_type=category&order_type=rating&req_id="+a.tid+"&req_param=1",method:"GET",timeout:120,successfn:function(b,d){a.callback({multpage:!0,result:b,
header:d})}}},finder:function(a){if("timeline4h5"==a.flag){var b=JSON.parse(getstr(/jsonp_\w+\((.*?)\r*\n*\)$/g,a.result)||"{}").timeline_list||[];return{json:!0,str:JSON.stringify(b),successfn:function(b){array_count(b)?(b=b.comi_list)&&b.forEach(function(b){a.callback({pid:b.comic_id,title:b.comic_title,img:"http://cdn.comicool.cn/"+b.comic_cover_url+"?imageView2/1/w/213/h/142/q/100",stitle:b.comic_desc_lite,content:getboxitem(b.comic_auth)+getboxitem(b.left_slogan),comment:1})}):a.callback()}}}b=
JSON.parse(getstr(/jsonp_\w+\((.*?)\r*\n*\)$/g,a.result)||"{}").content_list||[];plugfns(a.plugin).comic_lastpid=b[b.length-1].content_action;return{json:!0,str:JSON.stringify(b),successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:function(a){return{successfn:function(b){a.callback({pagecount:"timeline4h5"==a.flag?-1:0})}}}},searchflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"searchinfo4h5?keyword="+a.keyword,method:"GET",
timeout:120,successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})}}},finder:function(a){var b=JSON.parse(getstr(/jsonp_\w+\((.*?)\r*\n*\)$/g,a.result)||"{}").comi_list||[];return{json:!0,str:JSON.stringify(b),successfn:function(b){array_count(b)?a.multsearch?a.callback(obj_contact(a,{pid:b.comic_id,title:b.comic_title,img:"http://cdn.comicool.cn/"+b.comic_cover_url+"?imageView2/1/w/213/h/142/q/100",content:"\u66f4\u65b0\u65e5\u671f:"+getLocalTime(1E3*parseInt(b.ep_list_update_time))})):
a.callback(obj_contact(a,{pid:b.comic_id,title:b.comic_title,img:"http://cdn.comicool.cn/"+b.comic_cover_url+"?imageView2/1/w/213/h/142/q/100",stitle:"\u66f4\u65b0\u65e5\u671f:"+getLocalTime(1E3*parseInt(b.ep_list_update_time)),content:b.comic_desc_lite,comment:1})):a.callback()}}},countloader:!1,countfinder:function(a){return{successfn:function(b){a.callback({pagecount:-1})}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"comicdetail4h5?comic_id="+a.pid,method:"GET",timeout:120,
successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){a.result=getstr(/jsonp_\w+\((.*?)\r*\n*\)$/g,a.result);return{json:!0,str:a.result,successfn:function(b,c,d,e){b=(b||{}).ep_list;if(array_count(b)){if(a.checkupdate)return c=b.pop(),a.callback({pid:a.pid,cid:c.ep_id,title:c.ep_title}),!0;e=[];b.forEach(function(c,d){e[d]=a.callback({id:d,newest:a.newest&&0==d,pid:a.pid,cid:c.ep_id,title:c.ep_title,count:b.length,reverse:0})});return e}a.callback()}}},infoloader:!1,infofinder:function(a){a.result=
getstr(/jsonp_\w+\((.*?)\r*\n*\)$/g,a.result);return{json:!0,str:a.result,successfn:function(b,c,d,e){b=b.comic_info;c="http://cdn.comicool.cn/"+b.comic_cover_large;d=b.comic_title;e=getLocalTime(1E3*parseInt(b.comic_info_update_time));var f=b.comic_auth;b=b.comic_desc;a.callback({name:d,img:c,added:a.data,description:"<p>"+(f?"\u3010\u4f5c\u8005\u3011"+f+"<br>":"")+(e?"\u3010\u66f4\u65b0\u3011"+e+"<br>":"")+(b?"\u3010\u7b80\u4ecb\u3011"+b:"")+"</p>",comment:1,preview:0,tags:gettag(d)+gettag(f),sourceurl:"http://m.comicool.cn/content/detail.html?comic_id="+
a.pid});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"epinfo4h5?comic_id="+a.pid+"&ep_id="+a.cid,method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){a.result=getstr(/jsonp_\w+\((.*?)\r*\n*\)$/g,a.result);return{json:!0,str:a.result,successfn:function(b,c,d,e){b=b.frame_list;array_count(b)?(b=b.map(function(a){return"http://cdn.comicool.cn/"+a.frame_url}),a.download?a.callback({source:b,download:a.download,plugin:a.plugin}):
a.callback({source:b,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.callback();return!0}}}},commentflag:{loader:function(a){a.page=a.page||1;1==a.page&&(plugfns(a.plugin).post_id=0);return{url:pluginfo(a.plugin).apihost+"getpostlist4h5?comic_id="+a.pid+"&include=comic&order_type=update_time&post_id="+plugfns(a.plugin).post_id+"&page_size=20&page_direction=2",method:"GET",timeout:120,successfn:function(b,c){b?a.callback({result:b,header:c,commentbrowser:{url:"http://m.comicool.cn/content/detail.html?comic_id="+
a.pid,title:"\u8bc4\u8bba - "+pluginfo(a.plugin).name+'<br><span style="font-size:16px">'+(myContent.name||"")+"</span>",browser:!1,flag:""}}):a.callback()}}},finder:function(a){a.result=getstr(/jsonp_\w+\((.*?)\r*\n*\)$/g,a.result);return{json:!0,str:a.result,successfn:function(b,c,d,e){var f=b.user_list;b=b.post_list;var g=[];b.forEach(function(a,b){f[b]&&g.push({user:f[b].nickname,img:f[b].icon.replace("https://","http://"),time:getLocalTime(1E3*parseInt(a.post_time)),content:((a.post_rich||[])[0]||
{}).text})});if(array_count(g))for(var h in g)a.callback({page:a.page||1,pagecount:-1,comment:{text:g[h].content,name:g[h].user,avatar:g[h].img,type:"received",label:g[h].time,day:"",time:"",reverse:1,extra:""}})}}},send:!1},previewflag:{loader:!1,finder:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return 1<a.page?(a.multupdate(),!1):{url:pluginfo(a.plugin).apihost+"timeline4h5",method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){var b=
JSON.parse(getstr(/jsonp_\w+\((.*?)\r*\n*\)$/g,a.result)||"{}").timeline_list||[];return{json:!0,str:JSON.stringify(b),successfn:function(b){array_count(b)?(b=b.comi_list)&&b.forEach(function(b){a.callback(obj_contact(a,{pid:b.comic_id,title:b.comic_title,img:"http://cdn.comicool.cn/"+b.comic_cover_url+"?imageView2/1/w/213/h/142/q/100",stitle:b.comic_desc_lite,content:getboxitem(b.comic_auth)+(b.left_slogan?getboxitem(b.left_slogan):""),comment:1}))}):a.callback()}}}},hotflag:{loader:function(a){return 1<
a.page?(a.multhot(),!1):{url:pluginfo(a.plugin).apihost+"allcomic4h5?comic_id=0&page_size=100&page_direction=2&list_type=all&order_type=rating&req_id=0&req_param=0",method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){var b=JSON.parse(getstr(/jsonp_\w+\((.*?)\r*\n*\)$/g,a.result)||"{}").content_list||[];return{json:!0,str:JSON.stringify(b),successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}}}},fns:{pagedeal:function(a,
b){b=b||{};var c=a.content_category,c=c.split("|")||[],c=c.map(function(a){return a.split("#").length?getboxitem(a.split("#")[1]):""});console.log(a);var d=a.content_action,e="http://cdn.comicool.cn/"+a.content_poster+"?imageView2/1/w/213/h/142/q/100",f=a.content_title||a.content_subtitle,g=(a.content_desc_lite||a.third_title||"")+" "+(a.content_update_time?getLocalTime(1E3*parseInt(a.content_update_time)):""),c=c.join("")+(a.content_desc_lite2||"");if(b.multupdate||b.multhot||b.multsearch)return b.callback(obj_contact(b,
{pid:d,img:e,title:f,content:g})),!1;b.callback({pid:d,title:f,img:e,stitle:g,content:c,comment:1})}}});
