ExView.Plugins({info:{name:"Cosplay啦图库",version:"2.2",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAeFBMVEX/////+/z/9/v/bqH/ap7/4ev/xtr/wdf/nb//k7n/8/f/7fT/5O3+1+T/uNH/qMb/ocL/mb7/ibL/ga3/d6f/6vP/6PH/3en/zuH/y93/yNz/utX/ss//o8P/nsH/lrz/hrD/+P3/0OP/0uL/rsr/jLT/i7T/fKrONxDGAAAAjUlEQVQY04WNVw7DMAxD6e3svdokTff9b1gpSD/8lQeYBCnBwh+BkMc9iMk6BDlt7DHodjNtcfyTS7bu27C/HMYcTKQn0kWrZ55xHnVNC25Lbe33YtUFr13oVSUXN1WyOoht8FTjqlsrYGrrK8RVT7dKpT5+KZp3TNMZxBSp1kFKiHTOsGMS1rg3Euf8ACfkBimxqEC3AAAAAElFTkSuQmCC",
db:"cosplayla",apihost:"http://cosplay.la/",pagetitle:["<br>","收藏","最新更新","类型","下载"],lazyload:!0,download:!0,setting:!0,nativeres:!0,gallerymode:!0,galleryopen:!0,theme:"pink",cdn:""},set:function(a){},unset:function(a){},init:function(a){ExView.workers.fav.listloader({callback:function(){}})},flags:{indexflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"photo/index/2-0-"+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){a.callback({img:pluginfo(a.plugin).icon,
multpage:!0,result:b,header:c})}}},finder:function(a){return{query:!0,selector:".pics li",str:a.result,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:function(a){return{successfn:function(b){try{var c=$$(getquery(a.result,".pagen a")).eq(-2).text()||-1}catch(d){c=-1}a.callback({pagecount:c})}}}},typeflag:{loader:!1,finder:function(a){a.callback({title:"最新更新",img:pluginfo(a.plugin).icon,content:"最新更新"});
a.callback({tid:"1",title:"COS正片",img:pluginfo(a.plugin).icon,content:"COS正片"});a.callback({tid:"2",title:"COS预告",img:pluginfo(a.plugin).icon,content:"COS预告"});a.callback({tid:"3",title:"转发COS",img:pluginfo(a.plugin).icon,content:"转发COS"});a.callback({tid:"4",title:"私房写真",img:pluginfo(a.plugin).icon,content:"私房写真"});a.callback({tid:"5",title:"漫展场照",img:pluginfo(a.plugin).icon,content:"漫展场照"})}},
listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"photo/index/2-"+a.tid+"-"+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})}}},finder:function(a){return{query:!0,selector:".pics li",str:a.result,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:function(a){return{successfn:function(b){try{var c=$$(getquery(a.result,".pagen a")).eq(-2).text()||-1}catch(d){c=-1}a.callback({pagecount:c})}}}},
searchflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"photo/index/2-0-"+(a.page||1)+"?key="+encodeURIComponent(a.keyword),method:"GET",timeout:120,successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})}}},finder:function(a){return{query:!0,selector:".pics li",str:a.result,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:function(a){return{successfn:function(b){try{var c=$$(getquery(a.result,".pagen a")).eq(-2).text()||
-1}catch(d){c=-1}a.callback({pagecount:c})}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"photo/show/"+a.pid,method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{successfn:function(b,c,d,e){if(a.checkupdate)return{pid:a.pid,cid:"1",title:"全1话"};e=[];e[0]=additemlist({id:0,newest:a.newest&&0==d,pid:a.pid,cid:"1",title:"全1话",count:1,reverse:0});return e}}},infoloader:!1,infofinder:!1},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"photo/show/"+a.pid,method:"GET",timeout:120,ua:"windows",successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{query:!0,selector:".talk_pic",str:a.result,successfn:function(b,c,d,e){if(array_count(b)){var f=[];$$(b).find("img").each(function(){var b=$$(this).attr("src"),b=getimgload(b,a.plugin,{nativeres:!0,cacheheader:{Referer:pluginfo(a.plugin).apihost}});f.push(b)});a.download?a.callback({source:f,download:a.download,plugin:a.plugin}):a.callback({source:f,type:"image",
startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})}else a.callback();return!0}}}},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"photo/index/2-0-"+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{query:!0,selector:".pics li",str:a.result,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"photo/index/1-0-"+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{query:!0,selector:".pics li",str:a.result,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}}}},fns:{pagedeal:function(a,b){b=b||{};var c=getstr(/show\/(\d+)/,$$(a).find("a").attr("href")),d=$$(a).find("img").attr("src"),d=getimgload(d,b.plugin,{nativeres:!0,cacheheader:{Referer:pluginfo(b.plugin).apihost}}),e=$$(a).find(".tits").text(),
f=$$(a).find(".fleft").text(),g=$$(a).find(".fright").attr("rel"),g=f+" "+g;if(b.multupdate||b.multhot||b.multsearch)return b.callback(obj_contact(b,{pid:c,img:d,title:e,content:g})),!1;b.callback({pid:c,title:e,img:d,stitle:f||"",content:g,comment:0})}}});
