ExView.Plugins({info:{name:"Cosplay\u5566\u56fe\u5e93",version:"2.2",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAeFBMVEX/////+/z/9/v/bqH/ap7/4ev/xtr/wdf/nb//k7n/8/f/7fT/5O3+1+T/uNH/qMb/ocL/mb7/ibL/ga3/d6f/6vP/6PH/3en/zuH/y93/yNz/utX/ss//o8P/nsH/lrz/hrD/+P3/0OP/0uL/rsr/jLT/i7T/fKrONxDGAAAAjUlEQVQY04WNVw7DMAxD6e3svdokTff9b1gpSD/8lQeYBCnBwh+BkMc9iMk6BDlt7DHodjNtcfyTS7bu27C/HMYcTKQn0kWrZ55xHnVNC25Lbe33YtUFr13oVSUXN1WyOoht8FTjqlsrYGrrK8RVT7dKpT5+KZp3TNMZxBSp1kFKiHTOsGMS1rg3Euf8ACfkBimxqEC3AAAAAElFTkSuQmCC",
db:"cosplayla",apihost:"http://120.25.155.80:8088/",pagetitle:["<br>","\u6536\u85cf","\u56fe\u96c6","\u7c7b\u578b","\u4e0b\u8f7d"],lazyload:!0,download:!0,setting:!0,search:!1,nativeres:!1,gallerymode:!0,galleryopen:!0,vphotomode:!0,theme:"pink",cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){}})},flags:{indexflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"share/GetPhotoList",method:"POST",data:"key=&p="+(a.page||1)+
"&psize=16&order=0",postform:!0,timeout:120,successfn:function(b,c){a.callback&&a.callback({img:pluginfo(a.plugin).icon,multpage:!0,result:b,header:c})}}},finder:function(a){try{var b=JSON.stringify(JSON.parse(a.result).Data)}catch(c){b=""}return{json:!0,str:b,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:!1},typeflag:{loader:!1,finder:function(a){addtypelist({title:"\u56fe\u96c6",img:pluginfo(a.plugin).icon,content:"\u56fe\u96c6"})}},
listflag:{loader:!1,countloader:!1,countfinder:!1},searchflag:{loader:function(a){a.multsearch||ExView.fw.alert("\u6b64\u63d2\u4ef6\u4e0d\u652f\u6301\u641c\u7d22\u529f\u80fd\uff01");a.callback()},finder:!1,countloader:!1,countfinder:!1},contentflag:{loader:!1,finder:function(a){return{successfn:function(b,c,e,d){console.log(typeof b);if(a.checkupdate)return{pid:a.pid,cid:"1",title:"\u51681\u8bdd"};d=[];d[0]=additemlist({id:0,newest:a.newest&&0==e,pid:a.pid,cid:"1",title:"\u51681\u8bdd",count:1,reverse:0});
return d}}},infoloader:!1,infofinder:!1},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"share/GetById",method:"POST",data:"shareid="+a.pid,postform:!0,timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){console.log(a);return{json:!0,str:a.result,successfn:function(b,c,e,d){b=b.Data.Share.PhotoLists;array_count(b)?(b=b.map(function(a){return a.PicPath}),console.log(b),a.download?chapterpredownload({source:b,download:a.download,
plugin:a.plugin}):chapterviewer({source:b,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.download?chapterpredownload({error:"\u89e3\u6790\u9519\u8bef\uff01",download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u56fe\u7247\u4fe1\u606f\u83b7\u53d6\u5931\u8d25\uff01","ExView"));return!0}}}},commentflag:{loader:!1,finder:!1},previewflag:{loader:!1,finder:!1,more:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"api/data/%E7%A6%8F%E5%88%A9/20/"+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){try{var b=JSON.stringify(JSON.parse(getresult(a.result)).results)}catch(c){b=""}return{json:!0,str:b,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"api/data/%E7%A6%8F%E5%88%A9/20/"+(a.page||1),method:"GET",timeout:120,successfn:function(b,
c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){try{var b=JSON.stringify(JSON.parse(getresult(a.result)).results)}catch(c){b=""}return{json:!0,str:b,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}}}},fns:{pagedeal:function(a,b){b=b||{};var c=a.Id,e=a.Title,d=a.DefaultImage;if(c&&e){var f=a.NickName;if(b.multupdate)return b.multupdate(obj_contact(b,{pid:c,img:d,title:e,content:f})),!1;if(b.multhot)return b.multhot(obj_contact(b,{pid:c,img:d,
title:e,content:f})),!1;if(b.multsearch)return b.multsearch(obj_contact(b,{pid:c,img:d,title:e,content:f})),!1;addcardlist({pid:c,title:e,img:d,content:"",stitle:a.NickName,comment:0,preview:0,extrabutton:""})}}}});
