ExView.Plugins({info:{name:"大角虫漫画",version:"2.2",author:"Gentle",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAA1VBMVEXqyxnx0SvvzibtyxHqyAznxAblwgPtzSLxzxfqyh3oxxoTExQgISLkwQIlJSU6NjTuzRrmxRj11S8cGRCmjgu8nwVSS0lEPj322S+mkS8uLSZTSRByYgtuXgsHBgfauQTVtATKqwT////r6urf39+VlJR9enlbVVPjyTDTvi/ixi6Siy7qzy3rzS2xmi3ErSyckiwuLCpLSChVTieGdyYcHSYaHCTfwSOikCKcjR+Mgh4gHhxbURttYBaPfBFIPg4sJg5gUg0rJw2RfQkNCwgKCQfhvgLXIdpWAAAAAXRSTlMZJI1wpgAAAJRJREFUGNNdxkUSwkAABdGPy0gc4oK7u/v9j0RCZUHN23QDcvmPDOQEyAtQEKAoAGOey9jVNQwWPe8RQ0hiOvGIYxBNIx8EOqV6uDlTeuGU0gCDPl/w6drmfGjOlnYP49dIfZuaqvoH/7Z77JERICtAKbVNi0pCturSSv4tqjGr1q1L0vyUPKAok1qj3ZGaraOjKPgCLf0PxgGVibsAAAAASUVORK5CYII=",
db:"djcmh",apihost:"http://dajiaochong.517w.com/",pagetitle:["<br>","收藏","日更","类型","下载"],download:!0,lazyload:!0,setting:!0,vphotomode:!0,theme:"amber",cdn:""},set:function(a){},unset:function(a){},init:function(a){ExView.workers.fav.listloader({callback:function(){}})},flags:{indexflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"index.php?m=web_app&c=index&a=dw_list&wi=1",method:"GET",timeout:120,successfn:function(b,c){a.callback({img:pluginfo(a.plugin).icon,
multpage:!0,result:b,header:c})}}},finder:function(a){return{query:!0,selector:".dw_ls_ul li",str:a.result,successfn:function(b){array_count(b)?a.callback({pid:($$(b).find(".bnels").attr("onclick").match(/enterBook\((\d+)\)/)||[])[1],title:$$(b).find(".titlekb").text(),img:$$(b).find(".bnels").attr("src"),content:$$(b).find(".titlekbh").text(),comment:1}):a.callback()}}},countloader:!1,countfinder:function(a){return{successfn:function(b){a.callback({pagecount:-1})}}}},typeflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"dacu_app/app/?c=MainCategory&a=get_tag_list&userid=0&type=0&ui=0&ui_id=0",method:"GET",ua:"kidstone.cn/2.0.0/15/Android",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){a.callback({title:"日更",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"日更"});a.callback({tid:"",listflag:"dacu_app/app/?c=MainRank&a=get_label_rank&label=0&get_type=6&start=0&ui=0&ui_id=0&userid=0&home=0",title:"人气榜",img:pluginfo(a.plugin).icon,
group:{name:"daohang",title:"导航"},content:"人气榜"});a.callback({tid:"",listflag:"dacu_app/app/?c=MainRank&a=get_label_rank&label=31&get_type=6&start=0&ui=0&ui_id=0&userid=0&home=0",title:"少女榜",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"少女榜"});a.callback({tid:"",listflag:"dacu_app/app/?c=MainRank&a=get_label_rank&label=33&get_type=6&start=0&ui=0&ui_id=0&userid=0&home=0",title:"耽美榜",img:pluginfo(a.plugin).icon,
group:{name:"daohang",title:"导航"},content:"耽美榜"});a.callback({tid:"",listflag:"dacu_app/app/?c=MainRank&a=get_label_rank&label=4&get_type=5&start=0&ui=0&ui_id=0&userid=0&home=0",title:"潜力榜",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"潜力榜"});return{json:!0,str:a.result,successfn:function(b){if(array_count(b)){var c=b.data.src_host;b=b.data.data;b.forEach(function(b){var e=b.label_id,d=b.labelname;b=b.pic_url?
c+b.pic_url:pluginfo(a.plugin).icon;a.callback({tid:e,title:d,img:b,group:{name:"fenlei",title:"分类"},content:d})})}}}}},listflag:{loader:function(a){return a.flag?{url:pluginfo(a.plugin).apihost+a.flag,method:"GET",ua:"kidstone.cn/2.0.0/15/Android",timeout:120,successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})}}:{url:pluginfo(a.plugin).apihost+"dacu_app/get_tag_book.php?tag=2&type=0&start="+20*((a.page||1)-1)+"&label_type=0",method:"GET",ua:"kidstone.cn/2.0.0/15/Android",
timeout:120,successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})}}},finder:function(a){var b=(JSON.parse(a.result||"{}").data||{}).data||[];return{json:!0,str:JSON.stringify(b),successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:function(a){return{successfn:function(b){a.callback({pagecount:a.flag?-1:0})}}}},searchflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"dacu_app/get_filter.php?type=0&str="+a.keyword+
"&start="+20*((a.page||1)-1)+"&click=1",method:"GET",ua:"kidstone.cn/2.0.0/15/Android",timeout:120,successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})}}},finder:function(a){var b=(JSON.parse(a.result||"{}").data||{}).data||[];return{json:!0,str:JSON.stringify(b),successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:function(a){return{successfn:function(b){a.callback({pagecount:0})}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"dacu_app/get_chapter_info.php?id="+a.pid+"&beginId=0",method:"GET",ua:"kidstone.cn/2.0.0/15/Android",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b,c,g,e){b=((b||{}).data||{}).chapter;if(array_count(b)){if(a.checkupdate)return c=b[0],a.callback({pid:a.pid,cid:c.cid,title:c.name}),!0;e=[];b.forEach(function(c,f){e[f]=a.callback({id:b.length-1-f,newest:a.newest&&0==f,pid:a.pid,cid:c.cid,title:c.name,count:b.length,
reverse:1})});return e}a.callback()}}},infoloader:function(a){return{url:pluginfo(a.plugin).apihost+"dacu_app/app/?c=BookDetail&a=get_book_info&id="+a.pid+"&comment=1&ui=0&ui_id=0&userid=0",method:"GET",ua:"kidstone.cn/2.0.0/15/Android",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},infofinder:function(a){return{json:!0,str:a.result,successfn:function(b,c,g,e){b=b.data;c=b.thumb;g=b.title;e=getLocalTime(1E3*parseInt(b.updatetime));var d=b.author,f=(b.label||[]).map(function(a){return a.labelname});
b=b.description;a.callback({name:g,img:c,added:a.data,description:"<p>"+(d?"【作者】"+d+"<br>":"")+(f?"【类型】"+f.join(",")+"<br>":"")+(e?"【更新】"+e+"<br>":"")+(b?"【简介】"+b:"")+"</p>",comment:1,preview:0,tags:gettag(g)+gettag(d)+gettag(f||"")});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"dacu_app/get_chapter.php?cid="+a.cid,method:"GET",ua:"kidstone.cn/2.0.0/15/Android",timeout:120,successfn:function(b,
c){a.callback({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b,c,g,e){b=b.data;array_count(b)?(b=b.map(function(a){return"http://cdn.517w.com/"+a.image}),a.download?a.callback({source:b,download:a.download,plugin:a.plugin}):a.callback({source:b,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.callback();return!0}}}},commentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"dacu_app/app/?c=Comment&a=get_comment&bid="+
a.pid+"&start="+20*((a.page||1)-1)+"&commentid=0&type=0&ui=0&ui_id=0&userid=0",method:"GET",ua:"kidstone.cn/2.0.0/15/Android",timeout:120,successfn:function(b,c){b?a.callback({result:b,header:c,commentbrowser:!1}):a.callback()}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b,c,g,e){b=b.data.data;var d=[];b.forEach(function(a){d.push({user:a.username,img:a.head,time:getLocalTime(1E3*parseInt(a.creat_at)),content:a.content})});if(array_count(d))for(var f in d)a.callback({page:a.page||
1,pagecount:-1,comment:{text:d[f].content,name:d[f].user,avatar:d[f].img,type:"received",label:d[f].time,day:"",time:"",reverse:1,extra:""}})}}},send:!1},previewflag:{loader:!1,finder:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return 1<a.page?(a.multupdate(),!1):{url:pluginfo(a.plugin).apihost+"index.php?m=web_app&c=index&a=dw_list&wi=1",method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{query:!0,selector:".dw_ls_ul li",str:a.result,
successfn:function(b){array_count(b)?a.callback(obj_contact(a,{pid:($$(b).find(".bnels").attr("onclick").match(/enterBook\((\d+)\)/)||[])[1],title:$$(b).find(".titlekb").text(),img:$$(b).find(".bnels").attr("src"),content:$$(b).find(".titlekbh").text()})):a.callback()}}}},hotflag:{loader:function(a){return 1<a.page?(a.multhot(),!1):{url:pluginfo(a.plugin).apihost+"dacu_app/app/?c=MainRank&a=get_label_rank&label=0&get_type=6&start=0&ui=0&ui_id=0&userid=0&home=0",method:"GET",ua:"kidstone.cn/2.0.0/15/Android",
timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){var b=(JSON.parse(a.result||"{}").data||{}).data||[];return{json:!0,str:JSON.stringify(b),successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}}}},fns:{pagedeal:function(a,b){b=b||{};console.log(a);var c=a.bookid,g=a.thumb,e=a.title,d=a.update_chapter_name+" "+getLocalTime(1E3*parseInt(a.updatetime)),f=a.author,f='<span style="font-size:10px;"><span class="color-white bg-'+getnowtheme()+
'" style="padding:3px;border-radius:3px;margin-right:3px;">'+f+"</span></span>"+a.description;if(b.multupdate||b.multhot||b.multsearch)return b.callback(obj_contact(b,{pid:c,img:g,title:e,content:d})),!1;b.callback({pid:c,title:e,img:g,stitle:d,content:f,comment:1})}}});
