ExView.Plugins({info:{name:"\u52a8\u6f2b\u5c4b\u6f2b\u753b",version:"2.2",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAABQSURBVDhPY/hPIaCNAQw5uDE6wGsAMYA2LsAGSDIA2UZ0jA6IdgEuQAUDooBmYMMwgE0OCSMMQAbIYgTYg8kAdAwDyHwsbCiPfEChAf//AwCTAnkMNUGWwAAAAABJRU5ErkJggg==",author:"Gentle",db:"dm5",apihost:"http://www.dm5.com/",pagetitle:["<br>","\u6536\u85cf","\u9996\u9875","\u7c7b\u578b","\u4e0b\u8f7d"],download:!0,
lazyload:!0,setting:!0,theme:"brown",cacheheader:{},nativeres:!0,typelistmode:!0,cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){ExView.workers.index.loader();ExView.workers.type.loader()}})},flags:{indexflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost,method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{"User-Agent":"ExView"},successfn:function(b,c){ExView.workers.index.countfinder(obj_contact(a,
{result:b,header:c}));a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"\u6b63\u5728\u52a0\u8f7d..."+(1<a.page?"<br>\u7b2c"+a.page+"\u9875":""),name:"\u9996\u9875",title:a.title,img:a.img}}},finder:function(a){return{reg:/\/manhua-([\w,\d,\_]+)\/"\s*title="((?!\").*?)"><img(.*?)<\/li>/g,str:(a.result||"").replace(/\r/g,"").replace(/\n/g,"").replace(/>\s*</g,"><").replace(/<li/g,"\n<li"),find:{pid:"$1",title:"$2",content:"$3"},successfn:function(a){console.log(JSON.stringify(a));if(array_count(a)){var c=
a.pid,d=a.title,e=getstr(/src="((?!\").*?)"/,a.content);a=getstr(/class="subtitle">((?!<).*?)</,a.content);c&&d&&addcardlist({pid:c,title:d,img:e,content:a?"\u66f4\u65b0\u81f3 "+a:"",comment:1})}else addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u6ca1\u6709\u5185\u5bb9</div>',2)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="-1|\u9996\u9875|index";mySession.nowlistpage=1;console.log(mySession.nowlistpages);
return!0}}}},typeflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"manhua-list-s1/",method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{"User-Agent":"ExView"},successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){addtypelist({title:"\u9996\u9875",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u9996\u9875"});addtypelist({tid:"new",title:"\u4eca\u65e5\u6f2b\u753b",img:pluginfo(a.plugin).icon,
group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u4eca\u65e5\u6f2b\u753b"});addtypelist({tid:"latest",title:"\u6700\u65b0\u7ae0\u8282",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u6700\u65b0\u7ae0\u8282"});addtypelist({tid:"updated",title:"\u8fde\u8f7d\u6f2b\u753b",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u8fde\u8f7d\u6f2b\u753b"});addtypelist({tid:"completed",title:"\u5b8c\u7ed3\u6f2b\u753b",img:pluginfo(a.plugin).icon,
group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u5b8c\u7ed3\u6f2b\u753b"});addtypelist({tid:"hktw",title:"\u6e2f\u6f2b",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u6e2f\u6f2b"});addtypelist({tid:"list-s4",title:"\u6392\u884c\u699c",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u6392\u884c\u699c"});return{reg:/type="checkbox"\s*value="(\d+)"\s*title="((?!\").*?)"/g,str:a.result,find:"$1{{separator}}$2",successfn:function(b){b=
b.split("{{separator}}");array_count(b)&&addtypelist({tid:"1"!=b[0]?"list-cg"+b[0]+"-s1":"list-s1",title:"1"!=b[0]?b[1]:"\u5168\u90e8",img:pluginfo(a.plugin).icon,group:{name:"fenlei",title:"\u5206\u7c7b"},content:"1"!=b[0]?b[1]:"\u5168\u90e8"})},afterfn:function(){for(var b=[],c=0;26>c;c++)b.push(String.fromCharCode(97+c));b.forEach(function(b){addtypelist({tid:"list-char"+b+"-s1",title:b.toUpperCase(),img:pluginfo(a.plugin).icon,group:{name:"souyin",title:"\u7d22\u5f15"},content:b.toUpperCase()})})}}}},
listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"manhua-"+a.keyword+(1<a.page?"-p"+a.page:"")+"/",method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{"User-Agent":"ExView"},successfn:function(b,c){b?(ExView.workers.list.countfinder(obj_contact(a,{result:b,header:c})),a.successfn&&a.successfn({result:b,header:c})):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u3010"+a.title+"\u3011<br>\u83b7\u53d6\u5931\u8d25\uff01","ExView"))},showinfo:{text:"\u6b63\u5728\u52a0\u8f7d..."+
(1<a.page?"<br>\u7b2c"+a.page+"\u9875":""),name:"\u3010"+a.title+"\u3011",title:a.title,img:a.img}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:a.result,find:plugfns(a.plugin).pagefind,successfn:function(b){b?plugfns(a.plugin).pagedeal(b,a):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u6ca1\u6709\u5185\u5bb9</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{reg:/\u5f53\u524d\u7b2c\s*<span\s*class="redzi">\d+\/(\d+)<\/span>\s*\u9875/g,
str:a.result,find:"$1",successfn:function(b){mySession.nowlistpages=(b||"-1")+"|"+a.keyword+"|list";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},searchflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"search?page="+(a.page||1)+"&title="+encodeURIComponent(a.keyword),method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{"User-Agent":"ExView"},successfn:function(b,c){b?(a.multsearch||(ExView.workers.search.countfinder(obj_contact(a,{result:b,
header:c})),setnowlistname("\u641c\u7d22\u3010"+a.keyword+"\u3011")),a.successfn&&a.successfn({result:b,header:c})):a.multsearch?a.multsearch():(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u3010"+a.keyword+"\u3011<br>\u83b7\u53d6\u641c\u7d22\u7ed3\u679c\u5931\u8d25\uff01","ExView"))},errorfn:function(){ExView.fw.hidePreloader();mySession.isloading=0;(function(b){if(1<parseInt(a.page))return a.multsearch&&a.multsearch(),!1;ExView.modules.curl({url:pluginfo(a.plugin).apihost+"search.ashx?t="+
encodeURIComponent(b),method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{"User-Agent":"ExView"},successfn:function(c,d){mySession.nowlistmenu="search";$$("#card-page").html("");$$("#card-page").scrollTo(0,0);ExView.modules.rulefind({reg:/setMouseSearchVars\(\d+,\d+,'(.*?)','manhua-(\w[-\w.+]*)\/',\d+\)/g,str:c,find:"$1{{separator}}$2",successfn:function(c,d,g){c=(c||"").split("{{separator}}");if(array_count(c)){console.log(JSON.stringify(c));d=c[1];c=c[0];if(a.multsearch)return a.multsearch(obj_contact(a,
{pid:d,img:"img/nopic.png",title:c,content:""})),!1;addcardlist({pid:d,title:c,name:c,img:"img/nopic.png",content:"",comment:1})}else{if(a.multsearch)return a.multsearch(),!1;mySession.nowlistpages="-1|"+b+"|search";mySession.nowlistpage=1;console.log(mySession.nowlistpages);addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u6ca1\u6709\u5185\u5bb9</div>',1)}},afterfn:function(){a.multsearch||(setnopic(),setnowlistname("\u641c\u7d22\u3010"+b+"\u3011"),mySession.nowlistpages=
"-1|"+b+"|search",mySession.nowlistpage=1,ExView.fw.hidePreloader(),mySession.isloading=0,searchbar(0),$$(".swiper-container")[0].swiper.slideTo(1))}})},showinfo:a.multsearch?"":{text:"\u6b63\u5728\u641c\u7d22...",name:"\u3010"+b+"\u3011",title:"\u641c\u7d22"}})})(a.keyword)},showinfo:{text:"\u6b63\u5728\u641c\u7d22..."+(1<a.page?"<br>\u7b2c"+a.page+"\u9875":""),name:"\u3010"+a.keyword+"\u3011",title:"\u641c\u7d22"}}},finder:function(a){return{reg:/<div\s*class="item">(.*?)<\/dt>/g,str:getresult(a.result),
find:"$1",successfn:function(b,c,d){console.log(b);if(b){c=getstr(/\/manhua-(\w[-\w.+]*)\//,b);d=getstr(/src="((?!\").*?)"/,b);var e=getstr(/class="title">((?!<).*?)</,b);b=(b=getstr(/class="value\s*red">((?!<).*?)</,b))?"\u66f4\u65b0\u81f3 "+b:"";if(a.multsearch)return a.multsearch(obj_contact(a,{pid:c,img:d,title:e,content:b})),!1;addcardlist({pid:c,title:e,name:e,img:d,content:b,comment:1})}else a.multsearch?a.multsearch():addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u6ca1\u6709\u5185\u5bb9</div>',
1)}}},countloader:function(a){return!1},countfinder:function(a){return{reg:/>(\d+)<\/a>\n<a(?!<).*?>\u4e0b\u4e00\u9875<\/a>/g,str:getresult(a.result).replace(/<a/g,"\n<a"),find:"$1",successfn:function(a){return{pagecount:a}}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"manhua-"+a.pid+"/",method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{"User-Agent":"ExView",Cookie:"isAdult=1"},successfn:function(b,c){b?a.successfn&&a.successfn({result:b,header:c}):
a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u5185\u5bb9\u9875\u83b7\u53d6\u5931\u8d25\uff01","ExView"))},showinfo:{text:"\u6b63\u5728\u52a0\u8f7d\u5185\u5bb9\u9875...",title:"\u5185\u5bb9\u9875",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){return{reg:/<li [style="width:\d+px"]*><a\s*class="tg"\s*href="(?!\").*?\/([\w,\d]+)\/"\s*title="(?!<).*?">((?!<).*?)<\/a>\uff08((?!<).*?)\uff09.*?<\/li>/g,str:a.result,find:{pid:a.pid,cid:"$1",title:"$2($3)"},
successfn:function(b,c,d,e){console.log(typeof b);if(array_count(b)){if(a.checkupdate)return{pid:b.pid,cid:b.cid,title:b.title};additemlist({id:c.length-d-1,newest:a.newest&&0==d,pid:b.pid,cid:b.cid,title:b.title,count:c.length,reverse:1});myContent.good=1}else a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u5185\u5bb9\u9875\u83b7\u53d6\u5931\u8d25\uff01","ExView"))},errorfn:function(){myContent.good=0;ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("\u8be5\u5185\u5bb9\u88ab\u5c4f\u853d\uff0c\u8bf7\u79d1\u5b66\u4e0a\u7f51\uff01",
"ExView",function(){window.open(pluginfo(a.plugin).apihost+"manhua-"+a.pid+"/","_blank","location=no")})},afterfn:function(){!a.checkupdate&&myContent.good&&ExView.workers.content.infofinder(a)}}},infoloader:function(a){return!1},infofinder:function(a){console.log(a);return{reg:/<div\s*class="innr91"\s*style="\s*margin-right:\d+px">\s*<img\s*src="(.*?)"\s*alt="(.*?)"\s*\/>\s*<\/div>/g,str:a.result,find:"$1{{separator}}$2",successfn:function(b,c,d,e){b=b.split("{{separator}}");console.log(JSON.stringify(b));
c=b[0];b=b[1];d=getstr(/\u6f2b\u753b\u72b6\u6001\uff1a(.*?)</,a.result);e=getstr(/>\u66f4\u65b0\u65f6\u95f4\uff1a(.*?)<\/span>/,a.result);var f=gettext(getstr(/>\u6f2b\u753b\u4f5c\u8005\uff1a(.*?)<\/span>/,a.result)),g=gettext(getstr(/>\u6f2b\u753b\u7c7b\u578b\uff1a(.*?)<\/span>/,a.result)),h=getstr(/\u7b80\u4ecb<\/h3><\/b>\s*<p style="(?!<).*?">((?:.|[\r\n])*?)<\/p>/,a.result).replace('<a href="###;" class="fold_open">[+\u5c55\u5f00]</a><span style="display:none">',"").replace('<a href="###;" class="fold_close">[-\u6298\u53e0]</a></span>',
"");setlistpic({name:b,img:c,added:a.data,description:"<p>\u3010\u4f5c\u8005\u3011"+f+"<br>\u3010\u7c7b\u578b\u3011"+g+"<br>\u3010"+d+"\u3011"+e+"<br>\u3010\u7b80\u4ecb\u3011"+h+"</p>",sourceurl:pluginfo(a.plugin).apihost+"manhua-"+a.pid+"/",comment:1,preview:0,tags:gettag(b)+gettag(d)+gettag(g.split(" "))+gettag(f.split(" "))});return!0}}}},parseflag:{loader:function(a){return"t"==a.cid.substring(0,1)?(a.download?chapterpredownload({error:"\u6b64\u4e3a\u817e\u8baf\u6e90,\u8bf7\u79d1\u5b66\u4e0a\u7f51\uff01",
download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u6b64\u4e3a\u817e\u8baf\u6e90,\u8bf7\u79d1\u5b66\u4e0a\u7f51\uff01","ExView",function(){})),!1):{url:pluginfo(a.plugin).apihost+a.cid+"/chapterfun.ashx?cid="+a.cid.substring(1)+"&page=1&key=&language=1&gtk=6",method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{"User-Agent":"ExView",Referer:pluginfo(a.plugin).apihost+a.cid+"/"},successfn:function(b,c){a.successfn&&a.successfn({result:b,
header:c})},showinfo:{text:"\u6b63\u5728\u52a0\u8f7d\u56fe\u7247\u4fe1\u606f...",title:"\u56fe\u7247",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){console.log(a);return{successfn:function(b){if(a.result){var c=[],c=function(a){return eval(a)}(a.result),d=a.cid,e=a.pid,f=Math.ceil(parseInt(getstr(/\((\d+)\u9875\)/,a.title))),g=function(a){for(var b=[],c={},d=0,e;null!=(e=a[d]);d++)c[e]||(b.push(e),c[e]=!0);return b},h=function(b){ExView.modules.curl({url:pluginfo(a.plugin).apihost+
d+"/chapterfun.ashx?cid="+d.substring(1)+"&page="+b+"&key=&language=1&gtk=6",method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{"User-Agent":"ExView",Cookie:"image_time_cookie="+d.substring(1)+"|0|0",Referer:pluginfo(a.plugin).apihost+d+"/"},progressname:"progress_"+a.plugin+"_"+a.pid+"_"+a.cid,progressfn:function(b,c){if(b||c)$$(".downloadprogress_"+a.plugin+"_"+a.pid+"_"+a.cid+".downloadnowpage").html("\u6b63\u5728\u89e3\u6790\u4e2d..."),$$(".progress_"+a.plugin+"_"+a.pid+
"_"+a.cid).html(" "+b+(c?"/"+c:"")+" Bytes")},successfn:function(d,e){if(d){var k=function(a){return eval(a)}(d),l=k.length;c=c.concat(k);if(b<f)try{return h(b+l),!1}catch(m){}!a.download&&ExView.fw.hidePreloader();c=g(c);c=c.map(function(b){return getimgload(b,a.plugin,{cacheheader:{Referer:"http://www.dm5.com/"+a.cid+"/"}})});a.download?chapterpredownload({source:c,download:a.download,plugin:a.plugin}):chapterviewer({source:c,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,
zoom:!0,title:a.title})}else a.download?chapterpredownload({error:"\u89e3\u6790\u9519\u8bef\uff01",download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u56fe\u7247\u4fe1\u606f\u83b7\u53d6\u5931\u8d25\uff01","ExView"))},errorfn:function(){chapterpredownload({error:"\u89e3\u6790\u9519\u8bef\uff01",download:a.download,plugin:a.plugin})},showinfo:a.download?"":3==b?{text:"\u6b63\u5728\u52a0\u8f7d\u56fe\u7247\u4fe1\u606f...",title:"\u56fe\u7247",name:getlistname(e),
img:getlistimg(e)}:""})};h(3)}else a.download?chapterpredownload({error:"\u89e3\u6790\u9519\u8bef\uff01",download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u56fe\u7247\u4fe1\u606f\u83b7\u53d6\u5931\u8d25\uff01","ExView"));return!0}}}},commentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"manhua-"+a.pid+"/"+(1<a.page?"p"+a.page+"/":""),method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{"User-Agent":"ExView"},
successfn:function(b,c){b?a.callback&&a.callback({result:b,header:c,commentbrowser:{url:pluginfo(a.plugin).apihost+"manhua-"+a.pid+"/",title:"\u8bc4\u8bba - "+pluginfo(a.plugin).name+'<br><span style="font-size:16px">'+(myContent.name||"")+"</span>",browser:!1,flag:""}}):a.callback&&a.callback()}}},finder:function(a){console.log(a);return{reg:/<div\s*class="sy_tba1"><img\s*src="((?!<).*?)"(?!<).*?\/><br\s*\/><a\s*id="(?!<).*?">((?!<).*?)\s*<\/a><\/div>\s*<div\s*class="sy_tba2">((?!<).*?)<\/div>/g,
str:a.result,find:{avatar:"$1",name:"$2",text:"$3"},successfn:function(b,c,d,e){b&&(c=getstr(/>(\d+)<\/a><a href="[\/,\w,\d,\:]*\/manhua-\w[-\w.+]*\/p\d+\/#topic">\u4e0b\u4e00\u9875<\/a>/,a.result),a.callback&&a.callback({page:a.page||1,pagecount:c||-1,comment:{text:b.text.replace(/href=/g,"xhref=").replace(/\u70b9\u51fb\u67e5\u770b\u5168\u6587.../g,"").replace(/\n/g,"<br>"),name:b.name,avatar:b.avatar,type:"received",label:"",day:"",time:"",reverse:1,extra:""}}))}}},send:!1},previewflag:{loader:!1,
finder:!1,more:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"manhua-latest"+(1<a.page?"-p"+a.page:"")+"/",method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{"User-Agent":"ExView"},successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:a.result,find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));b&&plugfns(a.plugin).pagedeal(b,
a)}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"manhua-new"+(1<a.page?"-p"+a.page:"")+"/",method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{"User-Agent":"ExView"},successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:a.result,find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));b&&plugfns(a.plugin).pagedeal(b,a)}}}}},fns:{pagerule:/<li\s*class="red_lj">((?:.|[\r\n])*?)<\/li>/g,
pagefind:"$1",pagedeal:function(a,b){b=b||{};var c=getstr(/\/manhua-(\w[-\w.+]*)\//,a),d=getstr(/src="((?!").*?)"/,a),e=getstr(/<strong>((?!<).*?)<\/strong>/,a),f=getstr(/(\u7b2c\d+[\u56de|\u8bdd])/,a),g=getstr(/(\d+[\u5e74|-]\d+[\u6708|-]\d+[\u65e5]?)/,a),f=f?"\u66f4\u65b0\u81f3 "+f:"";if(b.multupdate)return b.multupdate(obj_contact(b,{pid:c,img:d,title:e,content:f})),!1;if(b.multhot)return b.multhot(obj_contact(b,{pid:c,img:d,title:e,content:f})),!1;addcardlist({pid:c,title:e,img:d,content:f,stitle:g,
comment:1,preview:0,extrabutton:""})}}});
