ExView.Plugins({info:{name:"\u52a8\u6f2b\u4e4b\u5bb6\u6f2b\u753b",version:"2.2",db:"dmzjmh",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAA7EAAAOxAGVKw4bAAABtklEQVQ4jZWTzWoUQRSFv1tV3WaCz+M+OGGMjiKKC0FFwSgaDS59BTeKE8MgY0AUF0JQCCaYKPoAPk5MKv0zdV1U/w0hSC4U1XX6nFP3nqYFYPDmr9rE4By4RHBOSFMhTSE5I6SJkKRgHVgriEAIgRfnUpHFURQbw6kMAMoy4MQYUNh+0APg2ocjAD5eTzmpnv+ZxgcVTA1eeusB+HJnjhC0IS/v5DzaK1j9XTZYWSploZQlOACt1uV3HmvBOmnIk4vHOynyKJgqOK3UOw/jCFc2PDJtybc2c1wC1sLGMJplmYKCqiL9tQM1EoP5/rjHcOL5ttw7cf667m3lqILRykkVLow9IbSkq+9jLjc+xWBvfs6ad9mRkmWKI3YTK0BHT6hyKwutZm/DLfJ4qQGou9hd6aEdh637cZSvd+O+eXuuNSiUotD4FWqTuCuDdc/uShQtjT0iIALbVdDDiW/4cv71gQL8XJ0HoD86bAR7T+aPhbc09jPnKsRZkioEhcW1wxl8sB5D7i7XJfRHUVB302ACAvx42uK1uSy82lcR0/Vpfpb/lYaAACy83FcxpzNRVX49Oyv/AAkByABrVBe1AAAAAElFTkSuQmCC",
apihost:"http://m.dmzj.com/",pagetitle:["<br>","\u6536\u85cf","\u9996\u9875","\u7c7b\u578b","\u4e0b\u8f7d"],download:!0,lazyload:!0,theme:"blue",setting:!0,cacheheader:{Referer:"http://m.dmzj.com/"},nativeres:!0,cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){ExView.workers.index.loader();ExView.workers.type.loader()}})},flags:{indexflag:{loader:function(a){a.front||a.page||setnowlistname("\u9996\u9875","",pluginfo(a.plugin).icon);return{url:pluginfo(a.plugin).apihost,
method:"GET",timeout:120,successfn:function(b,c){ExView.workers.index.countfinder(obj_contact(a,{result:b,header:c}));a.successfn&&a.successfn({result:b,header:c})},errorfn:function(){a.page||setnowlistname("\u9996\u9875","",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("\u7f51\u7edc\u9519\u8bef\uff01","ExView")},canclefn:function(){a.page||setnowlistname("\u9996\u9875","",pluginfo(a.plugin).icon)},showinfo:{text:"\u6b63\u5728\u52a0\u8f7d..."+(1<a.page?"<br>\u7b2c"+
a.page+"\u9875":""),name:"\u9996\u9875",title:a.title,img:a.img}}},finder:function(a){return{reg:/<a\s*class="ImgA"((?:.|[\r\n])*?)<\/li>/g,str:a.result,find:"$1",successfn:function(b){if(b){var c=getstr(/info\/([\w,\d]+)\.html/,b),d=getstr(/class="txtA(?!<).*?">((?!<).*?)</,b),e=getstr(/<img\s*src="((?!").*?)"/,b);b=getstr(/class="info">\u4f5c\u8005:((?!<).*?)</,b);addcardlist({pid:c,title:d,img:getimgload(e,a.plugin,a.plugin),stitle:b,comment:1})}else addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u6ca1\u6709\u5185\u5bb9</div>',
2)},errorfn:function(){a.page||setnowlistname("\u9996\u9875","",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("\u7f51\u7edc\u9519\u8bef\uff01","ExView")}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="-1|\u9996\u9875|index";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},typeflag:{loader:function(a){addtypelist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u6b63\u5728\u52a0\u8f7d\u7c7b\u578b...<div class="progress"></span></div>',
2);return{url:pluginfo(a.plugin).apihost+"classify.html",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){addtypelist({title:"\u9996\u9875",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u9996\u9875"});addtypelist({tid:"",listflag:"latest/{{page}}.json",title:"\u66f4\u65b0",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u66f4\u65b0"});addtypelist({tid:"",listflag:"rank/0-0-0-{{page}}.json",
title:"\u4eba\u6c14\u6392\u884c",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u4eba\u6c14\u6392\u884c"});addtypelist({tid:"",listflag:"rank/1-0-0-{{page}}.json",title:"\u5410\u69fd\u6392\u884c",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u5410\u69fd\u6392\u884c"});addtypelist({tid:"",listflag:"rank/2-0-0-{{page}}.json",title:"\u8ba2\u9605\u6392\u884c",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"\u5bfc\u822a"},
content:"\u8ba2\u9605\u6392\u884c"});return{reg:/<div\s*class="classopen"((?:.|[\r\n])*?)<\/div>/g,str:a.result,find:"$1",successfn:function(b){if(b){var c=["\u9898\u6750","\u8bfb\u8005\u7fa4","\u8fdb\u5ea6","\u5730\u57df"];ExView.modules.rulefind({reg:/<ul>((?:.|[\r\n])*?)<\/ul>/g,str:b,find:"$1",successfn:function(b,e,f){ExView.modules.rulefind({reg:/<li><a\s*onclick="itemClickAction\(([\d,\,,\ ]+)\)">((?!<).*?)<\/a><\/li>/g,str:b,find:"$1{{separator}}$2",successfn:function(b){b=b.split("{{separator}}");
var d="\u5168\u90e8"==b[1]?c[f]:b[1];addtypelist({tid:b[0],title:d,img:pluginfo(a.plugin).icon,group:{name:"fenlei_"+f,title:c[f]},content:d})}})}})}}}}},listflag:{loader:function(a){var b="0-0-0-0-0";if(!a.flag){for(var b=a.keyword.split(",")[0].trim(),c=a.keyword.split(",")[1].trim(),d=[],e=0;5>e;e++)e==parseInt(b)?d[e]=c:d[e]="0";b=d.join("-")}return{url:pluginfo(a.plugin).apihost+(a.flag?a.flag.replace(/{{page}}/g,parseInt(a.page||1)-1):"classify/"+b+"-"+(parseInt(a.page||1)-1)+".json"),method:"GET",
timeout:120,successfn:function(b,c){b?(ExView.workers.list.countfinder(obj_contact(a,{result:b,header:c})),a.successfn&&a.successfn({result:b,header:c})):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u3010"+a.title+"\u3011<br>\u83b7\u53d6\u5931\u8d25\uff01","ExView"))},showinfo:{text:"\u6b63\u5728\u52a0\u8f7d..."+(1<a.page?"<br>\u7b2c"+a.page+"\u9875":""),title:a.title,name:"\u3010"+a.title+"\u3011",img:a.img}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){array_count(b)?
plugfns(a.plugin).pagedeal(b):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u6ca1\u6709\u5185\u5bb9</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages=("top"==a.flag?"-1":"0")+"|"+a.keyword+"|list";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},searchflag:{loader:function(a){return 1<parseInt(a.page)?(a.multsearch&&a.multsearch(),!1):{url:pluginfo(a.plugin).apihost+
"search/"+encodeURIComponent(a.keyword)+".html",method:"GET",timeout:120,successfn:function(b,c){b?(b=getstr(/var\s*serchArry=(.*?)\r*\n/,b),a.multsearch||(ExView.workers.search.countfinder(obj_contact(a,{result:b,header:c})),setnowlistname("\u641c\u7d22\u3010"+a.keyword+"\u3011")),a.successfn&&a.successfn({result:b,header:c})):a.multsearch?a.multsearch():(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u3010"+a.keyword+"\u3011<br>\u83b7\u53d6\u641c\u7d22\u7ed3\u679c\u5931\u8d25\uff01",
"ExView"))},showinfo:{text:"\u6b63\u5728\u641c\u7d22..."+(1<a.page?"<br>\u7b2c"+a.page+"\u9875":""),name:"\u3010"+a.keyword+"\u3011",title:"\u641c\u7d22"}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b,c,d){console.log(b);array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.multsearch?a.multsearch():addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u6ca1\u6709\u5185\u5bb9</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(b){mySession.nowlistpages=
"-1|"+a.keyword+"|search";mySession.nowlistpage=1;console.log(mySession.nowlistpages)}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"info/"+a.pid+".html",method:"GET",timeout:120,successfn:function(b,c){b?a.successfn&&a.successfn({result:b,header:c}):a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u5185\u5bb9\u9875\u83b7\u53d6\u5931\u8d25\uff01","ExView"))},showinfo:{text:"\u6b63\u5728\u52a0\u8f7d\u5185\u5bb9\u9875...",title:"\u5185\u5bb9\u9875",
name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){return{json:!0,str:getstr(/initIntroData\((.*?)\);/,a.result),successfn:function(b,c,d,e){c=b.data;console.log(typeof c);if(array_count(c)){if(a.checkupdate)return{pid:a.pid,cid:c[0].id,title:c[0].chapter_name};e=[];myContent.comic_id=c[0].comic_id;for(d=0;d<c.length;d++)e[d]=additemlist({id:c.length-d-1,newest:a.newest&&0==d,pid:a.pid,cid:c[d].id,title:c[d].chapter_name,count:c.length,reverse:1});return e}a.checkupdate||(ExView.fw.hidePreloader(),
mySession.isloading=0,ExView.fw.alert("\u5185\u5bb9\u9875\u83b7\u53d6\u5931\u8d25\uff01","ExView"))},afterfn:function(){a.checkupdate||ExView.workers.content.infofinder(a)}}},infoloader:function(a){return!1},infofinder:function(a){console.log(a);return{successfn:function(b,c,d,e){b=getstr(/id="Cover">\s*\r*\n*\s*<img\s*src="((?!").*?)"/,a.result);c=getstr(/id="comicName">((?!<).*?)</,a.result);d=getstr(/class="date">\s*([\-,\d,\:,\ ]+)\s*</,a.result);e=getstr(/introName"\s*href="(?!\").*?">((?!<).*?)<\/a>/,
a.result);var f=getstr(/class="txtDesc(?!\").*?">((?:.|[\r\n])*?)</,a.result);setlistpic({name:c,img:getimgload(b,a.plugin),added:a.data,description:"<p>\u3010\u4f5c\u8005\u3011"+e+"<br>\u3010\u66f4\u65b0\u3011"+d+"<br>\u3010\u7b80\u4ecb\u3011"+f+"</p>",comment:1,preview:0,tags:gettag(c)+gettag(e),sourceurl:pluginfo(a.plugin).apihost+"info/"+a.pid+".html"});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"view/"+a.pid+"/"+a.cid+".html",method:"GET",timeout:120,successfn:function(b,
c){a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"\u6b63\u5728\u52a0\u8f7d\u56fe\u7247\u4fe1\u606f...",title:"\u56fe\u7247",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){console.log(a);return{reg:/"page_url":((?!\]).*?),"chapter_type":/g,str:a.result,find:"$1",successfn:function(b,c,d,e){b?(b=JSON.parse(b),b=b.map(function(b){return getimgload(b,a.plugin,{cacheheader:{Referer:pluginfo(a.plugin).apihost+"view/"+a.pid+"/"+a.cid+".html"}})}),console.log(b),a.download?
chapterpredownload({source:b,download:a.download,plugin:a.plugin}):chapterviewer({source:b,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.download?chapterpredownload({error:"\u89e3\u6790\u9519\u8bef\uff01",download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u56fe\u7247\u4fe1\u606f\u83b7\u53d6\u5931\u8d25\uff01","ExView"));return!0}}}},commentflag:{loader:function(a){myContent.comic_id&&myContent.pid==
a.pid||$$.ajax({url:pluginfo(a.plugin).apihost+"info/"+a.pid+".html",success:function(a){if(a=getstr(/initIntroData\((.*?)\);/,a))a=JSON.parse(a),a=a[0].data,myContent.comic_id=a[0].comic_id},error:function(){},async:!1});if(!myContent.comic_id)return ExView.fw.hidePreloader(),!1;a.pid=myContent.comic_id;return{url:"http://interface.dmzj.com/api/comment/getComment?callback=success_jsonpCallback&type=0&type_id="+a.pid+"&cur_page="+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){b?((b=
b.replace("success_jsonpCallback",""))&&(b=b.substr(2,b.length-3)),a.callback&&a.callback({result:b,header:c,commentbrowser:{url:pluginfo(a.plugin).apihost+"comment/"+a.pid+".html",title:"\u8bc4\u8bba - "+pluginfo(a.plugin).name+'<br><span style="font-size:16px">'+(myContent.name||"")+"</span>",browser:!1,flag:""}})):a.callback&&a.callback()}}},finder:function(a){console.log(a);return{json:!0,str:a.result,successfn:function(b,c,d,e){if(array_count(b)){b=b.data;for(var f in b)a.callback&&a.callback({page:a.page||
1,pagecount:0,comment:{text:b[f].content,name:b[f].nickname,avatar:getimgload(b[f].avatar_url,a.plugin),type:"received",label:getLocalTime(1E3*parseInt(b[f].createtime)),day:"",time:"",reverse:1,extra:""}})}}}},send:!1},previewflag:{loader:!1,finder:!1,more:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"latest/"+(parseInt(a.page||1)-1)+".json",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{json:!0,
str:a.result,successfn:function(b){console.log(JSON.stringify(b));array_count(b)&&plugfns(a.plugin).pagedeal(b,a)}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"rank/0-0-0-"+(parseInt(a.page||1)-1)+".json",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){console.log(JSON.stringify(b));array_count(b)&&plugfns(a.plugin).pagedeal(b,a)}}}}},fns:{pagedeal:function(a,
b){b=b||{};var c=a.comic_py||a.id,d="http://images.dmzj.com/"+a.cover,d=getimgload(d,b.plugin),e=a.name,f="\u3010"+(a.status||a.types)+"\u3011 \u66f4\u65b0\u81f3 "+(a.last_update_chapter_name||a.chapter_name||a.authors);if(b.multupdate)return b.multupdate(obj_contact(b,{pid:c,img:d,title:e,content:f})),!1;if(b.multhot)return b.multhot(obj_contact(b,{pid:c,img:d,title:e,content:f})),!1;if(b.multsearch)return b.multsearch(obj_contact(b,{pid:c,img:d,title:e,content:f})),!1;addcardlist({pid:c,title:e,
img:d,stitle:getLocalTime(1E3*parseInt(a.last_updatetime)),content:f,comment:1})}}});
