ExView.Plugins({info:{name:"动漫之家漫画",version:"2.2",db:"dmzjmh",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAA7EAAAOxAGVKw4bAAABtklEQVQ4jZWTzWoUQRSFv1tV3WaCz+M+OGGMjiKKC0FFwSgaDS59BTeKE8MgY0AUF0JQCCaYKPoAPk5MKv0zdV1U/w0hSC4U1XX6nFP3nqYFYPDmr9rE4By4RHBOSFMhTSE5I6SJkKRgHVgriEAIgRfnUpHFURQbw6kMAMoy4MQYUNh+0APg2ocjAD5eTzmpnv+ZxgcVTA1eeusB+HJnjhC0IS/v5DzaK1j9XTZYWSploZQlOACt1uV3HmvBOmnIk4vHOynyKJgqOK3UOw/jCFc2PDJtybc2c1wC1sLGMJplmYKCqiL9tQM1EoP5/rjHcOL5ttw7cf667m3lqILRykkVLow9IbSkq+9jLjc+xWBvfs6ad9mRkmWKI3YTK0BHT6hyKwutZm/DLfJ4qQGou9hd6aEdh637cZSvd+O+eXuuNSiUotD4FWqTuCuDdc/uShQtjT0iIALbVdDDiW/4cv71gQL8XJ0HoD86bAR7T+aPhbc09jPnKsRZkioEhcW1wxl8sB5D7i7XJfRHUVB302ACAvx42uK1uSy82lcR0/Vpfpb/lYaAACy83FcxpzNRVX49Oyv/AAkByABrVBe1AAAAAElFTkSuQmCC",
apihost:"http://m.dmzj.com/",pagetitle:["<br>","收藏","首页","类型","下载"],download:!0,lazyload:!0,theme:"blue",setting:!0,cacheheader:{Referer:"http://m.dmzj.com/"},nativeres:!0,cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){ExView.workers.index.loader();ExView.workers.type.loader()}})},flags:{indexflag:{loader:function(a){a.front||a.page||setnowlistname("首页","",pluginfo(a.plugin).icon);return{url:pluginfo(a.plugin).apihost,
method:"GET",timeout:120,successfn:function(b,c){ExView.workers.index.countfinder(obj_contact(a,{result:b,header:c}));a.successfn&&a.successfn({result:b,header:c})},errorfn:function(){a.page||setnowlistname("首页","",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("网络错误！","ExView")},canclefn:function(){a.page||setnowlistname("首页","",pluginfo(a.plugin).icon)},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+
a.page+"页":""),name:"首页",title:a.title,img:a.img}}},finder:function(a){return{reg:/<a\s*class="ImgA"((?:.|[\r\n])*?)<\/li>/g,str:a.result,find:"$1",successfn:function(b){if(b){var c=getstr(/info\/([\w,\d]+)\.html/,b),d=getstr(/class="txtA(?!<).*?">((?!<).*?)</,b),e=getstr(/<img\s*src="((?!").*?)"/,b);b=getstr(/class="info">作者:((?!<).*?)</,b);e=getcoverload(e,{cacheheader:pluginfo(a.plugin).cacheheader,nativeres:pluginfo(a.plugin).nativeres});addcardlist({pid:c,title:d,img:e,
stitle:b,comment:1})}else addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',2)},errorfn:function(){a.page||setnowlistname("首页","",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("网络错误！","ExView")}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="-1|首页|index";mySession.nowlistpage=1;console.log(mySession.nowlistpages);
return!0}}}},typeflag:{loader:function(a){addtypelist('<div align="center" class="list-block"><img src="img/logo.png"/><br>正在加载类型...<div class="progress"></span></div>',2);return{url:pluginfo(a.plugin).apihost+"classify.html",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){addtypelist({title:"首页",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"首页"});
addtypelist({tid:"",listflag:"latest/{{page}}.json",title:"更新",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"更新"});addtypelist({tid:"",listflag:"rank/0-0-0-{{page}}.json",title:"人气排行",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"人气排行"});addtypelist({tid:"",listflag:"rank/1-0-0-{{page}}.json",title:"吐槽排行",img:pluginfo(a.plugin).icon,group:{name:"daohang",
title:"导航"},content:"吐槽排行"});addtypelist({tid:"",listflag:"rank/2-0-0-{{page}}.json",title:"订阅排行",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"订阅排行"});return{reg:/<div\s*class="classopen"((?:.|[\r\n])*?)<\/div>/g,str:a.result,find:"$1",successfn:function(b){if(b){var c=["题材","读者群","进度","地域"];ExView.modules.rulefind({reg:/<ul>((?:.|[\r\n])*?)<\/ul>/g,
str:b,find:"$1",successfn:function(b,e,f){ExView.modules.rulefind({reg:/<li><a\s*onclick="itemClickAction\(([\d,\,,\ ]+)\)">((?!<).*?)<\/a><\/li>/g,str:b,find:"$1{{separator}}$2",successfn:function(b){b=b.split("{{separator}}");var d="全部"==b[1]?c[f]:b[1];addtypelist({tid:b[0],title:d,img:pluginfo(a.plugin).icon,group:{name:"fenlei_"+f,title:c[f]},content:d})}})}})}}}}},listflag:{loader:function(a){var b="0-0-0-0-0";if(!a.flag){for(var b=a.keyword.split(",")[0].trim(),c=a.keyword.split(",")[1].trim(),
d=[],e=0;5>e;e++)e==parseInt(b)?d[e]=c:d[e]="0";b=d.join("-")}return{url:pluginfo(a.plugin).apihost+(a.flag?a.flag.replace(/{{page}}/g,parseInt(a.page||1)-1):"classify/"+b+"-"+(parseInt(a.page||1)-1)+".json"),method:"GET",timeout:120,successfn:function(b,c){b?(ExView.workers.list.countfinder(obj_contact(a,{result:b,header:c})),a.successfn&&a.successfn({result:b,header:c})):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+a.title+"】<br>获取失败！",
"ExView"))},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),title:a.title,name:"【"+a.title+"】",img:a.img}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages=("top"==
a.flag?"-1":"0")+"|"+a.keyword+"|list";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},searchflag:{loader:function(a){return 1<parseInt(a.page)?(a.multsearch&&a.multsearch(),!1):{url:pluginfo(a.plugin).apihost+"search/"+encodeURIComponent(a.keyword)+".html",method:"GET",timeout:120,successfn:function(b,c){b?(b=getstr(/var\s*serchArry=(.*?)\r*\n/,b),a.multsearch||(ExView.workers.search.countfinder(obj_contact(a,{result:b,header:c})),setnowlistname("搜索【"+a.keyword+
"】")),a.successfn&&a.successfn({result:b,header:c})):a.multsearch?a.multsearch():(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+a.keyword+"】<br>获取搜索结果失败！","ExView"))},showinfo:{text:"正在搜索..."+(1<a.page?"<br>第"+a.page+"页":""),name:"【"+a.keyword+"】",title:"搜索"}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b,c,d){console.log(b);array_count(b)?plugfns(a.plugin).pagedeal(b,
a):a.multsearch?a.multsearch():addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(b){mySession.nowlistpages="-1|"+a.keyword+"|search";mySession.nowlistpage=1;console.log(mySession.nowlistpages)}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"info/"+a.pid+".html",method:"GET",timeout:120,successfn:function(b,c){b?a.successfn&&
a.successfn({result:b,header:c}):a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},showinfo:{text:"正在加载内容页...",title:"内容页",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){return{json:!0,str:getstr(/initIntroData\((.*?)\);/,a.result),successfn:function(b,c,d,e){c=b.data;console.log(typeof c);if(array_count(c)){if(a.checkupdate)return{pid:a.pid,
cid:c[0].id,title:c[0].chapter_name};e=[];myContent.comic_id=c[0].comic_id;for(d=0;d<c.length;d++)e[d]=additemlist({id:c.length-d-1,newest:a.newest&&0==d,pid:a.pid,cid:c[d].id,title:c[d].chapter_name,count:c.length,reverse:1});return e}a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},afterfn:function(){a.checkupdate||ExView.workers.content.infofinder(a)}}},infoloader:function(a){return!1},infofinder:function(a){console.log(a);
return{successfn:function(b,c,d,e){b=getstr(/id="Cover">\s*\r*\n*\s*<img\s*src="((?!").*?)"/,a.result);c=getstr(/id="comicName">((?!<).*?)</,a.result);d=getstr(/class="date">\s*([\-,\d,\:,\ ]+)\s*</,a.result);e=getstr(/introName"\s*href="(?!\").*?">((?!<).*?)<\/a>/,a.result);var f=getstr(/class="txtDesc(?!\").*?">((?:.|[\r\n])*?)</,a.result);b=getcoverload(b,{cacheheader:pluginfo(a.plugin).cacheheader,nativeres:pluginfo(a.plugin).nativeres});setlistpic({name:c,img:b,added:a.data,description:"<p>【作者】"+
e+"<br>【更新】"+d+"<br>【简介】"+f+"</p>",comment:1,preview:0,tags:gettag(c)+gettag(e),sourceurl:pluginfo(a.plugin).apihost+"info/"+a.pid+".html"});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"view/"+a.pid+"/"+a.cid+".html",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"正在加载图片信息...",title:"图片",name:getlistname(a.pid),
img:getlistimg(a.pid)}}},finder:function(a){console.log(a);return{reg:/"page_url":((?!\]).*?),"chapter_type":/g,str:a.result,find:"$1",successfn:function(b,c,d,e){b?(b=JSON.parse(b),b=b.map(function(b){return getimgload(b,a.plugin,{cacheheader:{Referer:pluginfo(a.plugin).apihost+"view/"+a.pid+"/"+a.cid+".html"}})}),console.log(b),a.download?chapterpredownload({source:b,download:a.download,plugin:a.plugin}):chapterviewer({source:b,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,
zoom:!0,title:a.title})):a.download?chapterpredownload({error:"解析错误！",download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("图片信息获取失败！","ExView"));return!0}}}},commentflag:{loader:function(a){myContent.comic_id&&myContent.pid==a.pid||$$.ajax({url:pluginfo(a.plugin).apihost+"info/"+a.pid+".html",success:function(a){if(a=getstr(/initIntroData\((.*?)\);/,a))a=JSON.parse(a),a=a[0].data,
myContent.comic_id=a[0].comic_id},error:function(){},async:!1});if(!myContent.comic_id)return ExView.fw.hidePreloader(),!1;a.pid=myContent.comic_id;return{url:"http://interface.dmzj.com/api/comment/getComment?callback=success_jsonpCallback&type=0&type_id="+a.pid+"&cur_page="+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){b?((b=b.replace("success_jsonpCallback",""))&&(b=b.substr(2,b.length-3)),a.callback&&a.callback({result:b,header:c,commentbrowser:{url:pluginfo(a.plugin).apihost+"comment/"+
a.pid+".html",title:"评论 - "+pluginfo(a.plugin).name+'<br><span style="font-size:16px">'+(myContent.name||"")+"</span>",browser:!1,flag:""}})):a.callback&&a.callback()}}},finder:function(a){console.log(a);return{json:!0,str:a.result,successfn:function(b,c,d,e){if(array_count(b)){b=b.data;for(var f in b)a.callback&&a.callback({page:a.page||1,pagecount:0,comment:{text:b[f].content,name:b[f].nickname,avatar:getimgload(b[f].avatar_url,a.plugin),type:"received",label:getLocalTime(1E3*parseInt(b[f].createtime)),
day:"",time:"",reverse:1,extra:""}})}}}},send:!1},previewflag:{loader:!1,finder:!1,more:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"latest/"+(parseInt(a.page||1)-1)+".json",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){console.log(JSON.stringify(b));array_count(b)&&plugfns(a.plugin).pagedeal(b,a)}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"rank/0-0-0-"+(parseInt(a.page||1)-1)+".json",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){console.log(JSON.stringify(b));array_count(b)&&plugfns(a.plugin).pagedeal(b,a)}}}}},fns:{pagedeal:function(a,b){b=b||{};var c=a.comic_py||a.id,d="http://images.dmzj.com/"+a.cover,d=getcoverload(d,{cacheheader:pluginfo(b.plugin).cacheheader,nativeres:pluginfo(b.plugin).nativeres}),e=a.name,
f="【"+(a.status||a.types)+"】 更新至 "+(a.last_update_chapter_name||a.chapter_name||a.authors);if(b.multupdate)return b.multupdate(obj_contact(b,{pid:c,img:d,title:e,content:f})),!1;if(b.multhot)return b.multhot(obj_contact(b,{pid:c,img:d,title:e,content:f})),!1;if(b.multsearch)return b.multsearch(obj_contact(b,{pid:c,img:d,title:e,content:f})),!1;addcardlist({pid:c,title:e,img:d,stitle:getLocalTime(1E3*parseInt(a.last_updatetime)),content:f,comment:1})}}});
