ExView.Plugins({info:{name:"L绅士漫画",version:"2.2",author:"光腚菊",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAA3SURBVDhPY/hPIhjcGhgYUBBIAAQgknCAoQEJ0EgDHBGrAQkMFg1wBNMAB1BVEIp4MOg0/P8PAMLtkoro2Y50AAAAAElFTkSuQmCC",db:"erolord",apihost:"http://erolord.com/",pagetitle:["<br>","收藏","首页","类型","下载"],download:!0,lazyload:!0,setting:!0,settingextra:getui([{name:"typebox",
title:"类型方块界面",type:"checkbox"},{name:"nativeres",title:"使用本地请求",type:"checkbox"}]),nativeres:!1,typebox:!1,theme:"bluegray",cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){ExView.workers.index.loader();ExView.workers.type.loader()}})},flags:{indexflag:{loader:function(a){a.front||a.page||setnowlistname("首页","",plugfns(a.plugin).typelistext.index.imgurl);return{url:pluginfo(a.plugin).apihost+
(1<a.page?"page/"+a.page+"/":""),method:"GET",data:"",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,successfn:function(b,c){ExView.workers.index.countfinder(obj_contact(a,{result:b,header:c}));a.successfn&&a.successfn({result:b,header:c})},errorfn:function(){a.page||setnowlistname("首页","",plugfns(a.plugin).typelistext.index.imgurl);ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("网络错误！","ExView")},canclefn:function(){a.page||setnowlistname("首页",
"",plugfns(a.plugin).typelistext.index.imgurl)},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),name:"首页",title:a.title,img:a.img}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));b?plugfns(a.plugin).pagedeal(b):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',2)},errorfn:function(){a.page||
setnowlistname("首页","",plugfns(a.plugin).typelistext.index.imgurl);ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("网络错误！","ExView")}}},countloader:function(a){return!1},countfinder:function(a){return{reg:plugfns(a.plugin).pagecountrule,str:a.result,find:plugfns(a.plugin).pagecountfind,successfn:function(a){a=a.split("{{separator}}");mySession.nowlistpages=(a[0].replace(/\,/g,"")||"0")+"|首页|index";mySession.nowlistpage=1;console.log(mySession.nowlistpages);
return!0}}}},typeflag:{loader:function(a){return{successfn:function(){ExView.workers.type.finder()}}},finder:function(a){return{successfn:function(b){if(pluginfo(a.plugin).typebox){b='<table border="1" style="position:absolute;border-collapse:collapse;width:100%;height:100%;border:1px solid #000000"><tbody><tr>'+plugfns(a.plugin).gettypebox("",plugfns(a.plugin).typelistext.index.title,plugfns(a.plugin).typelistext.index.imgurl,"")+plugfns(a.plugin).gettypebox("ntr",plugfns(a.plugin).typelistext.topfive.title,
plugfns(a.plugin).typelistext.topfive.imgurl,"");var c=3,d;for(d in plugfns(a.plugin).typelist)b+=(1==c?"<tr>":"")+plugfns(a.plugin).gettypebox(d,plugfns(a.plugin).typelist[d].title,plugfns(a.plugin).typelist[d].imgurl,"")+(3==c?"</tr>":""),3==c?c=1:c++;addtypelist(b+"</tbody></table>",2);try{clearInterval(mySession.lazyload.typelistlazyloadser)}catch(e){}$$("#typelist").onscroll=""}else for(d in addtypelist("<ul></ul>",2),addtypelist({listbg:!0,title:plugfns(a.plugin).typelistext.index.title,img:plugfns(a.plugin).typelistext.index.imgurl,
content:plugfns(a.plugin).typelistext.index.title}),addtypelist({tid:"netorare",listbg:!0,title:plugfns(a.plugin).typelistext.topfive.title,img:plugfns(a.plugin).typelistext.topfive.imgurl,content:plugfns(a.plugin).typelistext.topfive.title}),plugfns(a.plugin).typelist)addtypelist({tid:d,listbg:!0,title:plugfns(a.plugin).typelist[d].title,img:plugfns(a.plugin).typelist[d].imgurl,content:plugfns(a.plugin).typelist[d].title})}}}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"page/"+
(a.page||1)+"/?s="+a.keyword,method:"GET",data:"",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,successfn:function(b,c){b?(ExView.workers.list.countfinder(obj_contact(a,{result:b,header:c})),a.successfn&&a.successfn({result:b,header:c})):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+a.title+"】<br>获取失败！","ExView"))},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),name:"【"+a.title+"】",
title:a.title,img:a.img}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b){b?plugfns(a.plugin).pagedeal(b):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{reg:plugfns(a.plugin).pagecountrule,str:a.result,find:plugfns(a.plugin).pagecountfind,successfn:function(b){b?(b=b.split("{{separator}}"),
mySession.nowlistpages=(b[0].replace(/\,/g,"")||"0")+"|"+a.keyword+"|list"):mySession.nowlistpages="-1|"+a.keyword+"|list";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},searchflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"page/"+(a.page||1)+"/?s="+a.keyword,method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{"Content-Type":"application/x-www-form-urlencoded"},successfn:function(b,c){b?(a.multsearch||(ExView.workers.search.countfinder(obj_contact(a,
{result:b,header:c})),setnowlistname("搜索【"+a.keyword+"】")),a.successfn&&a.successfn({result:b,header:c})):a.multsearch?a.multsearch():(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+a.keyword+"】<br>获取搜索结果失败！","ExView"))},showinfo:{text:"正在搜索..."+(1<a.page?"<br>第"+a.page+"页":""),name:"【"+a.keyword+"】",title:"搜索"}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,
str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b,c,d){console.log(b);b?plugfns(a.plugin).pagedeal(b,a):a.multsearch?a.multsearch():addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{reg:plugfns(a.plugin).pagecountrule,str:a.result,find:plugfns(a.plugin).pagecountfind,successfn:function(b){b?(b=b.split("{{separator}}"),mySession.nowlistpages=
(b[0].replace(/\,/g,"")||"0")+"|"+a.keyword+"|search"):mySession.nowlistpages="-1|"+a.keyword+"|search";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"doujin/"+a.pid+"/",method:"GET",data:"",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,successfn:function(b,c){b?a.successfn&&a.successfn({result:b,header:c}):a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！",
"ExView"))},showinfo:{text:"正在加载内容页...",title:"内容页",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){return{successfn:function(b){b=a.pid;if(a.checkupdate)return{pid:b,cid:1,title:"全1话"};for(var c=[],d=0;1>d;d++)c[d]=additemlist({id:d,newest:a.newest&&0==d,pid:b,cid:d+1,title:"全"+(d+1)+"话",count:1,reverse:0});console.log(c);return c},afterfn:function(){a.checkupdate||ExView.workers.content.infofinder(a)}}},infoloader:function(a){return!1},
infofinder:function(a){console.log(a);return{reg:/<h1\s(?!<).*?>((?!<).*?)<\/h1>/g,str:getresult(a.result),find:"$1",successfn:function(b,c,d,e){console.log(b);b=b.split("{{separator}}");a.cid=1;a.str=a.result;a.name=b[0];c=gettag(getstr(/"og:description"\s*content="(.*?)"/,a.result).replace(/\s*\,\s*/g,",").split(","));if(d=getstr(/src="((?!\").*?)"\s*class="attachment-thumbnail"/,a.result))d="//"==d.substr(0,2)?"http:"+d:d,d="/"==d.substr(0,1)?pluginfo(a.plugin).apihost.split("//")[0]+"//"+pluginfo(a.plugin).apihost.split("//")[1].split("/")[0]+
"/"+d.substr(1):d;e=getstr(/totalthumbs\s*=\s*(\d+)/,a.result);myContent.imgcount=e||0;setlistpic({name:b[0],img:d,added:a.data,description:"<p>共"+(e||0)+"张图片</p>",comment:0,preview:1,tags:gettag(b[0])+c,sourceurl:pluginfo(a.plugin).apihost+"doujin/"+a.pid+"/"});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"post-thumbnails/?doujin="+a.pid,method:"GET",data:"",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,successfn:function(b,c){a.successfn&&
a.successfn({result:b,header:c})},showinfo:{text:"正在加载图片信息...",title:"图片",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){console.log(a);return{reg:/<div\s*class="\w+\d+"><a\s*href="(.*?)"><img\s*src="(.*?)".*?><\/a><\/div>/g,str:a.result,find:"$1",successfn:function(b,c,d,e){array_count(e)?(b=[],b=e.map(function(b){return getpageload(0==b.indexOf("/")?"http://"+pluginfo(a.plugin).apihost.replace("http://","").split("/")[0]+b:b,
a.plugin)}),console.log(b),a.download?chapterpredownload({source:b,download:a.download,plugin:a.plugin}):chapterviewer({source:b,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.download?chapterpredownload({error:"解析错误！",download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("图片信息获取失败！","ExView"));return!0}}}},commentflag:{loader:!1,
finder:!1},previewflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"post-thumbnails/?doujin="+a.pid,method:"GET",data:"",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,successfn:function(b,c){b?a.successfn&&a.successfn({result:b,header:c}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("预览信息获取失败！","ExView"))},showinfo:{text:"正在获取预览信息...",title:"预览页",name:getlistname(a.pid),
img:getlistimg(a.pid)}}},finder:function(a){console.log(a);return{reg:/<div\s*class="\w+\d+"><a\s*href="(.*?)"><img\s*src="(.*?)".*?><\/a><\/div>/g,str:a.result,find:"$1{{separator}}$2",successfn:function(b,c,d,e){b=(b||"").split("{{separator}}");c="//"==b[1].substr(0,2)?"http:"+b[1]:b[1];c="/"==c.substr(0,1)?pluginfo(a.plugin).apihost.split("//")[0]+"//"+pluginfo(a.plugin).apihost.split("//")[1].split("/")[0]+"/"+c.substr(1):c;b="/"==b[0].substr(0,1)?pluginfo(a.plugin).apihost.split("//")[0]+"//"+
pluginfo(a.plugin).apihost.split("//")[1].split("/")[0]+"/"+b[0].substring(1):b[0];addpreviewlist({page:a.page||1,pagecount:myContent.items.length,preview:{imgurl:c,pageurl:b}})}}}},pageimgflag:{parser:function(a){return{reg:/<img\s*src=\'(.*?)'/g,str:a.result,find:"$1",successfn:function(b){b&&(b=0==b.indexOf("/")?"http://"+pluginfo(a.plugin).apihost.replace("http://","").split("/")[0]+b:b);a.loadimgurl(b)}}}},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+(1<a.page?"page/"+
a.page+"/":""),method:"GET",data:"",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));b&&plugfns(a.plugin).pagedeal(b,a)}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"page/"+(a.page||1)+"/?s=color",method:"GET",data:"",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,
successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));b&&plugfns(a.plugin).pagedeal(b,a)}}}}},fns:{gettypebox:function(a,b,c,d,e){return'<td style="overflow: hidden;width: 33%;"><div onclick="'+(a||e?e?e:"ExView.workers.list.loader({tid:'"+a+"',keyword:'"+a+"',img:'"+c+"',title:'"+b+"',flag:'"+d+"',turnpage:1})":"ExView.workers.index.loader({turnpage:1,front:1,img:'"+
c+"',title:'"+b+"',flag:'"+d+"'})")+'" style="background-image:url('+c+');width:100%;height:100%;background-repeat:no-repeat;background-size:cover;text-align:center;background-size:100%100%;"></div><div style="font-size:16px;text-align:center;background-color: black;margin-top:-24px;opacity: 0.8;position: relative;color: white;">'+b+"</div></td>"},typelistext:{index:{title:"首页",imgurl:getbaiduimg("d3304434970a304eeae53a66d7c8a786c8175c12")},topfive:{title:"NTR",imgurl:getbaiduimg("e65387c379310a5540bf2322b04543a983261036")}},
typelist:{doujinshi:{title:"同人",imgurl:getbaiduimg("1b309b19ebc4b745b51c4ac0c8fc1e17888215c5")},manga:{title:"漫画",imgurl:getbaiduimg("61aa13c79f3df8dc6b797347ca11728b46102801")},loli:{title:"萝莉",imgurl:getbaiduimg("574621f790529822470fc615d0ca7bcb0b46d489")},game:{title:"游戏CG",imgurl:getbaiduimg("9be791014a90f6038e4160913e12b31bb251eddd")},girl:{title:"少女",imgurl:getbaiduimg("6a897ce736d12f2ec04351b648c2d56284356803")},"non-h":{title:"全年龄",
imgurl:getbaiduimg("8137b022720e0cf3e088b12d0d46f21fbf09aa4a")},color:{title:"全彩",imgurl:getbaiduimg("3448fc2a2834349b48489153ceea15ce37d3be7b")},kantai:{title:"舰娘",imgurl:getbaiduimg("20c8e3ef76094b36c7a8e53ba4cc7cd98c109d97")},TouHou:{title:"幻想乡",imgurl:getbaiduimg("574621f790529822462bc715d0ca7bcb0b46d4b5")},misc:{title:"杂项",imgurl:getbaiduimg("574621f7905298224624c715d0ca7bcb0b46d4b2")}},pagerule:/<div\s*class="thumb">(.*?)div>/g,pagefind:"$1",pagecountrule:/page\/(\d+)\/(\?s=[\%\w\d]+)*">[\w\d]+<\/a>\n<\/div>/g,
pagecountfind:"$1",pagedeal:function(a,b){b=b||{};var c=getstr(/\/doujin\/(\d+)\//,a),d=getstr(/title="((?!\").*?)"/,a),e=getstr(/src="((?!\").*?)"/,a);e&&(e="//"==e.substr(0,2)?"http:"+e:e);var f=getstr(/class="slider_text">((?!<).*?)</,a);if(b.multupdate)return b.multupdate(obj_contact(b,{pid:c,img:e,title:d,content:f})),!1;if(b.multhot)return b.multhot(obj_contact(b,{pid:c,img:e,title:d,content:f})),!1;if(b.multsearch)return b.multsearch(obj_contact(b,{pid:c,img:e,title:d,content:f})),!1;addcardlist({pid:c,
title:d,img:e,content:f,comment:0,preview:1,extrabutton:""})}}});
