ExView.Plugins({info:{name:"Gank\u56fe\u5e93",version:"2.2",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAE4SURBVDhPpVPRSsMwFA3oL/qkoF0V5kRQBEFxibA5ZtMqm6ijTFHEgSmy4QS1e/JDfBJ8dqCvu+bGBFwTR8UDB9rbcw43tzckixkhpnwaJAtlDj+5yLjAb1rmhhSlWWOWBcpTLR+HV+ZDl8FF1GrbNzDVJZzEguxWmRlj0y5BHqJXnjsSplDaayr6u5EldnGJhgmRDyOPhlCJr6FYbUCx0sgdgMQAwICDq1tVqMYdWKkdQbv7AGfdR5jfCaDZ6UFwIWCdt+Q7h1PRtwNayb0qLMsuVuvH8PL6pji7VQefhcq8ediG4cen0o8FmJDL/gDOe0+wEcUg0mfVwdz2vpx4qELXdAcnN3cmYERwECbkr/RxiP/+jQhcCpdgEq2V9ih/dwldtFbZIM9Ky3MPtNyN364z1uzrTMgXshUJGWL5mfUAAAAASUVORK5CYII=",
db:"gank",apihost:"http://gank.io/",pagetitle:["<br>","\u6536\u85cf","\u59b9\u5b50\u56fe","\u7c7b\u578b","\u4e0b\u8f7d"],lazyload:!0,download:!0,setting:!0,search:!1,nativeres:!1,gallerymode:!0,galleryopen:!0,vphotomode:!0,theme:"bluegray",cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){}})},flags:{indexflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"api/data/%E7%A6%8F%E5%88%A9/20/"+(a.page||1),timeout:120,successfn:function(b,
c){a.callback&&a.callback({img:pluginfo(a.plugin).icon,multpage:!0,result:b,header:c})}}},finder:function(a){try{var b=JSON.stringify(JSON.parse(getresult(a.result)).results)}catch(c){b=""}return{json:!0,str:b,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:!1},typeflag:{loader:!1,finder:function(a){addtypelist({title:"\u59b9\u5b50\u56fe",img:pluginfo(a.plugin).icon,content:"\u59b9\u5b50\u56fe"})}},listflag:{loader:!1,countloader:!1,
countfinder:!1},searchflag:{loader:function(a){a.multsearch?a.callback():ExView.fw.alert("\u6b64\u63d2\u4ef6\u4e0d\u652f\u6301\u641c\u7d22\u529f\u80fd\uff01")},finder:!1,countloader:!1,countfinder:!1},contentflag:{loader:!1,finder:function(a){return{successfn:function(b,c,e,d){console.log(typeof b);if(a.checkupdate)return{pid:a.pid,cid:"1",title:"\u51681\u8bdd"};d=[];d[0]=additemlist({id:0,newest:a.newest&&0==e,pid:a.pid,cid:"1",title:"\u51681\u8bdd",count:1,reverse:0});return d}}},infoloader:!1,
infofinder:!1},parseflag:{loader:function(a){return{successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){console.log(a);return{successfn:function(b,c,e,d){d=[litehextostring(a.pid)];array_count(d)?(b=d,console.log(b),a.download?chapterpredownload({source:b,download:a.download,plugin:a.plugin}):chapterviewer({source:b,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.download?chapterpredownload({error:"\u89e3\u6790\u9519\u8bef\uff01",
download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u56fe\u7247\u4fe1\u606f\u83b7\u53d6\u5931\u8d25\uff01","ExView"));return!0}}}},commentflag:{loader:!1,finder:!1},previewflag:{loader:!1,finder:!1,more:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"api/data/%E7%A6%8F%E5%88%A9/20/"+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){try{var b=
JSON.stringify(JSON.parse(getresult(a.result)).results)}catch(c){b=""}return{json:!0,str:b,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"api/data/%E7%A6%8F%E5%88%A9/20/"+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){try{var b=JSON.stringify(JSON.parse(getresult(a.result)).results)}catch(c){b=""}return{json:!0,
str:b,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}}}},fns:{pagedeal:function(a,b){b=b||{};var c=stringtolitehex(a.url),e=a.desc,d=a.url;if(c&&e){if(b.multupdate)return b.multupdate(obj_contact(b,{pid:c,img:d,title:e,content:""})),!1;if(b.multhot)return b.multhot(obj_contact(b,{pid:c,img:d,title:e,content:""})),!1;if(b.multsearch)return b.multsearch(obj_contact(b,{pid:c,img:d,title:e,content:""})),!1;addcardlist({pid:c,title:e,img:d,content:"",stitle:"",comment:0,
preview:0,extrabutton:""})}}}});
