ExView.Plugins({info:{name:"Gank图库",version:"2.2",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAE4SURBVDhPpVPRSsMwFA3oL/qkoF0V5kRQBEFxibA5ZtMqm6ijTFHEgSmy4QS1e/JDfBJ8dqCvu+bGBFwTR8UDB9rbcw43tzckixkhpnwaJAtlDj+5yLjAb1rmhhSlWWOWBcpTLR+HV+ZDl8FF1GrbNzDVJZzEguxWmRlj0y5BHqJXnjsSplDaayr6u5EldnGJhgmRDyOPhlCJr6FYbUCx0sgdgMQAwICDq1tVqMYdWKkdQbv7AGfdR5jfCaDZ6UFwIWCdt+Q7h1PRtwNayb0qLMsuVuvH8PL6pji7VQefhcq8ediG4cen0o8FmJDL/gDOe0+wEcUg0mfVwdz2vpx4qELXdAcnN3cmYERwECbkr/RxiP/+jQhcCpdgEq2V9ih/dwldtFbZIM9Ky3MPtNyN364z1uzrTMgXshUJGWL5mfUAAAAASUVORK5CYII=",
db:"gank",apihost:"http://gank.io/",pagetitle:["<br>","收藏","妹子图","类型","下载"],lazyload:!0,download:!0,setting:!0,search:!1,nativeres:!1,gallerymode:!0,galleryopen:!0,vphotomode:!0,theme:"bluegray",cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){}})},flags:{indexflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"api/data/%E7%A6%8F%E5%88%A9/20/"+(a.page||1),timeout:120,successfn:function(b,
c){a.callback&&a.callback({img:pluginfo(a.plugin).icon,multpage:!0,result:b,header:c})}}},finder:function(a){try{var b=JSON.stringify(JSON.parse(getresult(a.result)).results)}catch(c){b=""}return{json:!0,str:b,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:!1},typeflag:{loader:!1,finder:function(a){addtypelist({title:"妹子图",img:pluginfo(a.plugin).icon,content:"妹子图"})}},listflag:{loader:!1,countloader:!1,
countfinder:!1},searchflag:{loader:function(a){a.multsearch?a.callback():ExView.fw.alert("此插件不支持搜索功能！")},finder:!1,countloader:!1,countfinder:!1},contentflag:{loader:!1,finder:function(a){return{successfn:function(b,c,e,d){console.log(typeof b);if(a.checkupdate)return{pid:a.pid,cid:"1",title:"全1话"};d=[];d[0]=additemlist({id:0,newest:a.newest&&0==e,pid:a.pid,cid:"1",title:"全1话",count:1,reverse:0});return d}}},infoloader:!1,
infofinder:!1},parseflag:{loader:function(a){return{successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){console.log(a);return{successfn:function(b,c,e,d){d=[litehextostring(a.pid)];array_count(d)?(b=d,console.log(b),a.download?chapterpredownload({source:b,download:a.download,plugin:a.plugin}):chapterviewer({source:b,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.download?chapterpredownload({error:"解析错误！",
download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("图片信息获取失败！","ExView"));return!0}}}},commentflag:{loader:!1,finder:!1},previewflag:{loader:!1,finder:!1,more:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"api/data/%E7%A6%8F%E5%88%A9/20/"+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){try{var b=
JSON.stringify(JSON.parse(getresult(a.result)).results)}catch(c){b=""}return{json:!0,str:b,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"api/data/%E7%A6%8F%E5%88%A9/20/"+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){try{var b=JSON.stringify(JSON.parse(getresult(a.result)).results)}catch(c){b=""}return{json:!0,
str:b,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}}}},fns:{pagedeal:function(a,b){b=b||{};var c=stringtolitehex(a.url),e=a.desc,d=a.url;if(c&&e){if(b.multupdate)return b.multupdate(obj_contact(b,{pid:c,img:d,title:e,content:""})),!1;if(b.multhot)return b.multhot(obj_contact(b,{pid:c,img:d,title:e,content:""})),!1;if(b.multsearch)return b.multsearch(obj_contact(b,{pid:c,img:d,title:e,content:""})),!1;addcardlist({pid:c,title:e,img:d,content:"",stitle:"",comment:0,
preview:0,extrabutton:""})}}}});
