ExView.Plugins({info:{name:"汗汗漫画",version:"2.2",db:"hanhan",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAA3lBMVEUAAAD///8E2/8AnOkD5P8C4v8AzfwAwfIG5f8D0/8D0f8A4PsAyfcAxvIJ5v8C4f8B3/8D1v8K1P8L0f8Hzf8Hsv8UsP8Irf8A2fwA2/UAn/EAw+sAk98R0v8Dyv4AyPwAp/gA3vcAxfYAwvYAuvQAq/IAx+0Auu0AwOoAouoAmegAvOcAot4AldkAjtcK5f8K1/8ctP8UtP8dsv8Dqv8Dqf8A0PsArfoApvoAo/gAzfcAy/MA1/IA1PEApfEAvfAAw+8Aq+wAp+sAt+EAq+EAmOAAm9sAktIAjtAAic9cd21gAAAAAXRSTlOkkV2/lwAAAMVJREFUGNNNyNeSgkAQheHuHmAEA0hcxLS6pnV1zTln3/+FnEGr9L85dT4ASKpKJpNQ9MliWQfRt4CEAFVLpaM2QBjDv6KaAprtI4Rh0jJVIpNKFd5gDFaElkVIhF/VLQpYy/OEn4YE+gCOpxhkr2FvyMbzF4Oe7UngfC+hTmjoNpKOvHbAC4OIUDNstA2c1lrYuUKUTmmGU3A8r7xpnTs3aApwncLAC8o5lu/eAXaVouv2/WA0y/3muyCqlor+0A/GcwEAD6eYEVSGWeArAAAAAElFTkSuQmCC",
apihost:"http://www.hhaass.com/",imghost:"http://x8.1112223333.com/dm01/|http://x8.1112223333.com/dm02/|http://x8.1112223333.com/dm03/|http://x8.1112223333.com/dm04/|http://x8.1112223333.com/dm05/|http://x8.1112223333.com/dm06/|http://x8.1112223333.com/dm07/|http://x8.1112223333.com/dm08/|http://x8.1112223333.com/dm09/|http://x8.1112223333.com/dm10/|http://x8.1112223333.com/dm11/|http://x8.1112223333.com/dm12/|http://x8.1112223333.com/dm13/|http://x8.1112223333.com/dm14/|http://x8.1112223333.com/dm15/|http://x8.1112223333.com/dm16/",
pagetitle:["<br>","收藏","首页","类型","下载"],lazyload:!0,download:!0,setting:!0,settingextra:getui([{name:"imghost",title:"图片服务器<br>(一般在[{API服务器}/js/ds.js]可以找到)",type:"textarea"}]),theme:"brown",cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){ExView.workers.index.loader();ExView.workers.type.loader()}})},flags:{indexflag:{loader:function(a){a.front||
a.page||setnowlistname("首页","",pluginfo(a.plugin).icon);return{url:pluginfo(a.plugin).apihost+"dfcomiclist_"+(a.page||1)+".htm",method:"GET",timeout:120,successfn:function(b,c){ExView.workers.index.countfinder(obj_contact(a,{result:b,header:c}));a.successfn&&a.successfn({result:b,header:c})},errorfn:function(){a.page||setnowlistname("首页","",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("网络错误！","ExView")},canclefn:function(){a.page||
setnowlistname("首页","",pluginfo(a.plugin).icon)},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),name:"首页",title:a.title,img:a.img}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:a.result,find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));b?plugfns(a.plugin).pagedeal(b,a):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',2)},errorfn:function(){a.page||
setnowlistname("首页","",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("网络错误！","ExView")}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="0|首页|index";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},typeflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"comicsearch/",method:"GET",timeout:120,successfn:function(b,
c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){addtypelist({title:"首页",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"首页"});return{reg:/lists\/(\d+)"\s*title="((?!\").*?)"/g,str:a.result,find:"$1{{separator}}$2",successfn:function(b,c,f,e){if(array_count(e))return e.forEach(function(b){b=b.split("{{separator}}");addtypelist({tid:"lists/"+b[0],title:b[1],img:pluginfo(a.plugin).icon,group:{name:"fenlei",title:"分类"},
content:b[1]})}),!0;addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>加载失败，请刷新重试！</a></div>',2)},beforefn:function(){addtypelist({tid:"a",title:"今日最热",img:pluginfo(a.plugin).icon,listflag:"top",group:{name:"daohang",title:"导航"},content:"今日最热"});addtypelist({tid:"b",title:"最多人看",
img:pluginfo(a.plugin).icon,listflag:"top",group:{name:"daohang",title:"导航"},content:"最多人看"});addtypelist({tid:"c",title:"最受好评",img:pluginfo(a.plugin).icon,listflag:"top",group:{name:"daohang",title:"导航"},content:"最受好评"})},afterfn:function(){var b=["io9","io10"],c=["io11","io12","io13","io18"];ExView.modules.rulefind({reg:/href='\/lianwan\/(\d+)' class='nav_item_\w[-\w.+]*' title='((?!\').*?)'/g,str:a.result,find:"$1{{separator}}$2",
successfn:function(c,e,d){c&&(c=c.split("{{separator}}"),addtypelist({tid:"lianwan/"+c[0],title:c[1],img:pluginfo(a.plugin).apihost+"css/image/"+b[d]+".png",listflag:"lianwan",group:{name:"biaoqian",title:"标签"},content:c[1]}))}});ExView.modules.rulefind({reg:/href='\/(duzhequn|lists)\/(\d+)(\/|)' class='nav_item_\w[-\w.+]*' title='((?!\').*?)'/g,str:a.result,find:"$1{{separator}}$2{{separator}}$3{{separator}}$4",successfn:function(b,e,d){b&&(b=b.split("{{separator}}"),addtypelist({tid:b[0]+
"/"+b[1],title:b[3],img:pluginfo(a.plugin).apihost+"css/image/"+c[d]+".png",listflag:"duzhequn",group:{name:"duzhequn",title:"读者群"},content:b[3]}))}})}}}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+("top"==a.flag?"top/"+a.keyword+"-"+(a.page||1)+".htm":a.keyword+"/"+(a.page||1)+"/"),method:"GET",timeout:120,successfn:function(b,c){b?(ExView.workers.list.countfinder(obj_contact(a,{result:b,header:c})),a.successfn&&a.successfn({result:b,header:c})):(ExView.fw.hidePreloader(),
mySession.isloading=0,ExView.fw.alert("【"+a.title+"】<br>获取失败！","ExView"))},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),name:"【"+a.title+"】",title:a.title,img:a.img}}},finder:function(a){return{reg:"top"!=a.flag?plugfns(a.plugin).pagerule:/<li\s*class='clearfix section1'>(.*?)<\/a>/g,str:a.result,find:plugfns(a.plugin).pagefind,successfn:function(b){b?plugfns(a.plugin).pagedeal(b):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',
1)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="0|"+a.keyword+"|list";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},searchflag:{loader:function(a){return 1<parseInt(a.page)?(a.multsearch&&a.multsearch(),!1):{url:pluginfo(a.plugin).apihost+"comicsearch/s.aspx?s="+encodeURIComponent(a.keyword),method:"GET",timeout:120,successfn:function(b,c){b?(a.multsearch||(ExView.workers.search.countfinder(obj_contact(a,
{result:b,header:c})),setnowlistname("搜索【"+a.keyword+"】")),a.successfn&&a.successfn({result:b,header:c})):a.multsearch?a.multsearch():(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+a.keyword+"】<br>获取搜索结果失败！","ExView"))},showinfo:{text:"正在搜索..."+(1<a.page?"<br>第"+a.page+"页":""),name:"【"+a.keyword+"】",title:"搜索"}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,
str:a.result,find:plugfns(a.plugin).pagefind,successfn:function(b,c,f){console.log(b);b?plugfns(a.plugin).pagedeal(b,a):a.multsearch?a.multsearch():addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(b){mySession.nowlistpages="-1|"+a.keyword+"|search";mySession.nowlistpage=1;console.log(mySession.nowlistpages)}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"comic/"+a.pid+"/",method:"GET",timeout:120,successfn:function(b,c){b?a.successfn&&a.successfn({result:b,header:c}):a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},showinfo:{text:"正在加载内容页...",title:"内容页",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){return{reg:/vols\/([\_\d]+)\/'>((?!<).*?)<\/a>/g,str:a.result,find:{pid:a.pid,cid:"$1",
title:"$2"},successfn:function(b,c,f,e){console.log(typeof b);if(array_count(b)){if(a.checkupdate)return{pid:b.pid,cid:b.cid,title:b.title};additemlist({id:c.length-f-1,newest:a.newest&&0==f,pid:b.pid,cid:b.cid,title:b.title,count:c.length,reverse:1})}else a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},afterfn:function(){a.checkupdate||ExView.workers.content.infofinder(a)}}},infoloader:function(a){return!1},
infofinder:function(a){console.log(a);return{reg:/<div\s*class="pic">((?:.|[\r\n])*?)<\/div>/g,str:a.result,find:"$1",successfn:function(b,c,f,e){b=b.split("{{separator}}");console.log(JSON.stringify(b));try{var d=getstr(/<img\s*src='((?!\').*?)'/,b[0]),l=getstr(/<h3>((?!<).*?)<\/h3>/,b[0]),p=getstr(/<p>状态：((?!<).*?)(\d+)?<\/p>/,b[0]),h=getstr(/<p>更新日期：((?!<).*?)<\/p>/,b[0]),k=getstr(/<p>作者：((?!<).*?)<\/p>/,b[0]),g=getstr(/'>((?!<).*?)<\/a><\/p>/,
b[0]),q=getstr(/<p>人气：(\d+)<\/li><\/p>/,b[0]),m=getstr(/<div\s*class="ilist">((?:.|[\r\n])*?)<\/div>/,a.result);m&&(m=m.replace("<h3>漫画介绍：</h3>","").replace(/<p>/g,"").replace(/<\/p>/g,""));var n=gettag(p)+gettag(g)+gettag(k)}catch(r){}setlistpic({name:l,img:d.replace("http://imgs.hhxiee.net/","http://pic.huo80.com/"),added:a.data,description:"<p>【作者】"+k+"<br>【类型】"+g+"<br>【"+p+"】"+h+"<br>【人气】"+
q+"<br>【简介】"+m+"</p>",sourceurl:pluginfo(a.plugin).apihost+"comic/"+a.pid+"/",comment:1,preview:0,tags:gettag(l)+n+gettag(k)});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"vols/"+a.cid+"/",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"正在加载图片信息...",title:"图片",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){return{reg:/var\s*sFiles="(\w[-\w.+]*)";var\s*sPath="(\d+)";/g,
str:a.result,find:"$1{{separator}}$2",successfn:function(b){if(b){b=b.split("{{separator}}");try{var c=b[0],f=c.substring(c.length-1),e="abcdefghijklmnopqrstuvwxyz".indexOf(f)+1,d=c.substring(c.length-e-12,c.length-e-1),c=c.substring(0,c.length-e-12),l=d.substring(0,d.length-1),p=d.substring(d.length-1);for(i=0;i<l.length;i++)c=c.replace(new RegExp(l.substring(i,i+1),"gi"),i);var h=c.split(p),c="";for(i=0;i<h.length;i++)c+=String.fromCharCode(h[i]);var k=c.split("|"),g;var q=b[1],m=pluginfo(a.plugin).imghost||
"";if(m){arrDS=m.split("|");b="";for(i=0;i<arrDS.length;i++)if(q==i+1){b=arrDS[i];break}g=b}else ExView.fw.alert("请去插件设置里恢复默认，然后重试！"),g=void 0;var n=[];for(i=0;i<k.length;i++)n.push(g+k[i]);console.log(n)}catch(r){console.log(r)}console.log(n);a.download?chapterpredownload({source:n,download:a.download,plugin:a.plugin}):chapterviewer({source:n,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,
zoom:!0,title:a.title})}else a.download?chapterpredownload({error:"解析错误！",download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("图片信息获取失败！","ExView"));return!0}}}},commentflag:{loader:function(a){return{url:1==parseInt(a.page||1)?"http://changyan.sohu.com/api/2/topic/load?client_id=cyqVh5aXL&topic_url="+encodeURIComponent(pluginfo(a.plugin).apihost+"comic/"+a.pid+"/")+"&page_size=30&hot_size=0&topic_source_id="+
a.pid.substring(2):"http://changyan.sohu.com/api/2/topic/comments?client_id=cyqVh5aXL&page_size=30&topic_id="+a.sid+"&page_no="+(a.page+1),method:"GET",timeout:120,successfn:function(b,c){if(b){var f={};1==parseInt(a.page||1)&&(f=JSON.parse(b));a.callback&&a.callback({result:b,header:c,sid:f.topic_id||a.sid,commentbrowser:{url:pluginfo(a.plugin).apihost+"comic/"+a.pid+"/",title:"评论 - "+pluginfo(a.plugin).name+'<br><span style="font-size:16px">'+(myContent.name||"")+"</span>",browser:!1,
flag:""}})}else a.callback&&a.callback()}}},finder:function(a){console.log(a);return{json:!0,str:a.result,successfn:function(b,c,f,e){if(array_count(b)){c=b.comments;b=b.total_page_no;for(var d in c)a.callback&&a.callback({page:a.page||1,pagecount:b,comment:{text:c[d].content,name:c[d].passport.nickname,avatar:c[d].passport.img_url,type:"received",label:(new Date(parseInt(c[d].create_time))).toLocaleString().replace(/:\d{1,2}$/," "),day:"",time:"",reverse:1,extra:""}})}}}},send:!1},previewflag:{loader:!1,
finder:!1,more:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"dfcomiclist_"+(a.page||1)+".htm",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:a.result,find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));b&&plugfns(a.plugin).pagedeal(b,a)}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"top/a-"+(a.page||1)+".htm",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{reg:/<li\s*class='clearfix section1'>(.*?)<\/a>/g,str:a.result,find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));b&&plugfns(a.plugin).pagedeal(b,a)}}}}},fns:{pagerule:/<li\s*class='clearfix section1'>(.*?)<\/li>/g,pagefind:"$1",pagedeal:function(a,b){b=b||{};a=a.split("{{separator}}");try{var c=getstr(/comic\/(\d+)'/,
a[0]),f=getstr(/src='((?!\').*?)'/,a[0]).replace("http://imgs.hhxiee.net/","http://pic.huo80.com/"),e=getstr(/>((?!<).*?)<\/h3><p>/,a[0]),d=getstr(/<\/h3><p>((?!<).*?)<\/p>/,a[0]),l=getstr(/<\/p><p>((?!<).*?)<\/p>/,a[0]),p=getstr(/'color_red'>((?!<).*?)<\/span>/,a[0]),h=getstr(/class='h'>\[((?!<).*?)\]<\/span>/,a[0]),k=h?"【"+d+"】"+e:"",g=h?"【"+l+"】更新至"+h+"话":d}catch(q){}if(b.multupdate)return b.multupdate(obj_contact(b,{pid:c,img:f,title:e,content:g})),!1;if(b.multhot)return b.multhot(obj_contact(b,
{pid:c,img:f,title:e,content:g})),!1;if(b.multsearch)return b.multsearch(obj_contact(b,{pid:c,img:f,title:e,content:g})),!1;addcardlist({pid:c,title:e,name:k,img:f,content:g,stitle:p,comment:1,preview:0,extrabutton:""})}}});
