ExView.Plugins({info:{name:"Hitomi漫画",version:"2.2",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAwFBMVEX///83P0sjLDo9RFApMT/z9PQuNkM4QEwrM0EaIzE0PEgyOkYlLjzu7/C1uLzYdm7TdG1JUFxFTFf/+Pfp6ux8gop5foYsOkcSIC/r7O25vsLahn5wdn5qcnzmgXdeZG5aYWtSWWREO0UIFCT4+fn19vb24+L52teyvsPIv8GprLHBk5GEiZDMkI3hjIV8d3/Xgnxpb3jkfnXdfXXVenPHcmylZmWNW1x5U1hASldkS1FgP0VKOEAdKTcWJzYUHSw5YA+EAAAArklEQVQY01XP1xKCMBCF4Q3GECBIR6QXe++9vP9baQAH3ctvZufMD6aICCEIiQrGRBRNUCgxDINidok2GaMKIKGlgi0L3soC38OIwwBU+ZEftNHkXkEbevLzFOvrYHvuVmALxU3b63p8rKE9d52Fpmu7aw38rGA5yxlqAIbWmK9UL04YTQE60hds9ipCDs2sILm/oP5DvwQHwOegYJKmGcGslSTGJ47nU1rmU8rz3/7sDYHFVcCHAAAAAElFTkSuQmCC",
db:"hitomi",apihost:"https://hitomi.la/",pagetitle:["<br>","收藏","最新","类型","下载"],download:!0,lazyload:!0,setting:!0,settingextra:getui([{name:"nativeres",title:"使用本地请求",type:"checkbox"}]),nativeres:!1,nosearch:!0,theme:"bluegray",requestcookie:"",cdn:""},set:function(a){},unset:function(a){},init:function(a){ExView.workers.fav.listloader({callback:function(){}})},flags:{indexflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"index-all-"+(a.page||1)+".html",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,successfn:function(b,c){a.callback&&a.callback({multpage:!0,result:b,header:c})}}},finder:function(a){return{query:!0,selector:".gallery-content>div",str:a.result,successfn:function(b){b?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:function(a){return{reg:/\,\s*(\d+)\)\;/g,find:"$1",str:a.result,successfn:function(b){a.callback&&a.callback({pagecount:b||"-1"})}}}},typeflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost,
method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{successfn:function(b){a.callback({group:{name:"daohang",title:"导航"},title:"最新",img:pluginfo(a.plugin).icon,content:"最新"});a.callback({tid:"popular",listflag:"popular",group:{name:"daohang",title:"导航"},title:"热门",img:pluginfo(a.plugin).icon,content:"热门"});b=getquery(a.result,"#lang-list>li");for(var c=0;c<b.length;c++){var d=getstr(/index\-(\w+)\-1\.html/,
$$(b[c]).find("a").attr("href")),e=$$(b[c]).text();a.callback({tid:d,group:{name:"lang",title:"语言"},title:e,img:pluginfo(a.plugin).icon,content:e})}}}}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+(a.flag?a.flag+"-all-"+(a.page||1)+".html":"index-"+a.tid+"-"+(a.page||1)+".html"),method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,successfn:function(b,c){a.callback&&a.callback({multpage:!0,result:b,header:c})}}},finder:function(a){return{query:!0,selector:".gallery-content>div",
str:a.result,successfn:function(b){b?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:function(a){return{reg:/\,\s*(\d+)\)\;/g,find:"$1",str:a.result,successfn:function(b){a.callback&&a.callback({pagecount:b||"-1"})}}}},searchflag:{loader:!1,finder:!1,countloader:!1,countfinder:!1},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"galleries/"+a.pid+".html",method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,successfn:function(b,c){a.callback&&
a.callback({result:b,header:c})}}},finder:function(a){return{successfn:function(b){if(b){b=a.pid;if(a.checkupdate)return{pid:b,cid:1,title:"全1话"};for(var c=[],d=0;1>d;d++)c[d]=a.callback({id:d,newest:a.newest&&0==d,pid:b,cid:d+1,title:"全"+(d+1)+"话",count:1,reverse:0});console.log(c);return c}a.checkupdate||a.callback()}}},infoloader:!1,infofinder:function(a){console.log(a);return{query:!0,selector:".gallery",str:a.result,successfn:function(b,c,d,e){c=$$(b).find("h1").text();d=
$$(b).find("h2").text();e=getquery(a.result,".cover-column");e=$$(e).find("img").attr("src");var g=$$(b).find(".gallery-info").find("tr");b={};var k="";b.author=d;for(d=0;d<g.length;d++){var f=$$(g[d]).children("td").eq(0).text();if("Tags"!=f){var l=$$(g[d]).children("td").eq(1).text();b[f]=l}else $$(g[d]).children("td").eq(1).find("li").each(function(){k+=gettag($$(this).text())})}d="";for(f in b)d+="【"+f+"】"+b[f]+"<br>";e="//"==e.substr(0,2)?"https:"+e:e;f=getquery(a.result,".gallery-preview script");
f=$$(f).text();if(-1!=f.indexOf("thumbnails")){eval(f);var h=(h||[]).map(function(a){a=a.replace("g.hitomi.la","a.hitomi.la");return"//"==a.substr(0,2)?"https:"+a:a});myContent.previewdata={type:"img",data:h}}else-1!=f.indexOf("jwplayer")&&(h=getstr(/file\:\s*"((?!\").*?)"\s*\,/,a.result),h=JSON.parse('["'+h+'"]')[0],h="//"==h.substr(0,2)?"https:"+h:h,f=getstr(/url_from_url\("((?!\").*?)"\)\s*\,/,a.result),f=JSON.parse('["'+f+'"]')[0],f="//"==f.substr(0,2)?"https:"+f:f,f=f.replace("g.hitomi.la","a.hitomi.la"),
myContent.previewdata={type:"video",data:{videofile:h,imgfile:f}});a.callback({name:c,img:e,added:a.data,description:d,comment:0,preview:0,tags:gettag(c)+k});return!0}}}},parseflag:{loader:function(a){return"video"==myContent.previewdata.type?!1:{url:pluginfo(a.plugin).apihost+"reader/"+a.pid+".html",method:"GET",data:"",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,successfn:function(b,c){a.callback&&a.callback({result:b,header:c})}}},finder:function(a){console.log(a);return"video"==myContent.previewdata.type?
{successfn:function(b,c,d,e){a.download||(b=[],b.push(myContent.previewdata.data.videofile),c=myContent.previewdata.data.imgfile,ExView.fw.hidePreloader(),d=(d=/\/flv\/|\.flv/.test(b[0]))?"flv":"mp4",a.callback({poster:c,url:pluginfo(a.plugin).apihost+"galleries/"+a.pid+".html",source:b,type:"video",videoType:d,title:a.title}))}}:{query:!0,selector:".img-url",str:a.result,successfn:function(b,c,d,e){console.log([b,c,d,e]);if(array_count(c)){b=[];for(d=0;d<c.length;d++)e=$$(c[d]).text(),e=e.replace("g.hitomi.la",
"a.hitomi.la"),b.push("//"==e.substr(0,2)?"https:"+e:e);console.log(b);a.download?a.callback({source:b,download:a.download,plugin:a.plugin}):a.callback({source:b,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})}else a.callback();return!0}}}},commentflag:{loader:!1,finder:!1,send:!1},previewflag:{loader:!1,finder:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"index-all-"+(a.page||1)+".html",timeout:120,
nativerequest:pluginfo(a.plugin).nativeres,successfn:function(b,c){a.callback&&a.callback({result:b,header:c})}}},finder:function(a){return{query:!0,selector:".gallery-content>div",str:a.result,successfn:function(b){console.log(JSON.stringify(b));b&&plugfns(a.plugin).pagedeal(b,a)}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"popular-all-"+(a.page||1)+".html",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,successfn:function(b,c){a.callback&&a.callback({result:b,header:c})}}},
finder:function(a){return{query:!0,selector:".gallery-content>div",str:a.result,successfn:function(b){console.log(JSON.stringify(b));b&&plugfns(a.plugin).pagedeal(b,a)}}}}},fns:{pagedeal:function(a,b){b=b||{};var c=$$(a).find("a").attr("href"),c=getstr(/\/(\d+).html/g,c),d=$$(a).find("h1").text(),e=$$(a).find("img").attr("src"),e="//"==e.substr(0,2)?"https:"+e:e,g=$$(a).find(".date").text(),g=$$(a).find(".artist-list").text()+" "+g,k=[];$$(a).find(".dj-desc tr").each(function(){$$(this).find(".relatedtags").length?
$$(this).find(".relatedtags a").each(function(){k.push(getboxitem($$(this).text()))}):k.push(getboxitem($$(this).find("td").eq(1).text()))});var f=k.join("");if(b.multupdate)return b.multupdate(obj_contact(b,{pid:c,img:e,title:d,content:g})),!1;if(b.multhot)return b.multhot(obj_contact(b,{pid:c,img:e,title:d,content:g})),!1;if(b.multsearch)return b.multsearch(obj_contact(b,{pid:c,img:e,title:d,content:g})),!1;b.callback&&b.callback({pid:c,title:d,img:e,content:f,stitle:g,comment:0,preview:0,extrabutton:""})}}});
