ExView.Plugins({info:{name:"工口视图",version:"2.2",author:"Gentle",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAilBMVEUWoIX///8doYj9/f3r8vCe18yQ0sVJrZnW7unM6+QpqI8jpozp7+7S7efi6OfL4d2119Cuzceay8FitKQ2rZYno4sooorf6ecboof2/Pv5+fnF2tbB1dGZx751xraSvrVSuaVgtaRDs51erZ1AspxHp5Qnp47m9fLh8u/Y7+vF5+DR3NqAy7x9ybqXMXIsAAAAp0lEQVQY02WP2RaCMAxEY1rtxk7ZQWRz9/9/z7YgL96nZM7JZAYOBuI1cdwGtZ2t4HUsR8yXPiBOKFIEB04vYgSaws4UHIAkOJ82NPY1UAYXnz+qG+dihCWAMAOUUvO3lLKEvIXIOV798+ob/wn2pFRK849Sypw0zlQIv7oL8ZyBefbteNzQ2BETbICd1HPRh1/0tFjL0YRliBlLqFnW+jSMopASO38BiZgJ0gco5P0AAAAASUVORK5CYII=",
db:"hviewer",apihost:"https://raw.githubusercontent.com/H-Viewer-Sites/",pagetitle:["<br>","收藏","首页","类型","下载"],download:!0,lazyload:!0,setting:!0,typelistmode:!0,requestcookie:"PHPSESSID=11511561_2185579347e4defc34e480adde6ee1fe;",webpage:{url:"about:blank",title:"登陆",browser:!1,flag:"",callbackname:"webpagefork"},nativeres:!0,theme:"teal",cdn:""},set:function(a){},unset:function(a){},init:function(a){a=a||{};if(pluginfo(a.plugin).sourceUrl)if(pluginfo(a.plugin).sourceTxt){var b=
pluginfo(a.plugin).sourceTxt,c=plugfns(a.plugin);c.config=JSON.parse(b);c.referer=encodeURI(c.parseUrl(c.config.indexUrl,a));setnowlistname(c.config.title,"",pluginfo(a.plugin).icon||"img/logo.png");ExView.workers.fav.listloader({callback:function(){}})}else plugfns(a.plugin).getSource(pluginfo(a.plugin).sourceUrl,function(a){ExView.workers.fav.listloader({callback:function(){}});ExView.fw.hidePreloader()},function(a){ExView.workers.fav.listloader({callback:function(){}});ExView.fw.hidePreloader()},
a);else ExView.workers.fav.listloader({callback:function(){}})},flags:{indexflag:{loader:function(a){if(!plugfns(a.plugin).config)return addcardlist('<div align="center" class="list-block threat"><img src="img/logo.png"/><br>请先在分类哪里选择一个来源！</div>',2),{successfn:function(){}};1==(a.page||1)&&(plugfns(a.plugin).minid="");var b=plugfns(a.plugin).parseUrl(plugfns(a.plugin).config.indexUrl,a),c=plugfns(a.plugin).parseHeader(a);return{url:b,
method:"GET",timeout:120,header:c,autoencode:!1,webview:plugfns(a.plugin).getFlag(b,"webviewlist",a),webviewjs:plugfns(a.plugin).getFlag(b,"webviewjslist",a),encoding:plugfns(a.plugin).getFlag(b,"gbklist",a)?"gbk":void 0,cookie:plugfns(a.plugin).getFlag(b,"webreqlist",a)?void 0:pluginfo(a.plugin).requestcookie,ua:plugfns(a.plugin).getFlag(b,"webreqlist",a)?void 0:"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36",nativerequest:!plugfns(a.plugin).getFlag(b,
"webreqlist",a),successfn:function(b,c){a.callback({img:pluginfo(a.plugin).icon,multpage:!0,result:b,header:c})}}},finder:function(a){return{successfn:function(){var b=plugfns(a.plugin).config.indexRule;plugfns(a.plugin).parseDetail(b,a)}}},countloader:!1,countfinder:function(a){return{successfn:function(b){a.callback({pagecount:/{page:(.*?)}/.test(plugfns(a.plugin).config.indexUrl)?0:-1})}}}},typeflag:{loader:!1,finder:function(a){if(plugfns(a.plugin).config){var b=plugfns(a.plugin).config.categories;
b||a.callback({tid:"",listflag:plugfns(a.plugin).config.indexUrl,title:plugfns(a.plugin).config.title+" ♂ 首页",img:pluginfo(a.plugin).icon,group:{name:"site",title:"分类"},content:plugfns(a.plugin).config.title+" ♂ 首页"});(b||[]).forEach(function(b){a.callback({tid:"",listflag:b.url,title:plugfns(a.plugin).config.title+" ♂ "+b.title,img:pluginfo(a.plugin).icon,group:{name:"site",title:"分类"},content:plugfns(a.plugin).config.title+" ♂ "+b.title})})}else a.callback({tid:"",
listfn:"ExView.fw.alert('请选择一个站点!')",title:"首页",img:pluginfo(a.plugin).icon,group:{name:"site",title:"分类"},content:"首页"});b=function(b){ExView.modules.curl({url:b,method:"GET",successfn:function(b){JSON.parse(b).forEach(function(b){var c=b.title,d="t"+stringtolitehex(c);b.sites.forEach(function(b){a.callback({tid:stringtolitehex(b.json),title:b.title,img:b.icon,group:{name:d,title:c},content:b.title+"<br>"+b.lastUpdate})})})},showinfo:""})};
b(pluginfo(a.plugin).apihost+"Index/master/sites.json");b(pluginfo(a.plugin).apihost+"zhihaofans/master/sites.json")}},listflag:{loader:function(a){var b=function(b){1==(a.page||1)&&(plugfns(a.plugin).minid="");b=plugfns(a.plugin).parseUrl(b,a);var d=plugfns(a.plugin).parseHeader(a);ExView.modules.curl({url:b,method:"GET",timeout:120,header:d,autoencode:!1,webview:plugfns(a.plugin).getFlag(b,"webviewlist",a),webviewjs:plugfns(a.plugin).getFlag(b,"webviewjslist",a),encoding:plugfns(a.plugin).getFlag(b,
"gbklist",a)?"gbk":void 0,cookie:plugfns(a.plugin).getFlag(b,"webreqlist",a)?void 0:pluginfo(a.plugin).requestcookie,ua:plugfns(a.plugin).getFlag(b,"webreqlist",a)?void 0:"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36",nativerequest:!plugfns(a.plugin).getFlag(b,"webreqlist",a),successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})},errorfn:function(b){a.callback()},showinfo:{text:"正在加载...",title:"类型",
name:a.title,img:a.img}})};return{successfn:function(){console.log(a.result);a.tid?plugfns(a.plugin).getSource(litehextostring(a.tid),function(c){pluginfo(a.plugin,!0,"sourceUrl",litehextostring(a.tid));pluginfo(a.plugin,!0,"sourceTxt",c);b(plugfns(a.plugin).config.indexUrl);-1!=plugfns(a.plugin).config.flag.indexOf("loginRequired")&&shownotice("此站点需要登录使用！",3E3)},function(b){a.callback()},a):b(a.flag)}}},finder:function(a){return{successfn:function(){var b=
plugfns(a.plugin).config.indexRule;plugfns(a.plugin).parseDetail(b,a)}}},countloader:!1,countfinder:function(a){return{successfn:function(b){a.callback({pagecount:/{page:(.*?)}/.test(plugfns(a.plugin).config.indexUrl)?0:-1})}}}},searchflag:{loader:function(a){1==(a.page||1)&&(plugfns(a.plugin).minid="");var b=plugfns(a.plugin).parseUrl(plugfns(a.plugin).config.searchUrl,a),c=plugfns(a.plugin).parseHeader(a);return{url:b,method:"GET",timeout:120,header:c,webview:plugfns(a.plugin).getFlag(b,"webviewlist",
a),webviewjs:plugfns(a.plugin).getFlag(b,"webviewjslist",a),encoding:plugfns(a.plugin).getFlag(b,"gbklist",a)?"gbk":void 0,cookie:plugfns(a.plugin).getFlag(b,"webreqlist",a)?void 0:pluginfo(a.plugin).requestcookie,ua:plugfns(a.plugin).getFlag(b,"webreqlist",a)?void 0:"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36",nativerequest:!plugfns(a.plugin).getFlag(b,"webreqlist",a),successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})}}},
finder:function(a){return{successfn:function(b){b=plugfns(a.plugin).config.searchRule||plugfns(a.plugin).config.indexRule;plugfns(a.plugin).parseDetail(b,a)}}},countloader:!1,countfinder:function(a){return{successfn:function(b){a.callback({pagecount:/{page:(.*?)}/.test(plugfns(a.plugin).config.searchUrl)?0:-1})}}}},contentflag:{loader:function(a){var b=litehextostring(a.pid.split("_")[1]);if(!plugfns(a.plugin).config){var c=pluginfo(a.plugin).sourceTxt;if(!c)return{successfn:function(){ExView.fw.hidePreloader();
ExView.fw.alert("默认配置缺失，请配置好插件！")}};var d=plugfns(a.plugin);d.config=JSON.parse(c);d.referer=d.parseUrl(d.config.indexUrl,a);setnowlistname(d.config.title,"",pluginfo(a.plugin).icon||"img/logo.png")}if(b!=pluginfo(a.plugin).sourceUrl)return{successfn:function(){ExView.fw.hidePreloader();ExView.fw.confirm("此配置与当前选择的配置不一致，是否切换配置?",
function(){plugfns(a.plugin).getSource(b,function(c){pluginfo(a.plugin,!0,"sourceUrl",b);pluginfo(a.plugin,!0,"sourceTxt",c);ExView.fw.hidePreloader();addcardlist('<div align="center" class="list-block threat"><img src="img/logo.png"/><br>加载中...</div>',2);ExView.fw.alert("切换配置成功!");mySession.nowpluginfo.pagetitleindex=plugfns(a.plugin).config.title;setnowlistname(plugfns(a.plugin).config.title,"",pluginfo(a.plugin).icon||"img/logo.png")},function(a){ExView.fw.alert("切换配置失败！");
ExView.fw.hidePreloader()},a)})}};c=plugfns(a.plugin).config.galleryUrl||plugfns(a.plugin).config.indexUrl;if(plugfns(a.plugin).config.indexRule.pictureRule&&!(plugfns(a.plugin).config.galleryRule||{}).pictureRule&&0!=c.indexOf("http://")&&0!=c.indexOf("https://"))return!1;var e=plugfns(a.plugin).parseUrl(c,a),c=plugfns(a.plugin).parseHeader(a);return{url:e,method:"GET",timeout:120,header:c,webview:plugfns(a.plugin).getFlag(e,"webviewlist",a),webviewjs:plugfns(a.plugin).getFlag(e,"webviewjslist",
a),encoding:plugfns(a.plugin).getFlag(e,"gbklist",a)?"gbk":void 0,cookie:plugfns(a.plugin).getFlag(e,"webreqlist",a)?void 0:pluginfo(a.plugin).requestcookie,ua:plugfns(a.plugin).getFlag(e,"webreqlist",a)?void 0:"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36",nativerequest:!plugfns(a.plugin).getFlag(e,"webreqlist",a),successfn:function(b,c){a.callback({url:e,result:b,header:c})}}},finder:function(a){myContent.result=a.result;return{successfn:function(b,
c,d,e){if(array_count(b)){if(a.checkupdate)return a.callback({pid:a.pid,cid:0,title:"全一话"}),!0;e=[];d=0;e[d]=a.callback({id:d,newest:a.newest&&0==d,pid:a.pid,cid:d,title:"全一话",count:1,reverse:0});return e}a.callback()}}},infoloader:!1,infofinder:function(a){return{successfn:function(b,c,d,e){var f=plugfns(a.plugin).config.galleryRule;if(!f)return!1;var h=plugfns(a.plugin).parserSelector(f.cover,a.result),k=plugfns(a.plugin).parserSelector(f.title,a.result),g=plugfns(a.plugin).parserSelector(f.datetime,
a.result);b=plugfns(a.plugin).parserSelector(f.category,a.result);d=plugfns(a.plugin).parserSelector(f.description,a.result);e=plugfns(a.plugin).parserSelector(f.uploader,a.result);c=plugfns(a.plugin).parserSelector(f.tags,a.result);if(f=plugfns(a.plugin).parserRootSelector(f.tagRule,"title",a.result))c=c||[],"object"==typeof f?c=c.concat(f):c.push(f);f=0;try{plugfns(a.plugin).config.galleryRule.commentRule&&(f=1)}catch(m){}var n=0;try{(plugfns(a.plugin).config.galleryRule.videoRule||plugfns(a.plugin).config.galleryRule.pictureRule).thumbnail&&
(n=1)}catch(m){}h=h[0]||"";k=k[0]||getlistname(a.pid,a.plugin);g=g[0];e=e[0];c=c.join(",");b=b[0];d=d[0];a.callback({name:k,img:h,added:a.data,description:"<p>"+(e?"【作者】"+e+"<br>":"")+(c?"【类型】"+c+"<br>":"")+(g?"【更新】"+g+"<br>":"")+(b?"【其他】"+b+"<br>":"")+(d?"【简介】"+d:"")+"</p>",comment:f,preview:n,tags:gettag(k)+gettag(e)+gettag((c||"").split(",")),sourceurl:a.url});return!0}}}},parseflag:{loader:function(a){if(!a.download)return!1;
var b=plugfns(a.plugin).config.galleryUrl||plugfns(a.plugin).config.indexUrl;if(plugfns(a.plugin).config.indexRule.pictureRule&&!(plugfns(a.plugin).config.galleryRule||{}).pictureRule&&0!=b.indexOf("http://")&&0!=b.indexOf("https://"))return!1;var c=plugfns(a.plugin).parseUrl(b,a),b=plugfns(a.plugin).parseHeader(a);return{url:c,method:"GET",timeout:120,header:b,webview:plugfns(a.plugin).getFlag(c,"webviewlist",a),webviewjs:plugfns(a.plugin).getFlag(c,"webviewjslist",a),encoding:plugfns(a.plugin).getFlag(c,
"gbklist",a)?"gbk":void 0,cookie:plugfns(a.plugin).getFlag(c,"webreqlist",a)?void 0:pluginfo(a.plugin).requestcookie,ua:plugfns(a.plugin).getFlag(c,"webreqlist",a)?void 0:"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36",nativerequest:!plugfns(a.plugin).getFlag(c,"webreqlist",a),successfn:function(b,e){a.callback({url:c,result:b,header:e})}}},finder:function(a){return{successfn:function(b,c,d,e){if((plugfns(a.plugin).config.galleryRule||
{}).js){if(a.download)return a.callback(),!0;c=plugfns(a.plugin).config.galleryUrl||plugfns(a.plugin).config.indexUrl;c=plugfns(a.plugin).parseUrl(c,a);openweburl(c,myContent.name);ExView.fw.hidePreloader();return!0}var f=(plugfns(a.plugin).config.galleryRule||plugfns(a.plugin).config.indexRule).videoRule;if(f){if(f.item.selector&&!f.item.path){"this"==f.content.selector&&(f.content.selector=f.item.selector);var h=plugfns(a.plugin).parserSelector(f.content,myContent.result)}f.item.path&&!f.item.selector&&
(c=plugfns(a.plugin).parserJSON(f,myContent.result),h=[],(c||[]).forEach(function(b){var c=plugfns(a.plugin).evalStr;b=c(f.content.path,b,f.item.path);"object"==typeof b?h=h.concat(b):h.push(b)}));"object"==typeof h&&(h=h[0]);if(h){0==h.indexOf("//")&&(h="http:"+h);h=h.split("|")[0];-1!=h.indexOf(".mp4")?a.download?(a.callback(),fileopener(h)):a.callback({poster:getlistimg(a.pid,a.plugin),url:"",source:h,type:"video",videoType:"mp4",title:myContent.name}):a.download?a.callback():(window.open(h,"_blank",
"location=no"),ExView.fw.hidePreloader());return}if(!(plugfns(a.plugin).config.galleryRule||plugfns(a.plugin).config.indexRule||{}).pictureRule){a.callback();return}}var k=(plugfns(a.plugin).config.galleryRule||plugfns(a.plugin).config.indexRule).pictureRule,g=pluginfo(a.plugin).type;switch(g){default:case "image":g="图片";break;case "video":g="视频";break;case "text":g="文章"}var n=function(){b=myContent.itemimgs[0];if(array_count(b)){var c=b.map(function(b){return b=plugfns(a.plugin).parseHost(b)}),
e=function(b){var c=[];"object"==typeof b?b.forEach(function(b){b&&(b=plugfns(a.plugin).parseHost(b),b=b.replace(/\\\//g,"/"),c.push(getcommonload(b,{cacheheader:{Referer:encodeURI(plugfns(a.plugin).referer),Connection:"keep-alive","User-Agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"},nativeres:!plugfns(a.plugin).getFlag(b,"webimgreqlist",a)})))}):(img=img.replace(/\\\//g,"/"),c.push(getcommonload(b,{cacheheader:{Referer:encodeURI(plugfns(a.plugin).referer),
Connection:"keep-alive","User-Agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"},nativeres:!plugfns(a.plugin).getFlag(b,"webimgreqlist",a)})));a.download?a.callback({source:c,type:"image",download:a.download,plugin:a.plugin}):a.callback({source:c,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})};if(plugfns(a.plugin).config.extraRule){var d=c,f=d.length,c=[],h=function(){var b=
d.shift();if(/(?:(\.[png|jpg|jpeg|gif|bmp|webp]*$))/.test(b))c.push(b),d.length?h():e(c);else{var b=plugfns(a.plugin).parseUrl(b,a),k=f-d.length,m=plugfns(a.plugin).parseHeader(a);ExView.modules.curl({url:b,header:m,method:"GET",webview:plugfns(a.plugin).getFlag(b,"webviewlist",a),webviewjs:plugfns(a.plugin).getFlag(b,"webviewjslist",a),encoding:plugfns(a.plugin).getFlag(b,"gbklist",a)?"gbk":void 0,cookie:plugfns(a.plugin).getFlag(b,"webreqlist",a)?void 0:pluginfo(a.plugin).requestcookie,referer:pluginfo(a.plugin).referer,
ua:plugfns(a.plugin).getFlag(b,"webreqlist",a)?void 0:"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36",nativerequest:!plugfns(a.plugin).getFlag(b,"webreqlist",a),successfn:function(f){if(-1!=f.indexOf("</div>")&&-1!=f.indexOf("</body>")){var g=plugfns(a.plugin).config.extraRule||plugfns(a.plugin).config.galleryRule||plugfns(a.plugin).config.indexRule,l=g.pictureRule||{pictureRule:{}},g=g.pictureHighRes||g.pictureUrl||l.highRes||l.url;
l.item?(g=plugfns(a.plugin).parserRootSelector(l,l.highRes?"highRes":"url",f),g.length||(g=plugfns(a.plugin).parserRootSelector(l,"url",f))):g=plugfns(a.plugin).parserSelector(g,f);"object"==typeof g?c=c.concat(g):c.push(g)}else c.push(b);d.length?h():e(c)},errorfn:function(){c.push(b);d.length?h():e(c)},showinfo:a.download?"":{text:"正在加载"+g+"信息...<br>"+k+" / "+f,title:g,name:getlistname(a.pid),img:getlistimg(a.pid)}})}};h()}else e(c)}else a.callback()},m=function(b,
c){var e=0;if(plugfns(a.plugin).config.indexRule.pictureRule&&!(plugfns(a.plugin).config.galleryRule||{}).pictureRule){var d=plugfns(a.plugin).config.galleryUrl?plugfns(a.plugin).parseUrl(plugfns(a.plugin).config.galleryUrl,a):litehextostring(a.pid.split("_")[0]);myContent.itemimgs[0].push(d);return e=0}if(!k.item)return k.url&&((d=plugfns(a.plugin).parserSelector(k.highRes||k.url,c))||(d=plugfns(a.plugin).parserSelector(k.url,c)),"object"==typeof d?(d||[]).forEach(function(a){-1==myContent.itemimgs[0].indexOf(a)&&
a?(myContent.itemimgs[0].push(a),e=1):e=0}):-1==myContent.itemimgs[0].indexOf(d)&&d?(myContent.itemimgs[0].push(d),e=1):e=0),e;if(k.item.selector)return d=plugfns(a.plugin).parserRootSelector(k,k.highRes?"highRes":"url",c),d.length||(d=plugfns(a.plugin).parserRootSelector(k,"url",c)),"object"==typeof d?(d||[]).forEach(function(a){-1==myContent.itemimgs[0].indexOf(a)&&a?(myContent.itemimgs[0].push(a),e=1):e=0}):-1==myContent.itemimgs[0].indexOf(d)&&d?(myContent.itemimgs[0].push(d),e=1):e=0,e;if(k.item.path)return plugfns(a.plugin).parserJSON(k,
c).forEach(function(b){b=plugfns(a.plugin).evalStr((k.highRes||k.url).path,b,(k.item||{}).path);"object"==typeof b&&(b=JSON.stringify(b));var c=(k.highRes||k.url).regex;c&&(b=getstrs(b,new RegExp(c,"(.*)"==c?void 0:"g"),(k.highRes||k.url).replacement||"$1"));"object"==typeof b?(b||[]).forEach(function(a){-1==myContent.itemimgs[0].indexOf(a)&&a?(myContent.itemimgs[0].push(a),e=1):e=0}):-1==myContent.itemimgs[0].indexOf(b)&&b?(myContent.itemimgs[0].push(b),e=1):e=0}),e},p=function(b){var c=plugfns(a.plugin).config.galleryUrl,
c=plugfns(a.plugin).parseUrl(c,obj_contact(a,{page:b})),e=plugfns(a.plugin).parseHeader(a);ExView.modules.curl({url:c,header:e,method:"GET",webview:plugfns(a.plugin).getFlag(c,"webviewlist",a),webviewjs:plugfns(a.plugin).getFlag(c,"webviewjslist",a),encoding:plugfns(a.plugin).getFlag(c,"gbklist",a)?"gbk":void 0,cookie:plugfns(a.plugin).getFlag(c,"webreqlist",a)?void 0:pluginfo(a.plugin).requestcookie,ua:plugfns(a.plugin).getFlag(c,"webreqlist",a)?void 0:"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36",
nativerequest:!plugfns(a.plugin).getFlag(c,"webreqlist",a),successfn:function(c){m(b,c)&&(a.download?p(b+1):myContent.items[parseInt(a.cid)+1]||myContent.items.push({pid:a.pid,cid:parseInt(a.cid)+1+"",title:"续"+(parseInt(a.cid)+2)+"话"}));ExView.fw.hidePreloader();n()},errorfn:function(){ExView.fw.hidePreloader();n()},showinfo:{text:"正在加载"+g+"信息...",title:g,name:getlistname(a.pid),img:getlistimg(a.pid)}})};myContent.itemimgs=[];myContent.itemimgs[0]=[];/{page:(.*?)}/.test(plugfns(a.plugin).config.galleryUrl)?
p(parseInt(a.cid)+1):(m(1,myContent.result),n());return!0}}}},commentflag:{loader:function(a){var b=plugfns(a.plugin).parseUrl(plugfns(a.plugin).config.galleryUrl,a),c=plugfns(a.plugin).parseHeader(a);return{url:b,method:"GET",timeout:120,header:c,webview:plugfns(a.plugin).getFlag(b,"webviewlist",a),webviewjs:plugfns(a.plugin).getFlag(b,"webviewjslist",a),encoding:plugfns(a.plugin).getFlag(b,"gbklist",a)?"gbk":void 0,cookie:plugfns(a.plugin).getFlag(b,"webreqlist",a)?void 0:pluginfo(a.plugin).requestcookie,
ua:plugfns(a.plugin).getFlag(b,"webreqlist",a)?void 0:"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36",nativerequest:!plugfns(a.plugin).getFlag(b,"webreqlist",a),successfn:function(c,e){c?a.callback({result:c,header:e,commentbrowser:{url:b,title:"评论 - "+pluginfo(a.plugin).name+'<br><span style="font-size:16px">'+(myContent.name||"")+"</span>",browser:!0,flag:""}}):a.callback()}}},finder:function(a){ExView.fw.hidePreloader();
var b=plugfns(a.plugin).config.galleryRule;if(!b)return!1;var c=b.commentRule;if(!c)return!1;var d=[];c.item.selector&&(b=getquery(a.result,c.item.selector,$),array_count(b)&&b.each(function(b){var f=$$(this).html();b=plugfns(a.plugin).parserSelector(c.avatar,f);b=(b=b[0])?plugfns(a.plugin).parseHost(b):"";var h=plugfns(a.plugin).parserSelector(c.author,f),h=h[0],k=plugfns(a.plugin).parserSelector(c.datetime,f),k=k[0],f=plugfns(a.plugin).parserSelector(c.content,f),f=f[0];d.push({avatar:b,author:h,
datetime:k,content:f})}));c.item.path&&(b=plugfns(a.plugin).parserJSON(c,a.result,function(b){b=plugfns(a.plugin).evalStr(c.item.path,b);var f=c.item.regex;f&&(b=b.replace(new RegExp(f,"(.*)"==f?void 0:"g"),c.item.replacement||"$1"));b&&("object"==typeof b?d=thumbarr.concat(b):d.push(b))}));return{successfn:function(b,c,h,k){if(array_count(b)){b=/{page:(.*?)}/.test(plugfns(a.plugin).config.galleryUrl)?a.page+1:a.page-1;c=d;for(var g in c)a.callback({page:a.page||1,pagecount:b,comment:{text:c[g].content||
"",name:c[g].author||"",avatar:c[g].avatar||"",type:"received",label:c[g].datetime||"",day:"",time:"",reverse:1,extra:""}})}}}},send:!1},previewflag:{loader:function(a){var b=plugfns(a.plugin).parseUrl(plugfns(a.plugin).config.galleryUrl,a),c=plugfns(a.plugin).parseHeader(a);return{url:b,method:"GET",timeout:120,header:c,webview:plugfns(a.plugin).getFlag(b,"webviewlist",a),webviewjs:plugfns(a.plugin).getFlag(b,"webviewjslist",a),encoding:plugfns(a.plugin).getFlag(b,"gbklist",a)?"gbk":void 0,cookie:plugfns(a.plugin).getFlag(b,
"webreqlist",a)?void 0:pluginfo(a.plugin).requestcookie,ua:plugfns(a.plugin).getFlag(b,"webreqlist",a)?void 0:"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36",nativerequest:!plugfns(a.plugin).getFlag(b,"webreqlist",a),successfn:function(b,c){b?a.callback({result:b,header:c}):a.callback()}}},finder:function(a){var b=plugfns(a.plugin).config.galleryRule;if(!b)return!1;var c=b.videoRule||b.pictureRule;if(!c)return!1;var d=[];c.item?(c.item.selector&&
(b=plugfns(a.plugin).parserRootSelector(c,"thumbnail",a.result))&&("object"==typeof b?d=d.concat(b):d.push(b)),c.item.path&&plugfns(a.plugin).parserJSON(c,a.result,function(b){b=plugfns(a.plugin).evalStr(c.thumbnail.path,b,(c.thumbnail||{}).path);var f=c.thumbnail.regex;f&&(b=b.replace(new RegExp(f,"(.*)"==f?void 0:"g"),c.thumbnail.replacement||"$1"));b&&("object"==typeof b?d=d.concat(b):d.push(b))})):c.thumbnail&&(b=plugfns(a.plugin).parserSelector(c.thumbnail,a.result),array_remove(b,""),b&&("object"==
typeof b?d=d.concat(b):d.push(b)));return{successfn:function(b,c,h,k){d.forEach(function(b){b=plugfns(a.plugin).parseHost(b);b=b.replace(/\\\//g,"/");b=getcommonload(b,{cacheheader:{Referer:plugfns(a.plugin).referer,Connection:"keep-alive","User-Agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"},nativeres:!plugfns(a.plugin).getFlag(b,"webimgreqlist",a)});a.callback({page:a.page||1,pagecount:b&&/{page:(.*?)}/.test(plugfns(a.plugin).config.galleryUrl)?
a.page+1:a.page-1,preview:{imgurl:b,pageurl:b}})})}}}},pageimgflag:{parser:function(a){return{successfn:function(b){a.loadimgurl(a.url)}}}},updateflag:{loader:function(a){if(!plugfns(a.plugin).config){var b=pluginfo(a.plugin).sourceTxt;if(!b)return{successfn:function(){a.callback()}};var c=plugfns(a.plugin);c.config=JSON.parse(b);c.referer=c.parseUrl(c.config.indexUrl,a);setnowlistname(c.config.title,"",pluginfo(a.plugin).icon||"img/logo.png")}b=plugfns(a.plugin).parseUrl(plugfns(a.plugin).config.categories[0].url,
a);c=plugfns(a.plugin).parseHeader(a);return{url:b,header:c,method:"GET",timeout:120,webview:plugfns(a.plugin).getFlag(b,"webviewlist",a),webviewjs:plugfns(a.plugin).getFlag(b,"webviewjslist",a),encoding:plugfns(a.plugin).getFlag(b,"gbklist",a)?"gbk":void 0,cookie:plugfns(a.plugin).getFlag(b,"webreqlist",a)?void 0:pluginfo(a.plugin).requestcookie,ua:plugfns(a.plugin).getFlag(b,"webreqlist",a)?void 0:"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36",
nativerequest:!plugfns(a.plugin).getFlag(b,"webreqlist",a),successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{successfn:function(b){b=plugfns(a.plugin).config.indexRule;plugfns(a.plugin).parseDetail(b,a)}}}},hotflag:{loader:function(a){if(!plugfns(a.plugin).config){var b=pluginfo(a.plugin).sourceTxt;if(!b)return{successfn:function(){a.callback()}};var c=plugfns(a.plugin);c.config=JSON.parse(b);c.referer=c.parseUrl(c.config.indexUrl,a);setnowlistname(c.config.title,
"",pluginfo(a.plugin).icon||"img/logo.png")}b=plugfns(a.plugin).parseUrl(plugfns(a.plugin).config.categories[1].url,a);c=plugfns(a.plugin).parseHeader(a);return{url:b,header:c,method:"GET",timeout:120,webview:plugfns(a.plugin).getFlag(b,"webviewlist",a),webviewjs:plugfns(a.plugin).getFlag(b,"webviewjslist",a),encoding:plugfns(a.plugin).getFlag(b,"gbklist",a)?"gbk":void 0,cookie:plugfns(a.plugin).getFlag(b,"webreqlist",a)?void 0:pluginfo(a.plugin).requestcookie,ua:plugfns(a.plugin).getFlag(b,"webreqlist",
a)?void 0:"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36",nativerequest:!plugfns(a.plugin).getFlag(b,"webreqlist",a),successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{successfn:function(b){b=plugfns(a.plugin).config.indexRule;plugfns(a.plugin).parseDetail(b,a)}}}}},fns:{webviewjslist:["www.artstation.com/artwork/"],webviewlist:["www.artstation.com/artwork/","seiga.nicovideo.jp/seiga/","www.pixiv.net"],
httpslist:"pangci.cc www.pixiv.net bcy.net www.zerochan.net www.h-manga.moe www.zngirls.com www.dbmeinv.com www.nvshens.com www.deviantart.com www.pornhub.com gelbooru.com".split(" "),webreqlist:["exhentai.org","gentai.org","pic.sogou.com"],webimgreqlist:["exhentai.org","pic.sogou.com"],gbklist:["pangci.cc","www.meizitu.com","pic.yesky.com","t66y.com"],getFlag:function(a,b,c){var d=plugfns(c.plugin);if("webviewlist"==b&&-1!=plugfns(c.plugin).config.flag.indexOf("loginRequired")){var e=!0;d.webreqlist.forEach(function(b){-1!=
a.indexOf(b)&&(e=!1)});return e}if("webviewjslist"==b&&-1!=plugfns(c.plugin).config.flag.indexOf("jsNeeded"))return!0;e=!1;d[b].forEach(function(b){-1!=a.indexOf(b)&&(e=!0)});return e},getSource:function(a,b,c,d){ExView.modules.curl({url:a,method:"GET",timeout:120,successfn:function(a,f){var h=plugfns(d.plugin);try{h.config=JSON.parse(a)}catch(g){c&&c(g);return}h.referer=h.parseUrl(h.config.indexUrl,d);var k=h.config.categories;$$("#type-page .site ul").children().remove();k?(k||[]).forEach(function(a){addtypelist({tid:"",
listflag:a.url,title:h.config.title+" ♂ "+a.title,img:pluginfo(d.plugin).icon,group:{name:"site",title:"分类"},content:h.config.title+" ♂ "+a.title})}):addtypelist({tid:"",listflag:h.config.indexUrl,title:h.config.title+" ♂ 首页",img:pluginfo(d.plugin).icon,group:{name:"site",title:"分类"},content:h.config.title+" ♂ 首页"});b&&b(a)},errorfn:function(a){c&&c(a)},canclefn:function(a){c&&c(a)}})},webpagefork:function(a){if("string"==typeof a.container){$$(a.container);
a=plugfns(mySession.nowplugin);var b=a.config.loginUrl||a.parseUrl(a.config.indexUrl);setTimeout(function(){$$('.page[data-page="webpage"]').find(".back").trigger("click")},500);openweburl(b,a.config.title+" - 登录")}},parseUrl:function(a,b){b=b||{};page=b.page||1;keyword=b.keyword||"";pid=(b.pid||"").split("_")[0]||"";/{idCode:(\d,\w,\-,\_)*}/.test(a)&&(a=a.replace(/{idCode:(\d,\w,\-,\_)*}/,litehextostring(pid)||"$1"));if(/{pageStr:(.*?)*{page:([\d,\w,\_,\-]+)*}(.*?)*}/.test(a)){var c=getstr(/{page:(\d+)*/,
a);"0"==c&&--page;"minid"==a.replace(/.*?{pageStr:(.*?)*{page:([\d,\w,\_,\-]+)*}(.*?)*}.*?/,"$2")&&plugfns(b.plugin).minid&&(page=plugfns(b.plugin).minid);a=a.replace(/{pageStr:(.*?)*{page:([\d,\w,\_,\-]+)*}(.*?)*}/,1<page?"$1"+(page||"$2")+"$3":"")}/{keyword:(.*?)}/.test(a)&&(a=a.replace(/{keyword:(.*?)}/,keyword||"$1"));/{page:(\d+)*}/.test(a)&&(c=getstr(/{page:(\d+)*}/,a),"0"==c&&--page,a=a.replace(/{page:(\d+)*}/,page||"$1"));if(/{page:(\d+)\:(\d+)}/.test(a)){var c=parseInt(getstr(/{page:(\d+)\:(\d+)}/,
a,1))||0,d=parseInt(getstr(/{page:(\d+)\:(\d+)}/,a,2))||0;a=a.replace(/{page:(\d+)\:(\d+)}/,c+(parseInt(page||1)-1)*d)}plugfns(b.plugin).getFlag(a,"httpslist",b)&&(a=a.replace("http://","https://"));return a},parseHeader:function(a){a=plugfns(a.plugin).config.header;var b={};a&&(a=a.split("\n")||[],a.forEach(function(a){a=a.split(":");b[a[0]]=a[1]}));return b},parseHost:function(a){if(!a||!a.length)return"";var b=this.referer;(a=(a||"").trim())&&0!=a.indexOf("http://")&&0!=a.indexOf("https://")&&
(b=b.split("/"),0==a.indexOf("//")?(b=b[0],a=b+a):(b=b[0]+"//"+b[2],a=b+"/"+(0==a.indexOf("/")?a.substring(1):a)));plugfns("hviewer").getFlag(a,"httpslist",{plugin:"hviewer"})&&(a=a.replace("http://","https://"));return a},parserRootSelector:function(a,b,c){if(a&&c){var d=[];getquery(c,(a.item||a[b]).selector,$).each(function(c){c=this.outerHTML;0==a[b].selector.indexOf(a.item.selector)&&(a[b].selector=selector.replace(a.item.selector,"root"),c="<root>"+c+"</root>");c="this"==a[b].selector?$$(this):
getquery(c,a[b].selector,$);c.length&&c.each(function(){var c=a[b].fun?a[b].param?$$(this)[a[b].fun](a[b].param):$$(this)[a[b].fun]():this.outerHTML;a[b].regex&&(c=getstrs(c,new RegExp(a[b].regex,"(.*)"==a[b].regex?void 0:"g"),a[b].replacement||"$1"));"object"==typeof c?d=d.concat(c):d.push(c)})});return d}},parserSelector:function(a,b,c){if(!a||!a.selector)return[];var d=[];console.log(b);b="this"==a.selector?$$(c)||$$(b):getquery(b,a.selector,$);console.log(b);b.length&&b.each(function(){if(a.fun)console.log(this),
b=a.param?$$(this)[a.fun](a.param):$$(this)[a.fun]();else var b=this.outerHTML;a.regex&&(b=getstrs(b,new RegExp(a.regex,"(.*)"==a.regex?void 0:"g"),a.replacement||"$1"));"object"==typeof b?d=d.concat(b):d.push(b)});return d},parserJSON:function(a,b,c){var d=this.evalStr,e=JSON.parse(b),f=[];b=a.item.path.split(",");(b||[]).length?b.forEach(function(b){b=(b||"").replace(/\[\?\(\@\./g,"[0].").replace(/\)\]/g,"");try{if(d(b,e,a.item.path)){b=b.split("[0].")[0];var c=d(b,e,a.item.path);c&&(f=f.concat(c))}}catch(g){console.log(g)}}):
f=d(a.item.path,e);f.forEach(function(a,b){c&&c(a)});return f},evalStr:function(a,b,c){if(a&&b){var d=a.split(",");if(1<d.length){var e=[];d.forEach(function(a){c&&0!=a.indexOf("$")&&(a=c+"."+a);var d=null;try{(d=Function("var $=this;return "+a).apply(b))&&("object"==typeof d?e=e.concat(d):e.push(d))}catch(k){}});e.length||(e="");return e}c&&0!=a.indexOf("$")&&(a=c+"."+a);return Function("var $=this;return "+a).apply(b)}},parseDatailSelector:function(a,b,c,d){var e=plugfns(d.plugin).parserSelector(a.idCode,
b,c),f=plugfns(d.plugin).parserSelector(a.cover,b,c),h=plugfns(d.plugin).parserSelector(a.title,b,c),k=plugfns(d.plugin).parserSelector(a.datetime,b,c),g=plugfns(d.plugin).parserSelector(a.uploader,b,c);plugfns(d.plugin).parserSelector(a.description,b,c);var n=plugfns(d.plugin).parserSelector(a.tags,b,c);a=plugfns(d.plugin).parserSelector(a.category,b,c);e=e[0];f=f[0];f=plugfns(d.plugin).parseHost(f);return{pid:e,img:f,title:h[0],time:k[0],author:g[0],intro:a,tags:n}},parseDatailJSON:function(a,b,
c){var d=plugfns(c.plugin).evalStr,e=function(b,e){if(!b||!e)return"";var f=d(b.path,e,a.item.path);b.selector&&(f=plugfns(c.plugin).parserSelector(b,f));"object"==typeof f&&(f=f[0]);var g=b.regex;return g?(f||"").replace(new RegExp(g,"(.*)"==g?void 0:"g"),b.replacement||"$1"):f},f=e(a.idCode,b),h=e(a.cover,b),k=e(a.title,b);try{var g=e(a.datetime,b)}catch(q){g=""}try{var n=e(a.uploader,b)}catch(q){n=""}try{var m=e(a.description,b)}catch(q){m=""}try{var p=e(a.tags,b)}catch(q){p=""}return{pid:f,img:h,
title:k,time:g,author:n,intro:m,tags:p}},parseDetail:function(a,b){var c=0;try{plugfns(b.plugin).config.galleryRule.commentRule&&(c=1)}catch(u){}var d=0;try{(plugfns(b.plugin).config.galleryRule.videoRule||plugfns(b.plugin).config.galleryRule.pictureRule).thumbnail&&(d=1)}catch(u){}if(a.item.selector)var e=getquery((b.result||"").replace(/<textarea.*?>/g,"<text area$1>"),a.item.selector,$);a.item.path&&(e=plugfns(b.plugin).parserJSON(a,b.result));console.log(e);if(array_count(e))for(var f=0;f<e.length;f++){var h=
e[f];if(a.item.selector)var k=h.outerHTML,g=plugfns(b.plugin).parseDatailSelector(a,k,h,b),k=g.pid,n=g.title,m=g.img,p=g.time,q=g.author,t=g.intro,r=g.tags;a.item.path&&(g=plugfns(b.plugin).parseDatailJSON(a,h,b),k=g.pid,n=g.title,m=g.img,p=g.time,q=g.author,t=g.intro,r=g.tags);console.log(h);console.log(m);if(k){"string"==typeof r&&(r=[]);plugfns(b.plugin).minid=k;m=getcoverload(m,{cacheheader:{Referer:encodeURI(plugfns(b.plugin).referer),Connection:"keep-alive","User-Agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"},
nativeres:!plugfns(b.plugin).getFlag(m,"webimgreqlist",b)});g={pid:stringtolitehex(k.toString()),title:n||stringtolitehex(k.toString()),img:m,stitle:(q?q+" ":"")+(p?p+" ":""),content:function(){return(r||[]).map(function(a){return getboxitem(a)}).join("")||""}()+t,comment:c,preview:d};if(plugfns(b.plugin).config.indexRule.pictureRule&&!(plugfns(b.plugin).config.galleryRule||{}).pictureRule)if((a.pictureRule.item||{}).selector&&(a.pictureRule.item||{}).path){var l=plugfns(b.plugin).evalStr(a.pictureRule.item.path,
h);console.log(getquery(l,a.pictureRule.item.selector,$));"this"==a.pictureRule.url.selector&&(a.pictureRule.url.selector=(a.pictureRule.item||{}).selector);(l=getquery(l,a.pictureRule.url.selector,$))?(l=a.pictureRule.url.fun?a.pictureRule.url.param?l[a.pictureRule.url.fun](a.pictureRule.url.param):l[a.pictureRule.url.fun]():l.prop("outerHTML"),a.pictureRule.url.regex&&(l=getstrs(l,new RegExp(a.pictureRule.url.regex,"(.*)"==a.pictureRule.url.regex?void 0:"g"),a.pictureRule.url.replacement||"$1")),
"object"==typeof l&&(l=l[0]),g.pid=l?stringtolitehex(l):""):g.pid=""}else a.pictureRule.url.selector&&(l=a.pictureRule.url.fun?a.pictureRule.url.param?getquery(b.result,a.pictureRule.url.selector,$)[a.pictureRule.url.fun](a.pictureRule.url.param):getquery(b.result,a.pictureRule.url.selector,$)[a.pictureRule.url.fun]():l.prop("outerHTML"),a.pictureRule.url.regex&&(l=getstrs(l,new RegExp(a.pictureRule.url.regex,"(.*)"==a.pictureRule.url.regex?void 0:"g"),a.pictureRule.url.replacement||"$1")),"object"==
typeof l&&(l=l[0]),g.pid=stringtolitehex(l)),a.pictureRule.url.path&&("$"==a.pictureRule.url.path&&(a.pictureRule.url.path=(a.pictureRule.item||{}).path),l=plugfns(b.plugin).evalStr(a.pictureRule.url.path,h,(a.pictureRule.item||{}).path),"object"==typeof l&&(l=JSON.stringify(l)),a.pictureRule.url.regex&&(l=getstrs(l,new RegExp(a.pictureRule.url.regex,"(.*)"==a.pictureRule.url.regex?void 0:"g"),a.pictureRule.url.replacement||"$1")),"object"==typeof l&&(l=l[0]),g.pid=stringtolitehex(l));if(h=pluginfo(b.plugin).sourceUrl)g.pid=
g.pid+"_"+stringtolitehex(h);b.callback(g)}}else b.callback()}}});
