ExView.Plugins({info:{name:"精明眼漫画",version:"2.2",db:"iibq",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAA5FBMVEX///9MTExTU1NKSkpFRUWVlZVPT0/7/P3z9vfy8vPo6OjFxcWrq6tkZGT6+vrr8PDj4+Pg4OCzs7Olpaajo6SGhIVtbW1gYGD2+frm6e70xt7b29v2utjV1dX0tNXS0tK/v7+urq6tra1ug59bl52ampqPj4/gKIeAgIA1U3lzc3Nqamr88Pb87fXg6+zX3+XR4uTB2NrHz9rc1Niuy87Ly8utucjxnMi3xceotMTvlMO4uLiJs7iSobeGsbZpn6V4iqWsmqPmVJ+RnJ6cnJxKi5LiN4+HiIg6gIg9Wn/dFXxbW1taZhR4AAAAw0lEQVQY002O1c7CYBBEd/cTSt2Lu/O74O7y/u9DaEng3M3JZDKQ8FYqvcMruUO7AKnUU0wu7Zw1/nmKwmaYrXfr6SSlKyJY/36eu6tMnJ0rkxLRH8yz8UpZ9ny9prfIU74XfxlQA8PtI6NdC0eNU8OCf6Pa4UxzScftcj9TYIo2cSxrrCaPH18KgEbFiHNkqEsBd/KhEIxz3vdZJRZmkzwRUcftofO4FZEo2lWD8VB9mGZIaASaQA8STMt2VAXM/L1xA4ZlEIfdiwBbAAAAAElFTkSuQmCC",
apihost:"http://www.jmydm.com/",pagetitle:["<br>","收藏","当日最热","类型","下载"],lazyload:!0,download:!0,setting:!0,commentbar:!1,theme:"brown",cdn:""},set:function(a){},unset:function(a){},init:function(a){ExView.workers.fav.listloader({callback:function(){}})},flags:{indexflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"viewtop/",method:"GET",timeout:120,successfn:function(b,c){a.callback({img:pluginfo(a.plugin).icon,multpage:!0,result:b,
header:c})}}},finder:function(a){return{query:!0,selector:".cComicDL>div",str:a.result,successfn:function(b){if(array_count(b)){var c=getstr(/\/manhua\-([\d,\w,\-,\_]+)\//g,$$(b).find("a").attr("href")),d=$$(b).find("img").attr("alt"),e=$$(b).find("img").attr("src");b=$$(b).find(".cCDL3").text()||"";a.callback({pid:c,title:d,img:e,stitle:b||"",content:"",comment:1})}else a.callback()}}},countloader:!1,countfinder:function(a){return{successfn:function(b){a.callback({pagecount:-1})}}}},typeflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"comic",method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){a.callback({title:"当日最热",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"当日最热"});a.callback({tid:"update",title:"当日更新",img:pluginfo(a.plugin).icon,listflag:"comicupdate/",group:{name:"daohang",title:"导航"},content:"当日更新"});a.callback({tid:"top",title:"最受推荐榜",
listflag:"TopType-0101/",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"最受推荐榜"});a.callback({tid:"top",title:"最多人看榜",listflag:"TopType-0102/",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"最多人看榜"});a.callback({tid:"top",title:"最多收藏榜",listflag:"TopType-0103/",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"最多收藏榜"});
a.callback({tid:"top",title:"最高评分榜",listflag:"TopType-0104/",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"最高评分榜"});return{query:!0,selector:".cAreaTitle",str:a.result,successfn:function(b){if(array_count(b)){var c=$$(b).text(),d=ExView.tools.md5.hex_md5(c);$$(b).next().find("a").each(function(b){b=$$(this).attr("href");b=getstr(/\/([\d,\w,\-,\_]+)\//g,b);var f=$$(this).text();a.callback({tid:b,title:f,img:pluginfo(a.plugin).icon,
group:{name:"s"+d,title:c},content:f})})}}}}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+(a.flag?a.flag:a.tid+"-"+(a.page||1)),method:"GET",timeout:120,successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})}}},finder:function(a){return a.flag?"update"==a.tid?{query:!0,selector:".cComicNew2 .cNCI",str:a.result,successfn:function(b){if(array_count(b)){var c=getstr(/\/manhua\-([\d,\w,\-,\_]+)\//g,$$(b).find("a").attr("href")),d=$$(b).find("img").attr("alt"),e=$$(b).find("img").attr("src"),
f=b.childNodes[3].nodeValue,g=b.childNodes[7].nodeValue,h=b.childNodes[9].nodeValue,l=(b.childNodes[10]||{}).innerText||"";b=getboxitem(b.childNodes[5].nodeValue)+getboxitem(g)+h+" "+l;a.callback({pid:c,title:d,img:e,stitle:f||"",content:b,comment:1})}else a.callback()}}:{query:!0,selector:".cComicItem",str:a.result,successfn:function(b){if(array_count(b)){var c=getstr(/\/manhua\-([\d,\w,\-,\_]+)\//g,$$(b).find("a").attr("href")),d=$$(b).find("img").attr("alt"),e=$$(b).find("img").attr("src"),f=$$(b).find(".cComicAuthor").text();
b=$$(b).find(".cComicUpdate").text();a.callback({pid:c,title:d,img:e,stitle:f||"",content:b,comment:1})}else a.callback()}}:{query:!0,selector:".cComicDL>div",str:a.result,successfn:function(b){if(array_count(b)){var c=getstr(/\/manhua\-([\d,\w,\-,\_]+)\//g,$$(b).find("a").attr("href")),d=$$(b).find("img").attr("alt"),e=$$(b).find("img").attr("src");b=$$(b).find(".clw2").text()?"更新至 "+$$(b).find(".clw2").text().replace(/\[/,"").replace(/\]/,""):"";a.callback({pid:c,title:d,img:e,stitle:b||
"",content:"",comment:1})}else a.callback()}}},countloader:!1,countfinder:function(a){return{query:!0,selector:".cComicPageChange2",str:a.result,successfn:function(b){try{var c=b.childNodes[5].innerText}catch(d){c=-1}a.callback({pagecount:c})}}}},searchflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"comic/s.aspx",method:"POST",data:"tbSTxt="+a.keyword,postform:!0,timeout:120,successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})}}},finder:function(a){return{query:!0,selector:".cInfoItem",
str:a.result,successfn:function(b){var c=getstr(/\/manhua\-([\d,\w,\-,\_]+)\//g,$$(b).find("a").attr("href")),d=$$("<p>"+$$(b).find(".cListSlt img").attr("alt")+"</p>").text(),e=$$(b).find("img").attr("src"),f=$$(b).find(".cListh1").text().replace("作者"," 作者");$$(b).find(".cInfoTime").text();var g=($$(b).find(".clw2").text()||"").replace("[","").replace("]","");if(array_count(b)){if(a.multsearch)return a.callback(obj_contact(a,{pid:c,img:e,title:d,content:"更新至 "+
g})),!1;a.callback({pid:c,title:d,img:e,stitle:f||"",content:"更新至 "+g,comment:1})}else a.callback()}}},countloader:!1,countfinder:function(a){return{json:!0,str:a.result,successfn:function(b){a.callback({pagecount:-1})}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"manhua-"+a.pid+"/",method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{query:!0,selector:".cUlVolList li",str:a.result,successfn:function(b,
c,d,e){if(array_count(c)){if(a.checkupdate)return d=c[0],b=getstr(/comicdir\/(\d+)\//g,$$(d).children("a").attr("href")),d=$$(d).children("a").text(),a.callback({pid:a.pid,cid:b,title:d}),!0;e=[];console.log(c);c.each(function(b){var d=getstr(/comicdir\/(\d+)\//g,$$(this).children("a").attr("href")),h=$$(this).children("a").text();e[b]=a.callback({id:c.length-b-1,newest:a.newest&&0==b,pid:a.pid,cid:d,title:h,count:c.length,reverse:1})});return e}a.callback()}}},infoloader:!1,infofinder:function(a){return{query:!0,
selector:".cComicText",str:a.result,successfn:function(b,c,d,e){c=$$(b).find(".cDefaultImg img").attr("src");d=$$(b).find(".cDefaultImg img").attr("alt");e=$$(b).find(".cInfoLianWan").text();var f=[],g=[];$$(b).find(".cShuoMing tr").eq(2).find("a").each(function(){f.push($$(this).text());g.push($$(this).text())});$$(b).find(".cShuoMing tr").eq(3).find("a").each(function(){f.push($$(this).text())});f=f.join(",");g=g.join(",");b=$$(b).find(".cShuoMing tr").eq(9).text().replace("最后更新于：",
"");var h=getquery(a.result,".cInfoArea").text();a.callback({name:d,img:c,added:a.data,description:"<p>"+(g?"【作者】"+g+"<br>":"")+(f?"【类型】"+f+"<br>":"")+(h?"【状态】"+e+"<br>":"")+(b?"【更新】"+b+"<br>":"")+(h?"【简介】"+h:"")+"</p>",comment:1,preview:0,tags:gettag(d)+gettag((f||"").split(",")),sourceurl:pluginfo(a.plugin).apihost+"manhua-"+a.pid+"/"});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"comicdir/"+a.cid+"/",method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){var b=eval('(function(s,a){k=a.substring(0,a.length-1);f=a.substring(a.length-1);for(i=0;i<k.length;i++){eval("s=s.replace(/"+k.substring(i,i+1)+"/g,\'"+i+"\')")}ss=s.split(f);s="";for(i=0;i<ss.length;i++){s+=String.fromCharCode(ss[i])}return s})');return{reg:/var\s*[\d,\w]+="([\d,\w]+)";var\s*sPath="([\d,\w,\/]+)";/g,str:a.result,find:"$1{{separator}}$2",successfn:function(c,
d,e,f){c=c.split("{{separator}}");try{var g=c[0],g=b(g,"kxnelimwzsb"),h=c[1],l=g.split("|"),k=[];for(e=0;e<l.length;e++){var m="http://comic.jmydm.com:8080/"+(h+l[e]).replace(/\//g,"/"),m=getimgload(getcdnload(m,pluginfo(a.plugin).cdn),a.plugin||mySession.nowplugin,{cacheheader:{Referer:pluginfo(a.plugin).apihost},nativeres:!0});k.push(m)}}catch(n){console.log(n)}console.log(k);array_count(k)?a.download?a.callback({source:k,download:a.download,plugin:a.plugin}):a.callback({source:k,type:"image",startindex:a.startindex||
0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title}):a.callback();return!0}}}},commentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"ManHuaTaoLun-"+a.pid+"-"+(a.page||1)+"/",method:"GET",timeout:120,successfn:function(b,c){b?a.callback({result:b,header:c,commentbrowser:{url:pluginfo(a.plugin).apihost+"ManHuaTaoLun-"+a.pid+"-"+(a.page||1)+"/",title:"评论 - "+pluginfo(a.plugin).name+'<br><span style="font-size:16px">'+(myContent.name||"")+"</span>",browser:!1,flag:""}}):
a.callback()}}},finder:function(a){return{query:!0,selector:".cListItem",str:a.result,successfn:function(b,c,d,e){array_count(b)&&(c=getquery(a.result,".cPageTxt")[0].childNodes[5].innerText,a.callback({page:a.page||1,pagecount:c,comment:{text:$$(b).find(".cNorm").text(),name:$$(b).find(".c3 a").text(),avatar:"",type:"received",label:$$(b).find(".c3")[0].childNodes[2].nodeValue,day:"",time:"",reverse:1,extra:""}}))}}},send:!1},previewflag:{loader:!1,finder:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"comicupdate",method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{query:!0,selector:".cComicNew2 .cNCI",str:a.result,successfn:function(b){if(array_count(b)){var c=getstr(/\/manhua\-([\d,\w,\-,\_]+)\//g,$$(b).find("a").attr("href")),d=$$(b).find("img").attr("alt"),e=$$(b).find("img").attr("src");a.callback(obj_contact(a,{pid:c,img:e,title:d,content:b.childNodes[9].nodeValue+" "+b.childNodes[10].innerText}))}else a.callback()}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"viewtop/",method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{query:!0,selector:".cComicDL>div",str:a.result,successfn:function(b){if(array_count(b)){var c=getstr(/\/manhua\-([\d,\w,\-,\_]+)\//g,$$(b).find("a").attr("href")),d=$$(b).find("img").attr("alt"),e=$$(b).find("img").attr("src");b=$$(b).find(".cCDL3").text()||"";a.callback(obj_contact(a,{pid:c,img:e,title:d,content:b}))}else a.callback()}}}}},fns:{pagedeal:function(a,b){b=b||{};a.forEach(function(a){var d=
a.comicId,e=a.thumb,f=a.title,g=a.authorName,h=a.comicType;a="更新至 "+(a.lastCharpter||"").title;if(b.multupdate||b.multhot||b.multsearch)return b.callback(obj_contact(b,{pid:d,img:e,title:f,content:a})),!1;b.callback({pid:d,title:f,img:e,stitle:g||"",content:a+(h?"<br>"+function(a){var b="";(a.split(",")||[]).forEach(function(a){b+='<span style="font-size:10px;"><span class="color-white bg-'+getnowtheme()+'" style="padding:3px;border-radius:3px;margin-right:3px;">'+a+"</span></span>"});
return b}(h):""),comment:1})})}}});
