ExView.Plugins({info:{name:"精明眼漫画",version:"2.2",db:"iibq",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAA5FBMVEX///9MTExTU1NKSkpFRUWVlZVPT0/7/P3z9vfy8vPo6OjFxcWrq6tkZGT6+vrr8PDj4+Pg4OCzs7Olpaajo6SGhIVtbW1gYGD2+frm6e70xt7b29v2utjV1dX0tNXS0tK/v7+urq6tra1ug59bl52ampqPj4/gKIeAgIA1U3lzc3Nqamr88Pb87fXg6+zX3+XR4uTB2NrHz9rc1Niuy87Ly8utucjxnMi3xceotMTvlMO4uLiJs7iSobeGsbZpn6V4iqWsmqPmVJ+RnJ6cnJxKi5LiN4+HiIg6gIg9Wn/dFXxbW1taZhR4AAAAw0lEQVQY002O1c7CYBBEd/cTSt2Lu/O74O7y/u9DaEng3M3JZDKQ8FYqvcMruUO7AKnUU0wu7Zw1/nmKwmaYrXfr6SSlKyJY/36eu6tMnJ0rkxLRH8yz8UpZ9ny9prfIU74XfxlQA8PtI6NdC0eNU8OCf6Pa4UxzScftcj9TYIo2cSxrrCaPH18KgEbFiHNkqEsBd/KhEIxz3vdZJRZmkzwRUcftofO4FZEo2lWD8VB9mGZIaASaQA8STMt2VAXM/L1xA4ZlEIfdiwBbAAAAAElFTkSuQmCC",
apihost:"http://www.iibq.com/",pagetitle:["<br>","收藏","首页","类型","下载"],lazyload:!0,download:!0,setting:!0,commentbar:!1,theme:"brown",cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){ExView.workers.index.loader();ExView.workers.type.loader()}})},flags:{indexflag:{loader:function(a){a.front||a.page||setnowlistname("首页","",pluginfo(a.plugin).icon);a.front||a.page||addtypelist('<div align="center" class="list-block"><img src="img/logo.png"/><br>类型<br>正在加载...<div class="progress"></span></div>',
2);return{url:pluginfo(a.plugin).apihost,method:"GET",timeout:120,successfn:function(b,c){ExView.workers.index.countfinder(obj_contact(a,{result:b,header:c}));a.front||a.page||ExView.workers.type.finder({result:b,plugin:a.plugin});a.successfn&&a.successfn({result:b,header:c})},errorfn:function(){a.page||addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>加载失败，请刷新重试！</a></div>',
2);ExView.fw.alert("网络错误！","ExView")},canclefn:function(){a.page||addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>加载失败，请刷新重试！</a></div>',2)},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),name:"首页",title:a.title,img:a.img}}},finder:function(a){return{reg:/\/comic\/(\d+)'><img\s*src='((?!\').*?)'\s*alt='((?!\').*?)'.*?[(人氣：)|(当天人气:)]+<em>(\d+)<\/em>/g,
str:a.result,find:{pid:"$1",img:"$2",title:"$3",hot:"$4"},successfn:function(a){console.log(JSON.stringify(a));array_count(a)?addcardlist({pid:a.pid,title:a.title,img:a.img.replace("http://comicui.jmmh.net/","http://upimg.jmydm.com/"),content:"【人气】"+a.hot,comment:1}):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',2)},errorfn:function(){a.page||setnowlistname("首页","",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();
mySession.isloading=0;ExView.fw.alert("网络错误！","ExView")}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="-1|首页|index";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},typeflag:{loader:function(a){return{successfn:function(){ExView.workers.index.loader()}}},finder:function(a){addtypelist({title:"首页",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},
content:"首页"});addtypelist({tid:"new",listflag:"comicupdate/",title:"最新",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"最新"});addtypelist({tid:"hot",listflag:"ax/getViewTopDate.aspx?c=-1",title:"最热",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"最热"});var b=getstrs(a.result,/\/class\/(\d+)"\s*title="((?!\").*?)"/g,"$1{{separator}}$2"),b=array_unique(b);b.forEach(function(b){b=b.split("{{separator}}");
addtypelist({tid:"class/"+b[0],title:b[1],img:pluginfo(a.plugin).icon,group:{name:"leixing",title:"类型"},content:b[1]})});getstrs(a.result,/\/pinyin\/([\w,\d,\-]+)">((?!<).*?)</g,"$1{{separator}}$2").forEach(function(b){b=b.split("{{separator}}");addtypelist({tid:"pinyin/"+b[0],title:b[1],img:pluginfo(a.plugin).icon,group:{name:"suoyin",title:"索引"},content:b[1]})});return{reg:/\/tag\/(\w+)"\s*title="((?!\").*?)"/g,str:a.result,find:"$1{{separator}}$2",successfn:function(b,d,f,e){if(array_count(e))return e.forEach(function(b){b=
b.split("{{separator}}");addtypelist({tid:"tag/"+b[0],title:b[1],img:pluginfo(a.plugin).icon,group:{name:"fenlei",title:"分类"},content:b[1]})}),!0}}}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+(a.flag?a.flag:a.keyword+"/"+(a.page||1)+"/"),method:"GET",timeout:120,successfn:function(b,c){b?(ExView.workers.list.countfinder(obj_contact(a,{result:b,header:c})),a.successfn&&a.successfn({result:b,header:c})):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+
a.title+"】<br>获取失败！","ExView"))},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),name:"【"+a.title+"】",title:a.title,img:a.img}}},finder:function(a){return{reg:"new"==a.keyword?/<img\s*src='((?!\').*?)'><\/a><div><a\s*title='((?!\').*?)更新'\s*href='(?!\').*?\/comic\/(\d+)'>((?!<).*?)\s*\[((?!<).*?)\]<\/a><\/div><div>((?!<).*?)<\/div>/g:"hot"==a.keyword?/\/comic\/(\d+)'><img\s*src='((?!\').*?)'\s*alt='((?!\').*?)'.*?[(人氣：)|(当天人气:)]+<em>(\d+)<\/em>/g:
plugfns(a.plugin).pagerule,str:a.result,find:"new"==a.keyword?{img:"$1",update:"$2",pid:"$3",title:"$4",newest:"$5",author:"$6"}:"hot"==a.keyword?{pid:"$1",img:"$2",title:"$3",hot:"$4"}:plugfns(a.plugin).pagefind,successfn:function(b){array_count(b)?"new"==a.keyword?addcardlist({pid:b.pid,title:b.title,img:b.img.replace("http://comicui.jmmh.net/","http://upimg.jmydm.com/"),content:"【作者】"+b.author+"<br>【最新】"+b.newest+"<br>【更新】"+b.update,comment:1}):
"hot"==a.keyword?addcardlist({pid:b.pid,title:b.title,img:b.img.replace("http://comicui.jmmh.net/","http://upimg.jmydm.com/"),content:"【人气】"+b.hot,comment:1}):plugfns(a.plugin).pagedeal(b,a):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return a.flag?{successfn:function(){return{pagecount:-1}}}:{reg:/\/(\d+)'\s*title='最后一页'/,str:a.result,
find:"$1",successfn:function(b){mySession.nowlistpages=(b||"0")+"|"+a.keyword+"|list";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},searchflag:{loader:function(a){return 1<parseInt(a.page)?(a.multsearch&&a.multsearch(),!1):{url:pluginfo(a.plugin).apihost+"search/?keyword="+a.keyword,method:"GET",timeout:120,successfn:function(b,c){b?(a.multsearch||(ExView.workers.search.countfinder(obj_contact(a,{result:b,header:c})),setnowlistname("搜索【"+a.keyword+"】")),
a.successfn&&a.successfn({result:b,header:c})):a.multsearch?a.multsearch():(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+a.keyword+"】<br>获取搜索结果失败！","ExView"))},showinfo:{text:"正在搜索..."+(1<a.page?"<br>第"+a.page+"页":""),name:"【"+a.keyword+"】",title:"搜索"}}},finder:function(a){return{reg:/<div\s*class='cInfoItem'>(.*?)<\/a>/g,str:a.result,find:"$1",successfn:function(b,c,d){console.log(b);
if(b){c=getstr(/\/comic\/(\d+)'/,b);d=getstr(/src='((?!\').*?)'/,b).replace("http://comicui.jmmh.net/","http://upimg.jmydm.com/");var f=gettext(getstr(/\d+'>(.*?)<span\s*class='clw/,b));b=getstr(/class='clw\d+'>\[((?!<).*?)\]<\/span>/,b).replace("话","");plugfns(a.plugin).pagedeal({pid:c,img:d,title:f,newest:b},a)}else a.multsearch?a.multsearch():addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}},countloader:function(a){return!1},
countfinder:function(a){return{successfn:function(b){mySession.nowlistpages="-1|"+a.keyword+"|search";mySession.nowlistpage=1;console.log(mySession.nowlistpages)}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"comic/"+a.pid+"/",method:"GET",timeout:120,successfn:function(b,c){b?a.successfn&&a.successfn({result:b,header:c}):a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},showinfo:{text:"正在加载内容页...",
title:"内容页",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){return{successfn:function(b,c,d,f){var e=[];b=getstrs(getresult(a.result).replace(/class='cVolTag'/g,"<exview>class='cVolTag'").replace(/id="uyan_frame"/g,'<exview>id="uyan_frame"'),/class='cVolTag'>((?!<).*?)<(.*?)<exview>/g,"$1{{separator}}$2");b=b.map(function(a){a=a.split("{{separator}}");var b=a[0];a=getstrs(a[1],/\/viewcomic(\d+)\/'>((?!<).*?)</g,"$1{{separator}}$2");a.reverse();a.map(function(a){a=
(a||"").split("{{separator}}");e.push({group:{name:"type_"+ExView.tools.md5.hex_md5(b),title:b},item:{cid:a[0],title:a[1]}})})});array_count(e)||(b=getstrs(a.result,/\/viewcomic(\d+)\/'>((?!<).*?)</g,"$1{{separator}}$2"),e.push({group:{},item:b}));if(array_count(e)){if(a.checkupdate)return c=e,b=c[c.length-1],b=(b||{}).item,{pid:a.pid,cid:b.cid,title:b.title};c=e;f=[];e.map(function(b,d){var e=b.item;f[d]=additemlist({id:d,newest:a.newest&&0==d,pid:a.pid,cid:e.cid,title:e.title,group:b.group,count:c.length,
reverse:0})});return f}a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},afterfn:function(){a.checkupdate||ExView.workers.content.infofinder(a)}}},infoloader:function(a){return!1},infofinder:function(a){console.log(a);return{reg:/class="comicInfo"(.*?)class="imgList"/g,str:getresult(a.result),find:"$1",successfn:function(b,c,d,f){try{var e=getstr(/<img\s*src='((?!\').*?)'/,b),g=getstr(/itemprop="name">\s*((?!<).*?)\s*<\/h1>/,
getresult(a.result)),k=getstr(/<li>完結：((?!<).*?)<\/li>/,b),m=getstr(/<li>更新日期：((?!<).*?)<\/li>/,b),h=gettext(getstr(/<\/span>作者：(.*?)<br\s*\/>/,b)),n=gettext(getstr(/<li>分类：(.*?)<\/li>/,b)),p=getstr(/itemprop="description">.*?<br\s*\/>(.*?)<\/p>/,b),l=gettag(k)+gettag(n)+gettag(h)}catch(q){}setlistpic({name:g,img:e.replace("http://comicui.jmmh.net/","http://upimg.jmydm.com/"),added:a.data,description:"<p>【作者】"+
h+"<br>【类型】"+n+"<br>【状态】"+k+"<br>【更新】"+m+"<br>【简介】"+p+"</p>",sourceurl:pluginfo(a.plugin).apihost+"comic/"+a.pid+"/",comment:1,preview:0,tags:gettag(g)+l+gettag(h)});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"comic/"+a.pid+"/viewcomic"+a.cid+"/",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"正在加载图片信息...",
title:"图片",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){return{reg:/var\s*sFiles="([\d,\w]+)";var\s*sPath="([\d,\w,\/]+)";/g,str:a.result,find:"$1{{separator}}$2",successfn:function(b){if(b){b=b.split("{{separator}}");try{var c=b[0],d=c,f=d.substring(d.length-1),e="abcdefghijklmnopqrstuvwxyz".indexOf(f)+1,g=d.substring(d.length-e-12,d.length-e-1),d=d.substring(0,d.length-e-12),k=g.substring(0,g.length-1),m=g.substring(g.length-1);for(i=0;i<k.length;i++)d=d.replace(new RegExp(k.substring(i,
i+1),"gi"),i);var h=d.split(m),d="";for(i=0;i<h.length;i++)d+=String.fromCharCode(h[i]);var c=d,n=b[1],p=c.split("|"),l=[];for(i=0;i<p.length;i++){var q="http://comic.jmydm.com:8080/"+(n+p[i]).replace(/\//g,"/"),q=getimgload(getcdnload(q,pluginfo(a.plugin).cdn),a.plugin||mySession.nowplugin,{cacheheader:{Referer:pluginfo(a.plugin).apihost},nativeres:!0});l.push(q)}}catch(r){console.log(r)}console.log(l);a.download?chapterpredownload({source:l,download:a.download,plugin:a.plugin}):chapterviewer({source:l,
type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})}else a.download?chapterpredownload({error:"解析错误！",download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("图片信息获取失败！","ExView"));return!0}}}},commentflag:{loader:function(a){return{url:1==parseInt(a.page||1)?"http://api.uyan.cc/v4/comment/?uid=1834194&url="+pluginfo(a.plugin).apihost+
"comic/"+a.pid+"/":"http://api.uyan.cc/v4/action/?sid="+a.sid+"&sort=1&pn="+a.page,method:"GET",timeout:120,successfn:function(b,c){if(b){var d={};1==parseInt(a.page||1)&&(d=ExView.modules.commentpage.uyanloader(b),b=JSON.stringify(d));a.callback&&a.callback({result:b,header:c,sid:d.sid||a.sid,commentbrowser:{url:"http://api.uyan.cc/v4/comment/?uid=1834194&url="+pluginfo(a.plugin).apihost+"comic/"+a.pid+"/",title:"评论 - "+pluginfo(a.plugin).name+'<br><span style="font-size:16px">'+(myContent.name||
"")+"</span>",browser:!1,flag:""}})}else a.callback&&a.callback()}}},finder:function(a){console.log(a);return{json:!0,str:a.result,successfn:function(b,c,d,f){b=b||{};1==parseInt(a.page||1)&&(b=b.comments);var e=0<b.more?0:-1;b=(b||[]).data;array_count(b)&&b.forEach(function(b){a.callback&&a.callback({page:a.page||1,pagecount:e,comment:{text:b.cnt,name:b.uname,avatar:b.uface,type:"received",label:b.time,day:"",time:"",reverse:1}})})}}},send:!1},previewflag:{loader:!1,finder:!1,more:!1},pageimgflag:{parser:!1},
updateflag:{loader:function(a){return 1<parseInt(a.page||1)?(a.multupdate(),!1):{url:pluginfo(a.plugin).apihost+"comicupdate/",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{reg:/<img\s*src='((?!\').*?)'><\/a><div><a\s*title='((?!\').*?)更新'\s*href='(?!\').*?\/comic\/(\d+)'>((?!<).*?)\s*\[((?!<).*?)\]<\/a><\/div><div>((?!<).*?)<\/div>/g,str:a.result,find:{img:"$1",update:"$2",pid:"$3",title:"$4",newest:"$5",author:"$6"},
successfn:function(b){console.log(JSON.stringify(b));array_count(b)&&a.multupdate(obj_contact(a,{pid:b.pid,img:b.img.replace("http://comicui.jmmh.net/","http://upimg.jmydm.com/"),title:b.title,content:"更新至 "+b.newest+" 话"}))}}}},hotflag:{loader:function(a){return 1<parseInt(a.page||1)?(a.multhot(),!1):{url:pluginfo(a.plugin).apihost+"ax/getViewTopDate.aspx?c=-1",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{reg:/\/comic\/(\d+)'><img\s*src='((?!\').*?)'\s*alt='((?!\').*?)'.*?[(人氣：)|(当天人气:)]+<em>(\d+)<\/em>/g,
str:a.result,find:{pid:"$1",img:"$2",title:"$3",hot:"$4"},successfn:function(b){console.log(JSON.stringify(b));array_count(b)&&a.multhot(obj_contact(a,{pid:b.pid,img:b.img.replace("http://comicui.jmmh.net/","http://upimg.jmydm.com/"),title:b.title,content:"【人气】"+b.hot}))}}}}},fns:{pagerule:/src='((?!\').*?)'><\/a><h3><a\s*href='(?!\').*?\/comic\/(\d+)'(?!<).*?>((?!<).*?)<\/a><\/h3><p>\[(\d+)\]((?!<).*?)<\/p>/g,pagefind:{img:"$1",pid:"$2",title:"$3",newest:"$4",author:"$5"},pagedeal:function(a,
b){b=b||{};try{var c=a.pid,d=a.img.replace("http://comicui.jmmh.net/","http://upimg.jmydm.com/"),f=a.title,e=a.author,g=a.newest,k=g?"更新至"+g+"话":"",m=e?"【作者】"+e+"<br>":"",h=k}catch(n){}if(b.multupdate)return b.multupdate(obj_contact(b,{pid:c,img:d,title:f,content:h})),!1;if(b.multhot)return b.multhot(obj_contact(b,{pid:c,img:d,title:f,content:h})),!1;if(b.multsearch)return b.multsearch(obj_contact(b,{pid:c,img:d,title:f,content:h})),!1;addcardlist({pid:c,title:f,
img:d,content:m,stitle:k,comment:1,preview:0,extrabutton:""})}}});
