ExView.Plugins({info:{name:"\u9f20\u7ed8\u6f2b\u753b",version:"2.2",author:"Gentle",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAApVBMVEVra2t4eHgaDQ0fExHe29vc2NjV0NDTzc3AurrZ1dXOyMjg3d25s7MhFhTj4ODKxMTCvLzX0tK7tbUmGhnm4+Ph3t7JwsLGwcDEvr6qo6KVj45/d3ZyamluZWRBNjQ2LCorHx4jGBbLxcW9t7e3sLCKgoGFfXxRR0ZIPj08MTDr6enQysquqKeRi4qPiYiNh4Z5cXBqYWBpYF9gV1ZaUE8yJyUxJiROhCfWAAAAA3RSTlMTExMBR9m7AAAAvklEQVQY0y3L15aCQBAE0N6tGZjMEFSSIGY3r+n/P81BrJfqvucUkUmS+cILscmMMRVRmUZxrNQ6aNt3YkuRlNGTkkN36ntBkvEnfarjbi6wJKYZ53LcHYX3AbSbjZRGCVDu4ckVhdOMpevKYgwV3/tm4eI/4H+C+vfrZ6kGAPnlnmWWav+hLaa0QEN1yfjwggF2RVnedgBuIwgcKpLmBMDAnkOtchB3s3AAtplmpHQA5GDbF7xxEeq620z/+wMXTg4hcerqBAAAAABJRU5ErkJggg==",
db:"ishuhui",apihost:"http://www.ishuhui.net/",pagetitle:["<br>","\u6536\u85cf","\u6700\u65b0\u63a8\u8350","\u7c7b\u578b","\u4e0b\u8f7d"],download:!0,lazyload:!0,setting:!0,theme:"gray",cdn:""},set:function(a){},unset:function(a){},init:function(a){ExView.workers.fav.listloader({callback:function(){}})},flags:{indexflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"ComicBooks/GetAllBook?Recommended=1&Subscribe=0",method:"GET",timeout:120,successfn:function(b,c){a.callback({img:pluginfo(a.plugin).icon,
multpage:!0,result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:function(a){return{json:!0,str:a.result,successfn:function(b){a.callback({pagecount:-1})}}}},typeflag:{loader:!1,finder:function(a){a.callback({title:"\u6700\u65b0\u63a8\u8350",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u6700\u65b0\u63a8\u8350"});a.callback({tid:"3",title:"\u9f20\u7ed8\u6c49\u5316",
img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u9f20\u7ed8\u6c49\u5316"});a.callback({tid:"4",title:"\u70ed\u8840\u6f2b\u753b",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u70ed\u8840\u6f2b\u753b"});a.callback({tid:"2",title:"\u56fd\u4ea7\u6f2b\u753b",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u56fd\u4ea7\u6f2b\u753b"})}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"ComicBooks/GetAllBook?ClassifyId="+a.tid+"&Size=10&PageIndex="+(parseInt(a.page||1)-1),method:"GET",timeout:120,successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:function(a){return{json:!0,str:a.result,successfn:function(b){try{var c=parseInt(b.Return.ListCount)}catch(f){c=-1}a.callback({pagecount:c})}}}},searchflag:{loader:function(a){if(1<
a.page)a.callback();else return{url:pluginfo(a.plugin).apihost+"ComicBooks/GetAllBook?Title="+a.keyword,method:"GET",timeout:120,successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:function(a){return{successfn:function(b){a.callback({pagecount:-1})}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"ComicBooks/GetChapterList?id="+a.pid+"&PageIndex=0",method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b,c,f,e){b=((b||{}).Return||{}).List;myContent.itemarr=b;var d=function(b){$$.ajax({url:pluginfo(a.plugin).apihost+"ComicBooks/GetChapterList?id="+a.pid+"&PageIndex="+(b-1),method:"GET",async:!1,success:function(a){a=JSON.parse(a);a=((a||{}).Return||{}).List;array_count(a)&&(myContent.itemarr=myContent.itemarr.concat(a),
b++,d(b))}})};if(array_count(b)){if(a.checkupdate)return c=b[0],a.callback({pid:a.pid,cid:c.Id,title:c.Title}),!0;d(2);b=myContent.itemarr;e=[];b.forEach(function(c,d){e[d]=a.callback({id:b.length-1-d,newest:a.newest&&0==d,pid:a.pid,cid:c.Id,title:c.Title,count:b.length,reverse:1})});return e}a.callback()}}},infoloader:!1,infofinder:function(a){return{json:!0,str:a.result,successfn:function(b,c,f,e){b=b.Return.ParentItem;c=b.Title;f=b.RefreshTimeStr;e=b.Author;var d=b.Explain;a.callback({name:c,img:b.FrontCover,
added:a.data,description:"<p>"+(e?"\u3010\u4f5c\u8005\u3011"+e+"<br>":"")+(f?"\u3010\u66f4\u65b0\u3011"+f+"<br>":"")+(d?"\u3010\u7b80\u4ecb\u3011"+d:"")+"</p>",comment:0,preview:0,tags:gettag(c)+gettag(e)});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"ReadComicBooksToIsoV2/"+a.cid,method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{query:!0,selector:"img",str:a.result,successfn:function(b,c,f,e){if(array_count(c)){var d=
[];$$(c).each(function(){d.push($$(this).attr("src"))});a.download?a.callback({source:d,download:a.download,plugin:a.plugin}):a.callback({source:d,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})}else a.callback();return!0}}}},commentflag:{loader:!1,finder:!1,send:!1},previewflag:{loader:!1,finder:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"ComicBooks/GetAllBook?ClassifyId=3&Size=10&PageIndex="+
(parseInt(a.page||1)-1),method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"ComicBooks/GetAllBook?ClassifyId=4&Size=10&PageIndex="+(parseInt(a.page||1)-1),method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{json:!0,
str:a.result,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}}}},fns:{pagedeal:function(a,b){b=b||{};console.log(a);a=a.Return.List;a.forEach(function(a){var f=a.Id,e=a.FrontCover,d=a.Title,g=a.Author+" "+a.RefreshTimeStr;a=a.Explain;if(b.multupdate||b.multhot||b.multsearch)return b.callback(obj_contact(b,{pid:f,img:e,title:d,content:g})),!1;b.callback({pid:f,title:d,img:e,stitle:g,content:a,comment:0})})}}});
