ExView.Plugins({info:{name:"绝对领域图库",version:"2.2",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAtFBMVEX////9/f3ExMRcXFwAAADq6ur5+fna2toWGhoPDw/09PTm5ubd3d07Ozs2NzcoKCgaHBwSEhLf4eHNzc2xsbGtra2UlJR2dnZqamptYmJTU1NQUVFLS0s5ODgzMzMxMTEqKio6JiYVFhYdEhLt7e3l5eXZ2dnS0tLp0dHg0dG9vb3Ttra2tra+paWlpaWcnJyPj4+AgIBzc3OLcnJ/amp0YmJfX19bW1tEREQsLCwiIiINBQUKDoS1AAAAm0lEQVQY022J1Q6DQBQF79JlBSvuUqDurv//X4VNWkjTeTmZOfABXTHeQQ+H4/QrygQgxZVE6RgEuQs+xsl2zzXhgU7I2vMIBL7wqamCQMqVdih/hnepuETR6VUbRwBElpmilc111lcxNEEdqsguEVrU800CUDCLW5ZjVIyZJjtAy+wh0wx6SCNZM36CrYe3gUCEody9f4Mbo07eD20KQyAmETgAAAAASUVORK5CYII=",
db:"jdlingyu",apihost:"http://www.jdlingyu.fun/",pagetitle:["<br>","收藏","首页","类型","下载"],lazyload:!0,download:!0,theme:"indigo",setting:!0,cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){ExView.workers.index.loader()}})},flags:{indexflag:{loader:function(a){a.front||a.page||addtypelist('<div align="center" class="list-block"><img src="img/logo.png"/><br>类型<br>正在加载...<div class="progress"></span></div>',
2);return{url:pluginfo(a.plugin).apihost+(1<parseInt(a.page)?"page/"+a.page+"/":""),method:"GET",timeout:120,successfn:function(b,c){ExView.workers.index.countfinder(obj_contact(a,{result:b,header:c}));a.front||a.page||ExView.workers.type.finder({result:b,plugin:a.plugin});a.successfn&&a.successfn({result:b,header:c})},errorfn:function(){a.page||addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>加载失败，请刷新重试！</a></div>',
2);ExView.fw.alert("网络错误！","ExView")},canclefn:function(){a.page||addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>加载失败，请刷新重试！</a></div>',2)},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),name:"首页",title:a.title,img:a.img}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,
str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b){b?plugfns(a.plugin).pagedeal(b):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)},errorfn:function(){a.page||setnowlistname("首页","",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("网络错误！","ExView")}}},countloader:function(a){return!1},countfinder:function(a){return{reg:plugfns(a.plugin).pagecountrule,
str:getresult(a.result),find:plugfns(a.plugin).pagecountfind,successfn:function(a){mySession.nowlistpages=(a||"0")+"|首页|index";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},typeflag:{loader:function(a){return{successfn:function(){ExView.workers.index.loader()}}},finder:function(a){addtypelist({title:"首页",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"首页"});return{reg:/class="menu">(.*?)id="options"/g,str:getresult(a.result),
find:"$1",successfn:function(b){b=getstrs(b,/\/([\w,\d,\/,\%]*)\/">((?!<).*?)<\/a>/g,"$1{separate}$2");array_count(b)?b.forEach(function(b){b=(b||"").split("{separate}");addtypelist({tid:b[0],title:b[1],img:pluginfo(a.plugin).icon,group:{name:"fenlei",title:"分类"},content:b[1]})}):addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>加载失败，请刷新重试！</a></div>',
2)}}}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+a.keyword+"/page/"+(a.page||1)+"/",method:"GET",timeout:120,successfn:function(b,c){b?(ExView.workers.list.countfinder(obj_contact(a,{result:b,header:c})),a.successfn&&a.successfn({result:b,header:c})):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+a.title+"】<br>获取失败！","ExView"))},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),
name:"【"+a.title+"】",title:a.title,img:a.img}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b){b?plugfns(a.plugin).pagedeal(b):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{reg:plugfns(a.plugin).pagecountrule,str:getresult(a.result),find:plugfns(a.plugin).pagecountfind,
successfn:function(b){mySession.nowlistpages=(b||"-1")+"|"+a.keyword+"|list";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},searchflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"page/"+(a.page||1)+"/?s="+a.keyword,method:"GET",timeout:120,successfn:function(b,c){b?(a.multsearch||(ExView.workers.search.countfinder(obj_contact(a,{result:b,header:c})),setnowlistname("搜索【"+a.keyword+"】")),a.successfn&&a.successfn({result:b,header:c})):a.multsearch?
a.multsearch():(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+a.keyword+"】<br>获取搜索结果失败！","ExView"))},showinfo:{text:"正在搜索..."+(1<a.page?"<br>第"+a.page+"页":""),name:"【"+a.keyword+"】",title:"搜索"}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b){b?plugfns(a.plugin).pagedeal(b,a):a.multsearch?
a.multsearch():addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{reg:plugfns(a.plugin).pagecountrule,str:getresult(a.result),find:plugfns(a.plugin).pagecountfind,successfn:function(b){mySession.nowlistpages=(b||"0")+"|"+a.keyword+"|search";mySession.nowlistpage=1;console.log(mySession.nowlistpages)}}}},contentflag:{loader:function(a){return{successfn:function(b,c){a.successfn&&
a.successfn({result:b,header:c})},showinfo:{text:"正在加载内容页...",title:"内容页",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){return{successfn:function(b,c,e,d){console.log(typeof b);if(a.checkupdate)return{pid:a.pid,cid:"1",title:"全1话"};d=[];d[0]=additemlist({id:0,newest:a.newest&&0==e,pid:a.pid,cid:"1",title:"全1话",count:1,reverse:0});return d},afterfn:function(){a.checkupdate||ExView.workers.content.infofinder(a)}}},
infoloader:function(a){return!1},infofinder:function(a){console.log(a);return!1}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+a.pid+"/",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"正在加载图片信息...",title:"图片",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){console.log(a);return{reg:/data-original="((?!\").*?)"/g,str:a.result,find:"$1",successfn:function(b,
c,e,d){array_count(d)?(console.log(d),a.download?chapterpredownload({source:d,download:a.download,plugin:a.plugin}):chapterviewer({source:d,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.download?chapterpredownload({error:"解析错误！",download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("图片信息获取失败！","ExView"));return!0}}}},commentflag:{loader:!1,
finder:!1},previewflag:{loader:!1,finder:!1,more:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+(1<parseInt(a.page)?"page/"+a.page+"/":""),method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));b&&plugfns(a.plugin).pagedeal(b,a)}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"cosplay/"+(1<parseInt(a.page)?"page/"+a.page+"/":""),method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));b&&plugfns(a.plugin).pagedeal(b,a)}}}}},fns:{pagecountrule:/title='最后页'>(\d+)<\/a>/g,pagecountfind:"$1",pagerule:/class="pin-coat"(.*?)<\/div>/g,pagefind:"$1",pagedeal:function(a,
b){b=b||{};var c=getstr(/mflikes\('(\d+)'/,a),e=getstr(/class='bg'>((?!<).*?)</,a),d=getstr(/original='((?!\').*?)'/,a),f=getstr(/class="timer"><em><\/em><span>((?!<).*?)</,a);if(b.multupdate)return b.multupdate(obj_contact(b,{pid:c,img:d,title:e,content:f})),!1;if(b.multhot)return b.multhot(obj_contact(b,{pid:c,img:d,title:e,content:f})),!1;if(b.multsearch)return b.multsearch(obj_contact(b,{pid:c,img:d,title:e,content:f})),!1;addcardlist({pid:c,title:e,name:e,img:d,content:"",stitle:f,comment:0,
preview:0,extrabutton:""})}}});
