ExView.Plugins({info:{name:"看漫漫画",version:"2.2",author:"Gentle",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAFySURBVDhPnZNLSwJRHMXHb9WiIuixaRN9gx6WE4RSOgvTFkEELdr0FSIid1G0aVMGPaiEiAQjtGhwLCITp3nP6d7bqNy8hHbgMHfO/9zfcC+MRGUp8qmtyOjGZM8R22wqck5U6MQEciKJBt2YB6RiaMhYmOGKDVXj81zOAdzD/aAGqKl0q7i2HKRA7fiklRNzAOh6UAPsstbM/eJjkBK5bjOn5gG/ZMYjwrwenRYAlqJs6Jsm6ls7bK2GJ2Anf3Kq2sYm4Dh4nppsB7iZbVaqpldQGRrFRyIJ/ewcXu4aXuUVWt8wrKsb1nnfzbQDvFKJDbX+EZR7BmDsHbB3JtPC5+o6tN5Bdk/ui9oOcAoPQZvI94OFWLRrLM7yAHo22A6s23t2D1Qe+Zqvf7E1lXWXh1t5IwMPeizMA2xlDno2C98wSNMmMGL6ZLaY2QVfXKIwPhbs4QD/s2Qn5CfRoBOTnykvkaOFTCWiigp/OiEXAYS+AVFuI+P1o0fSAAAAAElFTkSuQmCC",
db:"kmmh",apihost:"https://api.yyhao.com/",pagetitle:["<br>","收藏","首页","类型","下载"],download:!0,lazyload:!0,setting:!0,theme:"deeporange",cdn:""},set:function(a){},unset:function(a){},init:function(a){ExView.workers.fav.listloader({callback:function(){}})},flags:{indexflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"app_api/v2/getrecommend/",method:"GET",timeout:120,successfn:function(b,c){a.callback({img:pluginfo(a.plugin).icon,multpage:!0,result:b,
header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){b=(b||{}).data;array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:function(a){return{successfn:function(b){a.callback({pagecount:-1})}}}},typeflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"app_api/v2/getconfig/",method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){a.callback({title:"首页",img:pluginfo(a.plugin).icon,
group:{name:"daohang",title:"导航"},content:"首页"});a.callback({tid:"",title:"更新",listflag:"app_api/v2/getsortlist/?comic_sort=lianzai&page={{page}}&orderby=date&search_key=",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"更新"});a.callback({tid:"",title:"排行",listflag:"app_api/v2/getsortlist/?comic_sort=wanjie&page={{page}}&orderby=score&search_key=",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},
content:"排行"});return{json:!0,str:a.result,successfn:function(b){b=(b||{}).comic_sort||[];array_count(b)&&b.forEach(function(b){var d=b.sort_group,f="s"+stringToHex(d),e;for(e in b.data)a.callback({tid:e,title:b.data[e],img:"http://image.jjmh.com/file/kanmanhua_images/sort/"+e+".png",group:{name:f,title:d},content:b.data[e]})})}}}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+(a.flag?a.flag.replace("{{page}}",a.page||1):"app_api/v2/getsortlist/?comic_sort="+a.tid+"&page="+
(a.page||1)+"&orderby=click&search_key="),method:"GET",timeout:120,successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){b=(b||{}).data;array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:function(a){return{json:!0,str:a.result,successfn:function(b){try{b=(b||{}).page;var c=b.total_page||0}catch(d){c=-1}a.callback({pagecount:c})}}}},searchflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"app_api/v2/getsortlist/?comic_sort=&page="+(a.page||1)+"&orderby=click&search_key="+encodeURIComponent(a.keyword),method:"GET",timeout:120,successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){b=(b||{}).data;array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:function(a){return{json:!0,str:a.result,successfn:function(b){try{b=(b||{}).page;var c=b.total_page||0}catch(d){c=-1}a.callback({pagecount:c})}}}},
contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"app_api/v4/getcomicinfo/?comic_id="+a.pid,method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b,c,d,f){b=b.comic_chapter;if(array_count(b)){if(a.checkupdate){c=b[0].chapter_type;try{b=b[0].chapter_list[0]}catch(h){b={}}var e=stringToHex(nativeConvertAscii(JSON.stringify(b.chapter_source[0])));a.callback({pid:a.pid,cid:e,title:b.title+
"("+b.chapter_source[0].end_num+"P)_"+c});return!0}f=[];var g=0;d=0;g=b.length;b.forEach(function(b){var c=[{site_id:-1,rule:b.rule,start_num:b.start_num,end_num:b.end_num,chapter_domain:b.chapter_domain}];b=b.chapter_name+"("+(c[0].end_num-c[0].start_num+1)+"P)";c=stringToHex(nativeConvertAscii(JSON.stringify(c[0])));f[d]=a.callback({id:g-d-1,newest:a.newest&&0==d,pid:a.pid,cid:c,title:b,count:g,reverse:1});d++});return f}a.callback()}}},infoloader:!1,infofinder:function(a){return{json:!0,str:a.result,
successfn:function(b,c,d,f){c="http://image.jjmh.com/mh/"+a.pid+".jpg";d=b.comic_name;f=getLocalTime(1E3*parseInt(b.update_time));var e=b.comic_author,g,h=[];for(g in b.comic_type)h.push(b.comic_type[g]);g=h.join(",");h=b.comic_desc;b=b.comic_status;a.callback({name:d,img:c,added:a.data,description:"<p>"+(e?"【作者】"+e+"<br>":"")+(g?"【类型】"+g+"<br>":"")+(f?"【"+(b?"连载":"完结")+"】"+f+"<br>":"")+(h?"【简介】"+h:"")+"</p>",
comment:1,preview:0,tags:gettag(d)+gettag((e||"").split(" "))+gettag((g||"").split(","))});return!0}}}},parseflag:{loader:function(a){var b=JSON.parse(litehextostring(a.cid)),c={};-1!=b.site_id&&(c={url:pluginfo(a.plugin).apihost+"static/"+b.site_id+".js",method:"GET",timeout:120});c.successfn=function(c,f){a.callback({config:b,result:c,header:f})};return c},finder:function(a){return{successfn:function(b,c,d,f){b=[];switch(String(a.config.site_id)){case "-1":for(d=a.config.start_num;d<a.config.end_num+
1;d++)b.push("http://mhpic."+(a.config.chapter_domain||"jjmh.com")+(a.config.rule||"").replace("$$",d)+"-kmw.middle");break;default:ExView.fw.alert("暂不支持此来源！")}array_count(b)?a.download?a.callback({source:b,download:a.download,plugin:a.plugin}):a.callback({source:b,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title}):a.callback();return!0}}}},commentflag:{loader:function(a){return{url:1==parseInt(a.page||1)?"http://changyan.sohu.com/api/2/topic/load?client_id=cysGR3Ozm&topic_url=%20&page_size=30&hot_size=0&topic_source_id=comic"+
a.pid:"http://changyan.sohu.com/api/2/topic/comments?client_id=cysGR3Ozm&page_size=30&topic_id="+a.sid+"&page_no="+(a.page+1),method:"GET",timeout:120,successfn:function(b,c){if(b){var d={};1==parseInt(a.page||1)&&(d=JSON.parse(b));a.callback&&a.callback({result:b,header:c,sid:d.topic_id||a.sid,commentbrowser:!1})}else a.callback&&a.callback()}}},finder:function(a){console.log(a);return{json:!0,str:a.result,successfn:function(b,c,d,f){if(array_count(b)){c=b.comments;b=b.total_page_no;for(var e in c)a.callback&&
a.callback({page:a.page||1,pagecount:b,comment:{text:c[e].content,name:c[e].passport.nickname,avatar:c[e].passport.img_url,type:"received",label:(new Date(parseInt(c[e].create_time))).toLocaleString().replace(/:\d{1,2}$/," "),day:"",time:"",reverse:1,extra:""}})}}}},send:!1},previewflag:{loader:!1,finder:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"app_api/v2/getsortlist/?comic_sort=lianzai&page="+(a.page||1)+"&orderby=date&search_key=",method:"GET",
timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){b=(b||{}).data;array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"app_api/v2/getsortlist/?comic_sort=wanjie&page="+(a.page||1)+"&orderby=score&search_key=",method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,
successfn:function(b){b=(b||{}).data;array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}}}},fns:{pagedeal:function(a,b){b=b||{};a.forEach(function(a){var d=a.comic_id,f="http://image.jjmh.com/mh/"+d+".jpg",e=a.comic_name;a=a.last_chapter_name?"更新至 "+a.last_chapter_name:"";if(b.multupdate||b.multhot||b.multsearch)return b.callback(obj_contact(b,{pid:d,img:f,title:e,content:a})),!1;b.callback({pid:d,title:e,img:f,stitle:""+d,content:a,comment:1})})}}});
