ExView.Plugins({info:{name:"快看漫画",version:"2.2",db:"kuaikan",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAnFBMVEX/1wQAAADyzAP/1wT/1wT/1wT/1wT/1wT/1wT/1wQ/NQH/1wQBAQAMCgEEAwDlwQPeuwNWSQE4LwERDgH1zwO9nwOnjQJzYQFkVAFdTgFTRgFIPAE/NQEWEgEfGgD70wPtyAPTsgPIqQOukwO4mwKghwKXfwJ3ZAIwKAEpIgHnwwPmwQPQrwPCpAO3mwKfhgKWfgKGcQJrWwJNQQHR1EIuAAAAC3RSTlP8APz1yQbOzG5qGhDT28gAAACYSURBVBjTbc5HFoMwDARQEUKaXLBNL6a39HL/uwV2QDIr6b9ZDBh7nOcER1wGzDXAD2QVeu502jnmhQPA1Vm8PJ6otMaAXACeRDJGyoT2d/5JETZUlSqifk9SJmQ8QkAHIqOQUClQdwhg06vuhkT7jxjftwlYG9ks9MMgdog3AhdNjU3rVm6BTvZn2HYN1vLfgWHNOubB+AKbMhAx68A/mQAAAABJRU5ErkJggg==",
apihost:"http://m.kuaikanmanhua.com/",pagetitle:["<br>","收藏","首页","类型","下载"],lazyload:!0,vphotomode:!0,theme:"amber",download:!0,setting:!0,cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){ExView.workers.index.loader();ExView.workers.type.loader()}})},flags:{indexflag:{loader:function(a){a.front||a.page||addtypelist('<div align="center" class="list-block"><img src="img/logo.png"/><br>类型<br>正在加载...<div class="progress"></span></div>',
2);return{url:pluginfo(a.plugin).apihost,method:"GET",timeout:120,successfn:function(b,c){ExView.workers.index.countfinder(obj_contact(a,{result:b,header:c}));a.front||a.page||ExView.workers.type.finder({result:b,plugin:a.plugin});a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),name:"首页",title:a.title,img:a.img}}},finder:function(a){return{reg:/<a href="\/mobile\/(\d+)\/(?!>).*?>(.*?)<\/a>/g,str:getresult(a.result),
find:"$1{{separator}}$2",successfn:function(a){a=a.split("{{separator}}");if(array_count(a)){var c=a[0],d=getstr(/<img\s*src="((?!\").*?)"/,a[1]);a=getstr(/alt="((?!\").*?)"/,a[1])||getstr(/<\/span>((?!<).*?)<\/h2>/,a[1]);addcardlist({pid:c,title:a,name:a,img:d,content:"",comment:0})}else addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',2)},errorfn:function(){a.page||setnowlistname("首页","",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();
mySession.isloading=0;ExView.fw.alert("网络错误！","ExView")}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="-1|首页|index";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},typeflag:{loader:function(a){return{successfn:function(){ExView.workers.index.loader()}}},finder:function(a){addtypelist({title:"首页",img:pluginfo(a.plugin).icon,content:"首页"});return{reg:/\/mobile\/category\/result\?tag=((?!\").*?)".*?<img\s*src="((?!\").*?)".*?<p>((?!<).*?)<\/p>/g,
str:getresult(a.result),find:"$1{{separator}}$2{{separator}}$3",successfn:function(a){a=a.split("{{separator}}");if(array_count(a)){var c=a[2];addtypelist({tid:a[0],title:c,img:a[1],listbg:!0,content:c})}else addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>加载失败，请刷新重试！</a></div>',2)}}}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"mobile/category/result?page="+(a.page||1)+"&limit=20&tag="+a.keyword,method:"GET",timeout:120,successfn:function(b,c){b?(ExView.workers.list.countfinder(obj_contact(a,{result:b,header:c})),a.successfn&&a.successfn({result:b,header:c})):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+a.title+"】<br>获取失败！","ExView"))},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),title:a.title,name:"【"+a.title+"】",
img:a.img}}},finder:function(a){return 1==parseInt(a.page||1)?{reg:/<li>(.*?)<\/li>/g,str:getresult(a.result),find:"$1",successfn:function(b){if(b){var c=getstr(/\/mobile\/(\d+)\/list/,b),d=getstr(/<img\s*src="((?!\").*?)"/,b),e=getstr(/class="rb-title(?!\").*?>((?!<).*?)<\/p>/,b);b=getstr(/class="rb-author(?!\").*?>((?!<).*?)<\/p>/,b);plugfns(a.plugin).pagedeal({pid:c,img:d,title:e,stitle:b,content:""})}else addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',
1)}}:{json:!0,str:a.result,successfn:function(b){b=b.data.topic_category;if(array_count(b))return b.forEach(function(b){var d=b.id,e=b.cover_image_url,f=b.title,g=b.user.nickname;b=b.description;plugfns(a.plugin).pagedeal({pid:d,img:e,title:f,stitle:g,content:b})}),!0;addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="0|"+
a.keyword+"|list";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},searchflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"mobile/search/result",method:"POST",data:"page="+(a.page||1)+"&limit=20&keyword="+encodeURIComponent(a.keyword),timeout:120,header:{"content-type":"application/x-www-form-urlencoded"},successfn:function(b,c){b?(a.multsearch||(ExView.workers.search.countfinder(obj_contact(a,{result:b,header:c})),setnowlistname("搜索【"+a.keyword+
"】")),a.successfn&&a.successfn({result:b,header:c})):a.multsearch?a.multsearch():(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+a.keyword+"】<br>获取搜索结果失败！","ExView"))},showinfo:{text:"正在搜索..."+(1<a.page?"<br>第"+a.page+"页":""),name:"【"+a.keyword+"】",title:"搜索"}}},finder:function(a){return 1==parseInt(a.page||1)?{reg:/<li>(.*?)<\/li>/g,str:getresult(a.result),find:"$1",
successfn:function(b){if(b){var c=getstr(/\/mobile\/(\d+)\/list/,b),d=getstr(/<img\s*src="((?!\").*?)"/,b),e=getstr(/class="rb-title(?!\").*?>((?!<).*?)<\/p>/,b);b=getstr(/class="rb-author(?!\").*?>((?!<).*?)<\/p>/,b);plugfns(a.plugin).pagedeal({pid:c,img:d,title:e,stitle:b,content:""},a)}else a.multsearch?a.multsearch():addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}:{json:!0,str:a.result,successfn:function(b){b=b.data.search_ret;
if(array_count(b))return b.forEach(function(b){var d=b.id,e=b.cover_image_url,f=b.title,g=b.user.nickname;b=b.description;plugfns(a.plugin).pagedeal({pid:d,img:e,title:f,stitle:g,content:b})}),!0;a.multsearch?a.multsearch():addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(b){mySession.nowlistpages="0|"+a.keyword+"|search";mySession.nowlistpage=1;
console.log(mySession.nowlistpages)}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"mobile/"+a.pid+"/list",method:"GET",timeout:120,successfn:function(b,c){b?a.successfn&&a.successfn({catalog:b,header:c,result:b}):a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},showinfo:{text:"正在加载内容页...",title:"内容页",name:getlistname(a.pid),img:getlistimg(a.pid)}}},
finder:function(a){return{reg:/<li>(.*?)<\/li>/g,str:getresult(a.result),find:"$1",successfn:function(b,c,d,e){if(array_count(c)){if(a.checkupdate)return f=e[c.length-2],g=getstr(/\/mobile\/comics\/(\d+)"/,f),f=getstr(/<p\s*class="overhidden">((?!<).*?)</,f),{pid:a.pid,cid:g,title:f};b=[];for(d=0;d<e.length;d++){var f=e[d],g=getstr(/\/mobile\/comics\/(\d+)"/,f),f=getstr(/<p\s*class="overhidden">((?!<).*?)</,f);g&&(b[d]=additemlist({id:d,newest:a.newest&&0==d,pid:a.pid,cid:g,title:f,count:c,reverse:0}))}return b}a.checkupdate||
(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},afterfn:function(){a.checkupdate||ExView.workers.content.infofinder(a)}}},infoloader:function(a){return!1},infofinder:function(a){console.log(a);return!1}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"mobile/comics/"+a.cid,method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"正在加载图片信息...",
title:"图片",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){console.log(a);return{reg:/<img\s*class="lazy"\s*src="((?!\").*?)"/g,str:a.result,find:"$1",successfn:function(b,c,d,e){array_count(e)?(console.log(e),a.download?chapterpredownload({source:e,download:a.download,plugin:a.plugin}):chapterviewer({source:e,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.download?chapterpredownload({error:"解析错误！",
download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("图片信息获取失败！","ExView"));return!0}}}},commentflag:{loader:!1,finder:!1},previewflag:{loader:!1,finder:!1,more:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"mobile/category/result?page="+(a.page||1)+"&limit=20&tag=%E4%BC%98%E7%A7%80%E6%96%B0%E8%BF%9E%E8%BD%BD",method:"GET",timeout:120,successfn:function(b,
c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return 1==parseInt(a.page||1)?{reg:/<li>(.*?)<\/li>/g,str:getresult(a.result),find:"$1",successfn:function(b){if(b){var c=getstr(/\/mobile\/(\d+)\/list/,b),d=getstr(/<img\s*src="((?!\").*?)"/,b),e=getstr(/class="rb-title(?!\").*?>((?!<).*?)<\/p>/,b);b=getstr(/class="rb-author(?!\").*?>((?!<).*?)<\/p>/,b);plugfns(a.plugin).pagedeal({pid:c,img:d,title:e,stitle:b,content:""},a)}else a.multupdate()}}:{json:!0,str:a.result,successfn:function(b){b=
b.data.topic_category;if(array_count(b))return b.forEach(function(b){var d=b.id,e=b.cover_image_url,f=b.title,g=b.user.nickname;b=b.description;plugfns(a.plugin).pagedeal({pid:d,img:e,title:f,stitle:g,content:b},a)}),!0;a.multupdate()}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"mobile/category/result?page="+(a.page||1)+"&limit=20&tag=%E7%9F%AD%E7%AF%87",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return 1==
parseInt(a.page||1)?{reg:/<li>(.*?)<\/li>/g,str:getresult(a.result),find:"$1",successfn:function(b){if(b){var c=getstr(/\/mobile\/(\d+)\/list/,b),d=getstr(/<img\s*src="((?!\").*?)"/,b),e=getstr(/class="rb-title(?!\").*?>((?!<).*?)<\/p>/,b);b=getstr(/class="rb-author(?!\").*?>((?!<).*?)<\/p>/,b);plugfns(a.plugin).pagedeal({pid:c,img:d,title:e,stitle:b,content:""},a)}else a.multhot()}}:{json:!0,str:a.result,successfn:function(b){b=b.data.topic_category;if(array_count(b))return b.forEach(function(b){var d=
b.id,e=b.cover_image_url,f=b.title,g=b.user.nickname;b=b.description;plugfns(a.plugin).pagedeal({pid:d,img:e,title:f,stitle:g,content:b},a)}),!0;a.multhot()}}}}},fns:{pagedeal:function(a,b){b=b||{};var c=a.pid,d=a.title,e=a.img,f=a.stitle;if(b.multupdate)return b.multupdate(obj_contact(b,{pid:c,img:e,title:d,content:f})),!1;if(b.multhot)return b.multhot(obj_contact(b,{pid:c,img:e,title:d,content:f})),!1;if(b.multsearch)return b.multsearch(obj_contact(b,{pid:c,img:e,title:d,content:f})),!1;addcardlist({pid:c,
title:d,img:e,stitle:f,content:a.content||"",comment:0})}}});
