ExView.Plugins({info:{name:"\u5feb\u770b\u6f2b\u753b",version:"2.2",db:"kuaikan",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAnFBMVEX/1wQAAADyzAP/1wT/1wT/1wT/1wT/1wT/1wT/1wQ/NQH/1wQBAQAMCgEEAwDlwQPeuwNWSQE4LwERDgH1zwO9nwOnjQJzYQFkVAFdTgFTRgFIPAE/NQEWEgEfGgD70wPtyAPTsgPIqQOukwO4mwKghwKXfwJ3ZAIwKAEpIgHnwwPmwQPQrwPCpAO3mwKfhgKWfgKGcQJrWwJNQQHR1EIuAAAAC3RSTlP8APz1yQbOzG5qGhDT28gAAACYSURBVBjTbc5HFoMwDARQEUKaXLBNL6a39HL/uwV2QDIr6b9ZDBh7nOcER1wGzDXAD2QVeu502jnmhQPA1Vm8PJ6otMaAXACeRDJGyoT2d/5JETZUlSqifk9SJmQ8QkAHIqOQUClQdwhg06vuhkT7jxjftwlYG9ks9MMgdog3AhdNjU3rVm6BTvZn2HYN1vLfgWHNOubB+AKbMhAx68A/mQAAAABJRU5ErkJggg==",
apihost:"http://m.kuaikanmanhua.com/",pagetitle:["<br>","\u6536\u85cf","\u9996\u9875","\u7c7b\u578b","\u4e0b\u8f7d"],lazyload:!0,vphotomode:!0,theme:"amber",download:!0,setting:!0,cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){ExView.workers.index.loader();ExView.workers.type.loader()}})},flags:{indexflag:{loader:function(a){a.front||a.page||addtypelist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u7c7b\u578b<br>\u6b63\u5728\u52a0\u8f7d...<div class="progress"></span></div>',
2);return{url:pluginfo(a.plugin).apihost,method:"GET",timeout:120,successfn:function(b,c){ExView.workers.index.countfinder(obj_contact(a,{result:b,header:c}));a.front||a.page||ExView.workers.type.finder({result:b,plugin:a.plugin});a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"\u6b63\u5728\u52a0\u8f7d..."+(1<a.page?"<br>\u7b2c"+a.page+"\u9875":""),name:"\u9996\u9875",title:a.title,img:a.img}}},finder:function(a){return{reg:/<a href="\/mobile\/(\d+)\/(?!>).*?>(.*?)<\/a>/g,str:getresult(a.result),
find:"$1{{separator}}$2",successfn:function(a){a=a.split("{{separator}}");if(array_count(a)){var c=a[0],d=getstr(/<img\s*src="((?!\").*?)"/,a[1]);a=getstr(/alt="((?!\").*?)"/,a[1])||getstr(/<\/span>((?!<).*?)<\/h2>/,a[1]);addcardlist({pid:c,title:a,name:a,img:d,content:"",comment:0})}else addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u6ca1\u6709\u5185\u5bb9</div>',2)},errorfn:function(){a.page||setnowlistname("\u9996\u9875","",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();
mySession.isloading=0;ExView.fw.alert("\u7f51\u7edc\u9519\u8bef\uff01","ExView")}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="-1|\u9996\u9875|index";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},typeflag:{loader:function(a){return{successfn:function(){ExView.workers.index.loader()}}},finder:function(a){addtypelist({title:"\u9996\u9875",img:pluginfo(a.plugin).icon,content:"\u9996\u9875"});return{reg:/\/mobile\/category\/result\?tag=((?!\").*?)".*?<img\s*src="((?!\").*?)".*?<p>((?!<).*?)<\/p>/g,
str:getresult(a.result),find:"$1{{separator}}$2{{separator}}$3",successfn:function(a){a=a.split("{{separator}}");if(array_count(a)){var c=a[2];addtypelist({tid:a[0],title:c,img:a[1],listbg:!0,content:c})}else addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>\u52a0\u8f7d\u5931\u8d25\uff0c\u8bf7\u5237\u65b0\u91cd\u8bd5\uff01</a></div>',2)}}}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"mobile/category/result?page="+(a.page||1)+"&limit=20&tag="+a.keyword,method:"GET",timeout:120,successfn:function(b,c){b?(ExView.workers.list.countfinder(obj_contact(a,{result:b,header:c})),a.successfn&&a.successfn({result:b,header:c})):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u3010"+a.title+"\u3011<br>\u83b7\u53d6\u5931\u8d25\uff01","ExView"))},showinfo:{text:"\u6b63\u5728\u52a0\u8f7d..."+(1<a.page?"<br>\u7b2c"+a.page+"\u9875":""),title:a.title,name:"\u3010"+a.title+"\u3011",
img:a.img}}},finder:function(a){return 1==parseInt(a.page||1)?{reg:/<li>(.*?)<\/li>/g,str:getresult(a.result),find:"$1",successfn:function(b){if(b){var c=getstr(/\/mobile\/(\d+)\/list/,b),d=getstr(/<img\s*src="((?!\").*?)"/,b),e=getstr(/class="rb-title(?!\").*?>((?!<).*?)<\/p>/,b);b=getstr(/class="rb-author(?!\").*?>((?!<).*?)<\/p>/,b);plugfns(a.plugin).pagedeal({pid:c,img:d,title:e,stitle:b,content:""})}else addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u6ca1\u6709\u5185\u5bb9</div>',
1)}}:{json:!0,str:a.result,successfn:function(b){b=b.data.topic_category;if(array_count(b))return b.forEach(function(b){var d=b.id,e=b.cover_image_url,f=b.title,g=b.user.nickname;b=b.description;plugfns(a.plugin).pagedeal({pid:d,img:e,title:f,stitle:g,content:b})}),!0;addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u6ca1\u6709\u5185\u5bb9</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="0|"+
a.keyword+"|list";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},searchflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"mobile/search/result",method:"POST",data:"page="+(a.page||1)+"&limit=20&keyword="+encodeURIComponent(a.keyword),timeout:120,header:{"content-type":"application/x-www-form-urlencoded"},successfn:function(b,c){b?(a.multsearch||(ExView.workers.search.countfinder(obj_contact(a,{result:b,header:c})),setnowlistname("\u641c\u7d22\u3010"+a.keyword+
"\u3011")),a.successfn&&a.successfn({result:b,header:c})):a.multsearch?a.multsearch():(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u3010"+a.keyword+"\u3011<br>\u83b7\u53d6\u641c\u7d22\u7ed3\u679c\u5931\u8d25\uff01","ExView"))},showinfo:{text:"\u6b63\u5728\u641c\u7d22..."+(1<a.page?"<br>\u7b2c"+a.page+"\u9875":""),name:"\u3010"+a.keyword+"\u3011",title:"\u641c\u7d22"}}},finder:function(a){return 1==parseInt(a.page||1)?{reg:/<li>(.*?)<\/li>/g,str:getresult(a.result),find:"$1",
successfn:function(b){if(b){var c=getstr(/\/mobile\/(\d+)\/list/,b),d=getstr(/<img\s*src="((?!\").*?)"/,b),e=getstr(/class="rb-title(?!\").*?>((?!<).*?)<\/p>/,b);b=getstr(/class="rb-author(?!\").*?>((?!<).*?)<\/p>/,b);plugfns(a.plugin).pagedeal({pid:c,img:d,title:e,stitle:b,content:""},a)}else a.multsearch?a.multsearch():addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u6ca1\u6709\u5185\u5bb9</div>',1)}}:{json:!0,str:a.result,successfn:function(b){b=b.data.search_ret;
if(array_count(b))return b.forEach(function(b){var d=b.id,e=b.cover_image_url,f=b.title,g=b.user.nickname;b=b.description;plugfns(a.plugin).pagedeal({pid:d,img:e,title:f,stitle:g,content:b})}),!0;a.multsearch?a.multsearch():addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u6ca1\u6709\u5185\u5bb9</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(b){mySession.nowlistpages="0|"+a.keyword+"|search";mySession.nowlistpage=1;
console.log(mySession.nowlistpages)}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"mobile/"+a.pid+"/list",method:"GET",timeout:120,successfn:function(b,c){b?a.successfn&&a.successfn({catalog:b,header:c,result:b}):a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u5185\u5bb9\u9875\u83b7\u53d6\u5931\u8d25\uff01","ExView"))},showinfo:{text:"\u6b63\u5728\u52a0\u8f7d\u5185\u5bb9\u9875...",title:"\u5185\u5bb9\u9875",name:getlistname(a.pid),img:getlistimg(a.pid)}}},
finder:function(a){return{reg:/<li>(.*?)<\/li>/g,str:getresult(a.result),find:"$1",successfn:function(b,c,d,e){if(array_count(c)){if(a.checkupdate)return f=e[c.length-2],g=getstr(/\/mobile\/comics\/(\d+)"/,f),f=getstr(/<p\s*class="overhidden">((?!<).*?)</,f),{pid:a.pid,cid:g,title:f};b=[];for(d=0;d<e.length;d++){var f=e[d],g=getstr(/\/mobile\/comics\/(\d+)"/,f),f=getstr(/<p\s*class="overhidden">((?!<).*?)</,f);g&&(b[d]=additemlist({id:d,newest:a.newest&&0==d,pid:a.pid,cid:g,title:f,count:c,reverse:0}))}return b}a.checkupdate||
(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u5185\u5bb9\u9875\u83b7\u53d6\u5931\u8d25\uff01","ExView"))},afterfn:function(){a.checkupdate||ExView.workers.content.infofinder(a)}}},infoloader:function(a){return!1},infofinder:function(a){console.log(a);return!1}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"mobile/comics/"+a.cid,method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"\u6b63\u5728\u52a0\u8f7d\u56fe\u7247\u4fe1\u606f...",
title:"\u56fe\u7247",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){console.log(a);return{reg:/<img\s*class="lazy"\s*src="((?!\").*?)"/g,str:a.result,find:"$1",successfn:function(b,c,d,e){array_count(e)?(console.log(e),a.download?chapterpredownload({source:e,download:a.download,plugin:a.plugin}):chapterviewer({source:e,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.download?chapterpredownload({error:"\u89e3\u6790\u9519\u8bef\uff01",
download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u56fe\u7247\u4fe1\u606f\u83b7\u53d6\u5931\u8d25\uff01","ExView"));return!0}}}},commentflag:{loader:!1,finder:!1},previewflag:{loader:!1,finder:!1,more:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"mobile/category/result?page="+(a.page||1)+"&limit=20&tag=%E4%BC%98%E7%A7%80%E6%96%B0%E8%BF%9E%E8%BD%BD",method:"GET",timeout:120,successfn:function(b,
c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return 1==parseInt(a.page||1)?{reg:/<li>(.*?)<\/li>/g,str:getresult(a.result),find:"$1",successfn:function(b){if(b){var c=getstr(/\/mobile\/(\d+)\/list/,b),d=getstr(/<img\s*src="((?!\").*?)"/,b),e=getstr(/class="rb-title(?!\").*?>((?!<).*?)<\/p>/,b);b=getstr(/class="rb-author(?!\").*?>((?!<).*?)<\/p>/,b);plugfns(a.plugin).pagedeal({pid:c,img:d,title:e,stitle:b,content:""},a)}else a.multupdate()}}:{json:!0,str:a.result,successfn:function(b){b=
b.data.topic_category;if(array_count(b))return b.forEach(function(b){var d=b.id,e=b.cover_image_url,f=b.title,g=b.user.nickname;b=b.description;plugfns(a.plugin).pagedeal({pid:d,img:e,title:f,stitle:g,content:b},a)}),!0;a.multupdate()}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"mobile/category/result?page="+(a.page||1)+"&limit=20&tag=%E7%9F%AD%E7%AF%87",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return 1==
parseInt(a.page||1)?{reg:/<li>(.*?)<\/li>/g,str:getresult(a.result),find:"$1",successfn:function(b){if(b){var c=getstr(/\/mobile\/(\d+)\/list/,b),d=getstr(/<img\s*src="((?!\").*?)"/,b),e=getstr(/class="rb-title(?!\").*?>((?!<).*?)<\/p>/,b);b=getstr(/class="rb-author(?!\").*?>((?!<).*?)<\/p>/,b);plugfns(a.plugin).pagedeal({pid:c,img:d,title:e,stitle:b,content:""},a)}else a.multhot()}}:{json:!0,str:a.result,successfn:function(b){b=b.data.topic_category;if(array_count(b))return b.forEach(function(b){var d=
b.id,e=b.cover_image_url,f=b.title,g=b.user.nickname;b=b.description;plugfns(a.plugin).pagedeal({pid:d,img:e,title:f,stitle:g,content:b},a)}),!0;a.multhot()}}}}},fns:{pagedeal:function(a,b){b=b||{};var c=a.pid,d=a.title,e=a.img,f=a.stitle;if(b.multupdate)return b.multupdate(obj_contact(b,{pid:c,img:e,title:d,content:f})),!1;if(b.multhot)return b.multhot(obj_contact(b,{pid:c,img:e,title:d,content:f})),!1;if(b.multsearch)return b.multsearch(obj_contact(b,{pid:c,img:e,title:d,content:f})),!1;addcardlist({pid:c,
title:d,img:e,stitle:f,content:a.content||"",comment:0})}}});
