ExView.Plugins({info:{name:"酷克漫画",version:"2.2",author:"黑色的月牙",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAV1BMVEX9/f3x/v74+Pj///////81NTU4ODiqqqqSkpJkZGROTk6YmJh5eXlvb29ERETh4eLU1NTKysrIyMjCwsK6uruioqKMjIyCgoKBgYF+fn5eXl5bW1w9PT1Hl1BQAAAABHRSTlP+EyoF1EsigAAAAHFJREFUGNNVjlkOg0AMQ0NrzwKUtuzb/c+JgmaiwR+W/aJIlhceqkT9NgKWAYdzLUCsXUfAgKfqCDGDWvuoIQF2O++POQEtH6hlwODdF/i3CWxUuYaD7Yhky0mKYSSXcmkg2ZfgJ40tzcynLpW6XeV9AfnxBXBGQOK+AAAAAElFTkSuQmCC",
db:"kuke",apihost:"http://121.41.65.66:88/comics/",pagetitle:["<br>","收藏","全部","类型","下载"],download:!0,lazyload:!0,setting:!0,theme:"black",cdn:""},set:function(a){},unset:function(a){},init:function(a){ExView.workers.fav.listloader({callback:function(){}})},flags:{indexflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"?page="+(a.page||1)+"&sign=dcf692dc1d4cead44ce1d5d1b9409e26",method:"GET",timeout:120,successfn:function(b,c){a.callback({img:pluginfo(a.plugin).icon,
multpage:!0,result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){b=(b||{}).entries;array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:function(a){return{json:!0,str:a.result,successfn:function(b){try{b=(b=(b||{}).total_pages)||-1}catch(c){b=-1}a.callback({pagecount:b})}}}},typeflag:{loader:!1,finder:function(a){a.callback({title:"全部",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"全部"});
a.callback({title:"热门",listflag:"features",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"热门"});"竞技 热血 高清单行 职场 冒险 魔法 萌系 生活 爱情 校园 神鬼 悬疑 治愈 欢乐向 耽美 科幻 伪娘 后宫 宅系 侦探 性转换 历史 机战 美食 百合 格斗 音乐舞蹈 战争 轻小说 搞笑 四格 西方魔幻 励志 欢乐向 颜艺 东方 其他 恐怖 武侠 奇幻 魔幻 仙侠".split(" ").forEach(function(b,
c){a.callback({tid:c+1,title:b,img:pluginfo(a.plugin).icon,group:{name:"fenlei",title:"分类"},content:b})})}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+(a.flag||"?q%5Btags_id_eq%5D="+a.tid+"&page="+(a.page||1))+"&sign=dcf692dc1d4cead44ce1d5d1b9409e26",method:"GET",timeout:120,successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){a.flag?(arr=[],b.slideshows.forEach(function(a){obj_contact(arr,
a.comics)}),b.subjects.forEach(function(a){obj_contact(arr,a.comics)})):b=(b||{}).entries;array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:function(a){return{json:!0,str:a.result,successfn:function(b){if(a.flag)var c=-1;else try{c=(b=(b||{}).total_pages)||-1}catch(d){c=-1}a.callback({pagecount:c})}}}},searchflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"?q[name_cont]="+encodeURIComponent(a.keyword)+"&page="+(a.page||1)+"&sign=dcf692dc1d4cead44ce1d5d1b9409e26",
method:"GET",timeout:120,successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){b=(b||{}).entries;array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:function(a){return{json:!0,str:a.result,successfn:function(b){try{b=(b=(b||{}).total_pages)||-1}catch(c){b=-1}a.callback({pagecount:b})}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+a.pid+"?sign=dcf692dc1d4cead44ce1d5d1b9409e26",
method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b,c,d,e){b=(b||{}).chapters;if(array_count(b)){if(a.checkupdate)return b=b.pop(),a.callback({pid:a.pid,cid:b.index,title:b.name}),!0;e=[];for(d=0;d<b.length;d++)e[d]=a.callback({id:d,newest:a.newest&&0==d,pid:a.pid,cid:b[d].index,title:b[d].name,count:b.length,reverse:0});return e}a.callback()}}},infoloader:!1,infofinder:function(a){return{json:!0,str:a.result,
successfn:function(b,c,d,e){c=b.cover;c=decodeURIComponent(c);-1!=(c||"").indexOf("images.dmzj.com")&&(c=getcoverload(c,{cacheheader:{Referer:"http://m.dmzj.com/"},nativeres:!0}));d=b.name;e=b.updated_date;var f=b.author,l=b.hot,g=(b.category||"").split(",").concat(b.tag_list||[]),h=b.description,k=b.status,m=b.source;myContent.mirrors=b.mirrors;myContent.moresource=function(){var a='<div class="list-block" style="margin:0"><ul class="videosourcecheck">'+myContent.mirrors.map(function(a,b){return'<li><label class="label-radio item-content"><input '+
(0==b?'checked="checked"':"")+' type="radio" name="my-radio" value="'+b+'"><div class="item-media"><i class="icon icon-form-radio"></i></div><div class="item-inner"><div class="item-title">'+gettext(a.source)+"</div></div></label></li>"}).join("")+"</ul></div>";ExView.fw.confirm(a,"更换来源",function(){var a="";$$(".videosourcecheck input").each(function(){$$(this).prop("checked")&&(a=$$(this).val())});a&&contentloader({plugin:myContent.plugin,pid:myContent.mirrors[a].id})})};a.callback({name:d,
img:c,added:a.data,description:"<p>"+(m?getboxitem("来源")+" "+m+"<br>":"")+(f?getboxitem("作者")+" "+f+"<br>":"")+(g?getboxitem("类型")+" "+g+"<br>":"")+(l?getboxitem("热度")+" "+l+"<br>":"")+(e?getboxitem("更新")+" "+e+"<br>":"")+(k?getboxitem("状态")+" "+k+"<br>":"")+(h?getboxitem("简介")+" "+h:"")+"</p>",more:'<a href="#" class="button button-fill color-brown" onclick="myContent.moresource()">更换来源</a>',comment:0,preview:0,
tags:gettag(d)+gettag(f)+gettag(g||"")});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+a.pid+"/"+a.cid+"?sign=dcf692dc1d4cead44ce1d5d1b9409e26",method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b,c,d,e){b=(b||{}).pages;array_count(b)?(b=b.map(function(a){a=a.track_url;a=decodeURIComponent(a);a=a.replace("tupianku.333dm.com","images.333dm.com");-1!=(a||"").indexOf("images.dmzj.com")&&
(a=getcommonload(a,{cacheheader:{Referer:"http://m.dmzj.com/"},nativeres:!0}));-1!=(a||"").indexOf("i.hamreus.com")&&(a=getcommonload(a,{cacheheader:{Referer:"http://m.ikanman.com/"},nativeres:!0}));return a}),a.download?a.callback({source:b,download:a.download,plugin:a.plugin}):a.callback({source:b,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.callback();return!0}}}},commentflag:{loader:!1,finder:!1,send:!1},previewflag:{loader:!1,finder:!1},
pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"?page="+(a.page||1)+"&sign=dcf692dc1d4cead44ce1d5d1b9409e26",method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){b=(b||{}).entries;array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"?page="+(a.page||1)+"&sign=dcf692dc1d4cead44ce1d5d1b9409e26",
method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){b=(b||{}).entries;array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}}}},fns:{pagedeal:function(a,b){b=b||{};a.forEach(function(a){var d=a.id,e=a.cover,e=decodeURIComponent(e);-1!=(e||"").indexOf("images.dmzj.com")&&(e=getcoverload(e,{cacheheader:{Referer:"http://m.dmzj.com/"},nativeres:!0}));var f=a.name,l=a.author,g=a.updated_date,h=a.status;
a=a.description;var k=(h?"【"+h+"】":"")+(g||"");if(b.multupdate||b.multhot||b.multsearch)return b.callback(obj_contact(b,{pid:d,img:e,title:f,content:k})),!1;b.callback({pid:d,title:f,img:e,stitle:l||"",content:getboxitem(h)+getboxitem(g)+a,comment:0})})}}});
