ExView.Plugins({info:{name:"酷漫漫画",version:"2.2",author:"Gentle",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAABj1BMVEX///86quE9reQUgsskkNIhi88XgMj///8Hf8gkk9QcjtEQh84JgcoDfMdpwu4ym9g6GQFNr+MhmNgaktUZi9ANhs0CesX//PlUtOY9pN47otsdldYXj9MUic4NhMsDeMUFd8SVz+5fu+qNw+lbuOhIrOExpeFEqd8sod03odsonts0ntokm9ormdcmldUfkNMVjNEYgssMfskTfMYNgMXopxz/5gn8zwf3ogP1qwDxowD49fPS4/Pe6vLY6PDO5O+83e6p1+5WvO7l7O1jvutHs+k8sOh2v+eMyuZRs+VEqeAPieD/+t6Syd10rdsVk9kbeNdsoNZ0q9Mzk9EMhdAlgMlOnMgdgMgNecUAdsNYobeYmJtll5v84pMVW4KoonCKbm9vbW21oWTUvV2pjFxwUVFORkl8UUfaqUPYljJGKiZPLiPrrCFWMCBjJxSdXBBZHw/4wgqtlgqZkgnJswi/rQbl2QPJngJxQgL5wwH82gD60wD4vwDmtgC9tQDlrACLhgDRhACPcACYYABYTQA9KSJlAAAAB3RSTlMBxL7LycXDXU9/8gAAAQBJREFUGNMdymOXAgEYQOG3Fo09jZFtt7Zt27a9P7xO9+NzLkAzPSp7KYrq97NKsgWgCY2w/l5PV2c3JYdooRUQVGV7XI3aBmjMAgJVOzakBoy7BjF3/Rgulqrbl9cHH683kl4Hfq3yy1zc3p+d/lekCTeQmztXDPP9WPxkmOe9IxvIw77yz9f7w93L01/1rURAftYaW906Pi8UTvbXp8vzkF+0BDrgpWQlabZndnEwptxGQmFHArEUIWJDGPDIJIElImoMNch0JshBPC3kTCGFYjgpcj49CmFNpBdIgkBIXPPhXBAcUd60PXPZ7NJMCNfCTgAHp4vIynLORnA+7oQaoYsstkTeq/MAAAAASUVORK5CYII=",
db:"kuman",apihost:"http://api.kuman.com/",pagetitle:["<br>","收藏","首页","类型","下载"],download:!0,lazyload:!0,setting:!0,cdn:""},set:function(b){},unset:function(b){},init:function(b){ExView.workers.fav.listloader({callback:function(){}})},flags:{indexflag:{loader:function(b){return{url:pluginfo(b.plugin).apihost+"main/config",method:"POST",timeout:120,successfn:function(a,c){b.callback({img:pluginfo(b.plugin).icon,multpage:!0,result:a,header:c})}}},finder:function(b){return{json:!0,
str:b.result,successfn:function(a){a=(a||{}).data;a=a.end_recommend_comic.concat(a.recommend_comic);array_count(a)?plugfns(b.plugin).pagedeal(a,b):b.callback()}}},countloader:!1,countfinder:function(b){return{json:!0,str:b.result,successfn:function(a){b.callback({pagecount:-1})}}}},typeflag:{loader:function(b){return{url:pluginfo(b.plugin).apihost+"category/categoryList",method:"POST",timeout:120,successfn:function(a,c){b.callback({result:a,header:c})}}},finder:function(b){b.callback({title:"首页",
img:pluginfo(b.plugin).icon,group:{name:"daohang",title:"导航"},content:"首页"});b.callback({tid:"-1",listflag:"comic/newComic",title:"新上架",img:pluginfo(b.plugin).icon,group:{name:"daohang",title:"导航"},content:"新上架"});b.callback({tid:"",listflag:"rank_id=1",title:"追漫最热榜 Top100",img:pluginfo(b.plugin).icon,group:{name:"daohang",title:"导航"},content:"追漫最热榜 Top100"});b.callback({tid:"",
listflag:"rank_id=2",title:"读者存留率 Top100",img:pluginfo(b.plugin).icon,group:{name:"daohang",title:"导航"},content:"读者存留率 Top100"});b.callback({tid:"",listflag:"rank_id=4",title:"本周潜力榜",img:pluginfo(b.plugin).icon,group:{name:"daohang",title:"导航"},content:"本周潜力榜"});b.callback({tid:"",listflag:"rank_id=5",title:"本周人气榜",img:pluginfo(b.plugin).icon,group:{name:"daohang",
title:"导航"},content:"本周人气榜"});return{json:!0,str:b.result,successfn:function(a){a=(a||{}).data||[];array_count(a)&&a.forEach(function(a){var e=a.category_type,f=a.category_label;a.category_list.forEach(function(a){b.callback({tid:e+"|"+a.category_id,title:a.category_name,img:pluginfo(b.plugin).icon,group:{name:e,title:f},content:a.category_name+"<br>("+a.total_comic+")"})})})}}}},listflag:{loader:function(b){var a={url:pluginfo(b.plugin).apihost+(b.flag?"rank/detail":
"category/comicList"),method:"POST",postform:!0,data:b.flag||"p="+(b.page||1)+"&limit=10&category_type="+(b.tid||"").split("|")[0]+"&category_id="+(b.tid||"").split("|")[1],timeout:120,successfn:function(a,e){b.callback({multpage:!0,result:a,header:e})}};-1==b.tid&&(a.url=pluginfo(b.plugin).apihost+b.flag,a.data="");return a},finder:function(b){return{json:!0,str:b.result,successfn:function(a){a=(a||{}).data;a=(a||{}).comic_list||(a||{}).new_comic;array_count(a)?plugfns(b.plugin).pagedeal(a,b):b.callback()}}},
countloader:!1,countfinder:function(b){return{json:!0,str:b.result,successfn:function(a){try{a=(a||{}).data;var c=a.page.total_page}catch(e){c=-1}b.callback({pagecount:c})}}}},searchflag:{loader:function(b){return{url:pluginfo(b.plugin).apihost+"search/comicOrAuthor",method:"POST",data:"p="+(b.page||1)+"&limit=10&keywords="+b.keyword,postform:!0,timeout:120,successfn:function(a,c){b.callback({multpage:!0,result:a,header:c})}}},finder:function(b){return{json:!0,str:b.result,successfn:function(a){a=
(a||{}).data;a=(a||{}).list;array_count(a)?plugfns(b.plugin).pagedeal(a,b):b.callback()}}},countloader:!1,countfinder:function(b){return{json:!0,str:b.result,successfn:function(a){try{a=(a=(a||{}).data)?0:-1}catch(c){a=-1}b.callback({pagecount:a})}}}},contentflag:{loader:function(b){return{url:pluginfo(b.plugin).apihost+"comic/detail",data:"source_id="+b.pid.split("_")[1]+"&comic_id="+b.pid.split("_")[0],method:"POST",postform:!0,timeout:120,successfn:function(a,c){b.callback({result:a,header:c})}}},
finder:function(b){return{json:!0,str:b.result,successfn:function(a,c,e,f){a=(a||{}).data;a=(a||{}).comicInfo;if(array_count(a)){if(b.checkupdate){try{a=a.chapterList[0]}catch(g){a={}}b.callback({pid:b.pid,cid:a.chapter_id,title:a.name+"("+a.image_count+"P)"});return!0}f=[];var d=a.chapterList.length;(a.chapterList||[]).forEach(function(a,c){f[c]=b.callback({id:d-c-1,newest:b.newest&&0==c,pid:b.pid,cid:a.chapter_id,title:a.name+"("+a.image_count+"P)",count:d,reverse:1})});return f}b.callback()}}},
infoloader:!1,infofinder:function(b){return{json:!0,str:b.result,successfn:function(a,c,e,f){a=(a||{}).data;a=(a||{}).comicInfo;c=a.cover;e=a.comic_name;f=getLocalTime(1E3*parseInt(a.last_update_time));var d=a.author,g=(a.category||[]).map(function(a){return a.category_name}).join(","),h=a.comic_description;b.callback({name:e,img:c,added:b.data,description:"<p>"+(d?"【作者】"+d+"<br>":"")+(g?"【类型】"+g+"<br>":"")+(f?"【"+(a.status?"连载":"完结")+
"】"+f+"<br>":"")+(h?"【简介】"+h:"")+"</p>",comment:1,preview:0,tags:gettag(e)+gettag(d)+gettag((g||"").split(","))});return!0}}}},parseflag:{loader:function(b){return{url:pluginfo(b.plugin).apihost+"comic/chapter",method:"POST",data:"source_id="+b.pid.split("_")[1]+"&comic_id="+b.pid.split("_")[0]+"&chapter_id="+b.cid,postform:!0,timeout:120,successfn:function(a,c){b.callback({result:a,header:c})}}},finder:function(b){return{json:!0,str:b.result,successfn:function(a,c,e,f){a=
(a||{}).data;array_count(a)?(a=a.imageList||[],a=a.map(function(a){return a.image_url}),b.download?b.callback({source:a,download:b.download,plugin:b.plugin}):b.callback({source:a,type:"image",startindex:b.startindex||0,lazyload:pluginfo(b.plugin).lazyload,zoom:!0,title:b.title})):b.callback();return!0}}}},commentflag:{loader:function(b){return{url:pluginfo(b.plugin).apihost+"forum/comicsReviewList",method:"POST",data:"p="+(b.page||1)+"&limit=10&forum_id="+b.pid.split("_")[2]+"&order=1&last_request_time=0",
postform:!0,timeout:120,successfn:function(a,c){a?b.callback({result:a,header:c,commentbrowser:!1}):b.callback()}}},finder:function(b){return{json:!0,str:b.result,successfn:function(a,c,e,f){a=(a||{}).data;if(array_count(a)){c=(a.page||{}).total_page;a=a.posts_list;for(var d in a)b.callback({page:b.page||1,pagecount:c,comment:{text:(a[d].title?a[d].title+"<br>":"")+a[d].content_summary,name:a[d].nickname||"",avatar:a[d].avatar,type:"received",label:getLocalTime(1E3*parseInt(a[d].post_date||0)),day:"",
time:"",reverse:1,extra:""}})}}}},send:!1},previewflag:{loader:!1,finder:!1},pageimgflag:{parser:!1},updateflag:{loader:function(b){return{url:pluginfo(b.plugin).apihost+"category/comicList",data:"p="+(b.page||1)+"&limit=10&category_type=serial_status&category_id=0",method:"POST",postform:!0,timeout:120,successfn:function(a,c){b.callback({result:a,header:c})}}},finder:function(b){return{json:!0,str:b.result,successfn:function(a){a=(a||{}).data;a=(a||{}).comic_list;array_count(a)?plugfns(b.plugin).pagedeal(a,
b):b.callback()}}}},hotflag:{loader:function(b){return{url:pluginfo(b.plugin).apihost+"category/comicList",data:"p="+(b.page||1)+"&limit=10&category_type=serial_status&category_id=1",method:"POST",postform:!0,timeout:120,successfn:function(a,c){b.callback({result:a,header:c})}}},finder:function(b){return{json:!0,str:b.result,successfn:function(a){a=(a||{}).data;a=(a||{}).comic_list;array_count(a)?plugfns(b.plugin).pagedeal(a,b):b.callback()}}}}},fns:{pagedeal:function(b,a){a=a||{};b.forEach(function(b){var e=
b.comic_id+"_"+b.default_source_id+"_"+b.forum_id,f=b.cover,d=b.comic_name,g=b.author,h=(b.category||[]).map(function(a){return a.category_name}).join(",");b="更新至 "+b.update_tips;if(a.multupdate||a.multhot||a.multsearch)return a.callback(obj_contact(a,{pid:e,img:f,title:d,content:b})),!1;a.callback({pid:e,title:d,img:f,stitle:g||"",content:b+(h?"<br>"+function(a){var b="";(a.split(",")||[]).forEach(function(a){b+='<span style="font-size:10px;"><span class="color-white bg-'+getnowtheme()+
'" style="padding:3px;border-radius:3px;margin-right:3px;">'+a+"</span></span>"});return b}(h):""),comment:1})})}}});
