ExView.Plugins({info:{name:"轻之文库",version:"2.2",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAeFBMVEUTtbH////r+PgXtrJr0M6u5uSO29kpvLj7/f3m9/fU8fDH7u02wLwsvbn2/PzM7+571tRHxcIduLTa8/NOyMU9wr/w+vrg9fS+6+m36Oej4uGG2ddx0tBgzctXyscmu7cjurbt+fnd9PPA6+q16Oaa392M29kgubXEdh9ZAAAAqElEQVQY02WPVxKEMAxDhRNSSEIJsPSy/f433AT2D/nHfjPySEiiKBUipWNFPDlDEON0gkwCcDZAmUVAEnOF8pFr4yQFwBnTNjr6FwNPQGxQqisYxqcLlJACablYvE1FJcIpsN9kjk/xhTUcIkxzU0k9ra11HhDRAp9vS1Er3UcLsUaManCoChxPE95MZb5ukpu22vkZzOv2rrs6MzP9o3tExejXcpf6P/85B8UO5vFmAAAAAElFTkSuQmCC",
author:"Gentle",type:"text",db:"linovel",apihost:"http://www.linovel.net/",pagetitle:["<br>","收藏","首页","类型","下载"],theme:"cyan",lazyload:!0,download:!0,setting:!0,typelistmode:!0,smallpicmode:!0,requestcookie:"",cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){ExView.workers.index.loader()}})},flags:{indexflag:{loader:function(a){a.front||a.page||addtypelist('<div align="center" class="list-block"><img src="img/logo.png"/><br>类型<br>正在加载...<div class="progress"></span></div>',
2);return{url:pluginfo(a.plugin).apihost+"cat/-1.html?page="+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){ExView.workers.index.countfinder(obj_contact(a,{result:b,header:c}));a.front||a.page||ExView.workers.type.finder({result:b,plugin:a.plugin});a.successfn&&a.successfn({result:b,header:c})},errorfn:function(){a.page||addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>加载失败，请刷新重试！</a></div>',
2);ExView.fw.alert("网络错误！","ExView")},canclefn:function(){a.page||addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>加载失败，请刷新重试！</a></div>',2)},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),name:"首页",title:a.title,img:a.img}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,
str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));array_count(b)?plugfns(a.plugin).pagedeal(b):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',2)},errorfn:function(){a.page||setnowlistname("首页","",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("网络错误！","ExView")}}},countloader:function(a){return!1},countfinder:function(a){return{reg:/\?page=\d+">(\d+)<\/a><\/li>/g,
str:a.result,find:"$1",successfn:function(a){mySession.nowlistpages=(a||"0")+"|首页|index";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},typeflag:{loader:function(a){return{successfn:function(a,c){ExView.workers.index.loader()}}},finder:function(a){addtypelist({title:"首页",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"首页"});return{reg:/\/cat\/(\d+)\.html">((?!<).*?)<\/a>/g,str:a.result,find:"$1{{separator}}$2",
successfn:function(b){b=b.split("{{separator}}");array_count(b)?addtypelist({tid:b[0],title:b[1],img:pluginfo(a.plugin).icon,group:{name:"fenlei",title:"分类"},content:b[1]}):addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>加载失败，请刷新重试！</a></div>',2)}}}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"cat/"+a.keyword+
".html?page="+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){b?(ExView.workers.list.countfinder(obj_contact(a,{result:b,header:c})),a.successfn&&a.successfn({result:b,header:c})):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+a.title+"】<br>获取失败！","ExView"))},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),name:"【"+a.title+"】",title:a.title,img:a.img}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,
str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{reg:plugfns(a.plugin).pagecountrule,str:a.result,find:plugfns(a.plugin).pagecountfind,successfn:function(b){mySession.nowlistpages=(b||"0")+"|"+a.keyword+"|list";mySession.nowlistpage=1;console.log(mySession.nowlistpages);
return!0}}}},searchflag:{loader:function(a){return 1<parseInt(a.page)?(a.multsearch&&a.multsearch(),!1):{url:pluginfo(a.plugin).apihost+"search/?kw="+a.keyword,method:"GET",timeout:120,successfn:function(b,c){b?(a.multsearch||(ExView.workers.search.countfinder(obj_contact(a,{result:b,header:c})),setnowlistname("搜索【"+a.keyword+"】")),a.successfn&&a.successfn({result:b,header:c})):a.multsearch?a.multsearch():(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+
a.keyword+"】<br>获取搜索结果失败！","ExView"))},showinfo:{text:"正在搜索..."+(1<a.page?"<br>第"+a.page+"页":""),name:"【"+a.keyword+"】",title:"搜索"}}},finder:function(a){return{reg:/\/book\/detail\?id=(\d+)"(.*?)<\/div>/g,str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b,c,f){console.log(b);b?plugfns(a.plugin).pagedeal(b,a):a.multsearch?a.multsearch():addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',
1)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(b){mySession.nowlistpages="-1|"+a.keyword+"|search";mySession.nowlistpage=1;console.log(mySession.nowlistpages)}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"book/"+a.pid+".html",method:"GET",timeout:120,ua:"ExView",successfn:function(b,c){b?a.successfn&&a.successfn({result:b,header:c}):a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！",
"ExView"))},showinfo:{text:"正在加载目录...",title:"内容页",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){var b=[],c=getquery(a.result,".section[data-index-name]");console.log(c);$$(c).each(function(a){(function(a){var c=$$(a).find(".volume-cover").find("img").attr("data-original"),f=$$(a).find(".volume-title").text();$$(a).find(".chapter").each(function(){var a=getstr(/\/book\/\d+\/(\d+)\.html/,$$(this).find("a").attr("href"))||"",e=$$(this).find("a").text();
b.push({group:{name:"type_"+ExView.tools.md5.hex_md5(f),title:f,img:c},item:{cid:a,title:e}})})})(this)});return{successfn:function(c,e,d,g){console.log(typeof c);if(array_count(c)){if(a.checkupdate)return e=b,c=e[e.length-1],d=(c||{}).group.title,c=(c||{}).item,{pid:a.pid,cid:c.cid,title:d+" "+c.title};e=b;g=[];b.map(function(b,c){var d=b.item;g[c]=additemlist({id:c,newest:a.newest&&0==c,pid:a.pid,cid:d.cid,title:d.title,group:b.group,count:e.length,reverse:0});g[c].title=b.group.title+" "+d.title});
return g}a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},afterfn:function(){a.checkupdate||ExView.workers.content.infofinder(a)}}},infoloader:function(a){return!1},infofinder:function(a){console.log(a);return{query:!0,selector:".detail-layout",str:a.result,successfn:function(b,c,f,e){c=$$(b).find("img").attr("data-original");f=$$(b).find(".book-title").text();var d=getquery(a.result,".author-frame");e=$$(d).find(".novelist .name").text();
var d=$$(d).find(".illustrator .name").text(),g=$$(b).find(".book-last-update").text(),k=$$(b).find(".book-data").text();b=$$(b).find(".about-text").text();var h=getstrs(a.result,/\/list\/cat\?cat=\d+">((?!<).*?)</g,"$1"),l=gettag(h),h=(h||[]).join(" ").trim();setlistpic({name:f,img:c,added:a.data,description:"<p>"+(e?"【作者】"+e+"<br>":"")+(h?"【类型】"+h+"<br>":"")+(d?"【插画】"+d+"<br>":"")+(k?k+"<br>":"")+(g?"【更新】"+g+"<br>":
"")+(b?"【简介】"+b:"")+"</p>",sourceurl:pluginfo(a.plugin).apihost+"book/"+a.pid+".html",comment:1,preview:0,tags:gettag(f)+l+gettag(e)+gettag(d)+gettag(status)});return!0}}}},parseflag:{loader:function(a){return a.cid?{url:pluginfo(a.plugin).apihost+"book/"+a.pid+"/"+a.cid+".html",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"正在加载文章信息...",title:"文章",name:getlistname(a.pid),
img:getlistimg(a.pid)}}:(a.download||(ExView.fw.alert("此作品已经被下架啦！！！"),ExView.fw.hidePreloader(),mySession.isloading=0),!1)},finder:function(a){console.log(a);return{reg:/id="readerArticle"(?!>).*?>(.*?)<\/article>/g,str:getresult(a.result),find:"$1",successfn:function(b){b?(b=getarticle(b),console.log(b),a.download?chapterpredownload({type:"text",source:b,download:a.download,plugin:a.plugin}):chapterviewer({source:b,type:"text",startindex:a.startindex||
0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.download?chapterpredownload({error:"解析错误！",download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("文章信息获取失败！","ExView"));return!0}}}},commentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"comment/getComments?type=0&oid="+a.pid+"&pageSize=20&page="+(a.page||1),method:"GET",timeout:120,successfn:function(b,
c){b?a.callback&&a.callback({result:b,header:c,commentbrowser:{url:pluginfo(a.plugin).apihost+"book/"+a.pid+".html",title:"评论 - "+pluginfo(a.plugin).name+'<br><span style="font-size:16px">'+(myContent.name||"")+"</span>",browser:!1,flag:""}}):a.callback&&a.callback()}}},finder:function(a){console.log(a);return{json:!0,str:a.result,successfn:function(b,c,f,e){if(array_count(b)){c=b.data.maxPage;b=b.data.lists;for(var d in b)a.callback&&a.callback({page:a.page||1,pagecount:c,comment:{text:b[d].comment,
name:b[d].usernick,avatar:getimgload(b[d].userAvatar,a.plugin),type:"received",label:getLocalTime(1E3*parseInt(b[d].date)),day:"",time:"",reverse:1,extra:""}})}}}},send:!1},previewflag:{loader:!1,finder:!1,more:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"cat/-1.html?page="+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:getresult(a.result),
find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.multupdate()}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"hub/getEditorRecommendBooks",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){console.log(JSON.stringify(b));b=(b||{}).data;if(array_count(b))return b.forEach(function(b){a.multhot(obj_contact(a,
{pid:b._id,img:b.cover,title:b.name,content:"更新至 "+b.nstv}))}),!1;a.multhot()}}}}},fns:{pagecountrule:/\?page=\d+">(\d+)<\/a><\/li>/g,pagecountfind:"$1",pagerule:/\/book\/(\d+).html(.*?)<\/div>/g,pagefind:{pid:"$1",content:"$2"},pagedeal:function(a,b){b=b||{};var c=a.pid,f=getstr(/data-original="((?!\").*?)"/,a.content);f||(f=getstr(/src="((?!\").*?)"/,a.content));var e=getstr(/class="title">((?!<).*?)</,a.content);e||(e=getstr(/class="title">(.*?)<\/h3/,a.content));var d=getstr(/class="author">((?!<).*?)</,
a.content),g=getstr(/字(?!<).*?数：\s*<span class="artist">((?!<).*?)</,a.content),k=gettext(getstr(/class="descs">简(?!<).*?介：<\/span>((?!<).*?)</,a.content)),h=getstr(/最新更新：((?!<).*?)</,a.content),l=gettext(getstr(/最新卷：(.*?)&nbsp;/,a.content)),m="更新日期 "+h;if(b.multupdate)return b.multupdate(obj_contact(b,{pid:c,img:f,title:e,content:m})),!1;if(b.multhot)return b.multhot(obj_contact(b,{pid:c,img:f,title:e,
content:m})),!1;if(b.multsearch)return b.multsearch(obj_contact(b,{pid:c,img:f,title:e,content:m})),!1;addcardlist({pid:c,title:e,img:f,content:d?"【作者】"+d+"<br>"+(g?"【字数】"+g+"<br>":"")+(l?"【最新】"+l+"<br>":"")+(h?"【更新】"+h+"<br>":"")+(k?"【简介】"+(100<k.length?cutstr(k,100)+"...":k)+"<br>":""):"",comment:1})}}});
