ExView.Plugins({info:{name:"\u8f7b\u4e4b\u6587\u5e93",version:"2.2",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAeFBMVEUTtbH////r+PgXtrJr0M6u5uSO29kpvLj7/f3m9/fU8fDH7u02wLwsvbn2/PzM7+571tRHxcIduLTa8/NOyMU9wr/w+vrg9fS+6+m36Oej4uGG2ddx0tBgzctXyscmu7cjurbt+fnd9PPA6+q16Oaa392M29kgubXEdh9ZAAAAqElEQVQY02WPVxKEMAxDhRNSSEIJsPSy/f433AT2D/nHfjPySEiiKBUipWNFPDlDEON0gkwCcDZAmUVAEnOF8pFr4yQFwBnTNjr6FwNPQGxQqisYxqcLlJACablYvE1FJcIpsN9kjk/xhTUcIkxzU0k9ra11HhDRAp9vS1Er3UcLsUaManCoChxPE95MZb5ukpu22vkZzOv2rrs6MzP9o3tExejXcpf6P/85B8UO5vFmAAAAAElFTkSuQmCC",
author:"Gentle",type:"text",db:"linovel",apihost:"http://www.linovel.net/",pagetitle:["<br>","\u6536\u85cf","\u9996\u9875","\u7c7b\u578b","\u4e0b\u8f7d"],theme:"cyan",lazyload:!0,download:!0,setting:!0,typelistmode:!0,smallpicmode:!0,requestcookie:"",cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){ExView.workers.index.loader()}})},flags:{indexflag:{loader:function(a){a.front||a.page||addtypelist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u7c7b\u578b<br>\u6b63\u5728\u52a0\u8f7d...<div class="progress"></span></div>',
2);return{url:pluginfo(a.plugin).apihost+"cat/-1.html?page="+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){ExView.workers.index.countfinder(obj_contact(a,{result:b,header:c}));a.front||a.page||ExView.workers.type.finder({result:b,plugin:a.plugin});a.successfn&&a.successfn({result:b,header:c})},errorfn:function(){a.page||addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>\u52a0\u8f7d\u5931\u8d25\uff0c\u8bf7\u5237\u65b0\u91cd\u8bd5\uff01</a></div>',
2);ExView.fw.alert("\u7f51\u7edc\u9519\u8bef\uff01","ExView")},canclefn:function(){a.page||addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>\u52a0\u8f7d\u5931\u8d25\uff0c\u8bf7\u5237\u65b0\u91cd\u8bd5\uff01</a></div>',2)},showinfo:{text:"\u6b63\u5728\u52a0\u8f7d..."+(1<a.page?"<br>\u7b2c"+a.page+"\u9875":""),name:"\u9996\u9875",title:a.title,img:a.img}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,
str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));array_count(b)?plugfns(a.plugin).pagedeal(b):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u6ca1\u6709\u5185\u5bb9</div>',2)},errorfn:function(){a.page||setnowlistname("\u9996\u9875","",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("\u7f51\u7edc\u9519\u8bef\uff01","ExView")}}},countloader:function(a){return!1},countfinder:function(a){return{reg:/\?page=\d+">(\d+)<\/a><\/li>/g,
str:a.result,find:"$1",successfn:function(a){mySession.nowlistpages=(a||"0")+"|\u9996\u9875|index";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},typeflag:{loader:function(a){return{successfn:function(a,c){ExView.workers.index.loader()}}},finder:function(a){addtypelist({title:"\u9996\u9875",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u9996\u9875"});return{reg:/\/cat\/(\d+)\.html">((?!<).*?)<\/a>/g,str:a.result,find:"$1{{separator}}$2",
successfn:function(b){b=b.split("{{separator}}");array_count(b)?addtypelist({tid:b[0],title:b[1],img:pluginfo(a.plugin).icon,group:{name:"fenlei",title:"\u5206\u7c7b"},content:b[1]}):addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>\u52a0\u8f7d\u5931\u8d25\uff0c\u8bf7\u5237\u65b0\u91cd\u8bd5\uff01</a></div>',2)}}}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"cat/"+a.keyword+
".html?page="+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){b?(ExView.workers.list.countfinder(obj_contact(a,{result:b,header:c})),a.successfn&&a.successfn({result:b,header:c})):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u3010"+a.title+"\u3011<br>\u83b7\u53d6\u5931\u8d25\uff01","ExView"))},showinfo:{text:"\u6b63\u5728\u52a0\u8f7d..."+(1<a.page?"<br>\u7b2c"+a.page+"\u9875":""),name:"\u3010"+a.title+"\u3011",title:a.title,img:a.img}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,
str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u6ca1\u6709\u5185\u5bb9</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{reg:plugfns(a.plugin).pagecountrule,str:a.result,find:plugfns(a.plugin).pagecountfind,successfn:function(b){mySession.nowlistpages=(b||"0")+"|"+a.keyword+"|list";mySession.nowlistpage=1;console.log(mySession.nowlistpages);
return!0}}}},searchflag:{loader:function(a){return 1<parseInt(a.page)?(a.multsearch&&a.multsearch(),!1):{url:pluginfo(a.plugin).apihost+"search/?kw="+a.keyword,method:"GET",timeout:120,successfn:function(b,c){b?(a.multsearch||(ExView.workers.search.countfinder(obj_contact(a,{result:b,header:c})),setnowlistname("\u641c\u7d22\u3010"+a.keyword+"\u3011")),a.successfn&&a.successfn({result:b,header:c})):a.multsearch?a.multsearch():(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u3010"+
a.keyword+"\u3011<br>\u83b7\u53d6\u641c\u7d22\u7ed3\u679c\u5931\u8d25\uff01","ExView"))},showinfo:{text:"\u6b63\u5728\u641c\u7d22..."+(1<a.page?"<br>\u7b2c"+a.page+"\u9875":""),name:"\u3010"+a.keyword+"\u3011",title:"\u641c\u7d22"}}},finder:function(a){return{reg:/\/book\/detail\?id=(\d+)"(.*?)<\/div>/g,str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b,c,g){console.log(b);b?plugfns(a.plugin).pagedeal(b,a):a.multsearch?a.multsearch():addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u6ca1\u6709\u5185\u5bb9</div>',
1)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(b){mySession.nowlistpages="-1|"+a.keyword+"|search";mySession.nowlistpage=1;console.log(mySession.nowlistpages)}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"book/"+a.pid+".html",method:"GET",timeout:120,successfn:function(b,c){b?a.successfn&&a.successfn({result:b,header:c}):a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u5185\u5bb9\u9875\u83b7\u53d6\u5931\u8d25\uff01",
"ExView"))},showinfo:{text:"\u6b63\u5728\u52a0\u8f7d\u76ee\u5f55...",title:"\u5185\u5bb9\u9875",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){var b=[];a.result=getresult(a.result);var c=getstrs(a.result,/class="swiper-slide"\s*data-index="(\d+)"(.*?)class="caption"/g,"$1{{separator}}$2"),c=c.map(function(c){c=(c||"").split("{{separator}}");var e=c[0],d=getstrs(c[1],/data-src="((?!\").*?)"\s*alt="((?!\").*?)".*?class="rank">((?!<).*?)</g,"$1{{separator}}$3 $2"),d=(d[0]||"").split("{{separator}}"),
d={groupimg:d[0],grouptitle:d[1]};getstrs(a.result,new RegExp('volume-info"\\s*data-index="'+e+'"(.*?)<div\\s*class="panel',"g"),"$1").map(function(a){getstrs(a,/href="((?!\").*?)"><i\s*class="icon-slab"><\/i>((?!<).*?)</g,"$1{{separator}}$2").forEach(function(a){a=(a||"").split("{{separator}}");b.push({group:{name:"type_"+ExView.tools.md5.hex_md5(d.grouptitle),title:d.grouptitle,img:d.groupimg},item:{cid:getstr(/\/book\/\d+\/(\d+)\.html/,a[0])||"",title:a[1]}})})})});return{successfn:function(c,
e,d,f){console.log(typeof c);if(array_count(c)){if(a.checkupdate)return e=b,c=e[e.length-1],d=(c||{}).group.title,c=(c||{}).item,{pid:a.pid,cid:c.cid,title:d+" "+c.title};e=b;f=[];b.map(function(b,c){var d=b.item;f[c]=additemlist({id:c,newest:a.newest&&0==c,pid:a.pid,cid:d.cid,title:d.title,group:b.group,count:e.length,reverse:0});f[c].title=b.group.title+" "+d.title});return f}a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u5185\u5bb9\u9875\u83b7\u53d6\u5931\u8d25\uff01",
"ExView"))},afterfn:function(){a.checkupdate||ExView.workers.content.infofinder(a)}}},infoloader:function(a){return!1},infofinder:function(a){console.log(a);return{reg:/class="row\s*info">(.*?)class="controls/g,str:getresult(a.result),find:"$1",successfn:function(b,c,g,e){console.log(JSON.stringify(b));c=getstr(/<img(?!<).*?data-original="((?!\").*?)"/,b);g=getstr(/class="works-title">((?!<).*?)</,b);e=gettext(getstr(/\u63d2\u753b:\s*<\/label>\s*(.*?)\s*<\/p>/,b)).replace(/&nbsp;/g,"").trim();var d=
gettext(getstr(/\u4f5c\u8005:\s*<\/label>\s*(.*?)\s*<label>/,b)).replace(/&nbsp;/g,"").trim(),f=getstrs(b,/\/list\/cat\?cat=\d+">((?!<).*?)</g,"$1"),h=gettext(getstr(/class="last-update">\u6700\u65b0\u66f4\u65b0:((?!<).*?)</,b)).trim(),k=gettext(getstr(/<label>\u603b\u5b57\u6570:\s*<\/label>\s*<label>((?!<).*?)<\/label>/,b)).trim();b=gettext(getstr(/class="text-content-actual">(.*?)<\/div>/,b)).replace(/\n/g,"<br>").trim();var l=gettag(f),f=(f||[]).join(" ").trim();setlistpic({name:g,img:c,added:a.data,
description:"<p>"+(d?"\u3010\u4f5c\u8005\u3011"+d+"<br>":"")+(f?"\u3010\u7c7b\u578b\u3011"+f+"<br>":"")+(e?"\u3010\u63d2\u753b\u3011"+e+"<br>":"")+(k?"\u3010\u5b57\u6570\u3011"+k+"<br>":"")+(h?"\u3010\u66f4\u65b0\u3011"+h+"<br>":"")+(b?"\u3010\u7b80\u4ecb\u3011"+b:"")+"</p>",sourceurl:pluginfo(a.plugin).apihost+"book/"+a.pid+".html",comment:1,preview:0,tags:gettag(g)+l+gettag(d)+gettag(e)+gettag(status)});return!0}}}},parseflag:{loader:function(a){return a.cid?{url:pluginfo(a.plugin).apihost+"book/"+
a.pid+"/"+a.cid+".html",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"\u6b63\u5728\u52a0\u8f7d\u6587\u7ae0\u4fe1\u606f...",title:"\u6587\u7ae0",name:getlistname(a.pid),img:getlistimg(a.pid)}}:(a.download||(ExView.fw.alert("\u6b64\u4f5c\u54c1\u5df2\u7ecf\u88ab\u4e0b\u67b6\u5566\uff01\uff01\uff01"),ExView.fw.hidePreloader(),mySession.isloading=0),!1)},finder:function(a){console.log(a);return{reg:/id="readerArticle"(?!>).*?>(.*?)<\/article>/g,
str:getresult(a.result),find:"$1",successfn:function(b){b?(b=getarticle(b),console.log(b),a.download?chapterpredownload({type:"text",source:b,download:a.download,plugin:a.plugin}):chapterviewer({source:b,type:"text",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.download?chapterpredownload({error:"\u89e3\u6790\u9519\u8bef\uff01",download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u6587\u7ae0\u4fe1\u606f\u83b7\u53d6\u5931\u8d25\uff01",
"ExView"));return!0}}}},commentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"comment/getComments?type=0&oid="+a.pid+"&pageSize=20&page="+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){b?a.callback&&a.callback({result:b,header:c,commentbrowser:{url:pluginfo(a.plugin).apihost+"book/"+a.pid+".html",title:"\u8bc4\u8bba - "+pluginfo(a.plugin).name+'<br><span style="font-size:16px">'+(myContent.name||"")+"</span>",browser:!1,flag:""}}):a.callback&&a.callback()}}},finder:function(a){console.log(a);
return{json:!0,str:a.result,successfn:function(b,c,g,e){if(array_count(b)){c=b.data.maxPage;b=b.data.lists;for(var d in b)a.callback&&a.callback({page:a.page||1,pagecount:c,comment:{text:b[d].comment,name:b[d].usernick,avatar:getimgload(b[d].userAvatar,a.plugin),type:"received",label:getLocalTime(1E3*parseInt(b[d].date)),day:"",time:"",reverse:1,extra:""}})}}}},send:!1},previewflag:{loader:!1,finder:!1,more:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"cat/-1.html?page="+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.multupdate()}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"hub/getEditorRecommendBooks",method:"GET",timeout:120,successfn:function(b,
c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){console.log(JSON.stringify(b));b=(b||{}).data;if(array_count(b))return b.forEach(function(b){a.multhot(obj_contact(a,{pid:b._id,img:b.cover,title:b.name,content:"\u66f4\u65b0\u81f3 "+b.nstv}))}),!1;a.multhot()}}}}},fns:{pagecountrule:/\?page=\d+">(\d+)<\/a><\/li>/g,pagecountfind:"$1",pagerule:/\/book\/(\d+).html(.*?)<\/div>/g,pagefind:{pid:"$1",content:"$2"},pagedeal:function(a,
b){b=b||{};var c=a.pid,g=getstr(/data-original="((?!\").*?)"/,a.content);g||(g=getstr(/src="((?!\").*?)"/,a.content));var e=getstr(/class="title">((?!<).*?)</,a.content);e||(e=getstr(/class="title">(.*?)<\/h3/,a.content));var d=getstr(/class="author">((?!<).*?)</,a.content),f=getstr(/\u5b57(?!<).*?\u6570\uff1a\s*<span class="artist">((?!<).*?)</,a.content),h=gettext(getstr(/class="descs">\u7b80(?!<).*?\u4ecb\uff1a<\/span>((?!<).*?)</,a.content)),k=getstr(/\u6700\u65b0\u66f4\u65b0\uff1a((?!<).*?)</,
a.content),l=gettext(getstr(/\u6700\u65b0\u5377\uff1a(.*?)&nbsp;/,a.content)),m="\u66f4\u65b0\u65e5\u671f "+k;if(b.multupdate)return b.multupdate(obj_contact(b,{pid:c,img:g,title:e,content:m})),!1;if(b.multhot)return b.multhot(obj_contact(b,{pid:c,img:g,title:e,content:m})),!1;if(b.multsearch)return b.multsearch(obj_contact(b,{pid:c,img:g,title:e,content:m})),!1;addcardlist({pid:c,title:e,img:g,content:d?"\u3010\u4f5c\u8005\u3011"+d+"<br>"+(f?"\u3010\u5b57\u6570\u3011"+f+"<br>":"")+(l?"\u3010\u6700\u65b0\u3011"+
l+"<br>":"")+(k?"\u3010\u66f4\u65b0\u3011"+k+"<br>":"")+(h?"\u3010\u7b80\u4ecb\u3011"+(100<h.length?cutstr(h,100)+"...":h)+"<br>":""):"",comment:1})}}});
