var $jscomp={scope:{},getGlobal:function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global?global:a}};$jscomp.global=$jscomp.getGlobal(this);$jscomp.initSymbol=function(){$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol);$jscomp.initSymbol=function(){}};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return"jscomp_symbol_"+a+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();$jscomp.global.Symbol.iterator||($jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));$jscomp.initSymbolIterator=function(){}};
$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();if(a[$jscomp.global.Symbol.iterator])return a[$jscomp.global.Symbol.iterator]();if(!(a instanceof Array||"string"==typeof a||a instanceof String))throw new TypeError(a+" is not iterable");var b=0;return{next:function(){return b==a.length?{done:!0}:{done:!1,value:a[b++]}}}};$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};
$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.arrayFromArguments=function(a){for(var b=[],c=0;c<a.length;c++)b.push(a[c]);return b};$jscomp.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if($jscomp.global.Object.defineProperties){var e=$jscomp.global.Object.getOwnPropertyDescriptor(b,d);$jscomp.global.Object.defineProperty(a,d,e)}else a[d]=b[d]};
$jscomp.array=$jscomp.array||{};$jscomp.array.done_=function(){return{done:!0,value:void 0}};$jscomp.array.arrayIterator_=function(a,b){a instanceof String&&(a=String(a));var c=0;$jscomp.initSymbol();$jscomp.initSymbolIterator();var d={},e=(d.next=function(){if(c<a.length){var d=c++;return{value:b(d,a[d]),done:!1}}e.next=$jscomp.array.done_;return $jscomp.array.done_()},d[Symbol.iterator]=function(){return e},d);return e};
$jscomp.array.findInternal_=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var h=a[e];if(b.call(c,h,e,a))return{i:e,v:h}}return{i:-1,v:void 0}};
$jscomp.array.from=function(a,b,c){b=void 0===b?function(a){return a}:b;var d=[];$jscomp.initSymbol();$jscomp.initSymbolIterator();if(a[Symbol.iterator]){$jscomp.initSymbol();$jscomp.initSymbolIterator();a=a[Symbol.iterator]();for(var e;!(e=a.next()).done;)d.push(b.call(c,e.value))}else{e=a.length;for(var h=0;h<e;h++)d.push(b.call(c,a[h]))}return d};$jscomp.array.of=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];return $jscomp.array.from(b)};
$jscomp.array.entries=function(){return $jscomp.array.arrayIterator_(this,function(a,b){return[a,b]})};$jscomp.array.entries$install=function(){Array.prototype.entries||(Array.prototype.entries=$jscomp.array.entries)};$jscomp.array.keys=function(){return $jscomp.array.arrayIterator_(this,function(a){return a})};$jscomp.array.keys$install=function(){Array.prototype.keys||(Array.prototype.keys=$jscomp.array.keys)};$jscomp.array.values=function(){return $jscomp.array.arrayIterator_(this,function(a,b){return b})};
$jscomp.array.values$install=function(){Array.prototype.values||(Array.prototype.values=$jscomp.array.values)};$jscomp.array.copyWithin=function(a,b,c){var d=this.length;a=Number(a);b=Number(b);c=Number(null!=c?c:d);if(a<b)for(c=Math.min(c,d);b<c;)b in this?this[a++]=this[b++]:(delete this[a++],b++);else for(c=Math.min(c,d+b-a),a+=c-b;c>b;)--c in this?this[--a]=this[c]:delete this[a];return this};$jscomp.array.copyWithin$install=function(){Array.prototype.copyWithin||(Array.prototype.copyWithin=$jscomp.array.copyWithin)};
$jscomp.array.fill=function(a,b,c){null!=c&&a.length||(c=this.length||0);c=Number(c);for(b=Number((void 0===b?0:b)||0);b<c;b++)this[b]=a;return this};$jscomp.array.fill$install=function(){Array.prototype.fill||(Array.prototype.fill=$jscomp.array.fill)};$jscomp.array.find=function(a,b){return $jscomp.array.findInternal_(this,a,b).v};$jscomp.array.find$install=function(){Array.prototype.find||(Array.prototype.find=$jscomp.array.find)};
$jscomp.array.findIndex=function(a,b){return $jscomp.array.findInternal_(this,a,b).i};$jscomp.array.findIndex$install=function(){Array.prototype.findIndex||(Array.prototype.findIndex=$jscomp.array.findIndex)};$jscomp.Map=function(a){a=void 0===a?[]:a;this.data_={};this.head_=$jscomp.Map.createHead_();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var b=a.next();!b.done;b=a.next())b=b.value,this.set(b[0],b[1])}};
$jscomp.Map.checkBrowserConformance_=function(){var a=$jscomp.global.Map;if(!a||!a.prototype.entries||!Object.seal)return!1;try{var b=Object.seal({x:4}),c=new a($jscomp.makeIterator([[b,"s"]]));if("s"!=c.get(b)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var d=c.entries(),e=d.next();if(e.done||e.value[0]!=b||"s"!=e.value[1])return!1;e=d.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!d.next().done?!1:!0}catch(h){return!1}};
$jscomp.Map.createHead_=function(){var a={};return a.previous=a.next=a.head=a};$jscomp.Map.getId_=function(a){if(!(a instanceof Object))return String(a);$jscomp.Map.key_ in a||a instanceof Object&&Object.isExtensible&&Object.isExtensible(a)&&$jscomp.Map.defineProperty_(a,$jscomp.Map.key_,++$jscomp.Map.index_);return $jscomp.Map.key_ in a?a[$jscomp.Map.key_]:" "+a};
$jscomp.Map.prototype.set=function(a,b){var c=this.maybeGetEntry_(a),d=c.id,e=c.list,c=c.entry;e||(e=this.data_[d]=[]);c?c.value=b:(c={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,value:b},e.push(c),this.head_.previous.next=c,this.head_.previous=c,this.size++);return this};
$jscomp.Map.prototype["delete"]=function(a){var b=this.maybeGetEntry_(a);a=b.id;var c=b.list,d=b.index;return(b=b.entry)&&c?(c.splice(d,1),c.length||delete this.data_[a],b.previous.next=b.next,b.next.previous=b.previous,b.head=null,this.size--,!0):!1};$jscomp.Map.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=$jscomp.Map.createHead_();this.size=0};$jscomp.Map.prototype.has=function(a){return!!this.maybeGetEntry_(a).entry};
$jscomp.Map.prototype.get=function(a){return(a=this.maybeGetEntry_(a).entry)&&a.value};$jscomp.Map.prototype.maybeGetEntry_=function(a){var b=$jscomp.Map.getId_(a),c=this.data_[b];if(c)for(var d=0;d<c.length;d++){var e=c[d];if(a!==a&&e.key!==e.key||a===e.key)return{id:b,list:c,index:d,entry:e}}return{id:b,list:c,index:-1,entry:void 0}};$jscomp.Map.prototype.entries=function(){return this.iter_(function(a){return[a.key,a.value]})};$jscomp.Map.prototype.keys=function(){return this.iter_(function(a){return a.key})};
$jscomp.Map.prototype.values=function(){return this.iter_(function(a){return a.value})};$jscomp.Map.prototype.forEach=function(a,b){for(var c=$jscomp.makeIterator(this.entries()),d=c.next();!d.done;d=c.next())d=d.value,a.call(b,d[1],d[0],this)};
$jscomp.Map.prototype.iter_=function(a){var b=this,c=this.head_;$jscomp.initSymbol();$jscomp.initSymbolIterator();var d={};return d.next=function(){if(c){for(;c.head!=b.head_;)c=c.previous;for(;c.next!=c.head;)return c=c.next,{done:!1,value:a(c)};c=null}return{done:!0,value:void 0}},d[Symbol.iterator]=function(){return this},d};$jscomp.Map.index_=0;$jscomp.Map.defineProperty_=Object.defineProperty?function(a,b,c){Object.defineProperty(a,b,{value:String(c)})}:function(a,b,c){a[b]=String(c)};
$jscomp.Map.Entry_=function(){};$jscomp.Map.ASSUME_NO_NATIVE=!1;$jscomp.Map$install=function(){$jscomp.initSymbol();$jscomp.initSymbolIterator();!$jscomp.Map.ASSUME_NO_NATIVE&&$jscomp.Map.checkBrowserConformance_()?$jscomp.Map=$jscomp.global.Map:($jscomp.initSymbol(),$jscomp.initSymbolIterator(),$jscomp.Map.prototype[Symbol.iterator]=$jscomp.Map.prototype.entries,$jscomp.initSymbol(),$jscomp.Map.key_=Symbol("map-id-key"));$jscomp.Map$install=function(){}};$jscomp.math=$jscomp.math||{};
$jscomp.math.clz32=function(a){a=Number(a)>>>0;if(0===a)return 32;var b=0;0===(a&4294901760)&&(a<<=16,b+=16);0===(a&4278190080)&&(a<<=8,b+=8);0===(a&4026531840)&&(a<<=4,b+=4);0===(a&3221225472)&&(a<<=2,b+=2);0===(a&2147483648)&&b++;return b};$jscomp.math.imul=function(a,b){a=Number(a);b=Number(b);var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0};$jscomp.math.sign=function(a){a=Number(a);return 0===a||isNaN(a)?a:0<a?1:-1};
$jscomp.math.log10=function(a){return Math.log(a)/Math.LN10};$jscomp.math.log2=function(a){return Math.log(a)/Math.LN2};$jscomp.math.log1p=function(a){a=Number(a);if(.25>a&&-.25<a){for(var b=a,c=1,d=a,e=0,h=1;e!=d;)b*=a,h*=-1,d=(e=d)+h*b/++c;return d}return Math.log(1+a)};$jscomp.math.expm1=function(a){a=Number(a);if(.25>a&&-.25<a){for(var b=a,c=1,d=a,e=0;e!=d;)b*=a/++c,d=(e=d)+b;return d}return Math.exp(a)-1};$jscomp.math.cosh=function(a){a=Number(a);return(Math.exp(a)+Math.exp(-a))/2};
$jscomp.math.sinh=function(a){a=Number(a);return 0===a?a:(Math.exp(a)-Math.exp(-a))/2};$jscomp.math.tanh=function(a){a=Number(a);if(0===a)return a;var b=Math.exp(2*-Math.abs(a)),b=(1-b)/(1+b);return 0>a?-b:b};$jscomp.math.acosh=function(a){a=Number(a);return Math.log(a+Math.sqrt(a*a-1))};$jscomp.math.asinh=function(a){a=Number(a);if(0===a)return a;var b=Math.log(Math.abs(a)+Math.sqrt(a*a+1));return 0>a?-b:b};
$jscomp.math.atanh=function(a){a=Number(a);return($jscomp.math.log1p(a)-$jscomp.math.log1p(-a))/2};
$jscomp.math.hypot=function(a,b,c){for(var d=[],e=2;e<arguments.length;++e)d[e-2]=arguments[e];a=Number(a);b=Number(b);for(var h=Math.max(Math.abs(a),Math.abs(b)),k=$jscomp.makeIterator(d),e=k.next();!e.done;e=k.next())h=Math.max(h,Math.abs(e.value));if(1E100<h||1E-100>h){a/=h;b/=h;k=a*a+b*b;d=$jscomp.makeIterator(d);for(e=d.next();!e.done;e=d.next())e=e.value,e=Number(e)/h,k+=e*e;return Math.sqrt(k)*h}h=a*a+b*b;d=$jscomp.makeIterator(d);for(e=d.next();!e.done;e=d.next())e=e.value,h+=e*e;return Math.sqrt(h)};
$jscomp.math.trunc=function(a){a=Number(a);if(isNaN(a)||Infinity===a||-Infinity===a||0===a)return a;var b=Math.floor(Math.abs(a));return 0>a?-b:b};$jscomp.math.cbrt=function(a){if(0===a)return a;a=Number(a);var b=Math.pow(Math.abs(a),1/3);return 0>a?-b:b};$jscomp.number=$jscomp.number||{};$jscomp.number.isFinite=function(a){return"number"!==typeof a?!1:!isNaN(a)&&Infinity!==a&&-Infinity!==a};$jscomp.number.isInteger=function(a){return $jscomp.number.isFinite(a)?a===Math.floor(a):!1};
$jscomp.number.isNaN=function(a){return"number"===typeof a&&isNaN(a)};$jscomp.number.isSafeInteger=function(a){return $jscomp.number.isInteger(a)&&Math.abs(a)<=$jscomp.number.MAX_SAFE_INTEGER};$jscomp.number.EPSILON=Math.pow(2,-52);$jscomp.number.MAX_SAFE_INTEGER=9007199254740991;$jscomp.number.MIN_SAFE_INTEGER=-9007199254740991;$jscomp.object=$jscomp.object||{};
$jscomp.object.assign=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];c=$jscomp.makeIterator(c);for(d=c.next();!d.done;d=c.next()){var d=d.value,e;for(e in d)Object.prototype.hasOwnProperty.call(d,e)&&(a[e]=d[e])}return a};$jscomp.object.is=function(a,b){return a===b?0!==a||1/a===1/b:a!==a&&b!==b};$jscomp.Set=function(a){a=void 0===a?[]:a;this.map_=new $jscomp.Map;if(a){a=$jscomp.makeIterator(a);for(var b=a.next();!b.done;b=a.next())this.add(b.value)}this.size=this.map_.size};
$jscomp.Set.checkBrowserConformance_=function(){var a=$jscomp.global.Set;if(!a||!a.prototype.entries||!Object.seal)return!1;var b=Object.seal({x:4}),a=new a($jscomp.makeIterator([b]));if(a.has(b)||1!=a.size||a.add(b)!=a||1!=a.size||a.add({x:4})!=a||2!=a.size)return!1;var a=a.entries(),c=a.next();if(c.done||c.value[0]!=b||c.value[1]!=b)return!1;c=a.next();return c.done||c.value[0]==b||4!=c.value[0].x||c.value[1]!=c.value[0]?!1:a.next().done};
$jscomp.Set.prototype.add=function(a){this.map_.set(a,a);this.size=this.map_.size;return this};$jscomp.Set.prototype["delete"]=function(a){a=this.map_["delete"](a);this.size=this.map_.size;return a};$jscomp.Set.prototype.clear=function(){this.map_.clear();this.size=0};$jscomp.Set.prototype.has=function(a){return this.map_.has(a)};$jscomp.Set.prototype.entries=function(){return this.map_.entries()};$jscomp.Set.prototype.values=function(){return this.map_.values()};
$jscomp.Set.prototype.forEach=function(a,b){var c=this;this.map_.forEach(function(d){return a.call(b,d,d,c)})};$jscomp.Set.ASSUME_NO_NATIVE=!1;$jscomp.Set$install=function(){!$jscomp.Set.ASSUME_NO_NATIVE&&$jscomp.Set.checkBrowserConformance_()?$jscomp.Set=$jscomp.global.Set:($jscomp.Map$install(),$jscomp.initSymbol(),$jscomp.initSymbolIterator(),$jscomp.Set.prototype[Symbol.iterator]=$jscomp.Set.prototype.values);$jscomp.Set$install=function(){}};$jscomp.string=$jscomp.string||{};
$jscomp.string.noRegExp_=function(a,b){if(a instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");};
$jscomp.string.fromCodePoint=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];for(var c="",b=$jscomp.makeIterator(b),d=b.next();!d.done;d=b.next()){d=d.value;d=+d;if(0>d||1114111<d||d!==Math.floor(d))throw new RangeError("invalid_code_point "+d);65535>=d?c+=String.fromCharCode(d):(d-=65536,c+=String.fromCharCode(d>>>10&1023|55296),c+=String.fromCharCode(d&1023|56320))}return c};
$jscomp.string.repeat=function(a){var b=this.toString();if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var c="";a;)if(a&1&&(c+=b),a>>>=1)b+=b;return c};$jscomp.string.repeat$install=function(){String.prototype.repeat||(String.prototype.repeat=$jscomp.string.repeat)};
$jscomp.string.codePointAt=function(a){var b=this.toString(),c=b.length;a=Number(a)||0;if(0<=a&&a<c){a|=0;var d=b.charCodeAt(a);if(55296>d||56319<d||a+1===c)return d;a=b.charCodeAt(a+1);return 56320>a||57343<a?d:1024*(d-55296)+a+9216}};$jscomp.string.codePointAt$install=function(){String.prototype.codePointAt||(String.prototype.codePointAt=$jscomp.string.codePointAt)};
$jscomp.string.includes=function(a,b){b=void 0===b?0:b;$jscomp.string.noRegExp_(a,"includes");return-1!==this.toString().indexOf(a,b)};$jscomp.string.includes$install=function(){String.prototype.includes||(String.prototype.includes=$jscomp.string.includes)};
$jscomp.string.startsWith=function(a,b){b=void 0===b?0:b;$jscomp.string.noRegExp_(a,"startsWith");var c=this.toString();a+="";for(var d=c.length,e=a.length,h=Math.max(0,Math.min(b|0,c.length)),k=0;k<e&&h<d;)if(c[h++]!=a[k++])return!1;return k>=e};$jscomp.string.startsWith$install=function(){String.prototype.startsWith||(String.prototype.startsWith=$jscomp.string.startsWith)};
$jscomp.string.endsWith=function(a,b){$jscomp.string.noRegExp_(a,"endsWith");var c=this.toString();a+="";void 0===b&&(b=c.length);for(var d=Math.max(0,Math.min(b|0,c.length)),e=a.length;0<e&&0<d;)if(c[--d]!=a[--e])return!1;return 0>=e};$jscomp.string.endsWith$install=function(){String.prototype.endsWith||(String.prototype.endsWith=$jscomp.string.endsWith)};
ExView.Plugins({info:{name:"漫画岛",version:"2.2",db:"manhuadao",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAE7SURBVDhPlZO9TsMwFIUzMBQCYkViYGGFhYbCwFDgCXgBxMMg8QoMfYEObAxMINY+AyoFqQ5qKySKaNPKvlzbJ44dVdAcyYp9fM+X6/xEWkqpF6ooznTzcBdeZXG2F2FuJBrrdhzU4BRKT3dJJGskDmNSn0O4RCHgaMNBSEq4ViKJ3Z4cCLhlANPzonHrBi6zxJvz9fBVAnCLKOrvrcDl9o83lwP066sLC/2j+b5WCVAzBenZtrlOHtr0c9eyQf0A9ZVhvhYC5CgtQuhqfHttO/kLIBJbrGaT4o4YNJ+7o/gqPUT7FrLOEw2vmgWAYWa/8R8AgazzyJ+ZdOvBxX6w7ysEoEXdgVkjoL6/grWvADC6bNLH+Q6pbAqHaPp8jxl/DydbfJwYKyv9M71iXlmcfc//yB68pWXDUfQLT6VO2MskC3IAAAAASUVORK5CYII=",apihost:"http://mhjk.1391.com/",
pagetitle:["<br>","收藏","最新更新","类型","下载"],download:!0,lazyload:!0,theme:"red",setting:!0,nativeres:!0,cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){ExView.workers.index.loader();ExView.workers.type.loader()}})},flags:{indexflag:{loader:function(a){a.front||a.page||setnowlistname("最新更新","",pluginfo(a.plugin).icon);return{url:pluginfo(a.plugin).apihost+"comic/comicslist?channelid=wandoujia",
method:"POST",data:'{"pageno":"'+(a.page||1)+'","pagesize":"20","sort":"1"}',timeout:120,ua:"android",nativerequest:pluginfo(a.plugin).nativeres,header:{"Content-Type":"application/json",Referer:"","Accept-Encoding":"none"},successfn:function(b,c){ExView.workers.index.countfinder(obj_contact(a,{result:b,header:c}));a.successfn&&a.successfn({result:b,header:c})},errorfn:function(){a.page||setnowlistname("最新更新","",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();mySession.isloading=
0;ExView.fw.alert("网络错误！","ExView")},canclefn:function(){a.page||setnowlistname("最新更新","",pluginfo(a.plugin).icon)},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),name:"最新更新",title:a.title,img:a.img}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){console.log(JSON.stringify(b));array_count(b)?(b=b.info.comicsList,plugfns(a.plugin).pagedeal(b,a)):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',
2)},errorfn:function(){a.page||setnowlistname("最新更新","",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("网络错误！","ExView")}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="0|最新更新|index";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},typeflag:{loader:function(a){return!1},finder:function(a){a.callback({title:"最新更新",
img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"最新更新"});a.callback({tid:"a",listflag:btoa('{"pageno":"{{page}}","pagesize":"20","sort":"3"}'),title:"热门排行",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"热门排行"});a.callback({tid:"a",listflag:btoa('{"pageno":"{{page}}","pagesize":"20","sort":"2"}'),title:"完结漫画",img:pluginfo(a.plugin).icon,group:{name:"daohang",
title:"导航"},content:"完结漫画"});[{subjectid:"1",title:"科幻",image:"http://mhdufile.1391.com/upload/tc/kehuan.png"},{subjectid:"2",title:"魔幻",image:"http://mhdufile.1391.com/upload/tc/mohuan.png"},{subjectid:"3",title:"热血",image:"http://mhdufile.1391.com/upload/mhmflf/rexue.png"},{subjectid:"4",title:"搞笑",image:"http://mhd.ufile.ucloud.com.cn/upload/zxt/sousuotubiao/caiman.jpg"},{subjectid:"5",title:"恋爱",image:"http://mhdufile.1391.com/upload/tc/lianai.png"},
{subjectid:"6",title:"动作",image:"http://mhdufile.1391.com/upload/tc/dongzuo.png"},{subjectid:"7",title:"战争",image:"http://mhdufile.1391.com/upload/tc/zhanzheng.png"},{subjectid:"8",title:"治愈",image:"http://mhdufile.1391.com/upload/tc/zhiyu.png"},{subjectid:"9",title:"恐怖",image:"http://mhdufile.1391.com/upload/mhmflf/kongbu.png"},{subjectid:"10",title:"推理"},{subjectid:"11",title:"体育",image:"http://mhdufile.1391.com/upload/mhmflf/tiyu.png"},
{subjectid:"12",title:"耽美"},{subjectid:"13",title:"百合"},{subjectid:"14",title:"美食",image:"http://mhdufile.1391.com/upload/mhmflf/meishi.png"},{subjectid:"15",title:"校园",image:"http://mhdufile.1391.com/upload/mhmflf/xiaoyuan.png"},{subjectid:"16",title:"销魂"},{subjectid:"17",title:"生肉"},{subjectid:"18",title:"冒险",image:"http://mhdufile.1391.com/upload/tc/maoxian.png"},{subjectid:"19",title:"四格",image:"http://mhdufile.1391.com/upload/tc/bingjiao.png"},
{subjectid:"20",title:"伪娘"},{subjectid:"21",title:"宅男腐女"},{subjectid:"22",title:"音乐舞蹈"},{subjectid:"23",title:"性转换"},{subjectid:"24",title:"东方"},{subjectid:"25",title:"高清单行本"},{subjectid:"26",title:"轻小说"},{subjectid:"27",title:"颜艺"},{subjectid:"28",title:"其他"},{subjectid:"30",title:"彩漫",image:"http://mhdufile.1391.com/upload/tc/caiman.png"},{subjectid:"32",
title:"动漫补完计划"},{subjectid:"34",title:"生活"},{subjectid:"35",title:"同人"},{subjectid:"36",title:"励志",image:"http://mhdufile.1391.com/upload/mhmflf/lizhi.png"},{subjectid:"37",title:"悬疑",image:"http://mhd.ufile.ucloud.com.cn/upload/zxt/sousuotubiao/xiaoshuo.jpg"},{subjectid:"38",title:"条漫"},{subjectid:"39",title:"少年"},{subjectid:"40",title:"少女",image:"http://mhdufile.1391.com/upload/mhmflf/shaonv.png"}].forEach(function(b){a.callback({tid:"b",
listflag:btoa('{"pageno":"{{page}}","pagesize":"20","subjectid":"'+b.subjectid+'","sort":"1"}'),title:b.title,img:b.image||pluginfo(a.plugin).icon,group:{name:"fenlei",title:"分类"},content:b.title})})}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"comic/comicslist?channelid=wandoujia",method:"POST",data:atob(a.flag).replace("{{page}}",a.page||1),timeout:120,ua:"android",nativerequest:pluginfo(a.plugin).nativeres,header:{"Content-Type":"application/json",Referer:"",
"Accept-Encoding":"none"},successfn:function(b,c){b?(ExView.workers.list.countfinder(obj_contact(a,{result:b,header:c})),a.successfn&&a.successfn({result:b,header:c})):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+a.title+"】<br>获取失败！","ExView"))},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),name:"【"+a.title+"】",title:a.title,img:a.img}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){array_count(b)?
(b=b.info.comicsList,plugfns(a.plugin).pagedeal(b)):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="0|"+a.keyword+"|list";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},searchflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"comic/searchbookauthor?pindex="+(parseInt(a.page||1)-1)+
"&psize=20&name="+encodeURIComponent(a.keyword)+"&type=2&version=2&channelid=wandoujia",method:"GET",timeout:120,ua:"android",nativerequest:pluginfo(a.plugin).nativeres,header:{"Content-Type":"application/json",Referer:"","Accept-Encoding":"none"},successfn:function(b,c){b?(a.multsearch||(ExView.workers.search.countfinder(obj_contact(a,{result:b,header:c})),setnowlistname("搜索【"+a.keyword+"】")),a.successfn&&a.successfn({result:b,header:c})):a.multsearch?a.multsearch():(ExView.fw.hidePreloader(),
mySession.isloading=0,ExView.fw.alert("【"+a.keyword+"】<br>获取搜索结果失败！","ExView"))},showinfo:{text:"正在搜索..."+(1<a.page?"<br>第"+a.page+"页":""),name:"【"+a.keyword+"】",title:"搜索"}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b,c,d){console.log(b);array_count(b)?(b=b.info.data.items,plugfns(a.plugin).pagedeal(b,a,"search")):a.multsearch?a.multsearch():addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',
1)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(b){mySession.nowlistpages="0|"+a.keyword+"|search";mySession.nowlistpage=1;console.log(mySession.nowlistpages)}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"comic/downloadcomicsview?bookid="+a.pid+"&channelid=wandoujia",method:"GET",timeout:120,ua:"android",nativerequest:pluginfo(a.plugin).nativeres,header:{"Content-Type":"application/json",Referer:"","Accept-Encoding":"none"},successfn:function(b,
c){b?a.successfn&&a.successfn({result:b,header:c}):a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},showinfo:{text:"正在加载内容页...",title:"内容页",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b,c,d,e){if(array_count(b)){b=b.info.bookPartList;if(a.checkupdate)return{pid:a.pid,cid:b[0].part_id,title:b[0].name};
e=[];for(d=0;d<b.length;d++)e[d]=additemlist({id:b.length-1-d,newest:a.newest&&0==d,pid:a.pid,cid:b[d].part_id,title:b[d].name,count:b.length,reverse:1});return e}a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},afterfn:function(){a.checkupdate||ExView.workers.content.infoloader(a)}}},infoloader:function(a){return{url:pluginfo(a.plugin).apihost+"comic/comicsdetail?bookid="+a.pid+"&channelid=wandoujia",method:"GET",
timeout:120,ua:"android",nativerequest:pluginfo(a.plugin).nativeres,header:{"Content-Type":"application/json",Referer:"","Accept-Encoding":"none"},successfn:function(b,c){b?a.successfn&&a.successfn({result:b,header:c}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},showinfo:{text:"正在加载简介信息...",title:"内容页",name:getlistname(a.pid),img:getlistimg(a.pid)}}},infofinder:function(a){console.log(a);
return{json:!0,str:a.result,successfn:function(b,c,d,e){b=b.info.comicsdetail||{};b=b[0]||{};c=b.coverurl;d=b.book_name;e="<p>"+(1!=b.progresstype?"【完结】":"【连载】")+b.updatedate+"<br>【作者】"+b.book_author.replace(/@@/g,"")+"<br>共"+b.totalpart+"话<br>"+b.book_brief+"</p>";setlistpic({name:d,img:c,added:a.data,description:e,comment:0,preview:0,tags:gettag(d)+gettag(b.book_author.replace(/@@/g,""))});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"comic_v2/comicsread?apptype=8&appversion=1.0&channel=android",method:"POST",data:plugfns(a.plugin).crack.format({bookid:a.pid,partid:a.cid}),postform:!0,timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"正在加载图片信息...",title:"图片",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){console.log(a);return{json:!0,str:a.result,successfn:function(b,c,d,e){array_count(b)?(b=JSON.parse(plugfns(a.plugin).crack.unformat(b.info)),
b=b.pages.map(function(a){return a.imgurl}),console.log(b),a.download?chapterpredownload({source:b,download:a.download,plugin:a.plugin}):chapterviewer({source:b,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.download?chapterpredownload({error:"解析错误！",download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("图片信息获取失败！","ExView"));
return!0}}}},commentflag:{loader:!1,finder:!1},previewflag:{loader:!1,finder:!1,more:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"comic/comicslist?channelid=wandoujia",method:"POST",data:'{"pageno":"'+(a.page||1)+'","pagesize":"20","sort":"1"}',timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{"Content-Type":"application/json",Referer:"","Accept-Encoding":"none"},successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},
finder:function(a){return{json:!0,str:a.result,successfn:function(b){console.log(JSON.stringify(b));array_count(b)&&(b=b.info.comicsList,plugfns(a.plugin).pagedeal(b,a))}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"comic/comicslist?channelid=wandoujia",method:"POST",data:'{"pageno":"'+(a.page||1)+'","pagesize":"20","special":"3","sort":"1"}',timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{"Content-Type":"application/json",Referer:"","Accept-Encoding":"none"},
successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){console.log(JSON.stringify(b));array_count(b)&&(b=b.info.comicsList,plugfns(a.plugin).pagedeal(b,a))}}}}},fns:{crack:function(){$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbolIterator();var a="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(a){return typeof a}:function(a){$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();
return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a},b=function(a,b){var c={},k=c.lib={},t=function(){},p=k.Base={extend:function(a){t.prototype=this;var b=new t;return a&&b.mixIn(a),b.hasOwnProperty("init")||(b.init=function(){b.$super.init.apply(this,arguments)}),b.init.prototype=b,b.$super=this,b},create:function(){var a=this.extend();return a.init.apply(a,arguments),a},init:function(){},mixIn:function(a){for(var b in a)a.hasOwnProperty(b)&&(this[b]=
a[b]);a.hasOwnProperty("toString")&&(this.toString=a.toString)},clone:function(){return this.init.prototype.extend(this)}},q=k.WordArray=p.extend({init:function(a,b){a=this.words=a||[];this.sigBytes=void 0!=b?b:4*a.length},toString:function(a){return(a||f).stringify(this)},concat:function(a){var b=this.words,d=a.words,c=this.sigBytes;if(a=a.sigBytes,this.clamp(),c%4)for(var e=0;e<a;e++)b[c+e>>>2]|=(d[e>>>2]>>>24-e%4*8&255)<<24-(c+e)%4*8;else if(65535<d.length)for(e=0;e<a;e+=4)b[c+e>>>2]=d[e>>>2];
else b.push.apply(b,d);return this.sigBytes+=a,this},clamp:function(){var b=this.words,c=this.sigBytes;b[c>>>2]&=4294967295<<32-c%4*8;b.length=a.ceil(c/4)},clone:function(){var a=p.clone.call(this);return a.words=this.words.slice(0),a},random:function(b){for(var c=[],e=0;e<b;e+=4)c.push(4294967296*a.random()|0);return new q.init(c,b)}}),v=c.enc={},f=v.Hex={stringify:function(a){var b=a.words;a=a.sigBytes;for(var d=[],c=0;c<a;c++){var e=b[c>>>2]>>>24-c%4*8&255;d.push((e>>>4).toString(16));d.push((15&
e).toString(16))}return d.join("")},parse:function(a){for(var b=a.length,d=[],c=0;c<b;c+=2)d[c>>>3]|=parseInt(a.substr(c,2),16)<<24-c%8*4;return new q.init(d,b/2)}},y=v.Latin1={stringify:function(a){var b=a.words;a=a.sigBytes;for(var d=[],c=0;c<a;c++)d.push(String.fromCharCode(b[c>>>2]>>>24-c%4*8&255));return d.join("")},parse:function(a){for(var b=a.length,c=[],d=0;d<b;d++)c[d>>>2]|=(255&a.charCodeAt(d))<<24-d%4*8;return new q.init(c,b)}},A=v.Utf8={stringify:function(a){try{return decodeURIComponent(escape(y.stringify(a)))}catch(b){throw Error("Malformed UTF-8 data");
}},parse:function(a){return y.parse(unescape(encodeURIComponent(a)))}},w=k.BufferedBlockAlgorithm=p.extend({reset:function(){this._data=new q.init;this._nDataBytes=0},_append:function(a){"string"==typeof a&&(a=A.parse(a));this._data.concat(a);this._nDataBytes+=a.sigBytes},_process:function(b){var c=this._data,e=c.words,f=c.sigBytes,h=this.blockSize,x=f/(4*h),x=b?a.ceil(x):a.max((0|x)-this._minBufferSize,0);if(b=x*h,f=a.min(4*b,f),b){for(var w=0;w<b;w+=h)this._doProcessBlock(e,w);w=e.splice(0,b);c.sigBytes-=
f}return new q.init(w,f)},clone:function(){var a=p.clone.call(this);return a._data=this._data.clone(),a},_minBufferSize:0});k.Hasher=w.extend({cfg:p.extend(),init:function(a){this.cfg=this.cfg.extend(a);this.reset()},reset:function(){w.reset.call(this);this._doReset()},update:function(a){return this._append(a),this._process(),this},finalize:function(a){return a&&this._append(a),this._doFinalize()},blockSize:16,_createHelper:function(a){return function(b,c){return(new a.init(c)).finalize(b)}},_createHmacHelper:function(a){return function(b,
c){return(new x.HMAC.init(a,c)).finalize(b)}}});var x=c.algo={};return c}(Math);!function(){var a=b.lib.WordArray;b.enc.Base64={stringify:function(a){var b=a.words,c=a.sigBytes,d=this._map;a.clamp();a=[];for(var p=0;p<c;p+=3)for(var q=(b[p>>>2]>>>24-p%4*8&255)<<16|(b[p+1>>>2]>>>24-(p+1)%4*8&255)<<8|b[p+2>>>2]>>>24-(p+2)%4*8&255,v=0;4>v&&p+.75*v<c;v++)a.push(d.charAt(q>>>6*(3-v)&63));if(b=d.charAt(64))for(;a.length%4;)a.push(b);return a.join("")},parse:function(b){var c=b.length,k=this._map,t=k.charAt(64);
t&&-1!=(t=b.indexOf(t))&&(c=t);for(var t=[],p=0,q=0;q<c;q++)if(q%4){var v=k.indexOf(b.charAt(q-1))<<q%4*2,f=k.indexOf(b.charAt(q))>>>6-q%4*2;t[p>>>2]|=(v|f)<<24-p%4*8;p++}return a.create(t,p)},_map:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/="}}();(function(a){function c(a,b,d,e,u,B,f){return((a=a+(b&d|~b&e)+u+f)<<B|a>>>32-B)+b}function h(a,b,c,d,u,e,f){return((a=a+(b&d|c&~d)+u+f)<<e|a>>>32-e)+b}function k(a,b,c,d,u,e,f){return((a=a+(b^c^d)+u+f)<<e|a>>>32-e)+b}function t(a,b,
c,d,u,e,f){return((a=a+(c^(b|~d))+u+f)<<e|a>>>32-e)+b}for(var p=b.lib,q=p.WordArray,v=p.Hasher,p=b.algo,f=[],y=0;64>y;y++)f[y]=4294967296*a.abs(a.sin(y+1))|0;p=p.MD5=v.extend({_doReset:function(){this._hash=new q.init([1732584193,4023233417,2562383102,271733878])},_doProcessBlock:function(a,b){for(var d=0;16>d;d++){var z=b+d,u=a[z];a[z]=16711935&(u<<8|u>>>24)|4278255360&(u<<24|u>>>8)}var d=this._hash.words,z=a[b+0],u=a[b+1],B=a[b+2],C=a[b+3],D=a[b+4],p=a[b+5],q=a[b+6],r=a[b+7],v=a[b+8],E=a[b+9],F=
a[b+10],G=a[b+11],y=a[b+12],H=a[b+13],I=a[b+14],J=a[b+15],g=d[0],n=d[1],l=d[2],m=d[3],g=c(g,n,l,m,z,7,f[0]),m=c(m,g,n,l,u,12,f[1]),l=c(l,m,g,n,B,17,f[2]),n=c(n,l,m,g,C,22,f[3]),g=c(g,n,l,m,D,7,f[4]),m=c(m,g,n,l,p,12,f[5]),l=c(l,m,g,n,q,17,f[6]),n=c(n,l,m,g,r,22,f[7]),g=c(g,n,l,m,v,7,f[8]),m=c(m,g,n,l,E,12,f[9]),l=c(l,m,g,n,F,17,f[10]),n=c(n,l,m,g,G,22,f[11]),g=c(g,n,l,m,y,7,f[12]),m=c(m,g,n,l,H,12,f[13]),l=c(l,m,g,n,I,17,f[14]),n=c(n,l,m,g,J,22,f[15]),g=h(g,n,l,m,u,5,f[16]),m=h(m,g,n,l,q,9,f[17]),
l=h(l,m,g,n,G,14,f[18]),n=h(n,l,m,g,z,20,f[19]),g=h(g,n,l,m,p,5,f[20]),m=h(m,g,n,l,F,9,f[21]),l=h(l,m,g,n,J,14,f[22]),n=h(n,l,m,g,D,20,f[23]),g=h(g,n,l,m,E,5,f[24]),m=h(m,g,n,l,I,9,f[25]),l=h(l,m,g,n,C,14,f[26]),n=h(n,l,m,g,v,20,f[27]),g=h(g,n,l,m,H,5,f[28]),m=h(m,g,n,l,B,9,f[29]),l=h(l,m,g,n,r,14,f[30]),n=h(n,l,m,g,y,20,f[31]),g=k(g,n,l,m,p,4,f[32]),m=k(m,g,n,l,v,11,f[33]),l=k(l,m,g,n,G,16,f[34]),n=k(n,l,m,g,I,23,f[35]),g=k(g,n,l,m,u,4,f[36]),m=k(m,g,n,l,D,11,f[37]),l=k(l,m,g,n,r,16,f[38]),n=k(n,
l,m,g,F,23,f[39]),g=k(g,n,l,m,H,4,f[40]),m=k(m,g,n,l,z,11,f[41]),l=k(l,m,g,n,C,16,f[42]),n=k(n,l,m,g,q,23,f[43]),g=k(g,n,l,m,E,4,f[44]),m=k(m,g,n,l,y,11,f[45]),l=k(l,m,g,n,J,16,f[46]),n=k(n,l,m,g,B,23,f[47]),g=t(g,n,l,m,z,6,f[48]),m=t(m,g,n,l,r,10,f[49]),l=t(l,m,g,n,I,15,f[50]),n=t(n,l,m,g,p,21,f[51]),g=t(g,n,l,m,y,6,f[52]),m=t(m,g,n,l,C,10,f[53]),l=t(l,m,g,n,F,15,f[54]),n=t(n,l,m,g,u,21,f[55]),g=t(g,n,l,m,v,6,f[56]),m=t(m,g,n,l,J,10,f[57]),l=t(l,m,g,n,q,15,f[58]),n=t(n,l,m,g,H,21,f[59]),g=t(g,n,
l,m,D,6,f[60]),m=t(m,g,n,l,G,10,f[61]),l=t(l,m,g,n,B,15,f[62]),n=t(n,l,m,g,E,21,f[63]);d[0]=d[0]+g|0;d[1]=d[1]+n|0;d[2]=d[2]+l|0;d[3]=d[3]+m|0},_doFinalize:function(){var b=this._data,c=b.words,e=8*this._nDataBytes,f=8*b.sigBytes;c[f>>>5]|=128<<24-f%32;var u=a.floor(e/4294967296);c[15+(f+64>>>9<<4)]=16711935&(u<<8|u>>>24)|4278255360&(u<<24|u>>>8);c[14+(f+64>>>9<<4)]=16711935&(e<<8|e>>>24)|4278255360&(e<<24|e>>>8);b.sigBytes=4*(c.length+1);this._process();b=this._hash;c=b.words;for(e=0;4>e;e++)f=c[e],
c[e]=16711935&(f<<8|f>>>24)|4278255360&(f<<24|f>>>8);return b},clone:function(){var a=v.clone.call(this);return a._hash=this._hash.clone(),a}});b.MD5=v._createHelper(p);b.HmacMD5=v._createHmacHelper(p)})(Math);(function(){var a=b.lib,c=a.Base,h=a.WordArray,a=b.algo,k=a.EvpKDF=c.extend({cfg:c.extend({keySize:4,hasher:a.MD5,iterations:1}),init:function(a){this.cfg=this.cfg.extend(a)},compute:function(a,b){for(var c=this.cfg,d=c.hasher.create(),e=h.create(),k=e.words,A=c.keySize,c=c.iterations;k.length<
A;){w&&d.update(w);var w=d.update(a).finalize(b);d.reset();for(var x=1;x<c;x++)w=d.finalize(w),d.reset();e.concat(w)}return e.sigBytes=4*A,e}});b.EvpKDF=function(a,b,c){return k.create(c).compute(a,b)}})();b.lib.Cipher||function(a){a=b;var c=a.lib,h=c.Base,k=c.WordArray,t=c.BufferedBlockAlgorithm,p=a.enc.Base64,q=a.algo.EvpKDF,v=c.Cipher=t.extend({cfg:h.extend(),createEncryptor:function(a,b){return this.create(this._ENC_XFORM_MODE,a,b)},createDecryptor:function(a,b){return this.create(this._DEC_XFORM_MODE,
a,b)},init:function(a,b,c){this.cfg=this.cfg.extend(c);this._xformMode=a;this._key=b;this.reset()},reset:function(){t.reset.call(this);this._doReset()},process:function(a){return this._append(a),this._process()},finalize:function(a){return a&&this._append(a),this._doFinalize()},keySize:4,ivSize:4,_ENC_XFORM_MODE:1,_DEC_XFORM_MODE:2,_createHelper:function(a){return{encrypt:function(b,c,d){return("string"==typeof c?z:x).encrypt(a,b,c,d)},decrypt:function(b,c,d){return("string"==typeof c?z:x).decrypt(a,
b,c,d)}}}});c.StreamCipher=v.extend({_doFinalize:function(){return this._process(!0)},blockSize:1});var f=a.mode={},y=function(a,b,c){var d=this._iv;d?this._iv=void 0:d=this._prevBlock;for(var e=0;e<c;e++)a[b+e]^=d[e]},A=(c.BlockCipherMode=h.extend({createEncryptor:function(a,b){return this.Encryptor.create(a,b)},createDecryptor:function(a,b){return this.Decryptor.create(a,b)},init:function(a,b){this._cipher=a;this._iv=b}})).extend();A.Encryptor=A.extend({processBlock:function(a,b){var c=this._cipher,
d=c.blockSize;y.call(this,a,b,d);c.encryptBlock(a,b);this._prevBlock=a.slice(b,b+d)}});A.Decryptor=A.extend({processBlock:function(a,b){var c=this._cipher,d=c.blockSize,e=a.slice(b,b+d);c.decryptBlock(a,b);y.call(this,a,b,d);this._prevBlock=e}});f=f.CBC=A;A=(a.pad={}).Pkcs7={pad:function(a,b){for(var c=4*b,c=c-a.sigBytes%c,d=c<<24|c<<16|c<<8|c,e=[],f=0;f<c;f+=4)e.push(d);c=k.create(e,c);a.concat(c)},unpad:function(a){a.sigBytes-=255&a.words[a.sigBytes-1>>>2]}};c.BlockCipher=v.extend({cfg:v.cfg.extend({mode:f,
padding:A}),reset:function(){v.reset.call(this);var a=this.cfg,b=a.iv,a=a.mode;if(this._xformMode==this._ENC_XFORM_MODE)var c=a.createEncryptor;else c=a.createDecryptor,this._minBufferSize=1;this._mode=c.call(a,this,b&&b.words)},_doProcessBlock:function(a,b){this._mode.processBlock(a,b)},_doFinalize:function(){var a=this.cfg.padding;if(this._xformMode==this._ENC_XFORM_MODE){a.pad(this._data,this.blockSize);var b=this._process(!0)}else b=this._process(!0),a.unpad(b);return b},blockSize:4});var w=c.CipherParams=
h.extend({init:function(a){this.mixIn(a)},toString:function(a){return(a||this.formatter).stringify(this)}}),f=(a.format={}).OpenSSL={stringify:function(a){var b=a.ciphertext;return a=a.salt,(a?k.create([1398893684,1701076831]).concat(a).concat(b):b).toString(p)},parse:function(a){a=p.parse(a);var b=a.words;if(1398893684==b[0]&&1701076831==b[1]){var c=k.create(b.slice(2,4));b.splice(0,4);a.sigBytes-=16}return w.create({ciphertext:a,salt:c})}},x=c.SerializableCipher=h.extend({cfg:h.extend({format:f}),
encrypt:function(a,b,c,d){d=this.cfg.extend(d);var e=a.createEncryptor(c,d);return b=e.finalize(b),e=e.cfg,w.create({ciphertext:b,key:c,iv:e.iv,algorithm:a,mode:e.mode,padding:e.padding,blockSize:a.blockSize,formatter:d.format})},decrypt:function(a,b,c,d){return d=this.cfg.extend(d),b=this._parse(b,d.format),a.createDecryptor(c,d).finalize(b.ciphertext)},_parse:function(a,b){return"string"==typeof a?b.parse(a,this):a}});a=(a.kdf={}).OpenSSL={execute:function(a,b,c,d){return d||(d=k.random(8)),a=q.create({keySize:b+
c}).compute(a,d),c=k.create(a.words.slice(b),4*c),a.sigBytes=4*b,w.create({key:a,iv:c,salt:d})}};var z=c.PasswordBasedCipher=x.extend({cfg:x.cfg.extend({kdf:a}),encrypt:function(a,b,c,d){return d=this.cfg.extend(d),c=d.kdf.execute(c,a.keySize,a.ivSize),d.iv=c.iv,a=x.encrypt.call(this,a,b,c.key,d),a.mixIn(c),a},decrypt:function(a,b,c,d){return d=this.cfg.extend(d),b=this._parse(b,d.format),c=d.kdf.execute(c,a.keySize,a.ivSize,b.salt),d.iv=c.iv,x.decrypt.call(this,a,b,c.key,d)}})}();(function(){for(var a=
b.lib.BlockCipher,c=b.algo,h=[],k=[],t=[],p=[],q=[],v=[],f=[],y=[],A=[],w=[],x=[],z=0;256>z;z++)x[z]=128>z?z<<1:z<<1^283;for(var u=0,B=0,z=0;256>z;z++){var C=B^B<<1^B<<2^B<<3^B<<4,C=C>>>8^255&C^99;h[u]=C;k[C]=u;var D=x[u],K=x[D],L=x[K],r=257*x[C]^16843008*C;t[u]=r<<24|r>>>8;p[u]=r<<16|r>>>16;q[u]=r<<8|r>>>24;v[u]=r;r=16843009*L^65537*K^257*D^16843008*u;f[C]=r<<24|r>>>8;y[C]=r<<16|r>>>16;A[C]=r<<8|r>>>24;w[C]=r;u?(u=D^x[x[x[L^D]]],B^=x[x[B]]):u=B=1}var M=[0,1,2,4,8,16,32,64,128,27,54],c=c.AES=a.extend({_doReset:function(){for(var a=
this._key,b=a.words,c=a.sigBytes/4,a=4*((this._nRounds=c+6)+1),d=this._keySchedule=[],e=0;e<a;e++)if(e<c)d[e]=b[e];else{var k=d[e-1];e%c?6<c&&4==e%c&&(k=h[k>>>24]<<24|h[k>>>16&255]<<16|h[k>>>8&255]<<8|h[255&k]):(k=k<<8|k>>>24,k=h[k>>>24]<<24|h[k>>>16&255]<<16|h[k>>>8&255]<<8|h[255&k],k^=M[e/c|0]<<24);d[e]=d[e-c]^k}b=this._invKeySchedule=[];for(c=0;c<a;c++)e=a-c,k=c%4?d[e]:d[e-4],b[c]=4>c||4>=e?k:f[h[k>>>24]]^y[h[k>>>16&255]]^A[h[k>>>8&255]]^w[h[255&k]]},encryptBlock:function(a,b){this._doCryptBlock(a,
b,this._keySchedule,t,p,q,v,h)},decryptBlock:function(a,b){var c=a[b+1];a[b+1]=a[b+3];a[b+3]=c;this._doCryptBlock(a,b,this._invKeySchedule,f,y,A,w,k);c=a[b+1];a[b+1]=a[b+3];a[b+3]=c},_doCryptBlock:function(a,b,c,d,e,f,h,g){for(var n=this._nRounds,l=a[b]^c[0],m=a[b+1]^c[1],k=a[b+2]^c[2],u=a[b+3]^c[3],r=4,x=1;x<n;x++)var p=d[l>>>24]^e[m>>>16&255]^f[k>>>8&255]^h[255&u]^c[r++],t=d[m>>>24]^e[k>>>16&255]^f[u>>>8&255]^h[255&l]^c[r++],q=d[k>>>24]^e[u>>>16&255]^f[l>>>8&255]^h[255&m]^c[r++],u=d[u>>>24]^e[l>>>
16&255]^f[m>>>8&255]^h[255&k]^c[r++],l=p,m=t,k=q;p=(g[l>>>24]<<24|g[m>>>16&255]<<16|g[k>>>8&255]<<8|g[255&u])^c[r++];t=(g[m>>>24]<<24|g[k>>>16&255]<<16|g[u>>>8&255]<<8|g[255&l])^c[r++];q=(g[k>>>24]<<24|g[u>>>16&255]<<16|g[l>>>8&255]<<8|g[255&m])^c[r++];u=(g[u>>>24]<<24|g[l>>>16&255]<<16|g[m>>>8&255]<<8|g[255&k])^c[r++];a[b]=p;a[b+1]=t;a[b+2]=q;a[b+3]=u},keySize:8});b.AES=a._createHelper(c)})();(function(){function b(a){return 10>a?"0"+h:a}function c(){return this.valueOf()}function h(a){return q.lastIndex=
0,q.test(a)?'"'+a.replace(q,function(a){return"string"==typeof A[a]?p:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function k(b,c){var d,e,p,t,q,v=f,r=c[b];switch(r&&"object"===(void 0===r?"undefined":a(r))&&"function"==typeof r.toJSON&&(r=r.toJSON(b)),"function"==typeof w&&(r=w.call(c,b,r)),void 0===r?"undefined":a(r)){case "string":return h(r);case "number":return isFinite(r)?String(r):"null";case "boolean":case "null":return String(r);case "object":if(!r)return"null";if(f+=
y,q=[],"[object Array]"===Object.prototype.toString.apply(r)){t=r.length;for(d=0;d<t;d+=1)q[d]=k(d,r)||"null";return p=0===q.length?"[]":f?"[\n"+f+q.join(",\n"+f)+"\n"+v+"]":"["+q.join(",")+"]",f=v,p}if(w&&"object"===(void 0===w?"undefined":a(w)))for(t=w.length,d=0;d<t;d+=1)"string"==typeof w[d]&&(e=w[d],(p=k(e,r))&&q.push(h(e)+(f?": ":":")+p));else for(e in r)Object.prototype.hasOwnProperty.call(r,e)&&(p=k(e,r))&&q.push(h(e)+(f?": ":":")+p);return p=0===q.length?"{}":f?"{\n"+f+q.join(",\n"+f)+"\n"+
v+"}":"{"+q.join(",")+"}",f=v,p}}var t=/^[\],:{}\s]*$/,p=/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,q=/[\\\" --­؀-؄܏឴឵‌-‏ - ⁠-⁯﻿￰-￿]/g,v=/[ ­؀-؄܏឴឵‌-‏ - ⁠-⁯﻿￰-￿]/g;"function"!=typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+b(this.getUTCMonth()+
1)+"-"+b(this.getUTCDate())+"T"+b(this.getUTCHours())+":"+b(this.getUTCMinutes())+":"+b(this.getUTCSeconds())+"Z":null},Boolean.prototype.toJSON=c,Number.prototype.toJSON=c,String.prototype.toJSON=c);var f,y,A,w;"function"!=typeof JSON.stringify&&(A={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},JSON.stringify=function(b,c,d){var e;if(f="",y="","number"==typeof d)for(e=0;e<d;e+=1)y+=" ";else"string"==typeof d&&(y=d);if(w=c,c&&"function"!=typeof c&&("object"!==(void 0===
c?"undefined":a(c))||"number"!=typeof c.length))throw Error("JSON.stringify");return k("",{"":b})});"function"!=typeof JSON.parse&&(JSON.parse=function(b,c){function d(b,e){var f,k,h=b[e];if(h&&"object"===(void 0===h?"undefined":a(h)))for(f in h)Object.prototype.hasOwnProperty.call(h,f)&&(k=d(h,f),void 0!==k?h[f]=k:delete h[f]);return c.call(b,e,h)}var e;if(b=String(b),v.lastIndex=0,v.test(b)&&(b=b.replace(v,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})),t.test(b.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,
"@").replace(p,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+b+")"),"function"==typeof c?d({"":e},""):e;throw new SyntaxError("JSON.parse");})})();var c={key:b.enc.Utf8.parse("r4rt5A8L6ye6ts8y"),iv:b.enc.Utf8.parse("fs0Hkjg8a23u8sE0"),mode:b.mode.CBC,padding:b.pad.Pkcs7,getAesString:function(a){return b.AES.encrypt(a,this.key,this)},getDAesString:function(a){return b.AES.decrypt(a,this.key,this).toString(b.enc.Utf8)}};return{format:function(a){return encodeURIComponent(c.getAesString(JSON.stringify(a)))},
unformat:function(a){return c.getDAesString(a)},domain:"https://mhjkm.1391.com",payDomain:"https://mhdpay.1391.com",param:"?apptype=8&appversion=1.0&channel=web-app",payParam:"?apptype=8&appversion=1.0&channel=web-app"}}(),pagedeal:function(a,b,c){b=b||{};a.length||(b.multsearch||b.multupdate||b.multhot?(b.multsearch&&b.multsearch(),b.multupdate&&b.multupdate(),b.multhot&&b.multhot()):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',
1));for(var d=0;d<a.length;d++){var e=a[d].book_id||a[d].id,h=a[d].coverurl||"img/nopic.png",k=a[d].book_name||a[d].name,t="【"+a[d].subject_name+"】";if(a[d].name)p="【"+(a[d].author?a[d].author.replace(/@@/g,"|"):"")+"】"+a[d].name+"【共"+a[d].partnumber+"话】",q=("1"!=a[d].progresstype?"【完结】":"【连载】")+(a[d].updatedate?" "+a[d].updatedate:"");else var p="【"+(a[d].book_author?a[d].book_author.replace(/@@/g,"|"):"")+"】"+
a[d].book_name+"【共"+a[d].totalpart+"话】",q=("1"!=a[d].progresstype?"【完结】":"【连载】")+(a[d].lastpartname?"更新至"+a[d].lastpartname:"");"search"==c&&(e=getstr(/coverimages\/(\d+)\//,h));b.multupdate?b.multupdate(obj_contact(b,{pid:e,img:h,title:k,content:q})):b.multhot?b.multhot(obj_contact(b,{pid:e,img:h,title:k,content:q})):b.multsearch?b.multsearch(obj_contact(b,{pid:e,img:h,title:k,content:q})):addcardlist({pid:e,title:k,name:p,
img:h,stitle:t,content:q,comment:0})}}}});
