ExView.Plugins({info:{name:"漫画岛",version:"2.2",db:"manhuadao",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAE7SURBVDhPlZO9TsMwFIUzMBQCYkViYGGFhYbCwFDgCXgBxMMg8QoMfYEObAxMINY+AyoFqQ5qKySKaNPKvlzbJ44dVdAcyYp9fM+X6/xEWkqpF6ooznTzcBdeZXG2F2FuJBrrdhzU4BRKT3dJJGskDmNSn0O4RCHgaMNBSEq4ViKJ3Z4cCLhlANPzonHrBi6zxJvz9fBVAnCLKOrvrcDl9o83lwP066sLC/2j+b5WCVAzBenZtrlOHtr0c9eyQf0A9ZVhvhYC5CgtQuhqfHttO/kLIBJbrGaT4o4YNJ+7o/gqPUT7FrLOEw2vmgWAYWa/8R8AgazzyJ+ZdOvBxX6w7ysEoEXdgVkjoL6/grWvADC6bNLH+Q6pbAqHaPp8jxl/DydbfJwYKyv9M71iXlmcfc//yB68pWXDUfQLT6VO2MskC3IAAAAASUVORK5CYII=",
apihost:"http://mhjk.1391.com/",pagetitle:["<br>","收藏","最新更新","类型","下载"],download:!0,lazyload:!0,theme:"red",setting:!0,nativeres:!0,cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){ExView.workers.index.loader();ExView.workers.type.loader()}})},flags:{indexflag:{loader:function(a){a.front||a.page||setnowlistname("最新更新","",pluginfo(a.plugin).icon);return{url:pluginfo(a.plugin).apihost+
"comic/comicslist?channelid=wandoujia",method:"POST",data:'{"pageno":"'+(a.page||1)+'","pagesize":"20","sort":"1"}',timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{"Content-Type":"application/json",Referer:""},successfn:function(b,c){ExView.workers.index.countfinder(obj_contact(a,{result:b,header:c}));a.successfn&&a.successfn({result:b,header:c})},errorfn:function(){a.page||setnowlistname("最新更新","",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();mySession.isloading=
0;ExView.fw.alert("网络错误！","ExView")},canclefn:function(){a.page||setnowlistname("最新更新","",pluginfo(a.plugin).icon)},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),name:"最新更新",title:a.title,img:a.img}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){console.log(JSON.stringify(b));array_count(b)?(b=b.info.comicsList,plugfns(a.plugin).pagedeal(b,a)):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',
2)},errorfn:function(){a.page||setnowlistname("最新更新","",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("网络错误！","ExView")}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="0|最新更新|index";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},typeflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"comic/recommendspecial?channelid=wandoujia",
method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{"Content-Type":"application/json",Referer:""},successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){addtypelist({title:"最新更新",img:pluginfo(a.plugin).icon,content:"最新更新"});return{json:!0,str:a.result,successfn:function(a){if(array_count(a)){a=a.info.specials;for(var c=0;c<a.length;c++)addtypelist({tid:a[c].specialid,title:a[c].name,img:a[c].coverurl,
listbg:!0,content:a[c].name})}else addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>加载失败，请刷新重试！</a></div>',2)}}}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"comic/comicslist?channelid=wandoujia",method:"POST",data:'{"pageno":"'+(a.page||1)+'","pagesize":"20","special":"'+a.keyword+'","sort":"1"}',timeout:120,nativerequest:pluginfo(a.plugin).nativeres,
header:{"Content-Type":"application/json",Referer:""},successfn:function(b,c){b?(ExView.workers.list.countfinder(obj_contact(a,{result:b,header:c})),a.successfn&&a.successfn({result:b,header:c})):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+a.title+"】<br>获取失败！","ExView"))},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),name:"【"+a.title+"】",title:a.title,img:a.img}}},finder:function(a){return{json:!0,
str:a.result,successfn:function(b){array_count(b)?(b=b.info.comicsList,plugfns(a.plugin).pagedeal(b)):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="0|"+a.keyword+"|list";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},searchflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"comic/searchbookauthor?pindex="+
(parseInt(a.page||1)-1)+"&psize=20&name="+encodeURIComponent(a.keyword)+"&type=2&channelid=wandoujia",method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{"Content-Type":"application/json",Referer:""},successfn:function(b,c){b?(a.multsearch||(ExView.workers.search.countfinder(obj_contact(a,{result:b,header:c})),setnowlistname("搜索【"+a.keyword+"】")),a.successfn&&a.successfn({result:b,header:c})):a.multsearch?a.multsearch():(ExView.fw.hidePreloader(),mySession.isloading=
0,ExView.fw.alert("【"+a.keyword+"】<br>获取搜索结果失败！","ExView"))},showinfo:{text:"正在搜索..."+(1<a.page?"<br>第"+a.page+"页":""),name:"【"+a.keyword+"】",title:"搜索"}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b,c,d){console.log(b);array_count(b)?(b=b.info.data.items,plugfns(a.plugin).pagedeal(b,a)):a.multsearch?a.multsearch():addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',
1)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(b){mySession.nowlistpages="0|"+a.keyword+"|search";mySession.nowlistpage=1;console.log(mySession.nowlistpages)}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"comic/downloadcomicsview?bookid="+a.pid+"&channelid=wandoujia",method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{"Content-Type":"application/json",Referer:""},successfn:function(b,c){b?a.successfn&&a.successfn({result:b,
header:c}):a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},showinfo:{text:"正在加载内容页...",title:"内容页",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b,c,d,e){if(array_count(b)){b=b.info.bookPartList;if(a.checkupdate)return{pid:a.pid,cid:b[0].part_id,title:b[0].name};e=[];for(d=0;d<b.length;d++)e[d]=
additemlist({id:b.length-1-d,newest:a.newest&&0==d,pid:a.pid,cid:b[d].part_id,title:b[d].name,count:b.length,reverse:1});return e}a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},afterfn:function(){a.checkupdate||ExView.workers.content.infoloader(a)}}},infoloader:function(a){return{url:pluginfo(a.plugin).apihost+"comic/comicsdetail?bookid="+a.pid+"&channelid=wandoujia",method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,
header:{"Content-Type":"application/json",Referer:""},successfn:function(b,c){b?a.successfn&&a.successfn({result:b,header:c}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},showinfo:{text:"正在加载简介信息...",title:"内容页",name:getlistname(a.pid),img:getlistimg(a.pid)}}},infofinder:function(a){console.log(a);return{json:!0,str:a.result,successfn:function(b,c,d,e){b=b.info.comicsdetail||
{};b=b[0]||{};c=b.coverurl;d=b.book_name;e="<p>"+(1!=b.progresstype?"【完结】":"【连载】")+b.updatedate+"<br>【作者】"+b.book_author.replace(/@@/g,"")+"<br>共"+b.totalpart+"话<br>"+b.book_brief+"</p>";setlistpic({name:d,img:c,added:a.data,description:e,comment:0,preview:0,tags:gettag(d)+gettag(b.book_author.replace(/@@/g,""))});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"comic/comicsread?bookid="+a.pid+"&partid="+
a.cid+"&channelid=wandoujia",method:"GET",timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{"Content-Type":"application/json",Referer:""},successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"正在加载图片信息...",title:"图片",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){console.log(a);return{json:!0,str:a.result,successfn:function(b,c,d,e){array_count(b)?(b=b.info.bookreaddetail.pics,console.log(b),
a.download?chapterpredownload({source:b,download:a.download,plugin:a.plugin}):chapterviewer({source:b,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.download?chapterpredownload({error:"解析错误！",download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("图片信息获取失败！","ExView"));return!0}}}},commentflag:{loader:!1,finder:!1},previewflag:{loader:!1,
finder:!1,more:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"comic/comicslist?channelid=wandoujia",method:"POST",data:'{"pageno":"'+(a.page||1)+'","pagesize":"20","sort":"1"}',timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{"Content-Type":"application/json",Referer:""},successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){console.log(JSON.stringify(b));
array_count(b)&&(b=b.info.comicsList,plugfns(a.plugin).pagedeal(b,a))}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"comic/comicslist?channelid=wandoujia",method:"POST",data:'{"pageno":"'+(a.page||1)+'","pagesize":"20","special":"3","sort":"1"}',timeout:120,nativerequest:pluginfo(a.plugin).nativeres,header:{"Content-Type":"application/json",Referer:""},successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){console.log(JSON.stringify(b));
array_count(b)&&(b=b.info.comicsList,plugfns(a.plugin).pagedeal(b,a))}}}}},fns:{pagedeal:function(a,b){b=b||{};a.length||(b.multsearch||b.multupdate||b.multhot?(b.multsearch&&b.multsearch(),b.multupdate&&b.multupdate(),b.multhot&&b.multhot()):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1));for(var c=0;c<a.length;c++){var d=a[c].book_id||a[c].id,e=a[c].coverurl||"img/nopic.png",g=a[c].book_name||a[c].name,k="【"+a[c].subject_name+
"】";if(a[c].name)h="【"+(a[c].author?a[c].author.replace(/@@/g,"|"):"")+"】"+a[c].name+"【共"+a[c].partnumber+"话】",f=("1"!=a[c].progresstype?"【完结】":"【连载】")+(a[c].updatedate?" "+a[c].updatedate:"");else var h="【"+(a[c].book_author?a[c].book_author.replace(/@@/g,"|"):"")+"】"+a[c].book_name+"【共"+a[c].totalpart+"话】",f=("1"!=a[c].progresstype?"【完结】":"【连载】")+(a[c].lastpartname?
"更新至"+a[c].lastpartname:"");b.multupdate?b.multupdate(obj_contact(b,{pid:d,img:e,title:g,content:f})):b.multhot?b.multhot(obj_contact(b,{pid:d,img:e,title:g,content:f})):b.multsearch?b.multsearch(obj_contact(b,{pid:d,img:e,title:g,content:f})):addcardlist({pid:d,title:g,name:h,img:e,stitle:k,content:f,comment:0})}}}});
