ExView.Plugins({info:{name:"M绅士漫画",version:"2.2",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAABelBMVEX////FFraSmJI/ADnnHNb9//33/vjs8ezg0N/vKN5ucG7t8u7uC9vtAdnGPLujpqOxFaNbAFH8/Pz6/fv3BePg2d/wJN/rHNrRzdDgGtDjANDbGcrGvcbRJMLPFr++u77FRbvLG7uvsa+9Cq+zWKusD56Zm5mKjouRI4dpEWFWGlFMAEQ6ETY8ADbt7O34C+Xk4uTk2OPxC97vG93eztzvC9zoK9nrBNfmFtXlHtTT3dPmB9PTpc/RhsvSgMvHzsjLfsTDx8PRBcDPEL/PAr7QAL7JOb3ODL3CcbzJF7nGIri/Ybe7brS7S7LBE7K+JrGtrq2toqyumay6Fay1Raunr6iwHKOsPaKgeZ2pHJyZdZaVlZWkAJWbNpOXTJGMUYeTDIePJ4aMNoWHEX16XHd2dnZ/A3N0K250JG52EG1rY2tmamdvAGNmFV9gS15oAF1jGVxgDlhRVFFOTk5TFE1SEkxGKkNEE0BDET9CDD03ETQmACIbBxkIAAatfIUBAAAA3UlEQVQY013OxXLCUABG4b+FG6Bpm2CF4u51d3d3xd3d4d3JDNnAzFl9q4ODw2ObXiKZ49rRm2x+fOxSxvTFltn6eWvaV8bKKHkKf8b7699EWEfjpOeG9vw/QhEq42VXAEeXhWpJcSkCKkWDGJhcmMD8leGBBqnmztY5EHBgD+pkIPHku3IIqtPUMwCZnCJDEO79vMoBtYNZ5GFV80UDU/22mofpmVkRB9438ShIzeNww38INzR3BHBKn5aBI88jthXWwIuFyQpc3xbG2Qhhc01rdzd9rTwbrXV8ddcADUsjxxYfU1QAAAAASUVORK5CYII=",
db:"mhentai",apihost:"https://www.load.la/",pagetitle:["<br>","收藏","首页","类型","下载"],download:!0,lazyload:!0,setting:!0,settingextra:getui([{name:"typebox",title:"类型方块界面",type:"checkbox"}]),nativeres:!0,theme:"purple",cdn:""},set:function(a){},unset:function(a){setloginscreen(!1)},init:function(a){ExView.workers.fav.listloader({callback:function(){}})},flags:{indexflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+(1<
parseInt(a.page||1)?"?num="+20*(parseInt(a.page||1)-1):""),timeout:120,referer:pluginfo(a.plugin).apihost,cookie:"__cfduid=d44ebf8c1c384f439a5b3caf7c48def9d1502505707; xo=1",successfn:function(b,c){a.callback&&a.callback({img:pluginfo(a.plugin).icon,multpage:!0,result:b,header:c})}}},finder:function(a){return{query:!0,selector:"#search_gallery_item",str:a.result,successfn:function(b){console.log(b);array_count(b)?plugfns(a.plugin).pagedeal(b,a,"index"):a.callback()}}},countloader:!1,countfinder:function(a){return{successfn:function(b){b=
getstrs(a.result,/search\.load\.la\/\?related\=([\w,\d]+)/g,"$1");plugfns(a.plugin).tags=b;a.callback&&a.callback({pagecount:0})}}}},typeflag:{loader:!1,finder:function(a){return{successfn:function(b){a.callback({title:"首页",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"首页"});a.callback({tid:"fav",listflag:"https://my.load.la/river2.php?num={{pagestart}}",title:"最新收藏",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},
content:"最新收藏"});a.callback({tid:"list",listflag:"https://my.load.la/?date=today&num={{pagestart}}",title:"今日排行",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"今日排行"});a.callback({tid:"list",listflag:"https://my.load.la/?date=week&num={{pagestart}}",title:"一周排行",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"一周排行"});a.callback({tid:"list",
listflag:"https://my.load.la/?date=month&num={{pagestart}}",title:"月度排行",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"月度排行"});a.callback({tid:"list",listflag:"https://my.load.la/?date=year&num={{pagestart}}",title:"全年排行",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"全年排行"});a.callback({tid:"fav",listflag:"https://search.load.la/?tag=color&num={{pagestart}}",
title:"全彩",img:pluginfo(a.plugin).icon,group:{name:"fenlei",title:"分类"},content:"全彩"});a.callback({tid:"fav",listflag:"https://search.load.la/?pages=short&num={{pagestart}}",title:"短篇（1-15）",img:pluginfo(a.plugin).icon,group:{name:"fenlei",title:"分类"},content:"短篇（1-15）"});a.callback({tid:"fav",listflag:"https://search.load.la/?pages=medium&num={{pagestart}}",title:"中篇（16-40）",img:pluginfo(a.plugin).icon,
group:{name:"fenlei",title:"分类"},content:"中篇（16-40）"});a.callback({tid:"fav",listflag:"https://search.load.la/?pages=large&num={{pagestart}}",title:"长篇（40-100）",img:pluginfo(a.plugin).icon,group:{name:"fenlei",title:"分类"},content:"长篇（40-100）"});a.callback({tid:"fav",listflag:"https://search.load.la/?pages=mega&num={{pagestart}}",title:"巨篇（100+）",img:pluginfo(a.plugin).icon,group:{name:"fenlei",title:"分类"},
content:"巨篇（100+）"});(plugfns(a.plugin).tags||[]).forEach(function(b){a.callback({tid:"search",listflag:"https://search.load.la/?tag="+b+"&num={{pagestart}}",title:b.toUpperCase(),img:pluginfo(a.plugin).icon,group:{name:"fenlei",title:"分类"},content:b.toUpperCase()})})}}}},listflag:{loader:function(a){return{url:a.flag.replace("{{pagestart}}",1<parseInt(a.page||1)?20*(parseInt(a.page||1)-1):""),method:"GET",timeout:120,referer:pluginfo(a.plugin).apihost,cookie:"__cfduid=d44ebf8c1c384f439a5b3caf7c48def9d1502505707; xo=1",
successfn:function(b,c){var f=getquery(b,"body");$$(f).find("table.search_gallery>tr").eq(0).remove();b=$$(f)[0].outerHTML;console.log(b);a.callback&&a.callback({multpage:!0,result:b,header:c})}}},finder:function(a){console.log(a.result);return{query:!0,selector:"#search_gallery_item",str:a.result,successfn:function(b){console.log(b);array_count(b)?plugfns(a.plugin).pagedeal(b,a,a.tid):a.callback()}}},countloader:!1,countfinder:function(a){return{successfn:function(b){a.callback&&a.callback({pagecount:Math.ceil(parseInt(getstr(/(\d+)\s*results/,
a.result)||0)/20)})}}}},searchflag:{loader:function(a){return{url:"https://search.load.la/?tag="+a.keyword+(1<parseInt(a.page||1)?"&num="+20*(parseInt(a.page||1)-1):""),method:"GET",timeout:120,referer:pluginfo(a.plugin).apihost,cookie:"__cfduid=d44ebf8c1c384f439a5b3caf7c48def9d1502505707; xo=1",successfn:function(b,c){var f=getquery(b,"body");$$(f).find("#search_gallery_item").each(function(){2>$$(this).find("img").length&&$$(this).remove()});b=$$(f)[0].outerHTML;console.log(b);a.callback&&a.callback({multpage:!0,
result:b,header:c})}}},finder:function(a){return{query:!0,selector:"#search_gallery_item",str:a.result,successfn:function(b,c,f){console.log(b);array_count(b)&&void 0==b.length?plugfns(a.plugin).pagedeal(b,a,"search"):a.multsearch?a.multsearch():a.callback()}}},countloader:!1,countfinder:function(a){return{successfn:function(b){a.callback&&a.callback({pagecount:Math.ceil(parseInt(getstr(/(\d+)\s*results/,a.result)||0)/20)})}}}},contentflag:{loader:function(a){var b=a.pid.split("_"),c="https://"+b[0]+
".load.la/manga/"+litehextostring(b[1]);return{url:pluginfo(a.plugin).apihost,method:"GET",timeout:120,referer:pluginfo(a.plugin).apihost,cookie:"__cfduid=d44ebf8c1c384f439a5b3caf7c48def9d1502505707; xo=1",successfn:function(b,d){var g=getstr(/\&o=(\d+)/g,b);plugfns(a.plugin).time=g;ExView.modules.curl({url:c+"&o="+(g||parseInt(getTimeNow()/1E3)),method:"GET",timeout:120,referer:pluginfo(a.plugin).apihost,cookie:"__cfduid=d44ebf8c1c384f439a5b3caf7c48def9d1502505707; xo=1",successfn:function(b,f){a.callback&&
a.callback({url:c,time:g,result:b,header:f})},errorfn:function(){a.callback&&a.callback()},showinfo:{text:"正在加载内容页...",title:"内容页",name:getlistname(a.pid),img:getlistimg(a.pid)}})}}},finder:function(a){return{successfn:function(b){if(b=getstr(/(\d+)\s*Images/,a.result)){var c=a.pid;b=Math.ceil(parseInt(b)/12);if(a.checkupdate)return{pid:c,cid:b,title:"第"+b+"话"};for(var f=[],d=0;d<b;d++)f[d]=a.callback({id:d,newest:a.newest&&0==d,pid:c,cid:d+
1,title:"第"+(d+1)+"话",count:b,reverse:0});console.log(f);return f}a.checkupdate||a.callback()}}},infoloader:!1,infofinder:function(a){console.log(a);return{successfn:function(b,c,f,d){try{var g=gettag(getquery(a.result,".pagination").eq(2).text().replace(/\s*:\s*/g,":").replace(/\s*,\s*/g,",").split(":")[1].split(","))}catch(e){g=""}b=getstr(/(\d+)\s*Images/,a.result);myContent.imgcount=b||0;a.callback({added:a.data,description:"<p>共"+(b||0)+"张图片</p>",comment:0,preview:1,
tags:gettag(getlistname(a.pid))+g})}}}},parseflag:{loader:function(a){var b=a.pid.split("_"),c="https://"+b[0]+".load.la/manga/"+litehextostring(b[1]);return{url:c+(1<parseInt(a.cid||1)?"&num="+12*parseInt(a.cid||1):"")+"&o="+(plugfns(a.plugin).time||parseInt(getTimeNow()/1E3)),method:"GET",timeout:120,referer:pluginfo(a.plugin).apihost,cookie:"__cfduid=d44ebf8c1c384f439a5b3caf7c48def9d1502505707; xo=1",successfn:function(b,d){a.callback&&a.callback({url:c,result:b,header:d})}}},finder:function(a){console.log(a);
var b=12*(parseInt(a.cid||1)-1),c=a.url,f=getstr(/(\d+)\s*Images/,a.result);return{successfn:function(d,g,e,h){h=[];for(e=b;e<b+12;e++)e<parseInt(f)&&h.push(c+"/0"+e+"&o="+parseInt(getTimeNow()/1E3));array_count(h)?(d=[],d=h.map(function(b){return getpageload(b,a.plugin,{nativeres:!0,cacheheader:{Referer:b,Cookie:"xo=1"},cachetime:3600})}),console.log(d),a.download?a.callback({source:d,download:a.download,plugin:a.plugin}):a.callback({source:d,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,
zoom:!0,title:a.title})):a.callback();return!0}}}},commentflag:{loader:!1,finder:!1,send:!1},previewflag:{loader:function(a){var b=a.pid.split("_"),c="https://"+b[0]+".load.la/manga/"+litehextostring(b[1]);return 1<a.page?{url:c+"&o="+(plugfns(a.plugin).time||parseInt(getTimeNow()/1E3)),method:"GET",timeout:120,referer:pluginfo(a.plugin).apihost,cookie:"__cfduid=d44ebf8c1c384f439a5b3caf7c48def9d1502505707; xo=1",successfn:function(b,d){b?a.callback&&a.callback({url:c,result:b,header:d}):a.callback&&
a.callback()}}:{url:pluginfo(a.plugin).apihost,method:"GET",timeout:120,referer:pluginfo(a.plugin).apihost,cookie:"__cfduid=d44ebf8c1c384f439a5b3caf7c48def9d1502505707; xo=1",successfn:function(b,d){var g=getstr(/\&o=(\d+)/g,b);plugfns(a.plugin).time=g;ExView.modules.curl({url:c+"&o="+(g||parseInt(getTimeNow()/1E3)),method:"GET",timeout:120,referer:pluginfo(a.plugin).apihost,cookie:"__cfduid=d44ebf8c1c384f439a5b3caf7c48def9d1502505707; xo=1",successfn:function(b,d){a.callback&&a.callback({url:c,result:b,
header:d})},errorfn:function(){a.callback&&a.callback()},showinfo:{text:"正在加载内容页...",title:"内容页",name:getlistname(a.pid),img:getlistimg(a.pid)}})}}},finder:function(a){var b=12*(parseInt(a.page||1)-1),c=a.url,f=getstr(/(\d+)\s*Images/,a.result),d=getstr(/src=\"(.*?)\/0\.jpg\"\s*\/><br>00<\/a>/,a.result);return{successfn:function(g,e,h,k){for(h=b;h<b+12;h++)h<f&&(g=d+"/"+h+".jpg",e=c+"/0"+h+"&o="+parseInt(getTimeNow()/1E3),g=getimgload(g,a.plugin,{nativeres:!0,
cacheheader:{Referer:e,Cookie:"xo=1"}}),a.callback({page:a.page||1,pagecount:myContent.items.length,preview:{imgurl:g,pageurl:e}}))}}}},pageimgflag:{parser:function(a){return{query:!0,selector:"td center img",str:a.result,successfn:function(b){b=$$(b).attr("src");b=getimgload(b,a.plugin,{nativeres:!0,cacheheader:{Referer:a.url,Cookie:"xo=1"}});console.log(b);a.callback({imgurl:b})}}}},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+(1<parseInt(a.page||1)?"?num="+20*(parseInt(a.page||
1)-1):""),timeout:120,referer:pluginfo(a.plugin).apihost,cookie:"__cfduid=d44ebf8c1c384f439a5b3caf7c48def9d1502505707; xo=1",successfn:function(b,c){a.callback&&a.callback({result:b,header:c})}}},finder:function(a){return{query:!0,selector:"#search_gallery_item",str:a.result,successfn:function(b){console.log(JSON.stringify(b));array_count(b)&&plugfns(a.plugin).pagedeal(b,a,"index")}}}},hotflag:{loader:function(a){return{url:"https://my.load.la/?date=today"+(1<parseInt(a.page||1)?"&num="+20*(parseInt(a.page||
1)-1):""),method:"GET",timeout:120,referer:pluginfo(a.plugin).apihost,cookie:"__cfduid=d44ebf8c1c384f439a5b3caf7c48def9d1502505707; xo=1",successfn:function(b,c){a.callback&&a.callback({result:b,header:c})}}},finder:function(a){return{query:!0,selector:"#search_gallery_item",str:a.result,successfn:function(b){console.log(JSON.stringify(b));b&&plugfns(a.plugin).pagedeal(b,a,"list")}}}}},fns:{pagedeal:function(a,b,c){b=b||{};switch(c){default:case "index":console.log(a);c=$$(a).children("a").attr("href");
console.log(c);c=/https:\/\/(\w+).load.la\/00\/(.*?)&o=(\d+)/.exec(c);c=c[1]+"_"+stringToHex(c[2]);var f=$$(a).find("img").attr("src"),d=$$(a).children("a").find(".pagination").text(),g=$$(a).children(".pagination").eq(0).text(),e=$$(a).children(".pagination").eq(1).text()||"",e=e.split(","),e=e.map(function(a){return(a=a.trim())?getboxitem(a):""}),e=e.join("");break;case "search":c=$$(a).children("a").attr("href");console.log(c);c=/https:\/\/(\w+).load.la\/00\/(.*?)&o=(\d+)/.exec(c);if(!c)return;
c=c[1]+"_"+stringToHex(c[2]);f=$$(a).find("img").attr("src");d=$$(a).children("a").find(".pagination").text();g=$$(a).children(".pagination").eq(0).text();e=$$(a).children(".pagination").eq(2).text()||"";e=e.split(",");e=e.map(function(a){return(a=a.trim())?getboxitem(a):""});a=$$(a).children(".pagination").eq(1).text();e=(a?getboxitem(a):"")+e.join("");break;case "fav":c=$$(a).children("a").attr("href");if(!c)return;console.log(c);try{c=/https:\/\/(\w+).load.la\/00\/(.*?)&o=(\d+)/.exec(c),c=c[1]+
"_"+stringToHex(c[2]),f=$$(a).find("img").attr("src"),d=$$(a).children("a").find(".pagination").text(),g=$$(a).children(".pagination").eq(0).text(),e=""}catch(h){return}break;case "list":c=$$(a).find("a").eq(1).attr("href"),console.log(c),c=/https:\/\/(\w+).load.la\/manga\/(.*?)&o=(\d+)/.exec(c),c=c[1]+"_"+stringToHex(c[2]),f=$$(a).find("img").attr("src"),d=$$(a).find("a").eq(2).text(),g=$$(a).find(".pagination").eq(0).text(),e=""}if(b.multupdate)return b.multupdate(obj_contact(b,{pid:c,img:f,title:d,
content:g})),!1;if(b.multhot)return b.multhot(obj_contact(b,{pid:c,img:f,title:d,content:g})),!1;if(b.multsearch)return b.multsearch(obj_contact(b,{pid:c,img:f,title:d,content:g})),!1;b.callback&&b.callback({pid:c,title:d,img:f,content:e,stitle:g,comment:0,preview:1,extrabutton:""})}}});
