ExView.Plugins({info:{name:"咪咕漫画",version:"2.2",author:"Gentle",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAwFBMVEWbStOqSu0AAACnT+KrS+6nVOKnTOynTObd2KitTPGwUvGvU++gVbivT/GcVLLVy6evVPCeUra0W+zFhuifTdPe2a3RxKbCrKKzWfC7be6tU+mfRt3GjNueSda9hcvi08i8h8alZMGsdLrj37jXwriqcrifVrardbWtfbDb1Ki6lqi4lqiyiqi9nqfWy6bNvaXPxqKsg6HLv6DFtKCjdaCaZZ/DsZ63nJ6xkZ6mfZ6TWJ7PyJuSXpnBsJivlpiYbZdxOsTbAAAACHRSTlMj+wD+/vsh/Lbf4XoAAACsSURBVBjTPY9VEgMxDEOz3YLc5TIzMzPc/1aV29m+D0vRJI5tEiblhKGjhI7No8kK8fJ5KjEmxVrpgxQbtJZxRKogmxcwYMIXHrAvPfz1G+h8gzbg+y5ZAt8AJIrcaEa1GXggge9eVXsMcmqmp9FWdRLf2B0PN9Vh3KN8vgRlal2DovZYlRAA96RwsByUZ5elwG8zIi3ahSW1eUFHNyJij5tJ+ZHmvpb8sdKJD8DADpdZzaKaAAAAAElFTkSuQmCC",
db:"migudm",apihost:"http://m.migudm.cn/",pagetitle:["<br>","收藏","首页","类型","下载"],download:!0,lazyload:!0,setting:!0,theme:"purple",cdn:""},set:function(a){},unset:function(a){},init:function(a){ExView.workers.fav.listloader({callback:function(){}})},flags:{indexflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost,method:"GET",timeout:120,cookie:"isInstall=true",successfn:function(b,c){a.callback({img:pluginfo(a.plugin).icon,multpage:!0,result:b,header:c})}}},
finder:function(a){return{query:!0,selector:".threeList li",str:a.result,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a,"index"):a.callback()}}},countloader:!1,countfinder:function(a){return{successfn:function(b){a.callback({pagecount:0})}}}},typeflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"comic/",method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){a.callback({title:"首页",img:pluginfo(a.plugin).icon,
group:{name:"daohang",title:"导航"},content:"首页"});a.callback({tid:"signed",title:"签约",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"签约"});a.callback({tid:"rimanzhuanqu",title:"日漫专区",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"日漫专区"});a.callback({tid:"dashenzuopin",title:"大神作品",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},
content:"大神作品"});a.callback({tid:"solo",title:"独家",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"独家"});a.callback({tid:"tiaoman",title:"条漫",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"条漫"});a.callback({tid:"end",title:"完结",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"完结"});a.callback({tid:"japan",title:"日漫",
img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"日漫"});return{query:!0,selector:".comicCategory li>a",str:a.result,successfn:function(b){console.log(b.length);array_count(b)&&$$(b).each(function(){a.callback({tid:getstr(/\/comic\/(\w+)\//g,$$(this).attr("href")),title:$$(this).attr("title"),img:$$(this).find("img").attr("src"),group:{name:"fenlei",title:"分类"},content:$$(this).attr("title")})})}}}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"comic/"+a.tid+"_p"+(a.page||1)+"/",method:"GET",timeout:120,successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})}}},finder:function(a){return{query:!0,selector:".comicResultList>a",str:a.result,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a,"list"):a.callback()}}},countloader:!1,countfinder:function(a){return{successfn:function(b){a.callback({pagecount:0})}}}},searchflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"opus/search/result.html?searchText="+
btoa(encodeURIComponent(a.keyword))+"&hintType=2&pageSize=10&pageNo="+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})}}},finder:function(a){return{query:!0,selector:".comicResultList>a",str:a.result,successfn:function(b){console.log(b);array_count(b)?plugfns(a.plugin).pagedeal(b,a,"search"):a.callback()}}},countloader:!1,countfinder:function(a){return{successfn:function(b){a.callback({pagecount:0})}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"comic/"+a.pid+".html",method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{query:!0,selector:".comicSelectAll a",str:a.result,successfn:function(b,c,d,f){console.log(b);if(array_count(c)){if(a.checkupdate)return a.callback({pid:a.pid,cid:c.length,title:"第"+c.length+"话"}),!0;for(d=0;d<c.length;d++)f[d]=a.callback({id:d,newest:a.newest&&0==d,pid:a.pid,cid:d+1,title:"第"+(d+1)+"话",count:c.length,reverse:0});return f}a.callback()}}},
infoloader:!1,infofinder:function(a){return{successfn:function(b,c,d,f){console.log(a.result);b=getquery(a.result,".comicImage img").attr("src");c=getquery(a.result,".comicDetailList h1").text();d=getquery(a.result,".comicLook").text();f=(getquery(a.result,".comicDetailAuthor").text()||"").replace("作者：","");var e=[];getquery(a.result,".bookType>label").each(function(){e.push($$(this).text())});var e=e.join(","),g=getquery(a.result,".moreText").text()||getquery(a.result,".comicDetailText").text();
a.callback({name:c,img:b,added:a.data,description:"<p>"+(f?"【作者】"+f+"<br>":"")+(e?"【类型】"+e+"<br>":"")+(d?"【热度】"+d+"<br>":"")+(g?"【简介】"+g:"")+"</p>",comment:1,sourceurl:pluginfo(a.plugin).apihost+"comic/"+a.pid+".html",preview:0,tags:gettag(c)+gettag(f)+gettag((e||"").split(","))});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+a.pid+"/chapter/"+a.cid+".html",method:"GET",timeout:120,successfn:function(b,
c){var d=getquery(b,".imgPlay").attr("value").split("=").pop();$$.get(pluginfo(a.plugin).apihost+"/comic/readImage.html?opusType=2&hwOpusId="+a.pid+"&hwItemId="+d,function(b,c){a.callback({nid:d,result:b,header:c})},function(){a.callback()})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b,c,d,f){b=(b||{}).data;b=(b||{}).jpgInfo;console.log(b);array_count(b)?(b=(b.jpgList||[]).map(function(a){return a.url}),a.download?a.callback({source:b,type:"image",download:a.download,plugin:a.plugin}):
a.callback({source:b,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.callback();return!0}}}},commentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"opus/topic/list.html?opusType=2&hwOpusId="+a.pid,method:"POST",data:"pageNo="+(a.page||1)+"&pageSize=20&hintKey=1",postform:!0,timeout:120,successfn:function(b,c){b?a.callback({result:b,header:c,commentbrowser:{url:pluginfo(a.plugin).apihost+"comic/"+a.pid+".html",title:"评论 - "+
pluginfo(a.plugin).name,browser:!0,flag:""}}):a.callback()}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b,c,d,f){b=(b||{}).data;if(array_count(b)){c=Math.ceil(b.total/20);b=b.comments;for(var e in b)a.callback({page:a.page||1,pagecount:c,comment:{text:b[e].content,name:b[e].nickName||"",avatar:b[e].ugLevelIconUrl,type:"received",label:b[e].createTime,day:"",time:"",reverse:1,extra:""}})}}}},send:!1},previewflag:{loader:!1,finder:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"comic/solo_p"+(a.page||1)+"/",method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{query:!0,selector:".comicResultList>a",str:a.result,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a,"list"):a.callback()}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"comic/end_p"+(a.page||1)+"/",method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{query:!0,
selector:".comicResultList>a",str:a.result,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a,"list"):a.callback()}}}}},fns:{pagedeal:function(a,b,c){b=b||{};if("index"==c){c=getstr(/comic\/(\d+)\.html/,$$(a).children("a").attr("href"));var d=$$(a).find("img").attr("name"),f=$$(a).children("a").attr("title"),e=$$(a).find(".number").text()}else{c=getstr(/comic\/(\d+)\.html/,$$(a).attr("href"));var d=$$(a).find("img").attr("name"),f=$$(a).attr("title"),g=$$(a).find(".fr").text(),e=
$$(a).find(".infoC").text(),h="";$$(a).find(".categoryC>label").each(function(){h+=getboxitem($$(this).text())});e=h+e}if(c){if(b.multupdate||b.multhot||b.multsearch)return b.callback(obj_contact(b,{pid:c,img:d,title:f,content:g})),!1;b.callback({pid:c,title:f,stitle:g,img:d,content:e,comment:1})}else b.callback()}}});
