ExView.Plugins({info:{name:"漫客栈漫画",version:"2.2",author:"Gentle",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAIVBMVEUAAADKKgDUUAD////bbQDiijHYYQDSRQDSSgDAAADWVgDzvTPzAAAAAXRSTlMUWjwMGwAAAGhJREFUCNdjYBAEAwYGxlAwEGAQDXEBAUcGUY2OjlVZWY4MIsbGxkZGyoUMIkbKSkZGxo0QhrFSIpwBk4KogSh2AYOJDCJuaWlZaSkTGRjd0ssLZ84UAFpaKCgoLsgAtBVIgAGjAJgCAMSgGbMjWI5dAAAAAElFTkSuQmCC",db:"mkzhan",apihost:"http://m.mkzhan.com/",pagetitle:["<br>","收藏","首页",
"类型","下载"],lazyload:!0,download:!0,setting:!0,webpage:{url:"http://m.mkzhan.com/wap.php/user/login",title:"登陆"},typelistmode:!0,cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){ExView.workers.index.loader()}})},flags:{indexflag:{loader:function(a){a.front||a.page||addtypelist('<div align="center" class="list-block"><img src="img/logo.png"/><br>类型<br>正在加载...<div class="progress"></span></div>',
2);return{url:pluginfo(a.plugin).apihost,method:"GET",timeout:120,successfn:function(b,c){ExView.workers.index.countfinder(obj_contact(a,{result:b,header:c}));a.front||a.page||ExView.workers.type.finder({result:b,plugin:a.plugin});a.successfn&&a.successfn({result:b,header:c})},errorfn:function(){a.page||addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>加载失败，请刷新重试！</a></div>',
2);ExView.fw.alert("网络错误！","ExView")},canclefn:function(){a.page||addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>加载失败，请刷新重试！</a></div>',2)},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),name:"首页",title:a.title,img:a.img}}},finder:function(a){return{reg:/wap.php\/Comic\/index\/id\/(\d+)"(?!>).*?><img\s*src="((?!\").*?)"\s*class="comic_img"\/>.*?class="comic_title">((?!>).*?)<\/span><span\s*class="comic_author">作者：((?!>).*?)<\/span>/g,
str:getresult(a.result),find:{pid:"$1",img:"$2",title:"$3",content:"$4"},successfn:function(a){console.log(JSON.stringify(a));array_count(a)?addcardlist({pid:a.pid,title:a.title,img:a.img,stitle:a.content,comment:0}):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',2)},errorfn:function(){a.page||setnowlistname("首页","",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("网络错误！",
"ExView")}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="-1|首页|index";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},typeflag:{loader:function(a){return{successfn:function(){ExView.workers.index.loader()}}},finder:function(a){addtypelist({title:"首页",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"首页"});return{reg:/\/comic\/clist\/([\d,\-]+)-1\.html">((?!<).*?)<\/a>/g,
str:a.result,find:"$1{{separator}}$2",successfn:function(b){b=b.split("{{separator}}");array_count(b)?addtypelist({tid:b[0],title:b[1],img:pluginfo(a.plugin).icon,group:{name:"fenlei",title:"分类"},content:b[1]}):addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>加载失败，请刷新重试！</a></div>',2)}}}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"wap.php/comic/clist/"+a.keyword+"-"+(a.page||1)+"/",method:"GET",timeout:120,successfn:function(b,c){b?(ExView.workers.list.countfinder(obj_contact(a,{result:b,header:c})),a.successfn&&a.successfn({result:b,header:c})):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+a.title+"】<br>获取失败！","ExView"))},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),name:"【"+a.title+"】",title:a.title,img:a.img}}},
finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b){b?plugfns(a.plugin).pagedeal(b):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="0|"+a.keyword+"|list";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},searchflag:{loader:function(a){return 1<
parseInt(a.page)?(a.multsearch&&a.multsearch(),!1):{url:pluginfo(a.plugin).apihost+"wap.php/comic/so/key/"+a.keyword+"/page/"+(a.page||1)+"/",method:"GET",timeout:120,successfn:function(b,c){b?(a.multsearch||(ExView.workers.search.countfinder(obj_contact(a,{result:b,header:c})),setnowlistname("搜索【"+a.keyword+"】")),a.successfn&&a.successfn({result:b,header:c})):a.multsearch?a.multsearch():(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+a.keyword+"】<br>获取搜索结果失败！",
"ExView"))},showinfo:{text:"正在搜索..."+(1<a.page?"<br>第"+a.page+"页":""),name:"【"+a.keyword+"】",title:"搜索"}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b,c,d){console.log(b);b?plugfns(a.plugin).pagedeal(b,a):a.multsearch?a.multsearch():addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}},countloader:function(a){return!1},
countfinder:function(a){return{successfn:function(b){mySession.nowlistpages="0|"+a.keyword+"|search";mySession.nowlistpage=1;console.log(mySession.nowlistpages)}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"wap.php/Comic/index/id/"+a.pid,method:"GET",timeout:120,successfn:function(b,c){b?a.successfn&&a.successfn({result:b,header:c}):a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},
showinfo:{text:"正在加载内容页...",title:"内容页",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){return{reg:/check_comic\('',\d+,\d+,(\d+)\)">.*?picnum='(\d+)'>((?!<).*?)<\/a>/g,str:getresult(a.result),find:{pid:a.pid,cid:"$1",title:"$3($2)"},successfn:function(b,c,d,e){console.log(typeof b);if(array_count(b)){if(a.checkupdate)return b=e[c.length-1],{pid:b.pid,cid:b.cid,title:b.title};additemlist({id:d,newest:a.newest&&0==d,pid:b.pid,cid:b.cid,
title:b.title,count:c.length,reverse:0})}else a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},afterfn:function(){a.checkupdate||ExView.workers.content.infofinder(a)}}},infoloader:function(a){return!1},infofinder:function(a){console.log(a);return{reg:/class="comic_infor">(.*?)<div\s*class="new_chapter">/g,str:getresult(a.result),find:"$1",successfn:function(b,c,d,e){console.log(JSON.stringify(b));c=getstr(/<img(?!<).*?src="((?!\").*?)"/,
b);d=getstr(/<h2>((?!<).*?)\s*</,b);e=getstr(/class="col_end">((?!<).*?)</,b).trim();var f=getstr(/>作者：((?!<).*?)<\/p>/,b).trim(),g=getstr(/>类型：((?!<).*?)<\/p>/,b).trim();b=getstr(/<p>简介：(.*?)<\/div>/,b).trim();var h=gettag(g.split("&nbsp;"));setlistpic({name:d,img:c,added:a.data,description:"<p>【作者】"+f+"<br>【类型】"+g.replace(/&nbsp;/g,",").replace(/,,/g,",")+"<br>【状态】"+e+"<br>【简介】"+
gettext(b)+"</p>",comment:0,preview:0,tags:gettag(d)+gettag(e)+h+gettag(f),sourceurl:pluginfo(a.plugin).apihost+"wap.php/Comic/index/id/"+a.pid});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"wap.php/read/index/comic/"+a.pid+"/chapterid/"+a.cid+"/",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"正在加载图片信息...",title:"图片",name:getlistname(a.pid),img:getlistimg(a.pid)}}},
finder:function(a){console.log(a);return{json:!0,str:a.result,successfn:function(b){b=(b||{}).msg;array_count(b)?(b=b.map(function(a){return a.src}),console.log(b),a.download?chapterpredownload({source:b,download:a.download,plugin:a.plugin}):chapterviewer({source:b,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.download?chapterpredownload({error:"解析错误！",download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),
mySession.isloading=0,ExView.fw.alert("图片信息获取失败！","ExView"));return!0}}}},commentflag:{loader:!1,finder:!1},previewflag:{loader:!1,finder:!1,more:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"wap.php/comic/clist/0-0-0-0-0-2-0-"+(a.page||1)+"/",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:getresult(a.result),
find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));b&&plugfns(a.plugin).pagedeal(b,a)}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"wap.php/comic/clist/0-0-0-0-42-2-0-"+(a.page||1)+"/",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));
b&&plugfns(a.plugin).pagedeal(b,a)}}}}},fns:{pagerule:/class="search_result_box"><a\s*href="(.*?)<\/a>/g,pagefind:"$1",pagedeal:function(a,b){b=b||{};var c=getstr(/\/id\/(\d+)"/,a),d=getstr(/<img(?!<).*?src="((?!\").*?)"/,a);getstr(/<i>((?!<).*?)<\/i>/,a).trim();var e=getstr(/"title_name">((?!<).*?)<\/p>/,a).trim(),f=getstr(/>作者：((?!<).*?)<\/p>/,a).trim();if(b.multupdate)return b.multupdate(obj_contact(b,{pid:c,img:d,title:e,content:f})),!1;if(b.multhot)return b.multhot(obj_contact(b,
{pid:c,img:d,title:e,content:f})),!1;if(b.multsearch)return b.multsearch(obj_contact(b,{pid:c,img:d,title:e,content:f})),!1;addcardlist({pid:c,title:e,name:e,img:d,content:"",stitle:f,comment:0,preview:0,extrabutton:""})}}});
