ExView.Plugins({info:{name:"漫客栈漫画",version:"2.2",author:"Gentle",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAIVBMVEUAAADKKgDUUAD////bbQDiijHYYQDSRQDSSgDAAADWVgDzvTPzAAAAAXRSTlMUWjwMGwAAAGhJREFUCNdjYBAEAwYGxlAwEGAQDXEBAUcGUY2OjlVZWY4MIsbGxkZGyoUMIkbKSkZGxo0QhrFSIpwBk4KogSh2AYOJDCJuaWlZaSkTGRjd0ssLZ84UAFpaKCgoLsgAtBVIgAGjAJgCAMSgGbMjWI5dAAAAAElFTkSuQmCC",db:"mkzhan",apihost:"https://m.mkzhan.com/",pagetitle:["<br>","收藏","首页",
"类型","下载"],lazyload:!0,download:!0,setting:!0,webpage:{url:"http://m.mkzhan.com/wap.php/user/login",title:"登陆"},theme:"orange",cdn:""},set:function(a){},unset:function(a){},init:function(a){ExView.workers.fav.listloader({callback:function(){}})},flags:{indexflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost,method:"GET",timeout:120,successfn:function(b,c){a.callback({img:pluginfo(a.plugin).icon,multpage:!0,result:b,header:c})}}},finder:function(a){return{query:!0,
selector:".floor-view",str:a.result,successfn:function(b){array_count(b)?$$(b).find("li").each(function(){var b=getstr(/\/(\d+)\//,$$(this).find("a").attr("href")),d=$$(this).find(".comic-name").text(),e=$$(this).find("img").attr("data-src"),f=$$(this).find(".comic-tip").text();a.callback({pid:b,title:d,img:e,content:f,comment:1})}):a.callback()}}},countloader:!1,countfinder:function(a){return{successfn:function(b){a.callback({pagecount:-1})}}}},typeflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"category",method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){a.callback({title:"首页",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"首页"});a.callback({tid:"nav",listflag:"comic/update|week_num=0&page_num={{page}}&page_size=10",title:"更新",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"更新"});a.callback({tid:"nav",listflag:"comic/top|top_type=1&type=1&page_num={{page}}&page_size=10",
title:"人气榜",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"人气榜"});a.callback({tid:"nav",listflag:"comic/top|top_type=2&type=2&page_num={{page}}&page_size=10",title:"月票榜",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"月票榜"});a.callback({tid:"nav",listflag:"comic/top|top_type=3&type=3&page_num={{page}}&page_size=10",title:"收藏榜",img:pluginfo(a.plugin).icon,group:{name:"daohang",
title:"导航"},content:"收藏榜"});a.callback({tid:"nav",listflag:"comic/top|top_type=4&type=3&page_num={{page}}&page_size=10",title:"独家榜",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"独家榜"});a.callback({tid:"nav",listflag:"comic/top|top_type=5&type=1&page_num={{page}}&page_size=10",title:"新作榜",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"新作榜"});a.callback({tid:"nav",
listflag:"comic/top|top_type=6&type=1&page_num={{page}}&page_size=10",title:"上升榜",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"上升榜"});return{query:!0,selector:".catalog-item",str:a.result,successfn:function(b){if(array_count(b)){var c=$$(b).find("a").attr("href"),d=$$(b).find("p").text();b=$$(b).find("img").attr("data-src");a.callback({tid:"type",listflag:c,title:d,img:b,group:{name:"fenlei",title:"分类"},content:d})}}}}},listflag:{loader:function(a){var b=
{url:"",method:"POST",postform:!0,timeout:120,successfn:function(b,d){a.callback({multpage:!0,result:b,header:d})}};switch(a.tid){case "nav":b.url=pluginfo(a.plugin).apihost+a.flag.split("|")[0];b.data=a.flag.split("|")[1].replace("{{page}}",a.page||1);break;default:b.url=pluginfo(a.plugin).apihost+"comic/lists",b.data="page_num="+(a.page||1)+"&page_size=12&"+a.flag.replace("/lists/?","")}return b},finder:function(a){return{json:!0,str:a.result,successfn:function(b){b=(b||{}).data;b=(b||{}).list;
array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:function(a){return{successfn:function(b){a.callback({pagecount:0})}}}},searchflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"spotlight?keyword="+encodeURIComponent(a.keyword),method:"GET",timeout:120,successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})}}},finder:function(a){return{query:!0,selector:".comic-list-item",str:a.result,successfn:function(b){if(array_count(b)){var c=getstr(/\/(\d+)\//,
$$(b).find("a").attr("href")),d=$$(b).find(".comic-name").text(),e=$$(b).find("img").attr("src"),f=$$(b).find(".comic-author").text();b=$$(b).find(".comic-update-at").text();if(a.multsearch)return a.callback(obj_contact(a,{pid:c,img:e,title:d,content:b})),!1;a.callback({pid:c,title:d,img:e,stitle:f||"",content:b,comment:1})}else a.callback()}}},countloader:!1,countfinder:function(a){return{successfn:function(b){a.callback({pagecount:-1})}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
a.pid+"/",method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{query:!0,selector:".catalog-list",str:a.result,successfn:function(b,c,d,e){if(array_count(b)){if(a.checkupdate)return b=b.pop(),d=getstr(/\/(\d+)\.html/,$$(b).find("a").attr("href")),b=gettrimtext($$(b).find("a").text()),a.callback({pid:a.pid,cid:d,title:"第"+b+"话"}),!0;e=[];c=$$(b).find(".chapter-item");c.each(function(b){var d=getstr(/\/(\d+)\.html/,$$(this).find("a").attr("href")),
h=gettrimtext($$(this).find("a").text());e[b]=a.callback({id:b,newest:a.newest&&0==b,pid:a.pid,cid:d,title:"第"+h+"话",count:c.length,reverse:0})});return e}a.callback()}}},infoloader:!1,infofinder:function(a){return{query:!0,selector:".detail-container",str:a.result,successfn:function(b,c,d,e){c=$$(b).find(".cover img").attr("data-src");d=$$(b).find(".comic-name").text();e=$$(b).find(".comic-author").text();var f=$$(b).find(".comic-tags").text(),f=(f||"").replace(/\ /g,","),g=$$(b).find(".comic-intro").text();
b=$$(b).find(".comic-hot num").text();a.callback({name:d,img:c,added:a.data,description:"<p>"+(e?"【作者】"+e+"<br>":"")+(f?"【类型】"+f+"<br>":"")+(b?"【人气】"+b+"<br>":"")+(g?"【简介】"+g:"")+"</p>",comment:1,preview:0,sourceurl:pluginfo(a.plugin).apihost+a.pid+"/",tags:gettag(d)+gettag(e)+gettag((f||"").split(","))});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"comic/content",method:"POST",postform:!0,
data:"comic_id="+a.pid+"&chapter_id="+a.cid,timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b,c,d,e){b=b.data.list;array_count(b)?(b=b.map(function(a){return a.image+"!width-800"}),a.download?a.callback({source:b,download:a.download,plugin:a.plugin}):a.callback({source:b,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.callback();return!0}}}},commentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"comic/comment_list",method:"POST",postform:!0,data:"comic_id="+a.pid+"&page_num="+(a.page||1)+"&page_size=10",timeout:120,successfn:function(b,c){b?a.callback({result:b,header:c,commentbrowser:{url:pluginfo(a.plugin).apihost+a.pid+"/",title:"评论 - "+pluginfo(a.plugin).name+'<br><span style="font-size:16px">'+(myContent.name||"")+"</span>",browser:!1,flag:""}}):a.callback()}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b,c,d,e){b=(b||{}).data;if(array_count(b)){c=Math.ceil(b.count/
10);b=b.list;for(var f in b)a.callback({page:a.page||1,pagecount:c,comment:{text:b[f].content,name:b[f].username||"",avatar:b[f].avatar,type:"received",label:b[f].create_time,day:"",time:"",reverse:1,extra:""}})}}}},send:!1},previewflag:{loader:!1,finder:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"comic/update",method:"POST",postform:!0,data:"week_num=0&page_num="+(a.page||1)+"&page_size=10",timeout:120,successfn:function(b,c){a.callback({result:b,
header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){b=(b||{}).data;b=(b||{}).list;array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"comic/top",method:"POST",postform:!0,data:"top_type=1&type=1&page_num="+(a.page||1)+"&page_size=10",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){b=(b||{}).data;b=
(b||{}).list;array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}}}},fns:{pagedeal:function(a,b){b=b||{};a.forEach(function(a){var d=a.comic_id,e=a.cover||a.comic_cover,e=e+"!width-300",f=a.title,g=a.author_title;a=a.chapter_title?"更新至 "+a.chapter_title:"";if(b.multupdate||b.multhot)return b.callback(obj_contact(b,{pid:d,img:e,title:f,content:a})),!1;b.callback({pid:d,title:f,img:e,stitle:g||"",content:a,comment:1})})}}});
