ExView.Plugins({info:{name:"\u6f2b\u5ba2\u6808\u6f2b\u753b",version:"2.2",author:"Gentle",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAIVBMVEUAAADKKgDUUAD////bbQDiijHYYQDSRQDSSgDAAADWVgDzvTPzAAAAAXRSTlMUWjwMGwAAAGhJREFUCNdjYBAEAwYGxlAwEGAQDXEBAUcGUY2OjlVZWY4MIsbGxkZGyoUMIkbKSkZGxo0QhrFSIpwBk4KogSh2AYOJDCJuaWlZaSkTGRjd0ssLZ84UAFpaKCgoLsgAtBVIgAGjAJgCAMSgGbMjWI5dAAAAAElFTkSuQmCC",db:"mkzhan",apihost:"http://m.mkzhan.com/",pagetitle:["<br>","\u6536\u85cf","\u9996\u9875",
"\u7c7b\u578b","\u4e0b\u8f7d"],lazyload:!0,download:!0,setting:!0,webpage:{url:"http://m.mkzhan.com/wap.php/user/login",title:"\u767b\u9646"},typelistmode:!0,cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){ExView.workers.index.loader()}})},flags:{indexflag:{loader:function(a){a.front||a.page||addtypelist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u7c7b\u578b<br>\u6b63\u5728\u52a0\u8f7d...<div class="progress"></span></div>',
2);return{url:pluginfo(a.plugin).apihost,method:"GET",timeout:120,successfn:function(b,c){ExView.workers.index.countfinder(obj_contact(a,{result:b,header:c}));a.front||a.page||ExView.workers.type.finder({result:b,plugin:a.plugin});a.successfn&&a.successfn({result:b,header:c})},errorfn:function(){a.page||addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>\u52a0\u8f7d\u5931\u8d25\uff0c\u8bf7\u5237\u65b0\u91cd\u8bd5\uff01</a></div>',
2);ExView.fw.alert("\u7f51\u7edc\u9519\u8bef\uff01","ExView")},canclefn:function(){a.page||addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>\u52a0\u8f7d\u5931\u8d25\uff0c\u8bf7\u5237\u65b0\u91cd\u8bd5\uff01</a></div>',2)},showinfo:{text:"\u6b63\u5728\u52a0\u8f7d..."+(1<a.page?"<br>\u7b2c"+a.page+"\u9875":""),name:"\u9996\u9875",title:a.title,img:a.img}}},finder:function(a){return{reg:/wap.php\/Comic\/index\/id\/(\d+)"(?!>).*?><img\s*src="((?!\").*?)"\s*class="comic_img"\/>.*?class="comic_title">((?!>).*?)<\/span><span\s*class="comic_author">\u4f5c\u8005\uff1a((?!>).*?)<\/span>/g,
str:getresult(a.result),find:{pid:"$1",img:"$2",title:"$3",content:"$4"},successfn:function(a){console.log(JSON.stringify(a));array_count(a)?addcardlist({pid:a.pid,title:a.title,img:a.img,stitle:a.content,comment:0}):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u6ca1\u6709\u5185\u5bb9</div>',2)},errorfn:function(){a.page||setnowlistname("\u9996\u9875","",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("\u7f51\u7edc\u9519\u8bef\uff01",
"ExView")}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="-1|\u9996\u9875|index";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},typeflag:{loader:function(a){return{successfn:function(){ExView.workers.index.loader()}}},finder:function(a){addtypelist({title:"\u9996\u9875",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u9996\u9875"});return{reg:/\/comic\/clist\/([\d,\-]+)-1\.html">((?!<).*?)<\/a>/g,
str:a.result,find:"$1{{separator}}$2",successfn:function(b){b=b.split("{{separator}}");array_count(b)?addtypelist({tid:b[0],title:b[1],img:pluginfo(a.plugin).icon,group:{name:"fenlei",title:"\u5206\u7c7b"},content:b[1]}):addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>\u52a0\u8f7d\u5931\u8d25\uff0c\u8bf7\u5237\u65b0\u91cd\u8bd5\uff01</a></div>',2)}}}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"wap.php/comic/clist/"+a.keyword+"-"+(a.page||1)+"/",method:"GET",timeout:120,successfn:function(b,c){b?(ExView.workers.list.countfinder(obj_contact(a,{result:b,header:c})),a.successfn&&a.successfn({result:b,header:c})):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u3010"+a.title+"\u3011<br>\u83b7\u53d6\u5931\u8d25\uff01","ExView"))},showinfo:{text:"\u6b63\u5728\u52a0\u8f7d..."+(1<a.page?"<br>\u7b2c"+a.page+"\u9875":""),name:"\u3010"+a.title+"\u3011",title:a.title,img:a.img}}},
finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b){b?plugfns(a.plugin).pagedeal(b):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u6ca1\u6709\u5185\u5bb9</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="0|"+a.keyword+"|list";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},searchflag:{loader:function(a){return 1<
parseInt(a.page)?(a.multsearch&&a.multsearch(),!1):{url:pluginfo(a.plugin).apihost+"wap.php/comic/so/key/"+a.keyword+"/page/"+(a.page||1)+"/",method:"GET",timeout:120,successfn:function(b,c){b?(a.multsearch||(ExView.workers.search.countfinder(obj_contact(a,{result:b,header:c})),setnowlistname("\u641c\u7d22\u3010"+a.keyword+"\u3011")),a.successfn&&a.successfn({result:b,header:c})):a.multsearch?a.multsearch():(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u3010"+a.keyword+"\u3011<br>\u83b7\u53d6\u641c\u7d22\u7ed3\u679c\u5931\u8d25\uff01",
"ExView"))},showinfo:{text:"\u6b63\u5728\u641c\u7d22..."+(1<a.page?"<br>\u7b2c"+a.page+"\u9875":""),name:"\u3010"+a.keyword+"\u3011",title:"\u641c\u7d22"}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b,c,d){console.log(b);b?plugfns(a.plugin).pagedeal(b,a):a.multsearch?a.multsearch():addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u6ca1\u6709\u5185\u5bb9</div>',1)}}},countloader:function(a){return!1},
countfinder:function(a){return{successfn:function(b){mySession.nowlistpages="0|"+a.keyword+"|search";mySession.nowlistpage=1;console.log(mySession.nowlistpages)}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"wap.php/Comic/index/id/"+a.pid,method:"GET",timeout:120,successfn:function(b,c){b?a.successfn&&a.successfn({result:b,header:c}):a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u5185\u5bb9\u9875\u83b7\u53d6\u5931\u8d25\uff01","ExView"))},
showinfo:{text:"\u6b63\u5728\u52a0\u8f7d\u5185\u5bb9\u9875...",title:"\u5185\u5bb9\u9875",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){return{reg:/check_comic\('',\d+,\d+,(\d+)\)">.*?picnum='(\d+)'>((?!<).*?)<\/a>/g,str:getresult(a.result),find:{pid:a.pid,cid:"$1",title:"$3($2)"},successfn:function(b,c,d,e){console.log(typeof b);if(array_count(b)){if(a.checkupdate)return b=e[c.length-1],{pid:b.pid,cid:b.cid,title:b.title};additemlist({id:d,newest:a.newest&&0==d,pid:b.pid,cid:b.cid,
title:b.title,count:c.length,reverse:0})}else a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u5185\u5bb9\u9875\u83b7\u53d6\u5931\u8d25\uff01","ExView"))},afterfn:function(){a.checkupdate||ExView.workers.content.infofinder(a)}}},infoloader:function(a){return!1},infofinder:function(a){console.log(a);return{reg:/class="comic_infor">(.*?)<div\s*class="new_chapter">/g,str:getresult(a.result),find:"$1",successfn:function(b,c,d,e){console.log(JSON.stringify(b));c=getstr(/<img(?!<).*?src="((?!\").*?)"/,
b);d=getstr(/<h2>((?!<).*?)\s*</,b);e=getstr(/class="col_end">((?!<).*?)</,b).trim();var f=getstr(/>\u4f5c\u8005\uff1a((?!<).*?)<\/p>/,b).trim(),g=getstr(/>\u7c7b\u578b\uff1a((?!<).*?)<\/p>/,b).trim();b=getstr(/<p>\u7b80\u4ecb\uff1a(.*?)<\/div>/,b).trim();var h=gettag(g.split("&nbsp;"));setlistpic({name:d,img:c,added:a.data,description:"<p>\u3010\u4f5c\u8005\u3011"+f+"<br>\u3010\u7c7b\u578b\u3011"+g.replace(/&nbsp;/g,",").replace(/,,/g,",")+"<br>\u3010\u72b6\u6001\u3011"+e+"<br>\u3010\u7b80\u4ecb\u3011"+
gettext(b)+"</p>",comment:0,preview:0,tags:gettag(d)+gettag(e)+h+gettag(f),sourceurl:pluginfo(a.plugin).apihost+"wap.php/Comic/index/id/"+a.pid});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"wap.php/read/index/comic/"+a.pid+"/chapterid/"+a.cid+"/",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"\u6b63\u5728\u52a0\u8f7d\u56fe\u7247\u4fe1\u606f...",title:"\u56fe\u7247",name:getlistname(a.pid),img:getlistimg(a.pid)}}},
finder:function(a){console.log(a);return{json:!0,str:a.result,successfn:function(b){b=(b||{}).msg;array_count(b)?(b=b.map(function(a){return a.src}),console.log(b),a.download?chapterpredownload({source:b,download:a.download,plugin:a.plugin}):chapterviewer({source:b,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.download?chapterpredownload({error:"\u89e3\u6790\u9519\u8bef\uff01",download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),
mySession.isloading=0,ExView.fw.alert("\u56fe\u7247\u4fe1\u606f\u83b7\u53d6\u5931\u8d25\uff01","ExView"));return!0}}}},commentflag:{loader:!1,finder:!1},previewflag:{loader:!1,finder:!1,more:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"wap.php/comic/clist/0-0-0-0-0-2-0-"+(a.page||1)+"/",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:getresult(a.result),
find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));b&&plugfns(a.plugin).pagedeal(b,a)}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"wap.php/comic/clist/0-0-0-0-42-2-0-"+(a.page||1)+"/",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));
b&&plugfns(a.plugin).pagedeal(b,a)}}}}},fns:{pagerule:/class="search_result_box"><a\s*href="(.*?)<\/a>/g,pagefind:"$1",pagedeal:function(a,b){b=b||{};var c=getstr(/\/id\/(\d+)"/,a),d=getstr(/<img(?!<).*?src="((?!\").*?)"/,a);getstr(/<i>((?!<).*?)<\/i>/,a).trim();var e=getstr(/"title_name">((?!<).*?)<\/p>/,a).trim(),f=getstr(/>\u4f5c\u8005\uff1a((?!<).*?)<\/p>/,a).trim();if(b.multupdate)return b.multupdate(obj_contact(b,{pid:c,img:d,title:e,content:f})),!1;if(b.multhot)return b.multhot(obj_contact(b,
{pid:c,img:d,title:e,content:f})),!1;if(b.multsearch)return b.multsearch(obj_contact(b,{pid:c,img:d,title:e,content:f})),!1;addcardlist({pid:c,title:e,name:e,img:d,content:"",stitle:f,comment:0,preview:0,extrabutton:""})}}});
