ExView.Plugins({info:{name:"漫画喵",version:"2.2",author:"miaopasi",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAABnlBMVEX//f/7//iqwU////v//////P/+//j+//T9+v/z7/75/vf2+PH09+z+/+n8/+jb6K/Q3Zasw2StyVmiuk2rykyivku10UidvUP5//38/v318vn9//j4/fb7/PT8//P+/+3z9Ozs7uPu8tv+/9j1/dbp9NLd39Hi7sbd67rZ5KiqtYazxH25x3qapnivwHK20me4z2SvyGSjs2ClvF+uzV2wyl2611i31VisxVipwFZ+h1WmvVS00FKqzVCnwFC00Ey0zku51kqx0EmryUmgtkm11UW00USs0z6q0Dr89f/6+vrv6/rt6fj39/Xw8O71+O3Y0Of7/+H5/9/QyN/v89zt+9ru+dno7NXEvNG1rcSnpaiioqTV4aPU4ZzC0om6y32jrXuyw3XB3W+1zW+0zW++4W2912qOmmq53GizzWKlt2Gqv2C62F6001ypwlylvlioy1etzFWSqFWwyVSkxVS11FOt0lGVqk+vzk2nwEqduUiZsEity0epyEaDmUaoyESTrUCx1T+oyz2nyjqdvjmiwTifxTSauTAvPwEoOABXZ12sAAABBUlEQVQY0w3I05IDURQAwHNHMUexbVsbr23btq2/zlT1U8PeTbfDZH9bre8j5r1b3oarcueT1ZbqtQbLf/zwZ5A6/2pEk490s6iJP78epyD6wKcvguuRxGrwJcewWtih92//w4FCYW33L5l+24BK7jASVjpmHVPKwIomr4XLWEKlkI0ADJuV/oPYPZTokNOzCBIJLHicoWYGapjaZTf0z81LDHaXGqsChy2P28Tk2CQptk2oMQ7amF9hBHJwiASzYgnrg3ZFZaUIADEQRqtKiHrRZ6FwPUEM4JTFl+egeuJFJlyGCxDynj7BddwtNSG5SCSnkN6tuYPM1oxOikaFQFLd9Ga2B96RMHEp1y3JAAAAAElFTkSuQmCC",
db:"pfmh",apihost:"漫画喵",realhost:"http://m.pufei.net/",pagetitle:["<br>","收藏","首页","类型","下载"],download:!0,lazyload:!0,setting:!0,theme:"lightgreen",cdn:""},set:function(a){},unset:function(a){},init:function(a){ExView.workers.fav.listloader({callback:function(){}})},flags:{indexflag:{loader:function(a){return{url:pluginfo(a.plugin).realhost,method:"GET",timeout:120,successfn:function(b,c){a.callback({img:pluginfo(a.plugin).icon,multpage:!0,result:b,
header:c})}}},finder:function(a){return{query:!0,selector:".main-list-wrap li",str:a.result,successfn:function(b){if(array_count(b)){var c=getstr(/\/manhua\/(\d+)/g,$$(b).find("a").attr("href")),d=$$(b).find("img").attr("data-src"),e=$$(b).find("h3").text();b=$$(b).find("p").text();a.callback(obj_contact(a,{pid:c,img:d,title:e,content:b}))}else a.callback()}}},countloader:!1,countfinder:function(a){return{successfn:function(b){a.callback({pagecount:-1})}}}},typeflag:{loader:function(a){return{url:pluginfo(a.plugin).realhost,
method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){a.callback({title:"首页",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"首页"});a.callback({tid:"update",listflag:"manhua/update.html",title:"更新",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"更新"});a.callback({tid:"paihang",listflag:"manhua/paihang.html",title:"排行",img:pluginfo(a.plugin).icon,
group:{name:"daohang",title:"导航"},content:"排行"});console.log(a);return{query:!0,selector:".cat-list a",str:a.result,successfn:function(b){if(array_count(b)){var c=getstr(/([\d,\w,\_]+)/g,$$(b).attr("href"));c&&(b=$$(b).text(),a.callback({tid:c,title:b,img:pluginfo(a.plugin).icon,group:{name:"fenlei",title:"分类"},content:b}))}}}}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).realhost+(a.flag?a.flag:a.tid+"/index"+(1<a.page?"_"+(a.page||1):"")+".html"),method:"GET",
timeout:120,successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})}}},finder:function(a){return{query:!0,selector:"#detail li",str:a.result,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:function(a){return{query:!0,selector:"a[title^=Total] b",str:a.result,successfn:function(b){try{var c=$$(b).text(),d=Math.ceil(parseInt(c)/25)}catch(e){d=-1}a.callback({pagecount:d})}}}},searchflag:{loader:function(a){return{url:pluginfo(a.plugin).realhost+
"e/search/?searchget=1&tbname=mh&show=title,player,playadmin,bieming,pinyin,playadmin&tempid=4&keyboard="+ExView.tools.gbk.encode(a.keyword),method:"GET",timeout:120,successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})}}},finder:function(a){return{query:!0,selector:"#detail li",str:a.result,successfn:function(b){console.log(b);array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:function(a){return{successfn:function(b){a.callback({pagecount:-1})}}}},
contentflag:{loader:function(a){return{url:pluginfo(a.plugin).realhost+"manhua/"+a.pid+"/",method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{query:!0,selector:".chapter-list li",str:a.result,successfn:function(b,c,d,e){if(array_count(c)){if(a.checkupdate)return d=c[0],b=getstr(/\/manhua\/\d+\/(\d+).html/g,$$(d).children("a").attr("href")),d=$$(d).children("a").text(),a.callback({pid:a.pid,cid:b,title:d}),!0;e=[];console.log(c);c.each(function(b){var d=
getstr(/\/manhua\/\d+\/(\d+).html/g,$$(this).children("a").attr("href")),f=$$(this).children("a").text();e[b]=a.callback({id:c.length-b-1,newest:a.newest&&0==b,pid:a.pid,cid:d,title:f,count:c.length,reverse:1})});return e}a.callback()}}},infoloader:!1,infofinder:function(a){return{query:!0,selector:".book-detail",str:a.result,successfn:function(b,c,d,e){c=$$(b).find(".thumb img").attr("src");d=$$(b).find(".thumb img").attr("alt").replace("海报","");e=$$(b).find(".thumb i").text();var h=$$(b).find("dl").eq(1).find("dd").text(),
g=$$(b).find("dl").eq(3).find("dd").text(),f=$$(b).find("dl").eq(2).find("dd").text();b=$$(b).find(".book-intro").text();a.callback({name:d,img:c,added:a.data,description:"<p>"+(f?"【作者】"+f+"<br>":"")+(g?"【类型】"+g+"<br>":"")+(b?"【状态】"+e+"<br>":"")+(h?"【更新】"+h+"<br>":"")+(b?"【简介】"+b:"")+"</p>",comment:0,preview:0,tags:gettag(d)+gettag((f||"").split(","))+gettag((g||"").split(","))});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).realhost+
"manhua/"+a.pid+"/"+a.cid+".html",method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{reg:/cp="(.*?)";/g,find:"$1",str:a.result,successfn:function(b,c,d,e){b?(b=ExView.tools.base64.decode(b),b=eval(b).map(function(a){return"http://cf.pufei.net/"+a}),a.download?a.callback({source:b,download:a.download,plugin:a.plugin}):a.callback({source:b,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):
a.callback();return!0}}}},commentflag:!1,previewflag:!1,pageimgflag:!1,updateflag:{loader:function(a){return{url:pluginfo(a.plugin).realhost+"manhua/update.html",method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{query:!0,selector:"#detail li",str:a.result,successfn:function(b){console.log(b);array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).realhost+"manhua/paihang.html",
method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{query:!0,selector:"#detail li",str:a.result,successfn:function(b){console.log(b);array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}}}},fns:{pagedeal:function(a,b){b=b||{};var c=getstr(/\/manhua\/(\d+)/g,$$(a).find("a").attr("href")),d=$$(a).find("img").attr("data-src"),e=$$(a).find("h3").text(),h=$$(a).find("dl").eq(0).find("dd").text(),g=$$(a).find("dl").eq(1).find("dd").text(),
f=$$(a).find("dl").eq(2).find("dd").text(),l=$$(a).find("dl").eq(3).find("dd").text(),k="更新至 "+f;if(b.multupdate||b.multhot||b.multsearch)return b.callback(obj_contact(b,{pid:c,img:d,title:e,content:k})),!1;b.callback({pid:c,title:e,img:d,stitle:h||"",content:k+(g?"<br>"+function(a){a&&f&&(a+=","+l);var b="";(a.split(",")||[]).forEach(function(a){b+='<span style="font-size:10px;"><span class="color-white bg-'+getnowtheme()+'" style="padding:3px;border-radius:3px;margin-right:3px;">'+
a+"</span></span>"});return b}(g):""),comment:0})}}});
