ExView.Plugins({info:{name:"绅士领域图库",version:"2.2",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAABUFBMVEUAAADvn8nrl8LpgrvzhLn9rbHqd5nmjrT+sbL+r7H////2iLj7iK/xjL72hrv4hbj1h7f7hbHlcp/jdZ7ufJz0irzvgbHsfZ/sfZz/6ez62On1jb30jbnth7j9i7f6iLX/srTxg7P8jK7md6L9kp76i5z/8fX85e/84e772+v85Or51OP/19z50Nz91Nr5w9b2q87xmcftm8bymMPxk8L3iLzuibv4irfvhLT6ibH8h7Hnia38oKr8iaTneaP9mKLvepzlcpz++fr97PT85/D+4ub62uP5yOD61N32ydf/0db3tdX9vtP3s9H+yM/3ucrypMn4osj1tMf+wcX9vcXzoMT0j8Hzqr/yjr/vkL3+tLzzpLr3ibn0orj+q7XrlLX7jLPshLL6sbH7iq/siq7xk637iqfohKbug6X8kaL9lKD8iKD0iJ7pdZ3rd5zxgJsS+RteAAAACXRSTlMA9fX19efn2NgRzmkjAAAA8UlEQVQY0x2K1XbCQBQAb717NxCDxglEcHcv1N3d3eX/37p03mbOAIxVg+FA4ITnzUqpPA4wGRz5mcHzgkDPqxPAPBXIVAxeiFN6ZZpQrxc3F5NLBqVI98OPbbCsPVxNJdiPtQbHiWA1t4u6nqTsaLW4tgixWOG4qZdpzUZuy46wMMe4LzU4hh1hoe+6rix9f/Zeeo7j3IkgyzLeZna7ed9HzfuIgix1EuuFFV9bzuKFR6IgSf2nhXTuN78Txw0yCkNl7TqdC+GRhocPhMDwZ3D5fHD69n6T7SJhYXoQYqjqlzdPGFMAM51XRVFV5d9n4Q/8CSXm0J4JZwAAAABJRU5ErkJggg==",
db:"ssly",apihost:"http://45.32.22.73/",pagetitle:["<br>","收藏","领域","类型","下载"],lazyload:!0,download:!0,setting:!0,search:!1,nativeres:!1,gallerymode:!0,galleryopen:!0,vphotomode:!0,theme:"pink",cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){}})},flags:{indexflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"mz_pbl/jdly_json.php?st="+50*(parseInt(a.page||1)-1)+"&en=50&type=1&mode=1&mode_lv=2&stop=0",
timeout:120,successfn:function(b,c){a.callback&&a.callback({img:pluginfo(a.plugin).icon,multpage:!0,result:b,header:c})}}},finder:function(a){try{var b=JSON.stringify(JSON.parse(getresult(a.result)).data.blogs)}catch(c){b=""}return{json:!0,str:b,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:!1},typeflag:{loader:!1,finder:function(a){addtypelist({title:"领域",img:pluginfo(a.plugin).icon,content:"领域"});addtypelist({tid:"2",
title:"COS",img:pluginfo(a.plugin).icon,content:"COS"});addtypelist({tid:"3",title:"女神",img:pluginfo(a.plugin).icon,content:"女神"});addtypelist({tid:"4",title:"胖次",img:pluginfo(a.plugin).icon,content:"胖次"})}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"mz_pbl/jdly_json.php?st="+50*(parseInt(a.page||1)-1)+"&en=50&type="+a.tid+"&mode=1&mode_lv=2&stop=0",timeout:120,successfn:function(b,c){a.callback&&a.callback({img:pluginfo(a.plugin).icon,
multpage:!0,result:b,header:c})}}},finder:function(a){try{var b=JSON.stringify(JSON.parse(getresult(a.result)).data.blogs)}catch(c){b=""}return{json:!0,str:b,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:!1},searchflag:{loader:function(a){a.multsearch?a.callback():ExView.fw.alert("此插件不支持搜索功能！")},finder:!1,countloader:!1,countfinder:!1},contentflag:{loader:!1,finder:function(a){return{successfn:function(b,
c,e,d){console.log(typeof b);if(a.checkupdate)return{pid:a.pid,cid:"1",title:"全1话"};d=[];d[0]=additemlist({id:0,newest:a.newest&&0==e,pid:a.pid,cid:"1",title:"全1话",count:1,reverse:0});return d}}},infoloader:function(a){return!1},infofinder:function(a){console.log(a);return!1}},parseflag:{loader:function(a){return{successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){console.log(a);return{successfn:function(b,c,e,d){d=[litehextostring(a.pid).replace("/images_min/",
"/images/")];array_count(d)?(b=d,console.log(b),a.download?chapterpredownload({source:b,download:a.download,plugin:a.plugin}):chapterviewer({source:b,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.download?chapterpredownload({error:"解析错误！",download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("图片信息获取失败！","ExView"));return!0}}}},
commentflag:{loader:!1,finder:!1},previewflag:{loader:!1,finder:!1,more:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"mz_pbl/jdly_json.php?st="+50*(parseInt(a.page||1)-1)+"&en=50&type=1&mode=1&mode_lv=2&stop=0",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){try{var b=JSON.stringify(JSON.parse(getresult(a.result)).data.blogs)}catch(c){b=""}return{json:!0,str:b,successfn:function(b){array_count(b)?
plugfns(a.plugin).pagedeal(b,a):a.callback()}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"mz_pbl/jdly_json.php?st="+50*(parseInt(a.page||1)-1)+"&en=50&type=2&mode=1&mode_lv=2&stop=0",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){try{var b=JSON.stringify(JSON.parse(getresult(a.result)).data.blogs)}catch(c){b=""}return{json:!0,str:b,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}}}},
fns:{pagedeal:function(a,b){b=b||{};var c=stringtolitehex(a.isrc),e=a.sms_intro,d=a.isrc;if(c&&e){if(b.multupdate)return b.multupdate(obj_contact(b,{pid:c,img:d,title:e,content:""})),!1;if(b.multhot)return b.multhot(obj_contact(b,{pid:c,img:d,title:e,content:""})),!1;if(b.multsearch)return b.multsearch(obj_contact(b,{pid:c,img:d,title:e,content:""})),!1;addcardlist({pid:c,title:e,img:d,content:"",stitle:"",comment:0,preview:0,extrabutton:""})}}}});
