ExView.Plugins({info:{name:"有妖气漫画",version:"2.2",db:"u17",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAChklEQVQ4jXWSO29TQRBGz+5ex9evOLHjPDCvOAKFh4gCTSQoAIVHBP+ADtHyV2hoEDSUCBoKlAYoEEgIJIIoIAgUApIDIcGYGGP7+t7doXBiMBJTrUY735yZ+ZSICP+JpqtgaQOg0SR0AYXu+eNtPUKpYwkBhQI27DKP6zeohBX6lM9QHE6nr6Iw3WJDH2qL4H79MpWojsMhTgExHtbu0XAblOKH2efvQeNtyoOnYkynT3UInISEDu5+uYPguh06uJql4CVLtZc96Dv9A0ynZjsCLflBI2yTkyKRhFTDL4CgEEb9CUQEhwVAABFHKTbJgFfqCGhi7E5Ocmr7Nzaq25lfuY4AcZ2ilDrcwd4EU9owkR0nkwpIqGE8QVizr1gNFnlbbvBi/dpmJ6FBjcflW3+NpBCEdOI8x/JXSOsxvE/tBzxdv8mj98/5+uvj5oqglJ1mR//BbvHn+jveV5+h0Az5BZJ6uLPMtNnGz2aLr9+WAcWWKZaaCyytLvzjDMVgfJR43BBTyY5ATu9lJFMgp4qMD03xojyPQnNw9AQx42OUQSnNm7Un1IMKIwO7SJnCHyNpFWMwnefs8WmWFyNcE8CxWH7avTlAO2oiAoN+hoTKdfMaYMq/xKi/n/X179jA4kU+aSmQdHmSLo9vs0StCBtY0v0eY97MHwKArBnHWs3K6gckgKNHzjA7M4ezjjvzt6m3qlSqZVDQ6H9N3uzrJYikRe1nlR8ba0gIqayjaI5hDJTXPvBuZQEXQjEzyaHcOeK6v5egJVWsCpibuYBgGRlLkDFFJDLMnZylEdRQRjMwophKXuy9i4iIdW1atoYlAhWiMKTMMKFr0ZYafSYBgCGBp/wegd9u1gRAXyivIQAAAABJRU5ErkJggg==",
apihost:"http://m.u17.com/",pagetitle:["<br>","收藏","首页","类型","下载"],download:!0,lazyload:!0,theme:"green",setting:!0,webpage:{url:"http://m.u17.com/login?target=http://m.u17.com/member",title:"登陆"},cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){ExView.workers.index.loader();ExView.workers.type.loader()}})},flags:{indexflag:{loader:function(a){a.front||a.page||setnowlistname("首页",
"",pluginfo(a.plugin).icon);return{url:pluginfo(a.plugin).apihost+"waterfall/list?page="+(a.page||1)+"&pageSize=20",method:"GET",timeout:120,successfn:function(b,c){ExView.workers.index.countfinder(obj_contact(a,{result:b,header:c}));a.successfn&&a.successfn({result:b,header:c})},errorfn:function(){a.page||setnowlistname("首页","",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("网络错误！","ExView")},canclefn:function(){a.page||
setnowlistname("首页","",pluginfo(a.plugin).icon)},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),name:"首页",title:a.title,img:a.img}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){console.log(JSON.stringify(b));array_count(b)?plugfns(a.plugin).pagedeal(b):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',2)},errorfn:function(){a.page||setnowlistname("首页",
"",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("网络错误！","ExView")}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="-1|首页|index";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},typeflag:{loader:function(a){addtypelist('<div align="center" class="list-block"><img src="img/logo.png"/><br>正在加载类型...<div class="progress"></span></div>',
2);return{url:pluginfo(a.plugin).apihost+"search.html",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){addtypelist({title:"首页",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"首页"});addtypelist({tid:"",listflag:"update/list/1?page={{page}}&pageSize=20",title:"最新更新",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"最新更新"});
addtypelist({tid:"",listflag:"rank/list?page={{page}}&size=20",title:"排行",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"排行"});addtypelist({tid:"",listflag:"color/list?page={{page}}&size=20",title:"彩漫",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"彩漫"});return{reg:/<a\s*href="sort\/list\/(\d+).html"\s*class=\"classify-tag\">((?!<).*?)<\/a>/g,str:a.result,find:"$1{{separator}}$2",successfn:function(b){b=
b.split("{{separator}}");array_count(b)?addtypelist({tid:b[0],title:b[1],img:pluginfo(a.plugin).icon,group:{name:"fenlei",title:"分类"},content:b[1]}):addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>加载失败，请刷新重试！</a></div>',2)}}}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+(a.flag?a.flag.replace(/{{page}}/g,20*((parseInt(a.page)||
1)-1)):"sort/theme/"+a.keyword+"?page="+(a.page||1)+"&size=20"),method:"GET",timeout:120,successfn:function(b,c){b?(ExView.workers.list.countfinder(obj_contact(a,{result:b,header:c})),a.successfn&&a.successfn({result:b,header:c})):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+a.title+"】<br>获取失败！","ExView"))},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),name:"【"+a.title+"】",title:a.title,
img:a.img}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){b?plugfns(a.plugin).pagedeal(b):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="0|"+a.keyword+"|list";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},searchflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"search/comic/",method:"POST",data:"key="+encodeURIComponent(a.keyword)+"&page="+parseInt(a.page||1),timeout:120,header:{"content-type":"application/x-www-form-urlencoded"},successfn:function(b,c){b?(a.multsearch||(ExView.workers.search.countfinder(obj_contact(a,{result:b,header:c})),setnowlistname("搜索【"+a.keyword+"】")),a.successfn&&a.successfn({result:b,header:c})):a.multsearch?a.multsearch():(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+a.keyword+
"】<br>获取搜索结果失败！","ExView"))},showinfo:{text:"正在搜索..."+(1<a.page?"<br>第"+a.page+"页":""),name:"【"+a.keyword+"】",title:"搜索"}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b,c,d){console.log(b);array_count(b)?(b.allPage&&(mySession.nowlistpages=b.allPage+"|"+a.keyword+"|search"),b=b.comics,b.length||(a.multsearch?a.multsearch():addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',
1)),b.forEach(function(b){plugfns(a.plugin).pagedeal(b,a)})):a.multsearch?a.multsearch():addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(b){mySession.nowlistpages="0|"+a.keyword+"|search";mySession.nowlistpage=1;console.log(mySession.nowlistpages)}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"chapter/list?comicId="+
a.pid,method:"GET",timeout:120,successfn:function(b,c){b?a.successfn&&a.successfn({result:b,header:c}):a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},showinfo:{text:"正在加载目录...",title:"内容页",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b,c,d,e){if(array_count(c)){if(a.checkupdate)return{pid:b.comicId,
cid:b.chapterId,title:b.name+(b.imageTotal?b.imageTotal+"P":"")};e=[];for(d=0;d<c.length;d++)e[d]=additemlist({id:c.length-d-1,newest:a.newest&&0==d,pid:c[d].comicId,cid:c[d].chapterId,title:(c[d].price?"【VIP】":"")+c[d].name+(c[d].imageTotal?"("+c[d].imageTotal+"P)":""),count:c.length,reverse:1});return e}a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},afterfn:function(){a.checkupdate||ExView.workers.content.infoloader(a)}}},
infoloader:function(a){return{url:pluginfo(a.plugin).apihost+"comic/"+a.pid,method:"GET",timeout:120,successfn:function(b,c){b?a.successfn&&a.successfn({result:b,header:c}):a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},showinfo:{text:"正在加载内容页...",title:"内容页",name:getlistname(a.pid),img:getlistimg(a.pid)}}},infofinder:function(a){console.log(a);return{json:!0,
str:a.result,successfn:function(b,c,d,e){c=b.cover;d=b.name;e=getLocalTime(1E3*parseInt(b.lastUpdateTime));var f=b.authorName;setlistpic({name:d,img:c,added:a.data,description:"<p>【作者】"+f+"<br>【更新】"+e+"<br>【简介】"+b.description+"</p>",comment:1,preview:0,tags:gettag(d)+gettag(f),sourceurl:pluginfo(a.plugin).apihost+"c/"+a.pid+".html"});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"image/list?comicId="+a.pid+
"&chapterId="+a.cid,method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"正在加载图片信息...",title:"图片",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){console.log(a);return{json:!0,str:a.result,successfn:function(b,c,d,e){array_count(b)?(b=b.data.list,b=b.map(function(a){return a.location}),console.log(b),a.download?chapterpredownload({source:b,download:a.download,plugin:a.plugin}):
chapterviewer({source:b,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.download?chapterpredownload({error:"解析错误！",download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("图片信息获取失败！","ExView"));return!0}}}},commentflag:{loader:function(a){myContent.threadId||$$.ajax({url:pluginfo(a.plugin).apihost+"comment/thread/"+a.pid,async:!1,
success:function(a){a=JSON.parse(a);myContent.threadId=a.threadId}});return{url:pluginfo(a.plugin).apihost+"comment/list?threadId="+myContent.threadId+"&page="+(a.page||1)+"&pageSize=20",method:"GET",timeout:120,successfn:function(b,c){b?a.callback&&a.callback({result:b,header:c,commentbrowser:{url:pluginfo(a.plugin).apihost+"c/"+a.pid+".html",title:"评论 - "+pluginfo(a.plugin).name+'<br><span style="font-size:16px">'+(myContent.name||"")+"</span>",browser:!1,flag:""}}):a.callback&&a.callback()}}},
finder:function(a){console.log(a);return{json:!0,str:a.result,successfn:function(b,c,d,e){array_count(b)?a.callback&&a.callback({page:a.page||1,pagecount:0,comment:{text:b.content,name:b.nickname,avatar:b.xxMember.face,type:"received",label:getLocalTime(1E3*parseInt(b.replyTime)),day:"",time:"",reverse:1,extra:""}}):a.callback&&a.callback({page:a.page||1,pagecount:-1})}}},send:!1},previewflag:{loader:!1,finder:!1,more:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"update/list/1?page="+20*(parseInt(a.page||1)-1)+"&pageSize=20",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){console.log(JSON.stringify(b));array_count(b)&&plugfns(a.plugin).pagedeal(b,a)}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"rank/list?page="+20*(parseInt(a.page||1)-1)+"&size=20",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,
header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){console.log(JSON.stringify(b));array_count(b)&&plugfns(a.plugin).pagedeal(b,a)}}}}},fns:{pagedeal:function(a,b){b=b||{};var c=a.comicId,d=a.comicCover||a.cover,e=a.comicName||a.name,f=a.brief||"更新至"+a.chapterNum+"话",h=a.lastUpdateTime?getLocalTime(1E3*a.lastUpdateTime):"",k=a.description,g=a.isVip;if(b.multupdate)return b.multupdate(obj_contact(b,{pid:c,img:d,title:e,content:f})),!1;if(b.multhot)return b.multhot(obj_contact(b,
{pid:c,img:d,title:e,content:f})),!1;if(b.multsearch)return b.multsearch(obj_contact(b,{pid:c,img:d,title:e,content:f})),!1;addcardlist({pid:c,title:e,img:d,stitle:f+" "+h,content:(g?"【VIP"+g+"】":"")+(k||""),comment:1})}}});
