ExView.Plugins({info:{name:"有妖气漫画",version:"2.2",db:"u17",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAChklEQVQ4jXWSO29TQRBGz+5ex9evOLHjPDCvOAKFh4gCTSQoAIVHBP+ADtHyV2hoEDSUCBoKlAYoEEgIJIIoIAgUApIDIcGYGGP7+t7doXBiMBJTrUY735yZ+ZSICP+JpqtgaQOg0SR0AYXu+eNtPUKpYwkBhQI27DKP6zeohBX6lM9QHE6nr6Iw3WJDH2qL4H79MpWojsMhTgExHtbu0XAblOKH2efvQeNtyoOnYkynT3UInISEDu5+uYPguh06uJql4CVLtZc96Dv9A0ynZjsCLflBI2yTkyKRhFTDL4CgEEb9CUQEhwVAABFHKTbJgFfqCGhi7E5Ocmr7Nzaq25lfuY4AcZ2ilDrcwd4EU9owkR0nkwpIqGE8QVizr1gNFnlbbvBi/dpmJ6FBjcflW3+NpBCEdOI8x/JXSOsxvE/tBzxdv8mj98/5+uvj5oqglJ1mR//BbvHn+jveV5+h0Az5BZJ6uLPMtNnGz2aLr9+WAcWWKZaaCyytLvzjDMVgfJR43BBTyY5ATu9lJFMgp4qMD03xojyPQnNw9AQx42OUQSnNm7Un1IMKIwO7SJnCHyNpFWMwnefs8WmWFyNcE8CxWH7avTlAO2oiAoN+hoTKdfMaYMq/xKi/n/X179jA4kU+aSmQdHmSLo9vs0StCBtY0v0eY97MHwKArBnHWs3K6gckgKNHzjA7M4ezjjvzt6m3qlSqZVDQ6H9N3uzrJYikRe1nlR8ba0gIqayjaI5hDJTXPvBuZQEXQjEzyaHcOeK6v5egJVWsCpibuYBgGRlLkDFFJDLMnZylEdRQRjMwophKXuy9i4iIdW1atoYlAhWiMKTMMKFr0ZYafSYBgCGBp/wegd9u1gRAXyivIQAAAABJRU5ErkJggg==",
apihost:"http://app.u17.com/",pagetitle:["<br>","收藏","首页","类型","下载"],download:!0,lazyload:!0,theme:"green",setting:!0,cdn:""},set:function(a){},unset:function(a){},init:function(a){ExView.workers.fav.listloader({callback:function(){}})},flags:{indexflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"v3/appV3_2/android/phone/comic/boutiqueListNew",method:"GET",timeout:120,successfn:function(b,c){a.callback({img:pluginfo(a.plugin).icon,multpage:!0,
result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){b=(b||{}).data.returnData.comicLists;array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.callback()}}},countloader:!1,countfinder:function(a){return{successfn:function(b){a.callback({pagecount:-1})}}}},typeflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"v3/appV3_2/android/phone/sort/mobileCateList",method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){a.callback({title:"首页",
img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"首页"});a.callback({tid:"",listflag:"v3/appV3_2/android/phone/rank/newRankList",title:"排行",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"排行"});a.callback({tid:"",listflag:"v3/appV3_2/android/phone/list/commonComicList?argValue=23&argName=sort&argCon=0&page={{page}}",title:"月票排行",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},
content:"月票排行"});a.callback({tid:"",listflag:"v3/appV3_2/android/phone/list/commonComicList?argValue=25&argName=sort&argCon=0&page={{page}}",title:"点击排行",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"点击排行"});a.callback({tid:"",listflag:"v3/appV3_2/android/phone/list/commonComicList?argValue=0&argName=sort&argCon=0&page={{page}}",title:"今日更新",img:pluginfo(a.plugin).icon,group:{name:"daohang",
title:"导航"},content:"今日更新"});a.callback({tid:"",listflag:"v3/appV3_2/android/phone/list/commonComicList?argValue=1&argName=serial&argCon=4&page={{page}}",title:"完结作品",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"完结作品"});a.callback({tid:"",listflag:"v3/appV3_2/android/phone/list/commonComicList?argValue=8&argName=topic&argCon=0&page={{page}}",title:"强力推荐",img:pluginfo(a.plugin).icon,
group:{name:"daohang",title:"导航"},content:"强力推荐"});a.callback({tid:"",listflag:"v3/appV3_2/android/phone/list/commonComicList?argValue=9&argName=topic&argCon=0&page={{page}}",title:"人气推荐",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"人气推荐"});a.callback({tid:"",listflag:"v3/appV3_2/android/phone/list/commonComicList?argValue=2&argName=sort&argCon=0&page={{page}}",title:"热门新品",
img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"热门新品"});a.callback({tid:"",listflag:"v3/appV3_2/android/phone/list/commonComicList?argValue=12&argName=topic&argCon=0&page={{page}}",title:"订阅漫画",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"订阅漫画"});a.callback({tid:"",listflag:"v3/appV3_2/android/phone/list/commonComicList?argValue=16&argName=topic&argCon=0&page={{page}}",
title:"新作签约",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"新作签约"});a.callback({tid:"",listflag:"v3/appV3_2/android/phone/list/commonComicList?argValue=15&argName=topic&argCon=4&page={{page}}",title:"独家签约",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"独家签约"});a.callback({tid:"",listflag:"v3/appV3_2/android/phone/list/commonComicList?argValue=14&argName=topic&argCon=0&page={{page}}",
title:"VIP会员漫画",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"VIP会员漫画"});a.callback({tid:"",listflag:"v3/appV3_2/android/phone/list/commonComicList?argValue=7&argName=topic&argCon=4&page={{page}}",title:"彩漫作品",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"彩漫作品"});a.callback({tid:"",listflag:"v3/appV3_2/android/phone/list/commonComicList?argValue=13&argName=topic&page={{page}}",
title:"条漫每日更新",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"条漫每日更新"});return{json:!0,str:a.result,successfn:function(b){b=(b||{}).data.returnData.rankingList||[];array_count(b)&&b.forEach(function(b){a.callback({tid:b.sortId,title:b.sortName,img:b.cover,listflag:"v3/appV3_2/android/phone/list/commonComicList?argValue="+b.argValue+"&argName="+b.argName+"&argCon="+b.argCon+"&page={{page}}",group:{name:"fenlei",
title:"分类"},content:b.sortName})})}}}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+a.flag.replace("{{page}}",a.page||1),method:"GET",timeout:120,successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){b=-1!=(a.flag||"").indexOf("page=")?b.data.returnData.comics:b.data.returnData.newVipList||b.data.returnData.newRankList;if(array_count(b)){if(-1!=(a.flag||"").indexOf("page=")){var c=
[];c.push({comics:b});b=c}plugfns(a.plugin).pagedeal(b,a)}else a.callback()}}},countloader:!1,countfinder:function(a){return{json:!0,str:a.result,successfn:function(b){b=-1!=(a.flag||"").indexOf("page=")?0:-1;a.callback({pagecount:b})}}}},searchflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"v3/appV3_2/android/phone/search/searchResult?q="+encodeURIComponent(a.keyword)+"&page="+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){a.callback({multpage:!0,result:b,header:c})}}},
finder:function(a){return{json:!0,str:a.result,successfn:function(b){b=(b||{}).data.returnData.comics;if(array_count(b)){var c=[];c.push({comics:b});b=c;plugfns(a.plugin).pagedeal(b,a)}else a.callback()}}},countloader:!1,countfinder:function(a){return{successfn:function(b){a.callback({pagecount:0})}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"v3/appV3_2/android/phone/comic/detail_static_new?comicid="+a.pid,method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,
header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b,c,d,e){b=(b||{}).data.returnData.chapter_list;if(array_count(b)){if(a.checkupdate)return b=b.pop(),a.callback({pid:a.pid,cid:b.chapter_id,title:(b.price?"【"+b.vip_images+"】":"")+"["+b.image_total+"P]"+b.name}),!0;b.forEach(function(c,d){e[d]=a.callback({id:d,newest:a.newest&&0==d,pid:a.pid,cid:c.chapter_id,title:(0<parseInt(c.price)?"【VIP】":"")+"["+c.image_total+"P]"+c.name,count:b.length,reverse:0})});
return e}a.callback()}}},infoloader:!1,infofinder:function(a){return{json:!0,str:a.result,successfn:function(b,c,d,e){b=(b||{}).data.returnData.comic;c=b.name;d=b.last_update_time;e=b.author.name;var f=b.theme_ids,k=b.description,g=b.cate_id;a.callback({name:c,img:b.cover,added:a.data,description:"<p>"+(e?"【作者】"+e+"<br>":"")+(f?"【题材】"+f+"<br>":"")+(d?"【更新】"+d+"<br>":"")+(g?"【类型】"+g+"<br>":"")+(k?"【简介】"+
k:"")+"</p>",sourceurl:"http://m.u17.com/c/"+a.pid+".html",comment:1,preview:0,tags:gettag(c)+gettag(e)+gettag(g||"")+gettag(f||"")});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"v3/appV3_2/android/phone/comic/chapterNew?chapter_id="+a.cid+"&key=0ec082a11b232b3428b30e413ccb2be001dc1db80d9f0328c06d2fb72f792228f101f77c1c2759b807ecaef47f61f314ffaa27454fe7f8ffbcaf725c21feb50cb75d519a2b541e9e7c1ded12b85ac987542985fc321493ed5950057b357efd14cd950953b589251795c3560d74a788367e2866142bdb8ce877225d1e5f40cad87d8608917883c5504ec01be2de5447a5013f5d9d669ea50e:::open",
method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b,c,d,e){c=b.data.stateCode;b=(b||{}).data.returnData.image_list;array_count(b)?(b=b.map(function(a){return a.location}),a.download?a.callback({source:b,type:"image",download:a.download,plugin:a.plugin}):a.callback({source:b,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):-4!=c||a.download?a.callback():
(ExView.fw.hidePreloader(),ExView.fw.alert("这为VIP章节！",function(){openweburl("http://m.u17.com/c/"+a.pid+".html",myContent.name)}));return!0}}}},commentflag:{loader:function(a){var b=function(b,d){b?a.callback({result:b,header:d,commentbrowser:!1}):a.callback()};return myContent.threatid?{url:pluginfo(a.plugin).apihost+"v3/appV3_2/android/phone/comment/list?thread_id="+myContent.threatid+"&object_id="+a.pid+"&page="+((a.page||1)-1),method:"GET",timeout:120,successfn:function(a,
d){b(a,d)}}:{url:"http://m.u17.com/c/"+a.pid+".html",method:"GET",timeout:120,successfn:function(c,d){myContent.threatid=getstr(/\$thread\_id\s*=\s*"(\d+)"\;/g,c);$$.get(pluginfo(a.plugin).apihost+"v3/appV3_2/android/phone/comment/list?thread_id="+myContent.threatid+"&object_id="+a.pid+"&page=0",function(a){b(a,d)},function(){b()})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b,c,d,e){b=(b||{}).data.returnData;if(array_count(b)){c=b.pageCount;b=b.commentList;for(var f in b)a.callback({page:a.page||
1,pagecount:c,comment:{text:b[f].content,name:b[f].nickname||"",avatar:b[f].face,type:"received",label:getLocalTime(1E3*parseInt(b[f].create_time||0)),day:"",time:"",reverse:1,extra:""}})}}}},send:!1},previewflag:{loader:!1,finder:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"v3/appV3_2/android/phone/list/commonComicList?argValue=0&argName=sort&argCon=0&page="+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},
finder:function(a){return{json:!0,str:a.result,successfn:function(b){b=b.data.returnData.comics;if(array_count(b)){var c=[];c.push({comics:b});b=c;plugfns(a.plugin).pagedeal(b,a)}else a.callback()}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"v3/appV3_2/android/phone/list/commonComicList?argValue=25&argName=sort&argCon=0&page="+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){a.callback({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){b=
b.data.returnData.comics;if(array_count(b)){var c=[];c.push({comics:b});b=c;plugfns(a.plugin).pagedeal(b,a)}else a.callback()}}}}},fns:{pagedeal:function(a,b){b=b||{};a.forEach(function(a){(function(a){a.comics.forEach(function(a){var c=a.comicId,d=a.cover,g=a.name,l=a.author_name,m=a.description,h=a.short_description;a=a.is_vip;if(b.multupdate||b.multhot||b.multsearch)return b.callback(obj_contact(b,{pid:c,img:d,title:g,content:h})),!1;b.callback({pid:c,title:g,img:d,stitle:l||"",content:(a?getboxitem("VIP"+
a):"")+m,comment:1})})})(a)})}}});
