ExView.Plugins({info:{name:"轻小说文库",version:"2.2",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAXVBMVEXD5/wAov9huP0brP4psP4RqP5hxP0Hpf9bwv295fy54/y04vyq3vyK0/xHu/4xtP4irv6C0P16zf1Pvv1xyv1px/2i2/ye2vyX2PyS1fxBuf46tv4wof6P1P2l3PzBmYhCAAAAhklEQVQY022PRw6EMAxF+Ti9QAp12v2POSFhMYN4C1t6+rbs7kJ/L0zuLBEbB9UEAaRSFgOTuopPYOLNHlGasSUi+ChogcVeReZIHFNQibelKDw5ZqyYm/BwWCfjtT4TnIgYCqyJRQZRmlQ+VuEIwBG056VGYNcDfkY6fxTrts3dPtf/8/oCiK0Eq4OpL1EAAAAASUVORK5CYII=",author:"Gentle",
type:"text",db:"wenku8",apihost:"http://www.wenku8.com/",pagetitle:["<br>","收藏","首页","类型","下载"],lazyload:!0,download:!0,setting:!0,typelistmode:!0,smallpicmode:!0,requestcookie:"",cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){ExView.modules.curl({url:pluginfo("wenku8").apihost+"login.php?do=submit",method:"POST",data:"username=ghostgzt&password=123456&usecookie=315360000&action=login&submit=%26%23160%3B%B5%C7%26%23160%3B%26%23160%3B%C2%BC%26%23160%3B",
timeout:120,header:{"Content-Type":"application/x-www-form-urlencoded"},successfn:function(a,b){var c=b["Set-Cookie"],d="",e;for(e in c)d+=c[e].split(";")[0]+";";d&&setpluginfo("wenku8","requestcookie",d,1);ExView.fw.hidePreloader();mySession.isloading=0;ExView.workers.index.loader();ExView.workers.type.loader()},canclefn:function(){ExView.fw.hidePreloader();mySession.isloading=0;ExView.workers.index.loader();ExView.workers.type.loader()},errorfn:function(){ExView.fw.hidePreloader();mySession.isloading=
0;ExView.workers.index.loader();ExView.workers.type.loader()},showinfo:{text:"正在初始化...",name:pluginfo("wenku8").name,img:pluginfo("wenku8").icon,title:"初始化"},autoencode:!1})}})},flags:{indexflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"index.php",method:"GET",timeout:120,successfn:function(b,c){ExView.workers.index.countfinder(obj_contact(a,{result:b,header:c}));a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"正在加载..."+
(1<a.page?"<br>第"+a.page+"页":""),title:a.title,name:"首页",img:a.img}}},finder:function(a){return{reg:/\/book\/(\d+).htm"(?!>).*?title="((?!\").*?)"><img src="((?!\").*?)"/g,str:a.result,find:{pid:"$1",img:"$3",title:"$2"},successfn:function(a){console.log(JSON.stringify(a));array_count(a)?addcardlist({pid:a.pid,title:a.title,img:a.img,content:a.content,comment:1}):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',2)},
errorfn:function(){a.page||setnowlistname("首页","",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("网络错误！","ExView")}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="-1|首页|index";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},typeflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"modules/article/articlelist.php",
method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){addtypelist({title:"首页",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"首页"});addtypelist({tid:"",listflag:"articlelist.php",title:"轻小说列表",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"轻小说列表"});addtypelist({tid:"",listflag:"toplist.php?sort=allvisit",
title:"热门轻小说",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"热门轻小说"});addtypelist({tid:"",listflag:"toplist.php?sort=anime",title:"动画化作品",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"动画化作品"});addtypelist({tid:"",listflag:"toplist.php?sort=lastupdate",title:"今日更新",img:pluginfo(a.plugin).icon,group:{name:"daohang",
title:"导航"},content:"今日更新"});addtypelist({tid:"",listflag:"toplist.php?sort=postdate",title:"新书一览",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"新书一览"});addtypelist({tid:"",listflag:"articlelist.php?fullflag=1",title:"完结全本",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"完结全本"});getstrs(a.result,/articlelist.php\?class=(.*?)">((?!<).*?)<\/a>/g,
"$1{{separator}}$2").forEach(function(b){b=(b||"").split("{{separator}}");addtypelist({tid:"",listflag:"articlelist.php?class="+b[0],title:b[1],img:pluginfo(a.plugin).icon,group:{name:"fenlei",title:"分类"},content:b[1]})});getstrs(getstr(/class="ulcenter">(.*?)<\/ul>/,getresult(a.result)),/toplist.php\?sort=(.*?)">((?!<).*?)<\/a>/g,"$1{{separator}}$2").forEach(function(b){b=(b||"").split("{{separator}}");addtypelist({tid:"",listflag:"toplist.php?sort="+b[0],title:b[1],img:pluginfo(a.plugin).icon,
group:{name:"paihang",title:"排行榜"},content:b[1]})});return!1}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"modules/article/"+a.flag+"&page="+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){b?(ExView.workers.list.countfinder(obj_contact(a,{result:b,header:c})),a.successfn&&a.successfn({result:b,header:c})):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+a.title+"】<br>获取失败！","ExView"))},showinfo:{text:"正在加载..."+
(1<a.page?"<br>第"+a.page+"页":""),title:a.title,name:"【"+a.title+"】",img:a.img}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{reg:plugfns(a.plugin).pagecountrule,
str:a.result,find:plugfns(a.plugin).pagecountfind,successfn:function(b){mySession.nowlistpages=(b||"0")+"|"+a.keyword+"|list";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},searchflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"modules/article/search.php?searchtype=articlename&searchkey="+ExView.tools.gbk.encode(a.keyword)+"&page="+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){b?(a.multsearch||(ExView.workers.search.countfinder(obj_contact(a,
{result:b,header:c})),setnowlistname("搜索【"+a.keyword+"】")),a.successfn&&a.successfn({result:b,header:c})):a.multsearch?a.multsearch():(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+a.keyword+"】<br>获取搜索结果失败！","ExView"))},showinfo:{text:"正在搜索..."+(1<a.page?"<br>第"+a.page+"页":""),name:"【"+a.keyword+"】",title:"搜索"},autoencode:!1}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,
str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b,c,d){console.log(b);array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.multsearch?a.multsearch():addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{reg:plugfns(a.plugin).pagecountrule,str:a.result,find:plugfns(a.plugin).pagecountfind,successfn:function(b){mySession.nowlistpages=(b||"0")+"|"+a.keyword+
"|search";mySession.nowlistpage=1;console.log(mySession.nowlistpages)}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"novel/"+plugfns(a.plugin).getnid(a.pid)+"/"+a.pid+"/index.htm",method:"GET",timeout:120,successfn:function(b,c){b?a.successfn&&a.successfn({result:b,header:c}):a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},showinfo:{text:"正在加载目录...",
title:"内容页",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){var b=[];a.result=getresult(a.result).replace(/<td\s*class="vcss"/g,'<exveiw><td class="vcss"').replace(/<\/table>/g,"<exveiw></table>");var c=getstrs(a.result,/<td\s*class="vcss"(.*?)<exveiw>/g,"$1"),c=c.map(function(a){var c=getstr(/colspan="\d+">((?!>).*?)<\/td>/,a);getstrs(a,/(\d+).htm">((?!>).*?)<\/a>/g,"$1{{separator}}$2").map(function(a){a=(a||"").split("{{separator}}");b.push({group:{name:"type_"+
ExView.tools.md5.hex_md5(c),title:c},item:{cid:a[0],title:a[1]}})})});return{successfn:function(c,e,g,f){console.log(typeof c);if(array_count(c)){if(a.checkupdate)return e=b,c=e[e.length-1],g=(c||{}).group.title,c=(c||{}).item,{pid:a.pid,cid:c.cid,title:g+" "+c.title};e=b;f=[];b.map(function(b,c){var d=b.item;f[c]=additemlist({id:c,newest:a.newest&&0==c,pid:a.pid,cid:d.cid,title:d.title,group:b.group,count:e.length,reverse:0});f[c].title=b.group.title+" "+d.title});return f}a.checkupdate||(ExView.fw.hidePreloader(),
mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},afterfn:function(){a.checkupdate||ExView.workers.content.infoloader(a)}}},infoloader:function(a){return{url:pluginfo(a.plugin).apihost+"book/"+a.pid+".htm",method:"GET",timeout:120,successfn:function(b,c){b?a.successfn&&a.successfn({result:b,header:c}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},showinfo:{text:"正在加载简介信息...",
title:"内容页",name:getlistname(a.pid),img:getlistimg(a.pid)}}},infofinder:function(a){console.log(a);return{reg:/id="content"(.*?)<fieldset/g,str:getresult(a.result),find:"$1",successfn:function(b,c,d,e){console.log(JSON.stringify(b));c=getstr(/<img(?!<).*?src="((?!\").*?)"/,b);d=getstr(/<b>((?!<).*?)<\/b>/,b);e=getstr(/>文章状态：((?!<).*?)<\/td>/,b).trim();var g=getstr(/>小说作者：((?!<).*?)<\/td>/,b).trim(),f=getstr(/>文库分类：((?!<).*?)<\/td>/,
b).trim(),l=gettext(getstr(/>最近章节：<\/span>(.*?)<\/span>/,b).trim()),m=getstr(/>最后更新：((?!<).*?)<\/td>/,b).trim(),h=getstr(/>全文长度：((?!<).*?)<\/td>/,b).trim();b=getstr(/class="hottext">内容简介：(.*?)<\/td>/,b).trim();var n=gettag(f);setlistpic({name:d,img:c,added:a.data,description:"<p>【作者】"+g+"<br>【类型】"+f+"<br>【字数】"+h+"<br>【"+e+"】"+m+"<br>【最新话】"+
l+"<br>【简介】"+gettext(b)+"</p>",sourceurl:pluginfo(a.plugin).apihost+"book/"+a.pid+".htm",comment:1,preview:0,tags:gettag(d)+gettag(e)+n+gettag(g)});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"novel/"+plugfns(a.plugin).getnid(a.pid)+"/"+a.pid+"/"+a.cid+".htm",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"正在加载文章信息...",title:"文章",
name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){console.log(a);return{reg:/<div\s*id="content">(.*?)<div\s*id="footlink">/g,str:getresult(a.result),find:"$1",successfn:function(b){b?(b=getarticle(b),console.log(b),a.download?chapterpredownload({type:"text",source:b,download:a.download,plugin:a.plugin}):chapterviewer({source:b,type:"text",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.download?chapterpredownload({error:"解析错误！",
download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("文章信息获取失败！","ExView"));return!0}}}},commentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"modules/article/reviews.php?aid="+a.pid+"&type=all&page="+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){b?a.callback&&a.callback({result:b,header:c,commentbrowser:{url:pluginfo(a.plugin).apihost+"modules/article/reviews.php?aid="+a.pid+
"&type=all",title:"评论 - "+pluginfo(a.plugin).name+'<br><span style="font-size:16px">'+(myContent.name||"")+"</span>",browser:!1,flag:""}}):a.callback&&a.callback()}}},finder:function(a){console.log(a);return{reg:/<td class="odd"><(?!>).*?>((?!<).*?)<.*?class="odd"><(?!>).*?>((?!<).*?)<.*?class="even">((?!<).*?)</g,str:getresult(a.result),find:{time:"$3",name:"$2",text:"$1"},successfn:function(b,c,d,e){array_count(b)&&(c=getstr(/class="last">(\d+)<\/a>/,a.result),a.callback&&a.callback({page:a.page||
1,pagecount:c,comment:{text:b.text,name:b.name,avatar:"",type:"received",label:b.time,day:"",time:"",reverse:1,extra:""}}))}}},send:!1},previewflag:{loader:!1,finder:!1,more:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"modules/article/toplist.php?sort=lastupdate&page="+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:getresult(a.result),
find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));array_count(b)&&plugfns(a.plugin).pagedeal(b,a)}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"modules/article/toplist.php?sort=allvisit&page="+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));
array_count(b)&&plugfns(a.plugin).pagedeal(b,a)}}}}},fns:{getnid:function(a){a=(a||"0").toString();return 4>a.length?0:a.substr(0,1)},pagecountrule:/class="last">(\d+)<\/a>/,pagecountfind:"$1",pagerule:/\/book\/(\d+).htm"(.*?)>我要阅读</g,pagefind:{pid:"$1",content:"$2"},pagedeal:function(a,b){b=b||{};var c=a.pid;a=a.content;var d=getstr(/<img(?!<).*?src="((?!\").*?)"/,a),e=getstr(/title="((?!\").*?)"/,a).trim(),g=getstr(/<p>作者:((?!<).*?)\//,a).trim(),f=getstr(/分类:((?!<).*?)\//,
a).trim(),l=getstr(/状态:((?!<).*?)<\/p>/,a).trim(),m=getstr(/<p>最后更新:((?!<).*?)[\<,\/]+/,a).trim(),h=getstr(/字数:(\d+)<\/p>/,a).trim(),n=gettext(getstr(/<p>简介:((?!<).*?)<\/p>/,a).trim()),k=f;if(b.multupdate)return b.multupdate(obj_contact(b,{pid:c,img:d,title:e,content:k})),!1;if(b.multhot)return b.multhot(obj_contact(b,{pid:c,img:d,title:e,content:k})),!1;if(b.multsearch)return b.multsearch(obj_contact(b,{pid:c,img:d,title:e,content:k})),!1;k=n;addcardlist({pid:c,
title:e,name:e,img:d,content:(f?"【类型】"+f+"<br>":"")+(g?"【作者】"+g+"<br>":"")+(l?"【状态】"+l+"<br>":"")+(h?"【字数】"+h+"<br>":"")+(m?"【最后更新】"+m+"<br>":"")+(h?"【字数】"+h+"<br>":"")+(k?"【简介】"+k+"<br>":""),comment:1,preview:0,extrabutton:""})}}});
