ExView.Plugins({info:{name:"\u8f7b\u5c0f\u8bf4\u6587\u5e93",version:"2.2",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAXVBMVEXD5/wAov9huP0brP4psP4RqP5hxP0Hpf9bwv295fy54/y04vyq3vyK0/xHu/4xtP4irv6C0P16zf1Pvv1xyv1px/2i2/ye2vyX2PyS1fxBuf46tv4wof6P1P2l3PzBmYhCAAAAhklEQVQY022PRw6EMAxF+Ti9QAp12v2POSFhMYN4C1t6+rbs7kJ/L0zuLBEbB9UEAaRSFgOTuopPYOLNHlGasSUi+ChogcVeReZIHFNQibelKDw5ZqyYm/BwWCfjtT4TnIgYCqyJRQZRmlQ+VuEIwBG056VGYNcDfkY6fxTrts3dPtf/8/oCiK0Eq4OpL1EAAAAASUVORK5CYII=",author:"Gentle",
type:"text",db:"wenku8",apihost:"http://www.wenku8.com/",pagetitle:["<br>","\u6536\u85cf","\u9996\u9875","\u7c7b\u578b","\u4e0b\u8f7d"],lazyload:!0,download:!0,setting:!0,typelistmode:!0,smallpicmode:!0,requestcookie:"",cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){ExView.modules.curl({url:pluginfo("wenku8").apihost+"login.php?do=submit",method:"POST",data:"username=ghostgzt&password=123456&usecookie=315360000&action=login&submit=%26%23160%3B%B5%C7%26%23160%3B%26%23160%3B%C2%BC%26%23160%3B",
timeout:120,header:{"Content-Type":"application/x-www-form-urlencoded"},successfn:function(a,b){var c=b["Set-Cookie"],d="",e;for(e in c)d+=c[e].split(";")[0]+";";d&&setpluginfo("wenku8","requestcookie",d,1);ExView.fw.hidePreloader();mySession.isloading=0;ExView.workers.index.loader();ExView.workers.type.loader()},canclefn:function(){ExView.fw.hidePreloader();mySession.isloading=0;ExView.workers.index.loader();ExView.workers.type.loader()},errorfn:function(){ExView.fw.hidePreloader();mySession.isloading=
0;ExView.workers.index.loader();ExView.workers.type.loader()},showinfo:{text:"\u6b63\u5728\u521d\u59cb\u5316...",name:pluginfo("wenku8").name,img:pluginfo("wenku8").icon,title:"\u521d\u59cb\u5316"},autoencode:!1})}})},flags:{indexflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"index.php",method:"GET",timeout:120,successfn:function(b,c){ExView.workers.index.countfinder(obj_contact(a,{result:b,header:c}));a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"\u6b63\u5728\u52a0\u8f7d..."+
(1<a.page?"<br>\u7b2c"+a.page+"\u9875":""),title:a.title,name:"\u9996\u9875",img:a.img}}},finder:function(a){return{reg:/\/book\/(\d+).htm"(?!>).*?title="((?!\").*?)"><img src="((?!\").*?)"/g,str:a.result,find:{pid:"$1",img:"$3",title:"$2"},successfn:function(a){console.log(JSON.stringify(a));array_count(a)?addcardlist({pid:a.pid,title:a.title,img:a.img,content:a.content,comment:1}):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u6ca1\u6709\u5185\u5bb9</div>',2)},
errorfn:function(){a.page||setnowlistname("\u9996\u9875","",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("\u7f51\u7edc\u9519\u8bef\uff01","ExView")}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="-1|\u9996\u9875|index";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},typeflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"modules/article/articlelist.php",
method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){addtypelist({title:"\u9996\u9875",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u9996\u9875"});addtypelist({tid:"",listflag:"articlelist.php",title:"\u8f7b\u5c0f\u8bf4\u5217\u8868",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u8f7b\u5c0f\u8bf4\u5217\u8868"});addtypelist({tid:"",listflag:"toplist.php?sort=allvisit",
title:"\u70ed\u95e8\u8f7b\u5c0f\u8bf4",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u70ed\u95e8\u8f7b\u5c0f\u8bf4"});addtypelist({tid:"",listflag:"toplist.php?sort=anime",title:"\u52a8\u753b\u5316\u4f5c\u54c1",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u52a8\u753b\u5316\u4f5c\u54c1"});addtypelist({tid:"",listflag:"toplist.php?sort=lastupdate",title:"\u4eca\u65e5\u66f4\u65b0",img:pluginfo(a.plugin).icon,group:{name:"daohang",
title:"\u5bfc\u822a"},content:"\u4eca\u65e5\u66f4\u65b0"});addtypelist({tid:"",listflag:"toplist.php?sort=postdate",title:"\u65b0\u4e66\u4e00\u89c8",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u65b0\u4e66\u4e00\u89c8"});addtypelist({tid:"",listflag:"articlelist.php?fullflag=1",title:"\u5b8c\u7ed3\u5168\u672c",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u5b8c\u7ed3\u5168\u672c"});getstrs(a.result,/articlelist.php\?class=(.*?)">((?!<).*?)<\/a>/g,
"$1{{separator}}$2").forEach(function(b){b=(b||"").split("{{separator}}");addtypelist({tid:"",listflag:"articlelist.php?class="+b[0],title:b[1],img:pluginfo(a.plugin).icon,group:{name:"fenlei",title:"\u5206\u7c7b"},content:b[1]})});getstrs(getstr(/class="ulcenter">(.*?)<\/ul>/,getresult(a.result)),/toplist.php\?sort=(.*?)">((?!<).*?)<\/a>/g,"$1{{separator}}$2").forEach(function(b){b=(b||"").split("{{separator}}");addtypelist({tid:"",listflag:"toplist.php?sort="+b[0],title:b[1],img:pluginfo(a.plugin).icon,
group:{name:"paihang",title:"\u6392\u884c\u699c"},content:b[1]})});return!1}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"modules/article/"+a.flag+"?page="+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){b?(ExView.workers.list.countfinder(obj_contact(a,{result:b,header:c})),a.successfn&&a.successfn({result:b,header:c})):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u3010"+a.title+"\u3011<br>\u83b7\u53d6\u5931\u8d25\uff01","ExView"))},showinfo:{text:"\u6b63\u5728\u52a0\u8f7d..."+
(1<a.page?"<br>\u7b2c"+a.page+"\u9875":""),title:a.title,name:"\u3010"+a.title+"\u3011",img:a.img}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u6ca1\u6709\u5185\u5bb9</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{reg:plugfns(a.plugin).pagecountrule,
str:a.result,find:plugfns(a.plugin).pagecountfind,successfn:function(b){mySession.nowlistpages=(b||"0")+"|"+a.keyword+"|list";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},searchflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"modules/article/search.php?searchtype=articlename&searchkey="+ExView.tools.gbk.encode(a.keyword)+"&page="+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){b?(a.multsearch||(ExView.workers.search.countfinder(obj_contact(a,
{result:b,header:c})),setnowlistname("\u641c\u7d22\u3010"+a.keyword+"\u3011")),a.successfn&&a.successfn({result:b,header:c})):a.multsearch?a.multsearch():(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u3010"+a.keyword+"\u3011<br>\u83b7\u53d6\u641c\u7d22\u7ed3\u679c\u5931\u8d25\uff01","ExView"))},showinfo:{text:"\u6b63\u5728\u641c\u7d22..."+(1<a.page?"<br>\u7b2c"+a.page+"\u9875":""),name:"\u3010"+a.keyword+"\u3011",title:"\u641c\u7d22"},autoencode:!1}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,
str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b,c,d){console.log(b);array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.multsearch?a.multsearch():addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u6ca1\u6709\u5185\u5bb9</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{reg:plugfns(a.plugin).pagecountrule,str:a.result,find:plugfns(a.plugin).pagecountfind,successfn:function(b){mySession.nowlistpages=(b||"0")+"|"+a.keyword+
"|search";mySession.nowlistpage=1;console.log(mySession.nowlistpages)}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"novel/"+plugfns(a.plugin).getnid(a.pid)+"/"+a.pid+"/index.htm",method:"GET",timeout:120,successfn:function(b,c){b?a.successfn&&a.successfn({result:b,header:c}):a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u5185\u5bb9\u9875\u83b7\u53d6\u5931\u8d25\uff01","ExView"))},showinfo:{text:"\u6b63\u5728\u52a0\u8f7d\u76ee\u5f55...",
title:"\u5185\u5bb9\u9875",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){var b=[];a.result=getresult(a.result).replace(/<td\s*class="vcss"/g,'<exveiw><td class="vcss"').replace(/<\/table>/g,"<exveiw></table>");var c=getstrs(a.result,/<td\s*class="vcss"(.*?)<exveiw>/g,"$1"),c=c.map(function(a){var c=getstr(/colspan="\d+">((?!>).*?)<\/td>/,a);getstrs(a,/(\d+).htm">((?!>).*?)<\/a>/g,"$1{{separator}}$2").map(function(a){a=(a||"").split("{{separator}}");b.push({group:{name:"type_"+
ExView.tools.md5.hex_md5(c),title:c},item:{cid:a[0],title:a[1]}})})});return{successfn:function(c,e,g,f){console.log(typeof c);if(array_count(c)){if(a.checkupdate)return e=b,c=e[e.length-1],g=(c||{}).group.title,c=(c||{}).item,{pid:a.pid,cid:c.cid,title:g+" "+c.title};e=b;f=[];b.map(function(b,c){var d=b.item;f[c]=additemlist({id:c,newest:a.newest&&0==c,pid:a.pid,cid:d.cid,title:d.title,group:b.group,count:e.length,reverse:0});f[c].title=b.group.title+" "+d.title});return f}a.checkupdate||(ExView.fw.hidePreloader(),
mySession.isloading=0,ExView.fw.alert("\u5185\u5bb9\u9875\u83b7\u53d6\u5931\u8d25\uff01","ExView"))},afterfn:function(){a.checkupdate||ExView.workers.content.infoloader(a)}}},infoloader:function(a){return{url:pluginfo(a.plugin).apihost+"book/"+a.pid+".htm",method:"GET",timeout:120,successfn:function(b,c){b?a.successfn&&a.successfn({result:b,header:c}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u5185\u5bb9\u9875\u83b7\u53d6\u5931\u8d25\uff01","ExView"))},showinfo:{text:"\u6b63\u5728\u52a0\u8f7d\u7b80\u4ecb\u4fe1\u606f...",
title:"\u5185\u5bb9\u9875",name:getlistname(a.pid),img:getlistimg(a.pid)}}},infofinder:function(a){console.log(a);return{reg:/id="content"(.*?)<fieldset/g,str:getresult(a.result),find:"$1",successfn:function(b,c,d,e){console.log(JSON.stringify(b));c=getstr(/<img(?!<).*?src="((?!\").*?)"/,b);d=getstr(/<b>((?!<).*?)<\/b>/,b);e=getstr(/>\u6587\u7ae0\u72b6\u6001\uff1a((?!<).*?)<\/td>/,b).trim();var g=getstr(/>\u5c0f\u8bf4\u4f5c\u8005\uff1a((?!<).*?)<\/td>/,b).trim(),f=getstr(/>\u6587\u5e93\u5206\u7c7b\uff1a((?!<).*?)<\/td>/,
b).trim(),l=gettext(getstr(/>\u6700\u8fd1\u7ae0\u8282\uff1a<\/span>(.*?)<\/span>/,b).trim()),m=getstr(/>\u6700\u540e\u66f4\u65b0\uff1a((?!<).*?)<\/td>/,b).trim(),h=getstr(/>\u5168\u6587\u957f\u5ea6\uff1a((?!<).*?)<\/td>/,b).trim();b=getstr(/class="hottext">\u5185\u5bb9\u7b80\u4ecb\uff1a(.*?)<\/td>/,b).trim();var n=gettag(f);setlistpic({name:d,img:c,added:a.data,description:"<p>\u3010\u4f5c\u8005\u3011"+g+"<br>\u3010\u7c7b\u578b\u3011"+f+"<br>\u3010\u5b57\u6570\u3011"+h+"<br>\u3010"+e+"\u3011"+m+"<br>\u3010\u6700\u65b0\u8bdd\u3011"+
l+"<br>\u3010\u7b80\u4ecb\u3011"+gettext(b)+"</p>",sourceurl:pluginfo(a.plugin).apihost+"book/"+a.pid+".htm",comment:1,preview:0,tags:gettag(d)+gettag(e)+n+gettag(g)});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"novel/"+plugfns(a.plugin).getnid(a.pid)+"/"+a.pid+"/"+a.cid+".htm",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"\u6b63\u5728\u52a0\u8f7d\u6587\u7ae0\u4fe1\u606f...",title:"\u6587\u7ae0",
name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){console.log(a);return{reg:/<div\s*id="content">(.*?)<div\s*id="footlink">/g,str:getresult(a.result),find:"$1",successfn:function(b){b?(b=getarticle(b),console.log(b),a.download?chapterpredownload({type:"text",source:b,download:a.download,plugin:a.plugin}):chapterviewer({source:b,type:"text",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.download?chapterpredownload({error:"\u89e3\u6790\u9519\u8bef\uff01",
download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u6587\u7ae0\u4fe1\u606f\u83b7\u53d6\u5931\u8d25\uff01","ExView"));return!0}}}},commentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"modules/article/reviews.php?aid="+a.pid+"&type=all&page="+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){b?a.callback&&a.callback({result:b,header:c,commentbrowser:{url:pluginfo(a.plugin).apihost+"modules/article/reviews.php?aid="+a.pid+
"&type=all",title:"\u8bc4\u8bba - "+pluginfo(a.plugin).name+'<br><span style="font-size:16px">'+(myContent.name||"")+"</span>",browser:!1,flag:""}}):a.callback&&a.callback()}}},finder:function(a){console.log(a);return{reg:/<td class="odd"><(?!>).*?>((?!<).*?)<.*?class="odd"><(?!>).*?>((?!<).*?)<.*?class="even">((?!<).*?)</g,str:getresult(a.result),find:{time:"$3",name:"$2",text:"$1"},successfn:function(b,c,d,e){array_count(b)&&(c=getstr(/class="last">(\d+)<\/a>/,a.result),a.callback&&a.callback({page:a.page||
1,pagecount:c,comment:{text:b.text,name:b.name,avatar:"",type:"received",label:b.time,day:"",time:"",reverse:1,extra:""}}))}}},send:!1},previewflag:{loader:!1,finder:!1,more:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"modules/article/toplist.php?sort=lastupdate?page="+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:getresult(a.result),
find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));array_count(b)&&plugfns(a.plugin).pagedeal(b,a)}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"modules/article/toplist.php?sort=allvisit?page="+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:getresult(a.result),find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));
array_count(b)&&plugfns(a.plugin).pagedeal(b,a)}}}}},fns:{getnid:function(a){a=(a||"0").toString();return 4>a.length?0:a.substr(0,1)},pagecountrule:/class="last">(\d+)<\/a>/,pagecountfind:"$1",pagerule:/\/book\/(\d+).htm"(.*?)>\u6211\u8981\u9605\u8bfb</g,pagefind:{pid:"$1",content:"$2"},pagedeal:function(a,b){b=b||{};var c=a.pid;a=a.content;var d=getstr(/<img(?!<).*?src="((?!\").*?)"/,a),e=getstr(/title="((?!\").*?)"/,a).trim(),g=getstr(/<p>\u4f5c\u8005:((?!<).*?)\//,a).trim(),f=getstr(/\u5206\u7c7b:((?!<).*?)\//,
a).trim(),l=getstr(/\u72b6\u6001:((?!<).*?)<\/p>/,a).trim(),m=getstr(/<p>\u6700\u540e\u66f4\u65b0:((?!<).*?)[\<,\/]+/,a).trim(),h=getstr(/\u5b57\u6570:(\d+)<\/p>/,a).trim(),n=gettext(getstr(/<p>\u7b80\u4ecb:((?!<).*?)<\/p>/,a).trim()),k=f;if(b.multupdate)return b.multupdate(obj_contact(b,{pid:c,img:d,title:e,content:k})),!1;if(b.multhot)return b.multhot(obj_contact(b,{pid:c,img:d,title:e,content:k})),!1;if(b.multsearch)return b.multsearch(obj_contact(b,{pid:c,img:d,title:e,content:k})),!1;k=n;addcardlist({pid:c,
title:e,name:e,img:d,content:(f?"\u3010\u7c7b\u578b\u3011"+f+"<br>":"")+(g?"\u3010\u4f5c\u8005\u3011"+g+"<br>":"")+(l?"\u3010\u72b6\u6001\u3011"+l+"<br>":"")+(h?"\u3010\u5b57\u6570\u3011"+h+"<br>":"")+(m?"\u3010\u6700\u540e\u66f4\u65b0\u3011"+m+"<br>":"")+(h?"\u3010\u5b57\u6570\u3011"+h+"<br>":"")+(k?"\u3010\u7b80\u4ecb\u3011"+k+"<br>":""),comment:1,preview:0,extrabutton:""})}}});
