ExView.Plugins({info:{name:"妖气漫画",version:"2.2",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAJ5SURBVDhPrZJLSFtBFIar+ETxjSj4QkUSNYmaRBQDKiqo2RZEcSmCEAU3IvjYuTI7lxJw56KVLBoSRXRREGxIcqNNck0116aJ1Rh8pEZsieHvmaC9lq5Ke+BymWHON//553+Ff6z/A5iZmcHs7CyMRiOCgoDQ0hI8MhmcaWlwpqbioKoKn8fH4T84gMlkwsLCAiYmJkSAXq+HRCKBjJpaWlrwPjMTh9nZcOfmwp2XB1dODpy0p1QoIJfLIZVKodPpRIDVaoVGo4FKpYKWAJ6CAnwqLYWvogK+ykqclJXhqLgYI9SsVquhIJDZbBYB8XgcI0ND0JKCd3T4pLwcX+rqcNbYiK+0F6QbT6ursUuw1wTpbmtDNBoVAY+xGExFRXBmZSVuZs0Xzc24am/HdUcHwq2tCZhAXjB1lpQUXNvtIuDu+Bi2pCQc0rwGGuNNby8uBwZw19eHaH8/It3d4AYHsT46CjP54iDA+eqqCLgld+3JyfhAgNOeHnD7+3g7NwdbZydutFqs0393cxOhtTVw+fng0tMRWFkRAd+vruAgBS6SzwwT6EXOSUmkqwvfCHhNBvsbGhI+MDMdpCK8sSECWLnIGM/kJHianR1kM4eUSlyS6xdNTQgQ1FtfD/fUFOyFhfhBl7L6BbixWMAxEw0GHM3PgyfjTmpq4KuthZfgPAWNZyOUlECYnn7qegFgdba4CAelzzU8DGFnB0EyN+D1QtjehmdsDByFiydjHx8enjpeAFgW7u/vwVOMHZQ8jkA2arCRKmdGBuy0dtAr3IbDibPP9QfA7/eD29uDa3kZPM3Lvo+kjNvags/nQyQSQYxy81y/jfD3BfwEx7T2MF5j1s4AAAAASUVORK5CYII=",
db:"yaoqmh",apihost:"http://m.yaoqmh.net/",pagetitle:["<br>","收藏","首页","类型","下载"],download:!0,lazyload:!0,theme:"red",setting:!0,cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){ExView.workers.index.loader()}})},flags:{indexflag:{loader:function(a){a.front||a.page||addtypelist('<div align="center" class="list-block"><img src="img/logo.png"/><br>类型<br>正在加载...<div class="progress"></span></div>',
2);return{url:pluginfo(a.plugin).apihost,method:"GET",timeout:120,successfn:function(b,c){ExView.workers.index.countfinder(obj_contact(a,{result:b,header:c}));a.front||a.page||ExView.workers.type.finder({result:b,plugin:a.plugin});a.successfn&&a.successfn({result:b,header:c})},errorfn:function(){a.front||a.page||addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>加载失败，请刷新重试！</a></div>',
2);mySession.customerror()},canclefn:function(){a.front||a.page||addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>加载失败，请刷新重试！</a></div>',2)},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),name:"首页",title:a.title,img:a.img}}},finder:function(a){return{reg:/<li\s*>\s*<a\s*href="\/((?!\").*?).html"\s*title="((?!\").*?)"\s*target="_blank"><img(?!\").*?rc="((?!\").*?)"/g,
str:a.result,find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));b?(b=b.split("{{separator}}"),plugfns(a.plugin).pagedeal(b,a)):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',2)},errorfn:function(){a.page||setnowlistname("首页","",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("网络错误！","ExView")}}},countloader:function(a){return!1},
countfinder:function(a){return{successfn:function(){mySession.nowlistpages="-1|首页|index";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},typeflag:{loader:function(a){return{successfn:function(){ExView.workers.index.loader()}}},finder:function(a){addtypelist({title:"首页",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"首页"});return{reg:/<li><a\s*href="(?!\").*?\/(\w[-\w.+]*)\/">((?!<).*?)<\/a>\s*<\/li>/g,str:getstr(/<div\s*id="menu">((?:.|[\r\n])*?)<\/div>/,
a.result),find:"$1{{separator}}$2",successfn:function(b){b=(b||"").split("{{separator}}");array_count(b)&&("xieejuntuan"!=b[0]?addtypelist({tid:b[0],title:b[1],img:pluginfo(a.plugin).icon,group:{name:"fenlei",title:"分类"},content:b[1]}):ExView.modules.curl({url:pluginfo(a.plugin).apihost+b[0]+"/",method:"GET",timeout:120,successfn:function(b,d){ExView.modules.rulefind({reg:/<li\s*>\s*<a\s*href="\/(\w[-\w.+]*)\/"\s*target="_blank"\s*title="((?!\").*?)"\s*><img(?!\").*?src="((?!\").*?)"/g,
str:b,find:"$1{{separator}}$2{{separator}}$3",successfn:function(b){b=(b||"").split("{{separator}}");array_count(b)&&addtypelist({tid:b[0],title:b[1],img:getcoverload((b[2]||"").replace("http://www.yaoqi.cc/",pluginfo(a.plugin).apihost),{cacheheader:{Referer:pluginfo(a.plugin).apihost},loadingimg:mySession.blankimg}),group:{name:"xieejuntuan",title:"漫画大全",fontsize:"16px"},content:b[1],listbg:!0})}})},showinfo:""}))}}}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
a.keyword+"/"+(1<a.page?"list_"+mySession.extralistpage+"_"+a.page+".html":""),method:"GET",timeout:120,successfn:function(b,c){b?(ExView.workers.list.countfinder(obj_contact(a,{result:b,header:c})),a.successfn&&a.successfn({result:b,header:c})):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+a.title+"】<br>获取失败！","ExView"))},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),name:"【"+a.title+"】",
title:a.title,img:a.img}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:a.result,find:plugfns(a.plugin).pagefind,successfn:function(b){b?(b=b.split("{{separator}}"),plugfns(a.plugin).pagedeal(b)):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{reg:/<a\s*href='list_(\d+)_(\d+).html'>末页<\/a>/g,str:a.result,find:"$1{{separator}}$2",successfn:function(b){b=
(b||"").split("{{separator}}");mySession.nowlistpages=(b[1]||"-1")+"|"+a.keyword+"|list";mySession.nowlistpage=1;mySession.extralistpage=b[0];console.log(mySession.nowlistpages);return!0}}}},searchflag:{loader:function(a){return{url:"http://zhannei.baidu.com/cse/search?q="+encodeURIComponent(a.keyword)+"&p="+(a.page||1)+"&s=2618091304794420160&entry=1",method:"GET",timeout:120,successfn:function(b,c){b?(a.multsearch||(ExView.workers.search.countfinder(obj_contact(a,{result:b,header:c})),setnowlistname("搜索【"+
a.keyword+"】")),a.successfn&&a.successfn({result:b,header:c})):a.multsearch?a.multsearch():(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+a.keyword+"】<br>获取搜索结果失败！","ExView"))},showinfo:{text:"正在搜索..."+(1<a.page?"<br>第"+a.page+"页":""),name:"【"+a.keyword+"】",title:"搜索"}}},finder:function(a){var b=/<a\s*class="result"\s*href="\s*(?!\").*?\/(\w[-\w.+]*)\/(\d+)\.html\n*\s*"\s*target="_self">\s*\r*\n*\r*\s*<div\s*class="result-title">(.*?)_妖气漫画网<\/div>/g;
-1!=window.navigator.userAgent.toLowerCase().indexOf("windows")&&(b=/<a\s*rpos=""\s*cpos="title"\s*href="(?!\").*?\/(\w[-\w.+]*)\/(\d+)\.html"\s*target="_blank">(.*?)_妖气漫画网<\/a>/g);return{reg:b,str:a.result,find:"$1{{separator}}$2{{separator}}$3",successfn:function(b,d,e){b?(b=b.split("{{separator}}"),b=[b[0]+"_"+b[1],b[2],"img/nopic.png"],console.log(b),plugfns(a.plugin).pagedeal(b,a)):a.multsearch?a.multsearch():addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',
1)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(b){mySession.nowlistpages="0|"+a.keyword+"|search";mySession.nowlistpage=1;console.log(mySession.nowlistpages)}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+a.pid.replace(/_/g,"/")+".html",method:"GET",timeout:120,successfn:function(b,c){b?a.successfn&&a.successfn({result:b,header:c}):a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！",
"ExView"))},showinfo:{text:"正在加载内容页...",title:"内容页",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){return{successfn:function(b,c,d,e){console.log(typeof b);if(array_count(b)){c=1;if(a.checkupdate)return{pid:a.pid,cid:c,title:"全"+c+"话"};e=[];for(d=0;d<c;d++)e[d]=additemlist({id:d,newest:a.newest&&0==d,pid:a.pid,cid:d+1,title:"全"+(d+1)+"话",count:c,reverse:1});return e}a.checkupdate||(ExView.fw.hidePreloader(),
mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},afterfn:function(){a.checkupdate||ExView.workers.content.infofinder(a)}}},infoloader:function(a){return!1},infofinder:function(a){console.log(a);return{successfn:function(b,c,d,e){b=getstr(/<h1\s*class="ptitle\s*fc1"><strong>(.*?)<\/strong><\/h1>/g,a.result);setlistpic({name:b,added:a.data,description:"",comment:0,preview:0,tags:gettag(b)});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
a.pid.replace(/_/g,"/")+".html",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"正在加载图片信息...",title:"图片",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){console.log(a);return{reg:/<a>共(\d+)页:\s*<\/a>/g,str:a.result,find:"$1",successfn:function(b){var c=[];if(b){b=b.split("{{separator}}");b=b[0];for(var d=0;d<b;d++)c[d]=getpageload(pluginfo(a.plugin).apihost+
a.pid.replace(/_/g,"/")+(0<d?"_"+(d+1):"")+".html",a.plugin)}else b=1,getquery(a.result,"#imgString img").each(function(){c.push(getimgload(this.src,a.plugin))});array_count(c)?(console.log(c),a.download?chapterpredownload({source:c,download:a.download,plugin:a.plugin}):chapterviewer({source:c,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.download?chapterpredownload({error:"解析错误！",download:a.download,plugin:a.plugin}):
(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("图片信息获取失败！","ExView"));return!0}}}},commentflag:{loader:!1,finder:!1},previewflag:{loader:!1,finder:!1,more:!1},pageimgflag:{parser:function(a){return{reg:/<img\s*alt="(?!<).*?"\s*src="((?!<).*?)"\s*\/>/g,str:a.result,find:"$1",successfn:function(b){a.loadimgurl(getimgload(b,a.plugin,{cacheheader:{Referer:pluginfo(a.plugin).apihost}}))}}}},updateflag:{loader:function(a){return 1<a.page?(a.multupdate(),
!1):{url:pluginfo(a.plugin).apihost,method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{reg:/<li\s*>\s*<a\s*href="\/((?!\").*?).html"\s*title="((?!\").*?)"\s*target="_blank"><img(?!\").*?rc="((?!\").*?)"/g,str:a.result,find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));b&&(b=b.split("{{separator}}"),plugfns(a.plugin).pagedeal(b,a))}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"shaonvmanhua/"+(1<a.page?"list_4_"+a.page+".html":""),method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{reg:plugfns(a.plugin).pagerule,str:a.result,find:plugfns(a.plugin).pagefind,successfn:function(b){console.log(JSON.stringify(b));b&&(b=b.split("{{separator}}"),plugfns(a.plugin).pagedeal(b,a))}}}}},fns:{pagerule:/<li\s*>\s*<a\s*href="\/((?!\").*?).html"\s*title="((?!\").*?)"\s*target="_blank"><img(?!\").*?xSrc="((?!\").*?)"/g,
pagefind:"$1{{separator}}$2{{separator}}$3",pagedeal:function(a,b){b=b||{};var c=a[0].replace(/\//g,"_"),d=a[1],e=getcoverload(a[2],{cacheheader:{Referer:pluginfo(b.plugin).apihost},loadingimg:"img/loading.png"});if(b.multupdate)return b.multupdate(obj_contact(b,{pid:c,img:e,title:d,content:""})),!1;if(b.multhot)return b.multhot(obj_contact(b,{pid:c,img:e,title:d,content:""})),!1;if(b.multsearch)return b.multsearch(obj_contact(b,{pid:c,img:e,title:d,content:""})),!1;addcardlist({pid:c,title:d,img:e,
content:"",comment:0,preview:0,extrabutton:""})}}});
