ExView.Plugins({info:{name:"迷糊轻小说",version:"2.2",icon:"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wgARCAAQABADAREAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABwUG/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgH/2gAMAwEAAhADEAAAAMIknEnzdiT/xAAlEAAABgIBAgcAAAAAAAAAAAABAgMEBREABgcSMhMhI0FCgpH/2gAIAQEAAT8A0+OGAkWEqs0JKR75Dwlk6AegT0IFoBEbyW1ltB6zs8m1h1UGshEqDR+8ilCAWACNUXNWIhCRTZeTkSC1cgX0LL2m9vP9q85C5MWda6ME1dJOkFydCinz+2f/xAAUEQEAAAAAAAAAAAAAAAAAAAAg/9oACAECAQE/AB//xAAUEQEAAAAAAAAAAAAAAAAAAAAg/9oACAEDAQE/AB//2Q==",
author:"Gentle",type:"text",db:"yidm",apihost:"http://www.yidm.com/",pagetitle:["<br>","收藏","首页","类型","下载"],lazyload:!0,download:!0,setting:!0,typelistmode:!0,smallpicmode:!0,requestcookie:"",cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){ExView.workers.index.loader();ExView.workers.type.loader()}})},flags:{indexflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"api/app/getarticles.php?begin="+
(a.page||1)+"&get=20&type=hot",method:"GET",timeout:120,successfn:function(b,c){ExView.workers.index.countfinder(obj_contact(a,{result:b,header:c}));a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),name:"首页",title:a.title,img:a.img}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){console.log(JSON.stringify(b));array_count(b)?plugfns(a.plugin).pagedeal(b):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',
2)},errorfn:function(){a.page||setnowlistname("首页","",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("网络错误！","ExView")}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="0|首页|index";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},typeflag:{loader:function(a){return{successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},
finder:function(a){addtypelist({title:"首页",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"首页"});addtypelist({tid:"top",title:"热门",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"热门"});addtypelist({tid:"score",title:"排行",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"导航"},content:"排行"});return{successfn:function(b){var c=plugfns(a.plugin).typelist,d;for(d in c)b=
c[d],addtypelist({tid:d,title:b.title,img:pluginfo(a.plugin).icon,group:{name:"fenlei",title:"分类"},content:b.title})}}}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"api/app/getarticles.php?begin=1&get=20&type="+a.keyword,method:"GET",timeout:120,successfn:function(b,c){b?(ExView.workers.list.countfinder(obj_contact(a,{result:b,header:c})),a.successfn&&a.successfn({result:b,header:c})):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+a.title+
"】<br>获取失败！","ExView"))},showinfo:{text:"正在加载..."+(1<a.page?"<br>第"+a.page+"页":""),title:a.title,name:"【"+a.title+"】",img:a.img}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){array_count(b)?plugfns(a.plugin).pagedeal(b):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(b){mySession.nowlistpages=
"0|"+a.keyword+"|list";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},searchflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"api/app/search.php?searchkey="+encodeURIComponent(a.keyword)+"&page="+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){b?(a.multsearch||(ExView.workers.search.countfinder(obj_contact(a,{result:b,header:c})),setnowlistname("搜索【"+a.keyword+"】")),a.successfn&&a.successfn({result:b,header:c})):a.multsearch?
a.multsearch():(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("【"+a.keyword+"】<br>获取搜索结果失败！","ExView"))},showinfo:{text:"正在搜索..."+(1<a.page?"<br>第"+a.page+"页":""),name:"【"+a.keyword+"】",title:"搜索"}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b,c,d){console.log(b);b=(b||{}).results;array_count(b)?b.forEach(function(b){plugfns(a.plugin).pagedeal(b,a)}):a.multsearch?
a.multsearch():addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(b){mySession.nowlistpages="0|"+a.keyword+"|search";mySession.nowlistpage=1;console.log(mySession.nowlistpages)}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"api/app/getarticleinfo.php?id="+a.pid,method:"GET",timeout:120,successfn:function(b,c){b?a.successfn&&
a.successfn({result:b,header:c}):a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！","ExView"))},showinfo:{text:"正在加载简介信息...",title:"内容页",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b,c,d,e){b=(b||{}).info;if(array_count(b)){b=b.volumes;if(a.checkupdate)return d=b[b.length-1].volume,c=b[b.length-
1].chapters,b=c[c.length-1],{pid:a.pid,cid:b.cid,title:d+" "+b.chapter};c=[];b.forEach(function(a){a.chapters.forEach(function(b){c.push({cid:b.cid,title:b.chapter,group:{name:"type_"+a.vid,title:a.volume}})})});e=[];c.map(function(b,d){e[d]=additemlist({id:d,newest:a.newest&&0==d,pid:a.pid,cid:b.cid,title:b.title,group:b.group,count:c.length,reverse:0});e[d].title=b.group.title+" "+b.title});return e}a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("内容页获取失败！",
"ExView"))},afterfn:function(){a.checkupdate||ExView.workers.content.infofinder(a)}}},infoloader:function(a){return!1},infofinder:function(a){console.log(a);return{json:!0,str:a.result,successfn:function(b,c,d,e){b=(b||{}).info;console.log(JSON.stringify(b));c="http://img.yidm.com/article/image/"+plugfns(a.plugin).getnid(b.articleid)+"/"+b.articleid+"/"+b.articleid+"s.jpg";d=b.articlename;e=b.author;var f=plugfns(a.plugin).typelist[b.sortid].title,g=b.lastupdate,h=b.score;b=b.intro;var k=gettag(f);
setlistpic({name:d,img:c,added:a.data,description:"<p>【作者】"+e+"<br>【类型】"+f+"<br>【分数】"+h+"<br>【更新】"+g+"<br>【简介】"+gettext(b)+"</p>",sourceurl:pluginfo(a.plugin).apihost+"article/info/"+plugfns(a.plugin).getnid(a.pid)+"/"+a.pid+".html",comment:1,preview:0,tags:gettag(d)+k+gettag(e)});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"article/html/"+plugfns(a.plugin).getnid(a.pid)+
"/"+a.pid+"/"+a.cid+".html",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"正在加载文章信息...",title:"文章",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){console.log(a);return{reg:/<div\s*class="bd">(.*?)<div\s*class="mod_toolbar/g,str:getresult(a.result),find:"$1",successfn:function(b){b?(b=getarticle(b,!1,/osrc="(.*?)"/),console.log(b),a.download?chapterpredownload({type:"text",
source:b,download:a.download,plugin:a.plugin}):chapterviewer({source:b,type:"text",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title},"online")):a.download?chapterpredownload({error:"解析错误！",download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("文章信息获取失败！","ExView"));return!0}}}},commentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+
"api/article/getReviews.php",method:"POST",data:"aid="+a.pid+"&page="+(a.page||1)+"&pageSize=10",postform:!0,timeout:120,successfn:function(b,c){b?a.callback&&a.callback({result:b,header:c,commentbrowser:{url:pluginfo(a.plugin).apihost+"article/info/"+plugfns(a.plugin).getnid(a.pid)+"/"+a.pid+".html",title:"评论 - "+pluginfo(a.plugin).name+'<br><span style="font-size:16px">'+(myContent.name||"")+"</span>",browser:!1,flag:""}}):a.callback&&a.callback()}}},finder:function(a){console.log(a);
return{json:!0,str:a.result,successfn:function(b,c,d,e){if(array_count(b)){c=Math.ceil(parseInt(b.total)/10);b=b.data;for(var f in b)a.callback&&a.callback({page:a.page||1,pagecount:c,comment:{text:b[f].posttext,name:b[f].poster,avatar:"",type:"received",label:b[f].posttime,day:"",time:"",reverse:1,extra:""}})}}}},send:!1},previewflag:{loader:!1,finder:!1,more:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"api/app/getarticles.php?begin="+(a.page||
1)+"&get=20&type=hot",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){console.log(JSON.stringify(b));array_count(b)&&plugfns(a.plugin).pagedeal(b,a)}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"api/app/getarticles.php?begin="+(a.page||1)+"&get=20&type=top",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{json:!0,
str:a.result,successfn:function(b){console.log(JSON.stringify(b));array_count(b)&&plugfns(a.plugin).pagedeal(b,a)}}}}},fns:{getnid:function(a){a=(a||"0").toString();return 4>a.length?0:a.substr(0,1)},typelist:{1:{tid:"1",title:"其他文库"},2:{tid:"2",title:"电击文库"},3:{tid:"3",title:"富士见书房"},4:{tid:"4",title:"角川文库"},5:{tid:"5",title:"MF文库J"},6:{tid:"6",title:"Fami通文库"},7:{tid:"7",title:"HJ文库"},
8:{tid:"8",title:"SuperDash文库"},10:{tid:"10",title:"GA文库"},12:{tid:"12",title:"讲谈社"},15:{tid:"15",title:"一迅社文库"},16:{tid:"16",title:"Gagaga文库"}},pagecountrule:/class="last">(\d+)<\/a>/,pagecountfind:"$1",pagerule:/\/book\/(\d+).htm"(.*?)>我要阅读</g,pagefind:{pid:"$1",content:"$2"},pagedeal:function(a,b){b=b||{};var c=a.articleid,d="http://img.yidm.com/article/image/"+plugfns(b.plugin).getnid(a.articleid)+"/"+a.articleid+
"/"+a.articleid+"s.jpg",e=a.articlename,f=a.author,g=plugfns(b.plugin).typelist[a.sortid].title,h=a.weekvisit,k=a.lastupdate,l=a.score,m=a.allvisit;if(b.multupdate)return b.multupdate(obj_contact(b,{pid:c,img:d,title:e,content:g})),!1;if(b.multhot)return b.multhot(obj_contact(b,{pid:c,img:d,title:e,content:g})),!1;if(b.multsearch)return b.multsearch(obj_contact(b,{pid:c,img:d,title:e,content:g})),!1;addcardlist({pid:c,title:e,img:d,content:(f?"【作者】"+f+"<br>":"")+(g?"【类别】"+
g+"<br>":"")+(m?"【点击量】"+m:"")+(h?"【一周浏览量】"+h:"")+(l?"【评分】"+l:""),stitle:k,comment:1})}}});
