ExView.Plugins({info:{name:"\u6709\u8da3\u5c9b\u6f2b\u753b",version:"2.2",db:"youqudao",icon:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAMFBMVEUmxPsAltgVi9knuvUZk+AAvP0enuscmeYBjtMosfB93/4ore0ipfERg9EAf8H////7H/3yAAAAAWJLR0QAiAUdSAAAAAlwSFlzAAAOxAAADsQBlSsOGwAAAHdJREFUCJljWHMGAhiyVoHBGoYDoXJy7x6G8jAkyL1///9fKBtDwvv//9+/e8gGEfn/j52hACTyD8goBqv5Z85QDKTfv39owuD8HsSCMEBqTBiU3/9/9/7dCyMGzffv/gO1T2LQ7ut49+7di0kMt3eDwV6Gu1AAANz3XG1lICT3AAAAAElFTkSuQmCC",apihost:"http://yqd.mobi/",
pagetitle:["<br>","\u6536\u85cf","\u6bcf\u5468\u63a8\u8350","\u7c7b\u578b","\u4e0b\u8f7d"],download:!0,lazyload:!0,setting:!0,cdn:""},set:function(a){},unset:function(a){},init:function(){ExView.workers.fav.listloader({callback:function(){ExView.workers.index.loader();ExView.workers.type.loader()}})},flags:{indexflag:{loader:function(a){a.front||a.page||setnowlistname("\u6bcf\u5468\u63a8\u8350","",pluginfo(a.plugin).icon);return{url:pluginfo(a.plugin).apihost+"web/reconmend",method:"GET",timeout:120,
successfn:function(b,c){ExView.workers.index.countfinder(obj_contact(a,{result:b,header:c}));a.successfn&&a.successfn({result:b,header:c})},errorfn:function(){a.page||setnowlistname("\u6bcf\u5468\u63a8\u8350","",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("\u7f51\u7edc\u9519\u8bef\uff01","ExView")},canclefn:function(){a.page||setnowlistname("\u6bcf\u5468\u63a8\u8350","",pluginfo(a.plugin).icon)},showinfo:{text:"\u6b63\u5728\u52a0\u8f7d..."+(1<a.page?"<br>\u7b2c"+
a.page+"\u9875":""),name:"\u6bcf\u5468\u63a8\u8350",title:a.title,img:a.img}}},finder:function(a){return{reg:/<li>\s*\r*\n*\r*\s*<a\s*href=".*?albumId=(.*?)"><img\s*src="(.*?)".*?\/><\/a>\s*\r*\n*\r*\s*<p><a\s*href="">(.*?)<\/a><\/p>/g,str:a.result,find:"$1{{separator}}$2{{separator}}$3",successfn:function(a){console.log(JSON.stringify(a));a=(a||"").split("{{separator}}");array_count(a)?addcardlist({pid:a[0],title:a[2],img:a[1],comment:1}):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u6ca1\u6709\u5185\u5bb9</div>',
2)},errorfn:function(){a.page||setnowlistname("\u6bcf\u5468\u63a8\u8350","",pluginfo(a.plugin).icon);ExView.fw.hidePreloader();mySession.isloading=0;ExView.fw.alert("\u7f51\u7edc\u9519\u8bef\uff01","ExView")}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="-1|\u6bcf\u5468\u63a8\u8350|index";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},typeflag:{loader:function(a){addtypelist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u6b63\u5728\u52a0\u8f7d\u7c7b\u578b...<div class="progress"></span></div>',
2);return{url:pluginfo(a.plugin).apihost+"web/category",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){addtypelist({title:"\u6bcf\u5468\u63a8\u8350",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u6bcf\u5468\u63a8\u8350"});addtypelist({tid:"zuixin",listflag:"jslast",title:"\u6700\u65b0",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u6700\u65b0"});addtypelist({tid:"remen",
listflag:"jshot",title:"\u70ed\u95e8",img:pluginfo(a.plugin).icon,group:{name:"daohang",title:"\u5bfc\u822a"},content:"\u70ed\u95e8"});return{reg:/<li.*?>\s*\r*\n*\r*\s*<a\s*href=".*?"><img\s*src="(.*?)"\s*width="100%"\s*alt=""\/><\/a>\s*\r*\n*\r*\s*<div\s*class="category"><a\s*href=".*?categoryId=(\d+)&page=1">(.*?)<\/a>/g,str:a.result,find:"$1{{separator}}$2{{separator}}$3",successfn:function(a){a=a.split("{{separator}}");if(array_count(a)){var c=a[2];addtypelist({tid:a[1],title:c,img:a[0],group:{name:"fenlei",
title:"\u5206\u7c7b"},content:c})}else addtypelist('<div align="center" class="list-block"><a href="javascript:void(0);" onclick="ExView.workers.type.loader();"><img src="img/logo.png"/><br>\u52a0\u8f7d\u5931\u8d25\uff0c\u8bf7\u5237\u65b0\u91cd\u8bd5\uff01</a></div>',2)}}}},listflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"web/list/"+(a.flag||"jssearch")+"?page="+(a.page||1)+"&categoryId="+a.keyword,method:"GET",timeout:120,successfn:function(b,c){b?(ExView.workers.list.countfinder(obj_contact(a,
{result:b,header:c})),a.successfn&&a.successfn({result:b,header:c})):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u3010"+a.title+"\u3011<br>\u83b7\u53d6\u5931\u8d25\uff01","ExView"))},showinfo:{text:"\u6b63\u5728\u52a0\u8f7d..."+(1<a.page?"<br>\u7b2c"+a.page+"\u9875":""),name:"\u3010"+a.title+"\u3011",title:a.title,img:a.img}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){(b=b.data)?plugfns(a.plugin).pagedeal(b):addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u6ca1\u6709\u5185\u5bb9</div>',
1)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(){mySession.nowlistpages="0|"+a.keyword+"|list";mySession.nowlistpage=1;console.log(mySession.nowlistpages);return!0}}}},searchflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"web/list/jssearch?page="+(a.page||1)+"&keyWord="+encodeURIComponent(a.keyword)+"&categoryId=0",method:"GET",timeout:120,successfn:function(b,c){b?(a.multsearch||(ExView.workers.search.countfinder(obj_contact(a,{result:b,
header:c})),setnowlistname("\u641c\u7d22\u3010"+a.keyword+"\u3011")),a.successfn&&a.successfn({result:b,header:c})):a.multsearch?a.multsearch():(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u3010"+a.keyword+"\u3011<br>\u83b7\u53d6\u641c\u7d22\u7ed3\u679c\u5931\u8d25\uff01","ExView"))},showinfo:{text:"\u6b63\u5728\u641c\u7d22..."+(1<a.page?"<br>\u7b2c"+a.page+"\u9875":""),name:"\u3010"+a.keyword+"\u3011",title:"\u641c\u7d22"}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b,
c,e){b=b.data;console.log(b);array_count(b)?plugfns(a.plugin).pagedeal(b,a):a.multsearch?a.multsearch():addcardlist('<div align="center" class="list-block"><img src="img/logo.png"/><br>\u6ca1\u6709\u5185\u5bb9</div>',1)}}},countloader:function(a){return!1},countfinder:function(a){return{successfn:function(b){mySession.nowlistpages="0|"+a.keyword+"|search";mySession.nowlistpage=1;console.log(mySession.nowlistpages)}}}},contentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"web/album/detail?albumId="+
a.pid,method:"GET",timeout:120,successfn:function(b,c){b?a.successfn&&a.successfn({result:b,header:c}):a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u5185\u5bb9\u9875\u83b7\u53d6\u5931\u8d25\uff01","ExView"))},showinfo:{text:"\u6b63\u5728\u52a0\u8f7d\u5185\u5bb9\u9875...",title:"\u5185\u5bb9\u9875",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){return{reg:/<li.*?><a\s*href=".*?workId=(\d+)&albumName=(.*?)"><span>(\d+)<\/span><\/a><\/li>/g,str:a.result,
find:{pid:a.pid,cid:"$1",title:"\u7b2c$3\u8bdd"},successfn:function(b,c,e,d){if(array_count(b)){if(a.checkupdate)return b=d[d.length-1],{pid:b.pid,cid:b.cid,title:b.title};additemlist({id:e,newest:a.newest&&0==e,pid:b.pid,cid:b.cid,title:b.title,count:c.length,reverse:0})}else a.checkupdate||(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u5185\u5bb9\u9875\u83b7\u53d6\u5931\u8d25\uff01","ExView"))},afterfn:function(){a.checkupdate||ExView.workers.content.infofinder(a)}}},infoloader:function(a){return!1},
infofinder:function(a){console.log(a);return{reg:/<section\s*class="mh_d">\s*\r*\n*\r*\s*<p\s*class="hot_box"><img\s*src="(.*?)".*?\/><\/p>\s*\r*\n*\r*\s*<article\s*class="hot_box1">\s*\r*\n*\r*\s*<header>\s*\r*\n*\r*\s*<div>\s*\r*\n*\r*\s*<p\s*class="tx">\u63d0\u4f9b\u5546\uff1a(.*?)<\/p>\s*\r*\n*\r*\s*<p\s*class="tx">\u4f5c\u8005\uff1a(.*?)<\/p>\s*\r*\n*\r*\s*<p\s*class="fl">.*?>(\d+)<\/span><\/p>\s*\r*\n*\r*\s*<\/div>\s*\r*\n*\r*\s*<\/header>\s*\r*\n*\r*\s*<\/article>\s*\r*\n*\r*\s*<\/section>\s*\r*\n*\r*\s*<p\s*class="mh_d1">((?:.|[\r\n])*?)<\/p>/g,
str:a.result,find:"$1{{separator}}$2{{separator}}$3{{separator}}$4{{separator}}$5",successfn:function(b,c,e,d){b=(b||"").split("{{separator}}");c=b[0];e=b[2];d=b[3];b=b[4];var f=getstr(/<title>(.*?)<\/title>/,a.result),g=e?e.split("/"):[],g=g.map(function(a){return gettag(a)});setlistpic({name:f,img:c,added:a.data,description:"<p>\u3010\u4f5c\u8005\u3011"+e+"<br>\u3010\u70ed\u5ea6\u3011"+d+"<br>\u3010\u7b80\u4ecb\u3011"+b+"</p>",comment:1,preview:0,tags:gettag(f)+g.join(""),sourceurl:pluginfo(a.plugin).apihost+
"web/album/detail?albumId="+a.pid});return!0}}}},parseflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"web/album/work?workId="+a.cid,method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})},showinfo:{text:"\u6b63\u5728\u52a0\u8f7d\u56fe\u7247\u4fe1\u606f...",title:"\u56fe\u7247",name:getlistname(a.pid),img:getlistimg(a.pid)}}},finder:function(a){console.log(a);return{reg:/<div\s*id="img\d".*?><img\s*src="(.*?)".*?\/><\/div>/g,str:a.result,find:"$1",
successfn:function(b,c,e,d){array_count(d)?(console.log(d),a.download?chapterpredownload({source:d,download:a.download,plugin:a.plugin}):chapterviewer({source:d,type:"image",startindex:a.startindex||0,lazyload:pluginfo(a.plugin).lazyload,zoom:!0,title:a.title})):a.download?chapterpredownload({error:"\u89e3\u6790\u9519\u8bef\uff01",download:a.download,plugin:a.plugin}):(ExView.fw.hidePreloader(),mySession.isloading=0,ExView.fw.alert("\u56fe\u7247\u4fe1\u606f\u83b7\u53d6\u5931\u8d25\uff01","ExView"));
return!0}}}},commentflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"web/album/comment?albumId="+a.pid+"&page="+(a.page||1),method:"GET",timeout:120,successfn:function(b,c){b?a.callback&&a.callback({result:b,header:c,commentbrowser:{url:"http://www.youqudao.com/comic/"+a.pid+".htm",title:"\u8bc4\u8bba - "+pluginfo(a.plugin).name+'<br><span style="font-size:16px">'+(myContent.name||"")+"</span>",browser:!1,flag:""}}):a.callback&&a.callback()}}},finder:function(a){console.log(a);return{reg:/<p\s*class="fl"><img\s*src="(.*?)".*?\/><\/p>\s*\r*\n*\r*\s*<div>\s*\r*\n*\r*\s*<p\s*class="tl\s*fl">(.*?)<\/p>\s*\r*\n*\r*\s*<p\s*class="tl1\s*fr">(.*?)<\/p>\s*\r*\n*\r*\s*<\/div>\s*\r*\n*\r*\s*<h1>(.*?)<\/h1>/g,
str:a.result,find:{text:"$4",name:"$2",avatar:"$1",time:"$3"},successfn:function(b,c,e,d){array_count(b)?a.callback&&a.callback({page:a.page||1,pagecount:0,comment:{text:b.text,name:b.name,avatar:b.avatar,type:"received",label:b.time,day:"",time:"",reverse:1,extra:""}}):a.callback&&a.callback({page:a.page||1,pagecount:-1})}}},send:!1},previewflag:{loader:!1,finder:!1,more:!1},pageimgflag:{parser:!1},updateflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"web/list/jslast?page="+(a.page||
1)+"&categoryId=zuixin",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{json:!0,str:a.result,successfn:function(b){b=b.data;console.log(JSON.stringify(b));b&&plugfns(a.plugin).pagedeal(b,a)}}}},hotflag:{loader:function(a){return{url:pluginfo(a.plugin).apihost+"web/list/jshot?page="+(a.page||1)+"&categoryId=remen",method:"GET",timeout:120,successfn:function(b,c){a.successfn&&a.successfn({result:b,header:c})}}},finder:function(a){return{json:!0,
str:a.result,successfn:function(b){b=b.data;console.log(JSON.stringify(b));b&&plugfns(a.plugin).pagedeal(b,a)}}}}},fns:{pagedeal:function(a,b){b=b||{};a.forEach(function(a){var e=a.albumId,d=a.coverPic,f=a.name,g=a.author,h=a.label,k=a.descriptions;a=(new Date(parseInt(a.updateTime))).toLocaleString().replace(/:\d{1,2}$/," ");if(b.multupdate)return b.multupdate(obj_contact(b,{pid:e,img:d,title:f,content:a})),!1;if(b.multhot)return b.multhot(obj_contact(b,{pid:e,img:d,title:f,content:a})),!1;if(b.multsearch)return b.multsearch(obj_contact(b,
{pid:e,img:d,title:f,content:a})),!1;addcardlist({pid:e,title:f,name:"\u3010"+g+"\u3011"+f,img:d,stitle:a,content:"\u3010"+h+"\u3011"+k,comment:1})})}}});
