ExView.Plugins({info:{name:"轻应用",version:"2.3",icon:getbaiduimg("20c8e3ef76094b36c7a8e53ba4cc7cd98c109d97"),db:"WebApp",type:"feature",fn:"ExView.modules.webapppage.init();"},set:function(){ExView.modules.webapppage={load:function(a){ExView.tools.file.mkdir("ExView/WebApp",function(){ExView.tools.file.scandir("ExView/WebApp",function(d){for(var b=[],e=0;e<d.length;e++){var c=d[e],f=c.toURL()||c.fullPath;c.isFile&&-1!=f.split(".")[f.split(".").length-1].indexOf("ewp")&&(c=f.split("/")[f.split("/").length-
1],b.push(c.substring(0,c.lastIndexOf("."))))}if(!b.length)return $$("#webappviewpage").html('<div align="center" class="list-block"><img src="img/logo.png"/><br>没有内容</div>'),a&&a(),!1;$$("#webappviewpage").html('<div class="list-block" style="margin-top:0px"><ul></ul></div>');for(var g in b)(function(a,e){ExView.tools.file.getfile("ExView/WebApp/"+decodeURIComponent(a)+".ewp",null,function(a){a=JSON.parse(a);a.sicon=a.icon;a.icon=getcoverload(a.icon,{loadingimg:"img/logo.png",
errorimg:"img/logo.png"});$$("#webappviewpage").find("ul").append('<li class="swipeout"><a href="javascript:void(0);" data-name="'+a.name+'" data-url="'+a.url+'" data-icon="'+a.sicon+'" data-css="'+a.css+'" data-js="'+a.js+'" data-ua="'+(a.ua||"")+'" data-showtitlebar="'+(a.showtitlebar||"")+'" class="item-link webappopenbutton"><div class="item-content swipeout-content"><div class="item-media"><img onerror="imgerror(this,\'img/logo.png\');" lowsrc="img/logo.png" src="'+a.icon+'" data-error="0" data-src="'+
a.icon+'"></div><div class="item-inner"><div class="item-title">'+a.name+'</div><div class="item-after"></div></div></div></a><div class="swipeout-actions-right"><a href="javascript:void(0);" class="bg-blue webappeditbutton">编辑</a><a href="javascript:void(0);" class="bg-red webappdeletebutton">删除</a></div></li>')})})(b[g],a);setTimeout(function(){a&&a()},100)})})},callback:function(){$$(".addwebappbutton").on("click",function(){ExView.fw.swipeoutClose(".swipeout-opened");ExView.modules.webapppage.edit()});
$$(".webappdeletebutton").on("click",function(){ExView.fw.swipeoutClose(".swipeout-opened");var a=$$(this).parents("li").find(".item-title").html();ExView.fw.confirm("是否要删除？<br>"+a,function(){ExView.tools.file.rmfile("ExView/WebApp/"+a+".ewp",function(){ExView.fw.alert(a+"<br>删除成功！","ExView");ExView.modules.webapppage.load(ExView.modules.webapppage.callback)},function(){ExView.fw.alert(a+"<br>删除失败！","ExView");ExView.modules.webapppage.load(ExView.modules.webapppage.callback)});
ExView.fw.swipeoutClose(".swipeout-opened")})})},edit:function(a){var d=a?"配置"+getnavundertitle(a.name):"添加轻应用",b='<div class="list-block" style="margin-top:0px"><form id="webapp-form"><ul>'+getinput("name","名称")+getinput("url","网址(http://xxx.xxx.xxx/xxx)")+getinput("icon","图标(http://xxx.xxx.xxx/favicon.ico)")+getinput("ua","设置UA")+gettextarea("css","插入CSS","height:100px")+gettextarea("js","插入JS","height:100px")+
getcheckbox("showtitlebar","显示标题栏")+'<li class="align-top"><div class="item-content"><div class="item-inner"><div class="item-title floating-label">插入CSS说明</div><pre style="overflow:auto">'+ExView.tools.base64.decode("LyoqKioqKkNTU+aPkuWFpeaooeW8jyoqKioqKi8NCi8v566A5Y2V5qih5byPICDnm7TmjqXmj5LlhaXku6PnoIENCi8v5paH5Lu25qih5byPICB7ImZpbGUiOiJodHRwOi8veHh4Lnh4eC54eHgveHh4LmNzcyJ9DQovL+agh+WHhuaooeW8jyAge2NvZGU6Iip7dGV4dDpjZW50ZXJ9In0NCi8qKioqKipDU1Pmj5LlhaXmqKHlvI8qKioqKiov")+
'</pre></div></div></li><li class="align-top"><div class="item-content"><div class="item-inner"><div class="item-title floating-label">插入JS说明</div><pre style="overflow:auto">'+ExView.tools.base64.decode("LyoqKioqKkpT5o+S5YWl5qih5byPKioqKioqLw0KLy/pq5jnuqfmqKHlvI8gIG15V2ViQXBwPXt9DQovL+eugOWNleaooeW8jyAg55u05o6l5o+S5YWl5Luj56CBDQovL+aWh+S7tuaooeW8jyAgeyJmaWxlIjoiaHR0cDovL3h4eC54eHgueHh4L3h4eC5qcyJ9DQovL+agh+WHhuaooeW8jyAge2NvZGU6ImFsZXJ0KHdpbmRvdy5sb2NhdGlvbi5ocmVmKTsifQ0KLyoqKioqKkpT5o+S5YWl5qih5byPKioqKioqLw0KLyoqKioqKumrmOe6p+aooeW8j+S6i+S7tioqKioqKi8NCi8vYWxlcnQobXlXZWJWaWV3RXZlbnQudHlwZSk7DQovL2FsZXJ0KG15V2ViVmlld0V2ZW50LnVybCk7DQovL215V2ViVmlldy5pbnNlcnRDU1Moe2NvZGU6ImJvZHl7fSJ9LCBmdW5jdGlvbigpIHt9KTsNCi8vbXlXZWJWaWV3Lmluc2VydENTUyh7ZmlsZToiaHR0cDovL3h4eC54eHgueHh4L3h4eC5jc3MifSwgZnVuY3Rpb24oKSB7fSk7DQovL215V2ViVmlldy5leGVjdXRlU2NyaXB0KHtjb2RlOiJhbGVydCh3aW5kb3cubG9jYXRpb24uaHJlZik7In0sIGZ1bmN0aW9uKCkge30pOw0KLy9teVdlYlZpZXcuZXhlY3V0ZVNjcmlwdCh7ZmlsZToiaHR0cDovL3h4eC54eHgueHh4L3h4eC5qcyJ9LCBmdW5jdGlvbigpIHt9KTsNCi8qKioqKirpq5jnuqfmqKHlvI/kuovku7YqKioqKiovCQ==")+
"</pre></div></div></li></ul></from></div>";ExView.modules.createContentPage(d,b,"webappeditpage",'<a href="javascript:void(0);" class="link back savewebappbutton icon-only">保存</a>',function(){a||(a={url:"http://www.bilibili.com/mobile/index.html",name:"哔哩哔哩",icon:"http://static.hdslb.com/mobile/img/512.png",css:"ZGl2LmItYXBwLWRsLXdycHt6LWluZGV4Oi0xIWltcG9ydGFudH0=",js:sessionStorage.webappdefaultjscode});a.css=ExView.tools.base64.decode(a.css)||"";a.js=ExView.tools.base64.decode(a.js)||
"";ExView.fw.formFromJSON($$("#webapp-form"),a);$$(".item-title.floating-label").parent().addClass("not-empty-state");$$(".savewebappbutton").on("click",function(){var a=ExView.fw.formToJSON($$("#webapp-form"));a.css=ExView.tools.base64.encode(a.css)||"";a.js=ExView.tools.base64.encode(a.js)||"";if(!a.name||!a.url)return ExView.fw.alert("请填写轻应用名称和路径！","ExView"),!1;ExView.tools.file.mkdir("ExView/WebApp/",function(){ExView.tools.file.savefile("ExView/WebApp/"+
a.name+".ewp",JSON.stringify(a),{file_append:!1,filemime:"text/json",filetype:"text"},function(){ExView.fw.alert(a.name+" 已添加！","ExView");ExView.modules.webapppage.load(ExView.modules.webapppage.callback)},function(){ExView.fw.alert(a.name+" 添加失败！","ExView");ExView.modules.webapppage.load(ExView.modules.webapppage.callback)})},function(){ExView.fw.alert(a.name+" 添加失败！","ExView");ExView.modules.webapppage.load(ExView.modules.webapppage.callback)});
$$(".page[data-page='webappeditpage']").find(".dynamic-page-close").trigger("click")})},null,null,"")},init:function(){ExView.modules.createContentPage("轻应用","","webappviewpage",'<a href="#" class="link addwebappbutton icon-only"><i class="icon icon-plus"></i></a>',function(){ExView.modules.webapppage.load(ExView.modules.webapppage.callback)},null,null,"")}}}});
